### ISSUE TITLE
"Related guides" shows up multiple times in the table of contents

### ISSUE THREAD

**Issue by Kubik42** [OpenLiberty/openliberty.io#100]
"Related guides" will show up in every section that has subsections.

Example:
![screen shot 2018-01-03 at 2](https://user-images.githubusercontent.com/11563877/34537556-e1123700-f096-11e7-91ed-f5d49324456f.png)

See: 
- https://openliberty.io/guides/rest-hateoas.html
- https://openliberty.io/guides/docker.html
- https://openliberty.io/guides/rest-client-java.html
- probably more

**Comment by kinueng** [comment]
My CSS selector is too broad and blindly appending to any `ul` element.  

I should be looking for an `ul` element with Asciidoctor's `sectlevel1` class and append the`Related guides` section to the bottom.  The assumption is the bottom of `sectlevel1` should be the bottom of the table of contents.
