### ISSUE TITLE
Copy button not work for html file - High priority 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1002]
- go to https://qa-guides-multipane.mybluemix.net/guides/rest-client-angularjs.html#creating-the-angularjs-template
- scroll to see
```
Create the starting point of your application.
src/main/webapp/index.html
```
- On the right pane, index.html should be shown
- click on the copy button at the top right
- paste to any editor but the html content is not pasted

**Comment by steven1046** [comment]
Interesting, it copies locally and I see some errors due to the security policy on qa-guides-multipane when loading.

**Comment by steven1046** [comment]
@gkwan-ibm this is fixed now: https://qa-guides-multipane.mybluemix.net/guides/rest-client-angularjs.html#creating-the-angularjs-template
