### ISSUE TITLE
Firefox only: The scrolling in the code pane is very sensitive

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1006]
I want to see the bit of code above a hotspot (because a hotspot is always at the top of the screen), I scroll a little bit, it goes all the way to the top of the file, which means I lost track of what I was looking at. Take the `pom.xml` file in the `getting-started` guide, for example, it's difficult to want to see the full block of code when there's one line hotspot. 

Note, FF shows the problem described. Chrome and Safari are good.

**Comment by steven1046** [comment]
Note for whoever fixes: The scrolling in firefox sticks for a short period when you try to scroll hard in the code pane. It also happens without even hovering over a hotspot.

**Comment by jamiecoleman92** [comment]
@tevans78 is also seeing this issue. Any idea on an eta for this fix? We are presenting a lab at Devoxx France in 3 weeks and it would be great if this could be fixed in time for that conference.

**Comment by yeekangc** [comment]
@justineechen and I ran into this too.  Tried it on Chrome and Safari and they were fine.  Looks to be Firefox primarily.  The scrolling feels jumpy.
