### ISSUE TITLE
Pre-populate download page cache in builds

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#1018]
The downloads page has a caching mechanism on the backend.  The cache is populated on the first load of the downloads page.  We should do this in the build rather than a human visiting the downloads page.

We should be visiting the downloads page for EVERY `cf` application.  Each geo region is backed by two `cf` apps behind one domain.  We need to somehow visit the downloads page for individual applications during the build to populate the cache in each application.

**Comment by mbroz2** [comment]
Are we unable to just make a server side call to DHE during server/app startup to populate the cache?

**Comment by steven1046** [comment]
@kinueng @mbroz2 What is the root reason for this issue? I built the app without changing anything and the downloads page loads fine on the first render.

**Comment by mbroz2** [comment]
it should be strictly for performance reasons; currently, the first user has to incur the cost of populating the cache, so it's slower than any subsequent request that would leverage the populated cache.  If instead we populate the cache during server build/start, than that would result in no penalty for the first user.

**Comment by steven1046** [comment]
We can add code to the BuildsManager constructor to initialize the data that dheBuildParser stores, I haven't had time to add a JUnit test to BuildsManagerTest.java. That's as far as I got with this issue. Building the application locally after adding the code makes the downloads page load quick, but I wasn't able to fully test it yet.

**Comment by deboer-tim** [comment]
+1 to this. I happened to be a 'first user'. The placeholder image didn't really make me think that anything was happening in the background, and it took almost a minute before the content appeared. I had time to look through all of the tabs and ping Alasdair about not having any releases before it actually showed up :), so anything to speed it up would be appreciated.

**Comment by barecode** [comment]
The core issue that causes this is that we crawl DHE, because DHE does not have a simple API that informs us in one query what builds are available. That crawling can take a lot of time, so generating this list during deployment / build would be ideal.

**Comment by NottyCode** [comment]
So I've done a PR in #1018 which causes us to load at server start. This isn't quite what this issue is calling for, but doing this at build time is complicated and @mbroz2 was concerned that doing it in build cloud cause issues that would be hard to detect (like if we broke the live function we wouldn't notice).

**Comment by NottyCode** [comment]
In PR #1604 we update how the build population works so during server start the latest release build will be fetched, this means that you won't get in the situation where there are no builds. 

It might seem odd to only see a single build, but it won't trigger the issue where it looks like we have no builds. The old code required all builds to be loaded before providing any information, the new one prioritizes data most recent first over no data which should mean the problem goes away. As a result I think when it goes live we will be able to close this issue.

**Comment by NottyCode** [comment]
#1604 is now live so I'm closing this as resolved for now.
