### ISSUE TITLE
Look for alternative way to specify branch when cloning guides

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#1019]
Right now we use `--single-branch` to specify which branch we want from the guide git repositories.  The drawback is `--single-branch` does not let you `git checkout` a different branch from the guide repos.

https://github.com/OpenLiberty/openliberty.io/blob/4582feb451c889ba9c140ef5edc887f11a84cc50/scripts/build_clone_guides.rb#L60

Look for a better way to specify `git clone <specific branch>` but also lets you checkout any branch from the guide repositories.

**Comment by steven1046** [comment]
`git clone -b #{guide_branch} https://github.com/OpenLiberty/#{repo_name}.git  src/main/content/guides/#{repo_name}`
