### ISSUE TITLE
Single file tag management for guides

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1021]
The goal is to have a single (or very few) file(s) that will be used for tagging.
Currently, each guide defines its own tags in the adoc but this is difficult to maintain.  Instead we'll want to move all those tags to a single file which would look something like:
{
tag1: ["guide1", guide2"],
tag2: ["guide2", guide3" "guide4"]
}
This 'tag focused' approach will make it easier to manage our tags.
What needs to be discussed is whether we would have a single tag file for all resources or a tag file per resource type (guides, blogs, concepts, etc) and where the file should live (which repo(s)).

**Comment by steven1046** [comment]
One thing to note is that guides have projectid's and blogs have no sort of id mechanism, just their file name to differentiate them.

**Comment by k8vance88** [comment]
Ellen has done something similar with blogs.  Please talk to her to use her work as a guideline.
