### ISSUE TITLE
Investigate enabling http/2

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1022]
The current buildpack comes with ibm-java-jre-8.0-5.27 so it should have ALPN support since that should have been added back in 8.0.5.15.  The switch should be as easy as adding protocolVersion="http/2" to our httpEndpoint or moving up to servlet 4.
Benefit: performance improvement in site load time

**Comment by k8vance88** [comment]
This will be fixed by #1406
