### ISSUE TITLE
Back button does not work as expected

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1033]
- Go to Guides page that lists all the guides
- Pick a guide and click into it
- Click Back button intending to get back to the Guides page that shows all the guides

Back button doesn't work as expected.  Clicking on Back is going back on the different sections of the guide and never seem to take user back to the previous page.  This isn't what the user has done.

Back seems to work (i.e. take you page to the previous page) only if you haven't browsed anything else on the guide after landing on it from the Guides page.

**Comment by steven1046** [comment]
When you scroll through the guide, we update the hash with the step that you're on so that's why clicking back will take you to the previous step.

**Comment by yeekangc** [comment]
I am not sure I am fond of that but I can probably live with it.  Then, it still won't take you back to the previous page after many Back clicks?

**Comment by steven1046** [comment]
Fixed https://openlibertydev.mybluemix.net/guides/
