### ISSUE TITLE
Titles in tiles for Related Guides aren't aligned properly in mobile view?

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1034]
They are aligned Bottom Left as opposed to Top Right (as in the regular web view)?  The extra whitespace at the top isn't as nice?

![img_0488](https://user-images.githubusercontent.com/4803104/53755411-7a4d4400-3e84-11e9-8763-67a1a2d3b92b.PNG)

Also, should we show the abstract?

**Comment by yeekangc** [comment]
Should we update the copyright year at the bottom with 2019?

**Comment by steven1046** [comment]
@yeekangc what do you mean by `Also, should we show the abstract?`

**Comment by yeekangc** [comment]
![image](https://user-images.githubusercontent.com/4803104/53764321-edfa4b80-3e9a-11e9-8568-b9265cde8dd1.png)

**Comment by steven1046** [comment]
The redlines for multipane removed the abstract from the cards at the end of the guide.

**Comment by yeekangc** [comment]
If the design is for not having the abstract, I am fine.  Just thought to note it.

Key is the spacing/alignment and copyright year.

**Comment by steven1046** [comment]
Fixed
