### ISSUE TITLE
Make the navbar hover when scrolling up

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1040]
See the designs for the hovering nav:
https://ibm.ent.box.com/file/316968974782
Ignore the first half of the video, it has old navigation links and details.

**Comment by mbroz2** [comment]
@cajaygle should this behavior be for all nav bars, or just the ones that are currently not docked to the top of the page (most docs pages have the navbar always docked at the top)

**Comment by mdenby** [comment]
@mbroz2 This should happen on all the pages. The navigation reappears when the user scrolls up. For the docs pages the sidebar will need to be fixed so it doesn't scroll off the top of the page.

**Comment by mbroz2** [comment]
Right now, docs & guides have the header fixed/stickied to the top, but all other pages do not; we should either have the header stickied for all pages, or implement this issue (header is never stickied, but 'drops down' as soon as user starts to scroll up).

**Comment by mdenby** [comment]
I agree it should be one way or the other. Is it possible to have the header _not_ be sticky on the docs and guides pages?

**Comment by mdenby** [comment]
Let's have the nav bar not sticky--If you scroll up a bit, even if you’re waaaaay down the page--then the nav bar should reappear

**Comment by mbroz2** [comment]
That's my preference as well, navbar is never stickied, but appears (dropsdown as an overlay) as soon as a user scrolls up.

**Comment by ellenwyllie** [comment]
@mdenby 
In the guides on mobile view, the Table of Contents button is fixed to the top of the screen like this:
<img width="499" alt="Screen Shot 2020-07-15 at 7 00 03 PM" src="https://user-images.githubusercontent.com/22085207/87662038-409e7580-c727-11ea-9615-47c29292c437.png">

How would this nav bar behavior work in this case? I was thinking that one option would be to push down the Table of Contents button and show the nav bar above it like this:
<img width="616" alt="Screen Shot 2020-07-15 at 6 56 54 PM" src="https://user-images.githubusercontent.com/22085207/87662046-4300cf80-c727-11ea-82f8-2c51ee2c0709.png">
