### ISSUE TITLE
'Contribute in GitHub' links in non-generated doc topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1046]
In the IBM Cloud docs, readers can click links at the top of each doc topic to either raise an issue with the topic in GitHub or to directly create an update and submit a PR for the topic. I've used this feature (as a reader wanting to make some updates; even just fixing a typo) a few times and it's really useful - it makes contributing back really, really easy (obviously, it needs there to be someone responding to them but if there are updates needed, it's better that someone is spotting them).

See, for example, https://cloud.ibm.com/docs/java?topic=java-overview#overview

![image](https://user-images.githubusercontent.com/3322532/54027430-6dd52e00-4199-11e9-99bd-a949119c15d3.png)

**Comment by mbroz2** [comment]
We can start working on the development of this as it will take time to get it correctly working for all our pages (this can also be staged in if necessary).  This does still need desgin (@cajaygle ), but since the extra content is minimal, it should be trivial to apply any styling changes afterwards.

**Comment by lauracowen** [comment]
Sounds good. Would it be feasible to just not add it to the generated docs for a first pass?

**Comment by NottyCode** [comment]
@mbroz2 can we  not just use the design from the IBM Cloud docs? It seems pretty clean, unobtrusive and it seems to me is likely already had design input.

**Comment by cajaygle** [comment]
I'm good with the design.

**Comment by mbroz2** [comment]
I've scoped this issue down to implementing the github links for non-generated site content.  I've opened #1085 to track the work for github links for generated content.
