### ISSUE TITLE
Some tabs are not showing up in the multimodules guide

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1053]
This is due to them having similar names: pom.xml, ear/pom.xml, war/pom.xml, etc. and we do contains to check if two tabs are the same name instead of a strict check.

**Comment by steven1046** [comment]
Per Eveline: In our guide's template, we have the follow sample codes. Notice both the `TodoManager` and the `SampleTodoManager` classes have the word `TodoManager` in their names. The follow section with code commands does not show up properly on the code pane. Only one class, ie, the `TodoManager` file shows up, and when hover over the other, the content of the other class displays, but there's still only one file on the code pane. Renaming one of the classes resolves this problem. 

```
== EXAMPLE: Creating an application manager

* Create a manager that is injected into the JAX-RS resource

[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `TodoManager` interface.#
`src/main/java/io/openliberty/guides/todo/managers/TodoManager.java`
----

TodoManager.java
[source, Java, linenums, indent=0, role="code_column"]
----
include::finish/src/main/java/io/openliberty/guides/todolistSample/managers/TodoManager.java[tags=**;!copyright;]
----

* Next, create the sample todo manager class

[role="code_command hotspot file=1", subs="quotes"]
----
#Create the `SampleTodoManager` class.#
`src/main/java/io/openliberty/guides/todolistSample/managers/samples/SampleTodoManager.java`
----

SampleTodoManager.java
[source, Java, linenums, indent=0, role="code_column"]
----
include::finish/src/main/java/io/openliberty/guides/todolistSample/managers/samples/SampleTodoManager.java[tags=**;!copyright;]
----
```

**Comment by evelinec** [comment]
You can get the template sample code here to try it out: https://github.com/OpenLiberty/draft-guides-template.
