### ISSUE TITLE
Create a 404 page

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/openliberty.io#107]
Currently we do not have a page for non-existent site content.

It would look much better to still have the site render with a page showing that the content does not exist.

**Comment by kinueng** [comment]
We can use these instructions for this issue.

https://jekyllrb.com/tutorials/custom-404-page/

> Custom 404 Page
> You can easily serve custom 404 error pages with Jekyll to replace the default Error 404 – File Not Found page displayed when one tries to access a broken link on your site.
>

**Comment by kinueng** [comment]
Added this issue to the Box note asking for designs on a 404 page and whether we want to redirect 404's to the homepage.

**Comment by kinueng** [comment]
Currently a 404 page looks really bad.
![image](https://user-images.githubusercontent.com/31117513/37780959-cf94acb0-2dbd-11e8-993c-a3ecaa5a51d7.png)
