### ISSUE TITLE
Deliver MicroProfile 2.2 Javadoc

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#1080]
When Liberty supports Eclipse MicroProfile 2.2 we need to upload the javadoc to the website.

[microprofile-2.2-javadoc.zip](https://github.com/OpenLiberty/openliberty.io/files/3006036/microprofile-2.2-javadoc.zip)

**Comment by steven1046** [comment]
Please update the redirect in redirects.properties to the latest version too.

**Comment by steven1046** [comment]
@NottyCode When will be able to upload the new Javadoc?
