### ISSUE TITLE
'Contribute in GitHub' links in support, downloads, about, contribute, and home pages

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1089]
This is meant to encompass all other views not covered in the other 'contribute in GitHub' issues (which cover docs and blogs).

**Comment by NottyCode** [comment]
I don't think this is appropriate. I think changes to the non-docs and non-blogs are something that need a lot of governance around and having an 'edit in github' for them implies a lower level of governance. Essentially I expect if someone contributes to docs we would accept it quickly with a single person reviewing. For the front page, or support page I'd expect a much wider discussion of any change that isn't typical of a PR.

**Comment by lauracowen** [comment]
Yes. I agree with Alasdair's comment above.
