### ISSUE TITLE
Don't hide guides on all guides page

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1091]
The presentation of the guides on the all guides page obscures the fact that we have ~30 guides now because many of them are hidden by default. In particular, the MicroProfile guides (probably the most important) are mostly hidden.

Categorisation is fine (and we need to work on that to make it more useful) but can we remove the collapse/expand bit from page design so that we don't hide guides?

![image](https://user-images.githubusercontent.com/3322532/55090836-b781ac00-50a7-11e9-83ea-4c7ed4196d21.png)

Instead, assume that people will use the filter (or CTRL+F) to find the guide they want. I don't think it's a problem to have a long page of them. And better to show the full range we have than to hide them.

@gcharters @NottyCode @cajaygle

**Comment by mdenby** [comment]
I'm in agreement with removing the collapse/expand in the MicroProfile Guides. 

Though I'm curious about how we could better categorize the 'More Guides' section. I think the search works well here. Though I believe it will be replaced by the search at the top of the site--so a filter for this page may be a good idea. I can talk to @cajaygle about working on that piece. But removing the collapse/expand seems like a good idea to me.

**Comment by lauracowen** [comment]
I'm open to better/alternatives to categorisation but one option that I'd like to consider is categorising the guides according to the 'layers' of microservice creation that Graham uses. He focuses on MicroProfile but could the non-MicroProfile guides go into that structure too? See the modules in https://github.com/gcharters/workshop-cloud-native-java

**Comment by steven1046** [comment]
On the weekly call, everyone agreed that we can go ahead and remove the collapsed sections in the interim until we have a new way to categorize the guides.

**Comment by yeekangc** [comment]
FYI, @gkwan-ibm.  We are looking at further categorization and will raise it when ready.  Some of what we are thinking is in line with comments above.

+1 to not collapse the current sections.
