### ISSUE TITLE
Static guide - Change github clone popup to prerequisites for the guide

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1095]

**Comment by mdenby** [comment]
![Prerequisite Kube final](https://user-images.githubusercontent.com/26823018/55487270-cc0bfa00-55fb-11e9-843f-e9a5f7e5d95e.png)
![Prerequisite_final](https://user-images.githubusercontent.com/26823018/55487271-cc0bfa00-55fb-11e9-93f8-99b6f9f9315a.png)
![mobile_prerequisites](https://user-images.githubusercontent.com/26823018/55487272-cc0bfa00-55fb-11e9-9e64-2bde66814c69.png)
![Mobile Kube Guides](https://user-images.githubusercontent.com/26823018/55487273-cc0bfa00-55fb-11e9-8580-d1441723119c.png)

**Comment by steven1046** [comment]
Are there any click or hover behaviors for the prerequisites?

**Comment by mdenby** [comment]
@steven1046 Yes, here is the hover behavior--it turns dark green (#4F660A) and keeps the light green border (#ABD155). If the user clicks on a prerequisite eg Maven, it should take them to the website to download it. 

![Prerequisites Hover](https://user-images.githubusercontent.com/26823018/58495674-11edc600-8146-11e9-8572-733c06e4f369.png)

**Comment by ellenwyllie** [comment]
@mbroz2 @mdenby  So are we totally getting rid of the github clone popup and replacing it with the prerequisites?
We don't currently have prerequisites defined for the guides, so are we going to ask all the guide authors to specify the prereqs for each guide?
Also, are all guides going to have prerequisites defined now? If not, what will be shown in right panel?

**Comment by mdenby** [comment]
Yes, the idea is to totally get rid of the GitHub clone popup (which strangely is not a pop-up :-) because it can't be closed). At the very least the user will need Java and I'm sure some other common things. As they scroll down they are still given the instruction to clone in the right side, so that is not lost. We felt prerequisites were good information instead of the cta to immediately clone--which was repeated later anyway--and also just hung out floating on the right panel for a long time while the user scrolled.

**Comment by mbroz2** [comment]
@mdenby just to clarify, we're only going to list prerequisite 'technologies' on the right side, but not any actual instructions/steps that are prereqs to do the guide, correct?

@ellenwyllie we'll want to work with @yeekangc @evelinec @gkwan-ibm to decide on the list of "Prerequisites" items that we'll want to possibly list and get them added to each guide.  I think we'll just add a new field like 'guide-prereqs' so we'd have something like ":guide-prereqs: ['Java', 'Docker']"

**Comment by steven1046** [comment]
Since the designs call for linking the prereqs to their respective documentation, we may want a central place that stores the link to each technology so we don't have to duplicate the url for each in each of the guides.

**Comment by mbroz2** [comment]
@steven1046 I agree which is why we need to work with the guides team; I think an approach similar to #1021 would make sense (a single file with all he different 'prereqs' and their mapping to guides, plus links to source content)

**Comment by mdenby** [comment]
[Prerequisites redlines.zip](https://github.com/OpenLiberty/openliberty.io/files/3248739/Prerequisites.redlines.zip)

**Comment by mdenby** [comment]
@mbroz2 Correct :-) I think the only guide that is slightly different is the Kubernetes guides that have Mac/Windows/Linux tabs in the left.

**Comment by yeekangc** [comment]
Yes, we should work with a sample of what should be shown and then, we can see if we need to tweak the design further as well as work out how they should be captured/documented.

The main ones would be the Kuberntes and Istio series of guides.  Once we have something worked out, we can see if we should propagate to everything too.

Please work with @gkwan-ibm who can help to look at this on the content side.

**Comment by yeekangc** [comment]
I suspect in some cases, we will need more than a button with a simple label.  Does it show details when you click on it?

**Comment by mdenby** [comment]
![Prerequisites Hover with version](https://user-images.githubusercontent.com/26823018/59125522-943d6d80-8930-11e9-93de-2d8f8aa02c19.png)
![Prerequisites Copy](https://user-images.githubusercontent.com/26823018/59125523-943d6d80-8930-11e9-9dd2-ad1b4e7df0f0.png)

**Comment by ellenwyllie** [comment]
Blocked by https://github.com/OpenLiberty/guides-common/issues/292
