### ISSUE TITLE
Static guide - Change OS specific instructions design

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1096]
Right now we only have the platform specific instructions in the Kubernetes intro guide: https://openliberty.io/guides/kubernetes-intro.html#prerequisites. We want to change the design to a tabbed format with a fixed OS order so the user can view all of the platform instructions but only one at a time.

**Comment by steven1046** [comment]
Desktop
![image](https://user-images.githubusercontent.com/6392944/55410909-45d3b300-552a-11e9-887d-a26dc7b4090c.png)

Mobile
![image](https://user-images.githubusercontent.com/6392944/55410948-571cbf80-552a-11e9-8fc6-84bd40fb33bf.png)

**Comment by mbroz2** [comment]
For any guide that has platform specific instructions (like Kubernetes & Docker guides), display the platforms in the following tabbed order (based on users) :
Windows, Mac, Linux 
If the user-agent string provides one of the 3 values, than automatically select it, and if it doesn't, than select Windows as the default.

**Comment by ellenwyllie** [comment]
Is it still necessary to say "After following one of the sets of instructions" now that we'll only be showing one set of instructions at a time? It sounds a little weird to me

**Comment by gkwan-ibm** [comment]
I gave comments at https://github.com/OpenLiberty/guides-common/pull/286#issuecomment-499197610

**Comment by steven1046** [comment]
Hi @cajaygle @mdenby, @DannyS03 brought up that it might look better if the content was more indented underneath the operating system tabs so the user knows what is being changed when they click on the tabs.

**Comment by cajaygle** [comment]
I don't feel it needs to be indented but it's not a strong opinion, so if you all think indenting will help then go ahead and use an indented style.   We're short a visual designer right now since Thuy-Hanh left so we can't give you a mockup so ident it as you feel appropriate..

**Comment by gkwan-ibm** [comment]
http://lgdev1.fyre.ibm.com:4020/guides/istio-intro.html#starting-and-preparing-your-cluster-for-deployment is the guide which we were updated to see how the existing OS specific design look. It has many places with OS specific content.

We think it should be better to have a visual clue to identify the OS specific content, either indented or any other clue.

**Comment by gkwan-ibm** [comment]
@steven1046 For the current implementation,  the guide need to define as following:
```
[.tab_link][.windows_link]`*WINDOWS*`
[.tab_link][.mac_link]`*MAC*`
[.tab_link][.linux_link]`*LINUX*`

[.tab_content][.windows_section]
---
...
---
[.tab_content][.mac_section]
---
...
---
[.tab_content][.linux_section]
---
...
---
```
is it possible to reduce the required  [.tab_link] and [.tab_content]?
```
[.windows_link]`*WINDOWS*`
[.mac_link]`*MAC*`
[.linux_link]`*LINUX*`

[.windows_section]
---
...
---
[.mac_section]
---
...
---
[.linux_section]
---
...
---
```
is it possible to use one single `[.tab_???_link]` because we always only support 3 platforms?
```
[.tab_os_link]

[.windows_section]
---
...
---
[.mac_section]
---
...
---
[.linux_section]
---
...
---
```
how to support same content in 2 platforms instead of duplicating the content?
```
[.tab_os_link]

[.windows_section | mac_section]
---
... same instruction for Windows and Mac ...
---
[.linux_section]
---
...
---
```

**Comment by ellenwyllie** [comment]
@gkwan-ibm  [.tab_link] and [.tab_content] are used for the css but I can adjust the css so that they are not required if you think that would be a bit cleaner.

I can also look into combining the 3 links to see if it's possible. 

For your comment about duplicating content, are you referring to repeating code in the adoc file or do you want to change the design if windows and mac have the same instructions?

**Comment by gkwan-ibm** [comment]
> [.tab_link] and [.tab_content] are used for the css but I can adjust the css so that they are not required if you think that would be a bit cleaner.

Yes, it is cleaner if no  [.tab_link] and [.tab_content]. I do not mind to rename as [._tab_windows_section] or keep as [.windows_section] . I think one [..._section] tag should be enough.

**Comment by gkwan-ibm** [comment]
regarding the same content for 2 platforms, for the existing design, the code like following:
```
[.tab_link][.windows_link]`*WINDOWS*`
[.tab_link][.mac_link]`*MAC*`
[.tab_link][.linux_link]`*LINUX*`

[.tab_content][.windows_section]
---
... same instruction for Windows and Mac ...
---
[.tab_content][.mac_section]
---
... same instruction for Windows and Mac ...
---
[.tab_content][.linux_section]
---
... instruction for Linux ...
---
```

I suggest to change whatever (maybe the design), so that we do not need to duplicate the content. Assume the first 2 changes are good. The future code will be either
```
[.tab_os_link]

[.windows_section | .mac_section]
---
... same instruction for Windows and Mac ...
---
[.linux_section]
---
...
---
```

or
```
[.tab_os_link]

[.windows_section][.mac_section]
---
... same instruction for Windows and Mac ...
---
[.linux_section]
---
...
---
```
or any other suggestion
