### ISSUE TITLE
H3 headings in blog posts are really indistinct

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1099]
The design in #458 (linked in #339 where I originally raised the H3 problem) suggests the headings are more distinct than they actually appear in the blog posts now: https://openliberty.io/blog/2019/03/28/microprofile22-liberty-19003.html#mp22

The H3 headings are rendering as much the same as normal text but bold. This isn't enough to be able to easily skim down the page to spot them. Even when clicking a link directly to them they don't really stand out.

I'm not sure if the live stylesheet hasn't been implemented exactly, or if it just looks better in the proposed design than it does in the recent blog post.

**Comment by mbroz2** [comment]
Resolved by #458
