### ISSUE TITLE
404 pages for top google search results

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#1105]
https://www.google.com/search?q=openliberty.io+jsonb&oq=openliberty.io+jsonb&aqs=chrome..69i57.3195j0j4&sourceid=chrome&ie=UTF-8

![image](https://user-images.githubusercontent.com/31117513/55488133-0faf3580-55f5-11e9-8d84-73f564126db9.png)

https://openliberty.io/javadocs/liberty-javaee8-javadoc/javax/json/bind/Jsonb.html
![image](https://user-images.githubusercontent.com/31117513/55488173-25bcf600-55f5-11e9-9b8e-f7834c4a39c6.png)

**Comment by steven1046** [comment]
The google links work now
