### ISSUE TITLE
"Back to text" button shows up on multipane

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1106]
The "Back to text" button shows up on multipane design: 

![image](https://user-images.githubusercontent.com/33134427/55491973-71c36700-5604-11e9-8dda-2abf7079ad78.png)

Possible steps to reproduce it: 
1. Go to a guide: ie, https://openliberty.io/guides/rest-intro.html
2. Minimize the browser screen to show single pane content
3. Click on a code file and then click on the "Back to text" button
4. Maximize the browser to show multipane 
5. Scroll up and down the guide content (middle pane)
6. You can observe the "Back to text" button shows up at the button of some of the code files
7. The button is not clickable, of course

Other times, we found that the button just shows up on the multipane without going through the above steps.

**Comment by evelinec** [comment]
@kin @steven1046

**Comment by mbroz2** [comment]
This would be resolved by #1094 but we can do a quick fix in the interim.

**Comment by evelinec** [comment]
Verified the rest-intro guide. Seems good.
