### ISSUE TITLE
The guide feedback selection faces do not have any response

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1109]
From a Micro Lab session, some attendees pointed out that the feedback selection under "What did you think of this guide" doesn't have any response once clicked. He/She doesn't know whether anything had happened.

**Comment by mbroz2** [comment]
It does have a response; the icons/faces of the other ratings become opaque, however, I agree that this is not enough of feedback and I have been meaning to open this exact issue to address that.  
#1158 will address this for the two lower ratings, but it will still be an issue for the two high ratings.

**Comment by mdenby** [comment]
Posted in #1158 for the design and closing this.
