### ISSUE TITLE
Migrate the development sites from personal to WASDev account

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1120]
As part of this work, we'll need to look into a way to split the credentials used by the CloudFoundary push for deploying production vs development on the WASDev account.

This would than enable us to use .openliberty.io subdomains for the various 'development' sites.

**Comment by kinueng** [comment]
We would need to make some DNS changes in CIS so that we route a specific .openliberty.io subdomain to a particular CloudFoundary app in a particular datacenter.

**Comment by steven1046** [comment]
Closing, as all of the draft/staging environments have been moved to the WASDev account. Any other existing apps on personal accounts aren't used for ol.io.
