### ISSUE TITLE
Iframe Scrolling Updates

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1122]
Design would like to update the scrolling on the pages with iframes. See the comments on #802 for background on this issue. Here is what they would like to do:

1. Remove the iframe from the main body copy. Having three scrollable areas is confusing. When the user scrolls through the main content it should just scroll the page.

2. Show the scrollbar for the main content/page as the user scrolls so they can see their progress.

3. In the sidebar, if it is scrollable, show a scrollbar all the time.

4. When the user scrolls to the bottom of the main content, the footer scrolls into view.

**Comment by steven1046** [comment]
I think we should separate this out to one issue per type of doc, since the changes and time investment could be pretty large for certain pages.
