### ISSUE TITLE
Make the body text size and color in guides/docs consistent.

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1123]
https://ibm-cloud.slack.com/archives/C4U7TQUSY/p1554912839127700 - "Here are some changes for guides and docs to create a unified design between the two. The body text will now be 14 px and #24243B through out.

For each page
Update the main body text to 14px and #24243B
![image](https://user-images.githubusercontent.com/6392944/56214550-b814bf00-6023-11e9-8cb8-bff812bdb5ef.png)

- [x] Update static guides
- [x] Update interactive guides
- [x] Update Intro docs
- [x] Update Config
- [x] Update Features
- [x] Update General docs
- [x] Update Commands
- [x] Update Javadocs

Guide example:
![image](https://user-images.githubusercontent.com/6392944/55896232-70a1b500-5b83-11e9-9db8-46aff5b55b71.png)

**Comment by steven1046** [comment]
@TreeHanh should we update the javadocs as well? They are in a different format than the rest of the docs/guides.

**Comment by steven1046** [comment]
Guides are already 14px so it's probably just the docs that need to be consistent. Do check the color of the guide text though.

**Comment by TreeHanh** [comment]
@steven1046 Yes, we'll want to make the changes across all the docs and guides including javadocs.

**Comment by steven1046** [comment]
@TreeHanh @mdenby should the code snippets inside the blue/purple bubbles also be 14px or remain 16px?
