### ISSUE TITLE
Redesign grouping of guides

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1126]
Under #1091 we're going to show all guides instead of having them collapsed.  Under this issue, a new way to categorize/group guides will be provided.

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by mdenby** [comment]
[GuidesCategory-05312019.pdf](https://github.com/OpenLiberty/openliberty.io/files/3242888/GuidesCategory-05312019.pdf)

**Comment by yeekangc** [comment]
Should see if we can improve navigability and ability for users to spot what's available somehow.

- Can we provide an 'outline' of what's available that users can easily spot and grasp when they land on the page?
- Make it easier to scroll and look at e.g. making the cards smaller?
- Make sub-categories more visible and easier to identify/follow?

**Comment by mdenby** [comment]
Here is the murally board of all the card sort ideas. https://app.mural.co/t/olg3054/m/olg3054/1561574738608/97e509dd8f6ed69dcfff0a23190432f314049172

**Comment by mdenby** [comment]
Here are everyone's ideas--the first pass. We can review them tomorrow morning and I can update them based on feedback. 

Michal's version:
![Michal's Version 01](https://user-images.githubusercontent.com/26823018/62252701-a03e2c80-b3c1-11e9-8ee3-a389b814d793.jpg)
![Michal's Version 02](https://user-images.githubusercontent.com/26823018/62252704-a16f5980-b3c1-11e9-83b3-3991db1206a5.jpg)
![Michal's Version 03](https://user-images.githubusercontent.com/26823018/62252708-a3391d00-b3c1-11e9-9623-583cc93b3e08.jpg)

Functional version:
![Functional Version 01](https://user-images.githubusercontent.com/26823018/62252796-d9769c80-b3c1-11e9-95cc-4e36954a2c40.jpg)

YK's version:
![YK's Version](https://user-images.githubusercontent.com/26823018/62252808-e3000480-b3c1-11e9-9de9-e5519ab14cb3.jpg)

**Comment by mdenby** [comment]
Notes from Thursday meeting:
Sidebar should be sticky
Retain the 'Search all Guides'
Keep all the top level categories open
Add a 'Basics' category. There is a question about what guides should be in 'Basics'. I will open a new issue for this. Also, there are three guides that have no subcategory.

**Comment by mdenby** [comment]
Here are the updated Guides.

![Michal's Version 01](https://user-images.githubusercontent.com/26823018/62476238-99723980-b774-11e9-8fe8-aff7a10812a6.jpg)
![Michal's Version 02](https://user-images.githubusercontent.com/26823018/62476239-99723980-b774-11e9-8fc9-3c20bbf9308d.jpg)
![Michal's Version 03](https://user-images.githubusercontent.com/26823018/62476241-99723980-b774-11e9-8896-0796f11c45ad.jpg)

**Comment by mdenby** [comment]
Newest version with all on the same page. Emailing Graham Charters for an opinion.
![Homepage_Full_Scale Copy 19](https://user-images.githubusercontent.com/26823018/64209702-36f18380-ce6f-11e9-86b2-0f31e8ce6df9.jpg)

**Comment by yeekangc** [comment]
Note to be sure to capture in the guides wiki what a guide developer should consider and need to do to categorize a guide.

**Comment by mdenby** [comment]
[2019 New Categories Guides.zip](https://github.com/OpenLiberty/openliberty.io/files/4195034/2019.New.Categories.Guides.zip)

**Comment by ellenwyllie** [comment]
On the 2/27 call we decided that we will not have a default category. Guides will need to be categorized before they can be pushed to the site.

**Comment by ellenwyllie** [comment]
@mdenby What should happen when the user searches for something and there are no search results in a specific subcategory? I assume we want to hide the sections with no search results similar to what we do now on the site. But what do we want to do in the table of contents? It seems weird to show the categories in the toc if there are no search results for them

**Comment by mdenby** [comment]
So if there are search results--show only those sections, and subsections with the guides in the main part of the page. The sidebar should also change to only show the section (like Develop) and the subsections that contain guides.

If there is no search results--do not change the sidebar in any way. But display the "No search results" message. The user can either delete their search term in the search box or click on the sidebar to navigate to a section.

![No search results](https://user-images.githubusercontent.com/26823018/76549465-e20a7780-6466-11ea-8d82-b72eab8d8e93.jpg)

**Comment by mbroz2** [comment]
If I'm understanding the proposal correctly, the idea is that the sections in the sidebar that do not have any matching guides would disappear?  If so, I'd like to prose we instead always keep the entire ToC, but disable (grey out) the subsections that have no results and provide a hover over messagealong the lines of "No search results in [section]."  
The reason for this approach is that I'm concerned that a new user that follows a link (internal or external) to our guides (a common one https://openliberty.io/guides/?search=microprofile&key=tag) might otherwise be led to believe that we only have the sections under which the results are present under.
Also, it may otherwise seem odd to see the ToC shrinking as the user types into the filter, and then reset to its entirety once all the guides have been filtered out.

**Comment by mdenby** [comment]
So for the tablet view--when the user closes the sidebar navigation, let's add a space above the top category and have a table of contents menu. Here's an example of what Megan did before--it keeps it consistent. 
![Screen Shot 2020-03-20 at 3 32 46 PM](https://user-images.githubusercontent.com/26823018/77201134-588c2280-6ac2-11ea-854d-702bc0f6798f.png)

**Comment by ellenwyllie** [comment]
I’m also wondering how the search should work on mobile. So, say you search for ‘maven’ and there are results across different categories. How do you know which subcategory to open to find the search results? Or should the subcategories automatically open for the ones with search results?
<img width="376" alt="Screen Shot 2020-03-20 at 2 43 23 PM" src="https://user-images.githubusercontent.com/22085207/77202552-8ec6a380-6abc-11ea-86cc-a348db1767fb.png">

**Comment by mbroz2** [comment]
I think that's another benefit of greying out sections that don't match the search criteria, since that would address this issue as well.

**Comment by yeekangc** [comment]
@gkwan-ibm, can we provide the team an updated view of the categories based on the latest set of guides available?

**Comment by mbroz2** [comment]
@ellenwyllie @gkwan-ibm @yeekangc 
I believe the best way to move forward is for @ellenwyllie to deliver the current version of the json file to the guides-common branches.
Then we should open an issue in guides-common to update the file to reflect the current state of guides and what sections they should be under (I'm guessing owned by @gkwan-ibm) and mark that issue as blocking this one.
The reason for this approach is that it gives the guides team a chance to try the new flow before this goes live on the site and decouples the redesign work that Ellen owns with the organization of the guides work that the guides team owns.

**Comment by ellenwyllie** [comment]
The json file is in the Guides_Redesign branch in the guides-common repo: https://github.com/OpenLiberty/guides-common/blob/Guides_Redesign/guide_categories.json. 
The guides team is welcome to edit it, but if they want to see the changes they make on the demo site then we should push the file to the master branch.

**Comment by yeekangc** [comment]
It will be helpful to have a way to review it live.  Thanks, Ellen, Michal.
