### ISSUE TITLE
Server Config Iframe Scrolling Updates

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1128]
Design would like to update the scrolling on the pages with iframes. See the comments on #802 for background on this issue. Here is what they would like to do:

Remove the iframe from the main body copy. Having three scrollable areas is confusing. When the user scrolls through the main content it should just scroll the page.

Show the scrollbar for the main content/page as the user scrolls so they can see their progress.

In the sidebar, if it is scrollable, show a scrollbar all the time.

When the user scrolls to the bottom of the main content, the footer scrolls into view.

**Comment by mbroz2** [comment]
Note: first, the Server Config page should be rendered like the Features, General References, and Server commands (using divs instead of iFrames).  Once that's accomplished the scrolling fix should be the same as the one applied in #1129, #1130, and #1133.

**Comment by ellenwyllie** [comment]
Michal and I agreed to leave the iframe for now because there is a lot of javascript code that depends on it. So I have fixed all the scrolling issues without removing the iframe.
