### ISSUE TITLE
Server Feature Scrolling Updates

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1129]
See the comments on #802 for background on this issue. Here is what they would like to do:

Having three scrollable areas is confusing. When the user scrolls through the main content it should just scroll the page.

Show the scrollbar for the main content/page as the user scrolls so they can see their progress.

In the sidebar, if it is scrollable, show a scrollbar all the time.

When the user scrolls to the bottom of the main content, the footer scrolls into view.

**Comment by mbroz2** [comment]
Note: #1129, #1130, and #1133 will likely have the same fix.
