### ISSUE TITLE
Microprofile Docs Iframe Scrolling Updates

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1132]
Design would like to update the scrolling on the pages with iframes. See the comments on #802 for background on this issue. Here is what they would like to do:

Remove the iframe from the main body copy. Having three scrollable areas is confusing. When the user scrolls through the main content it should just scroll the page.

Show the scrollbar for the main content/page as the user scrolls so they can see their progress.

In the sidebar, if it is scrollable, show a scrollbar all the time.

When the user scrolls to the bottom of the main content, the footer scrolls into view.

**Comment by mbroz2** [comment]
#1131 & #1132 would have the same fix, if any. Currently, the generated javadoc provides the iframes. To remove the iframes, we would either need to write a processor to remove the iframes from the generated javadoc, or (the better, safer approach) change the javadoc behavior to provide an output without iframes.

**Comment by k8vance88** [comment]
Will be fixed with #1131
