### ISSUE TITLE
Add Featured Tags & Tags to Blog Posts

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1137]
The new Blog design includes tags for blog posts. We need to add these tags and also decide which tags will be "Featured" on the blog.

**Comment by cajaygle** [comment]
The design already has tags for blog posts and featured tags on the blog page.  what more design details are needed?

**Comment by cajaygle** [comment]
Design needed for what is shown when a tag is clicked on and the blog page is filtered.

**Comment by mdenby** [comment]
![Blog_Page Copy](https://user-images.githubusercontent.com/26823018/58976523-a8993300-8795-11e9-9580-eed2bdee4d02.jpg)
![5_Blog_All_TABLET Copy 2](https://user-images.githubusercontent.com/26823018/58976526-aa62f680-8795-11e9-93a1-99a4ff4f8a3e.png)
![Blog-Mobile Copy 2](https://user-images.githubusercontent.com/26823018/58976528-ab942380-8795-11e9-9d19-23f78c31e840.png)

**Comment by mbroz2** [comment]
In the event that many tags are listed as "Featured Tags", we'll only display the first 'x' that fit on the first two lines.

**Comment by mbroz2** [comment]
This is ready for development.  The only part that is not finalized is how (or if) tags for individual blog 'cards' will be displayed.  Until we have the finalized designs for that, we'll not do anything regarding exposing the tags of a blog on the card in /guides (they'll only be shown on the actual blog page).  This is the current behavior on ol.io.
