### ISSUE TITLE
Change padding for Microprofile intro page

### ISSUE THREAD

**Issue by TreeHanh** [OpenLiberty/openliberty.io#1139]
Need to get rid of the blue padding on https://openliberty.io/docs/intro/microprofile.html. New design can be seen below with white padding instead set for the max-width.

![3](https://user-images.githubusercontent.com/18586040/56227755-32553b80-6044-11e9-8925-dde7027600b5.jpg)

**Comment by mbroz2** [comment]
@TreeHanh is it intended for the sub-header's styling to span wider than the content? aka, the styling for "Rapidly deploy cloud-native Java microservices at scale" is wider than the title and content under it.

**Comment by TreeHanh** [comment]
@mbroz2 Yes, the styling (yellow bar) will span wider than the content. 

As for the static guides with no right-column content see the attachment below. 
![Example](https://user-images.githubusercontent.com/18586040/56687372-1be25c00-66a4-11e9-87d7-d84369e71f06.jpg)

**Comment by steven1046** [comment]
For reference, https://openliberty.io/guides/cloud-ibm.html is the guide with no code to show on the right side.

**Comment by steven1046** [comment]
For the guide with no code pane, I think https://github.com/OpenLiberty/openliberty.io/issues/1177 addresses a further redesign than removing the blue padding on the sides of that guide as it will make the guide full width.
