### ISSUE TITLE
Provide a means for feedback in guides if poor rating was received

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1158]
We should make it easy (and encourage) a user to provide us feedback for a guide if they rated it "dislike" or "extreme dislike".  The simplest implementation would be to make it as easy and inviting as possible for them to open an issue for the guide (we already have the link for it right above the review).

For this issue, we want to avoid any 'forms' directly on the site as that would necessitate a backend DB,  which is why we want to use issues in GH for the feedback and we just need to make that process as easy as possible.

As part of this work, we should also look into making it more clear when a user provided feedback.  I think adding a simple message below the rating like "Thank you for your feedback." would suffice.

**Comment by mdenby** [comment]
A screen for both "positive" smiley faces. Please note that I've moved the feedback smiley faces up in the bottom section.

![Positive Feedback](https://user-images.githubusercontent.com/26823018/58735011-1ecd1c80-83c7-11e9-920e-2d55a89f429b.png)

A screen for both "negative" smiley faces. This will take them to Github to open an issue. 

![Negative Feedback](https://user-images.githubusercontent.com/26823018/58735040-33a9b000-83c7-11e9-953e-9c3befc4f8a6.png)

**Comment by mdenby** [comment]
[Feedback redlines.zip](https://github.com/OpenLiberty/openliberty.io/files/3257408/Feedback.redlines.zip)
