### ISSUE TITLE
User review feedback on the single pane guide's site

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1165]
There's one guide that doesn't have any code to display on the code pane from end-to-end, thus it's designed to display as a single pane. See here for the draft: https://draft-guides.mybluemix.net/guides/cloud-ibm.html

We recently had this guide user reviewed and there're some feedback, we think it's worth mentioning, or need a fix. 

- [x] The massive chunk of whitespace between sections are not as friendly, ie, the white space between “why use kubernetes...” and “what you’ll learn” looks out of place.
- [x] The copy button in the code commands is only grey i.e. it does not contain the traditional copy image used on other guides.

**Comment by evelinec** [comment]
@steven1046 FYI.

**Comment by evelinec** [comment]
This draft guide is planning to be publish in the next cycle, we need to have at least the second point fixed. Thanks.

**Comment by evelinec** [comment]
@steven1046 thank you for the quick fix. would you let us know when the fix is in `master` branch? Thank you.

**Comment by steven1046** [comment]
Yes

**Comment by steven1046** [comment]
@evelinec this is in master now.

**Comment by evelinec** [comment]
Looks good on our draft site running with master branch UI code. Thank you @steven1046
