### ISSUE TITLE
Guide cards missing hover text when the screen is small and text cutoff

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#117]
For example:
![image](https://user-images.githubusercontent.com/6392944/35286615-1babbb4a-0026-11e8-9f88-0cbb9395d2c0.png)

The text is cutoff because of a lack of space, but we don't have hover text to show what the full text is.

**Comment by kinueng** [comment]
The guide card is also cutoff in the `Related Guides` in the guides

https://openliberty.io/guides/bulkhead.html#related-guides
![image](https://user-images.githubusercontent.com/31117513/37782971-44c1bbd2-2dc2-11e8-9675-576c2c47cc86.png)
