### ISSUE TITLE
The single pane guide design is too different from the multipane

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1177]
There's one guide that doesn't have any code to display on the code pane from end-to-end, thus it's currently being designed to display as a single pane. See here for the draft: https://draft-guides.mybluemix.net/guides/cloud-ibm.html

We had gotten multiple user experience feedback that this guide looks very different, and thus confusing, in terms of the design, compare to all of the other guides that are in multipane. We would like some design improvement on that.

**Comment by evelinec** [comment]
@yeekangc @cajaygle @mbroz2 FYI.

**Comment by yeekangc** [comment]
We have a case here with the IBM Cloud guide under development.  It feels awkward especially if you are used to the multi-pane design already.  Makes you wonder if something is wrong.

@mdenby @cajaygle, can the team take a look?

@gkwan-ibm

**Comment by cajaygle** [comment]
If you look at the Cloud guide alone it looks fine.   it is different from the other guides, but the static and interactive guides are also different from each other.   I'm not sure this is really going to cause user confusion.  I'm not sure what a solution is.  I definitely don't think it makes sense to present a code pane that is empty for the entirety of the guide -- that will surely look like a problem to users.   

@yeekangc @evelinec @gkwan-ibm Do you have suggestions for how to present this differently?

**Comment by yeekangc** [comment]
If it is used independently, yes.  If it will be used in a series as part of a broader context for a track, workshop or otherwise, it may throw users off.

The interactive guides don't feel that different since there is the basic layout there.

I don't think we should show an empty code pane -- not advocating for that -- but I believe some minor visual tweaks can make it better.

The main issue from what I can tell is with the TOC pane and perhaps the orange border around it.  If we will simply put it back, it may do the trick?  A bonus will be to make it collapsible too?

**Comment by mdenby** [comment]
@yeekangc So I just looked at the guide this morning and I kinda see what you mean. I wonder if we can have the single pane guide stretch the entire width of the screen--like the multi-pane guide does. And also, add the ability to close the TOC and have that orange stripe between the TOC and guide content.

**Comment by yeekangc** [comment]
@mdenby, I think that would be good and should make everything consistent if can be done.

**Comment by mdenby** [comment]
@yeekangc Is this something that I can remove 'design' from and move over to development? Or is there something more that needs to happen on my end like a mockup?

1. Make the single pane guide stretch the entire width of the screen--like the multi-pane guide does
2. Add the ability to close the TOC 
3. Have that orange stripe between the TOC and guide content

**Comment by yeekangc** [comment]
Looks like @mbroz2 already removed the tag and moved this issue to the backlog.  Thank you!
