### ISSUE TITLE
[IE Only] Overflowing link and code block on narrow browser width

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/openliberty.io#119]
Links will overflow past the content width, creating unwanted empty scrollable space on the right. This happens on Google Chrome and Safari (both browsers on mobile and desktop), and not Firefox. Firefox wraps URL lines on the **slashes** as well as hyphen, so it does not have a problem with the URLs being too long.

One easy example to see this issue is in the [Docker guide](https://openliberty.io/guides/docker.html) using the iPhone 7 mobile view.
![image](https://user-images.githubusercontent.com/689163/35461890-4c0b694e-02af-11e8-9e09-5dea9f18ea68.png)

Here, showing other shorter URLs exhibiting the same issue when the browser width is narrow enough. Again, in Google Chrome.
![out](https://user-images.githubusercontent.com/689163/35461770-d2e34f6e-02ae-11e8-9105-1429a8851cce.gif)

**Comment by kevinwlau** [comment]
Proposed fix is adding the `overflow-wrap: break-word;` CSS styling to the `#guide_content a` selector.

**Comment by kevinwlau** [comment]
#121 fixes this issue in Chrome and Safari, but is still broken in IE 11

**Comment by steven1046** [comment]
Moving to backlog since it's not fully fixed yet.

**Comment by lavenal** [comment]
Overflow behavior is also shown for text styled with <code> block.
