### ISSUE TITLE
When saving a guide locally the Nice Work link shows up twice

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1194]
`Nice work! Where to next?`link shows up twice on the TOC, when the webpage is saved and launched locally. 

![image](https://user-images.githubusercontent.com/33134427/58185997-0d2a9d00-7c82-11e9-822f-88027bc88f79.png)

Step to reproduce: 
1. Open a guide on ol.io, ie, https://openliberty.io/guides/microprofile-health.html
2. Click File > Save Page As..
3. Save the page
4. Open the page on a web browser, FF/Chrome 
5. The `Nice work! Where to next?`link shows up twice on the TOC

**Comment by evelinec** [comment]
@yeekangc FYI

**Comment by mbroz2** [comment]
Since the guides are saved for offline mode for labs/conferences/events (as a backup in case of poor internet), we should try and address this.
