### ISSUE TITLE
Find a way to support relative image paths for different root directories

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#120]
# Problem
Currently we have all of the images for the website under one folder.
> https://github.com/OpenLiberty/openliberty.io/tree/master/src/main/content/img

This includes all of the blog post images and guide images.  Because we store all images under one folder at the root dir of the website, it forces asciidoc files to have references to images to begin with the root folder `/img`.  (I know this might be confusing).

For example, we have an guide that is planning to use an image file.  The image file is packaged with the guide repository.  In the guide, the assumption is that the asciidoctor link is relative to the root folder of the guide repository.  All is good when rendering the asciidoctor file on GitHub.

> https://github.com/OpenLiberty/draft-guide-rest-cdi/blob/master/README.adoc

And the image path is `image::resources/diagram.png[Diagram, 450, , align="center"]`.

However in production, the image link is broken.
![image](https://user-images.githubusercontent.com/31117513/35461937-7e74c3f8-02af-11e8-95ff-ab58d0ab633e.png)

The fix is to change the asciidoc to change the path to
`image::/guides/draft-guide-rest-cdi/resources/diagram.png[Diagram, 450, , align="center"]`.

This is a brittle fix because of the hardcoded github repository name in the path.  It would be better to find a way to suppose `resources/diagram.png` for both GitHub and openliberty.io.

# Asciidoctor imagesdir attribute?

Maybe there is a way to set the relative path of images per asciidoctor?

  | You can set the imagesdir attribute multiple times in your document. This technique is useful if you store images for different parts, chapters, or sections of your document in different locations.
-- | --

src: http://asciidoctor.org/docs/user-manual/#setting-the-location-of-images

**Comment by kinueng** [comment]
Another example where it would be nice to have the images show up on GitHub and openliberty.io

https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_posts/2018-01-12-feature-detection-open-liberty-tools.adoc

**Comment by steven1046** [comment]
This is fixed by https://github.com/OpenLiberty/openliberty.io/pull/1070, and the guides no longer have to specify their full path.
