### ISSUE TITLE
Links won't open in a new tab on server command topics 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/openliberty.io#1205]
When you try to open the links under the 'See also' sections of the server command pages, you get a 404 error. 

The links work otherwise, but users should be able to open these related links in a new tab.

I'll look into the linking methods used in these server command topics versus the linking methods used elsewhere on ol.io where this issue doesn't occur.

**Comment by mbroz2** [comment]
For example, on https://www.openliberty.io/docs/ref/command/ if a user opens "server start" in a new window they'll get a 404 because the URL is https://www.openliberty.io/docs/ref/command/server-start.html instead of https://www.openliberty.io/docs/ref/command/#server-start.html

**Comment by mbroz2** [comment]
Also the links:
See also: * Start an Open Liberty server in the foreground. * Start an Open Liberty server as a background process.
are broken even when opened normally (also because they're missing the hash)

**Comment by Charlotte-Holt** [comment]
@mbroz2 @lauracowen These are all working now:

- https://openliberty.io/docs/ref/command/#server-create.html
- https://openliberty.io/docs/ref/command/#server-debug.html
- https://openliberty.io/docs/ref/command/#server-dump.html
- https://openliberty.io/docs/ref/command/#server-help.html
- https://openliberty.io/docs/ref/command/#server-javadump.html
- https://openliberty.io/docs/ref/command/#server-list.html
- https://openliberty.io/docs/ref/command/#server-package.html
- https://openliberty.io/docs/ref/command/#server-pause.html
- https://openliberty.io/docs/ref/command/#server-resume.html
- https://openliberty.io/docs/ref/command/#server-run.html
- https://openliberty.io/docs/ref/command/#server-start.html
- https://openliberty.io/docs/ref/command/#server-stop.html
- https://openliberty.io/docs/ref/command/#server-version.html

Let me know if you see any further updates that need to be made on this one. Thanks!
