### ISSUE TITLE
Direct links to doc content don't render

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1206]
Direct links to doc topics don’t display properly. eg https://openliberty.io/docs/ref/general/#/docs/concept/sync_async.html If I navigate to that location, the topic displays fine. If I click the link directly (Firefox or Chrome), the topic content doesn’t display:

**Comment by steven1046** [comment]
Direct links work on https://demo1-openlibertyio.mybluemix.net/docs/ref/general/#runnablejarfiles.html which is latest as of May 3, so it is a recent regression.

**Comment by steven1046** [comment]
The bug is due to the structure of the https://github.com/OpenLiberty/docs where one of the general references is in docs/concept/ instead of docs/ref/general/

**Comment by mbroz2** [comment]
Issue moved to [OpenLiberty/docs #317](https://github.com/OpenLiberty/docs/issues/317) via [**ZenHub**](https://www.zenhub.com/)
