### ISSUE TITLE
OL Logo and Badge page on site, assets into github

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#1212]
Create a page on the site (linked from footer) with OL logos and badges, along with the usage rights.
Add assets into github and link from webpage

**Comment by NottyCode** [comment]
@cajaygle repo is here: https://github.com/OpenLiberty/branding-assets

**Comment by mbroz2** [comment]
Scope of the issue: place content in github repo (logos & usage/legal statements) & a page on the site to expose them.

**Comment by barecode** [comment]
https://github.com/OpenLiberty/branding-assets remains empty.

**Comment by barecode** [comment]
Duplicated by #1463 - any progress on this?

**Comment by NottyCode** [comment]
It remains empty while we get words on the T&Cs for use since you can't distribute trademarks under an open source license.

**Comment by NottyCode** [comment]
Renamed branding-assets to logos since that seems more in keeping with expectations. So correct url is now https://github.com/OpenLiberty/logos

**Comment by barecode** [comment]
OK, thanks!

**Comment by mbroz2** [comment]
Add link to https://github.com/OpenLiberty/logos in the footer, after License

**Comment by ellenwyllie** [comment]
Are we happy with something like this for the logos link in the footer?
<img width="1236" alt="Screen Shot 2020-04-30 at 10 59 42 AM" src="https://user-images.githubusercontent.com/22085207/80732290-b7858400-8ad1-11ea-937d-aa54d000a5d5.png">

**Comment by mbroz2** [comment]
Looks good, just plz make sure there's no issues at different widths (though I don't expect any).

**Comment by barecode** [comment]
Looks great - thanks @ellenwyllie
