### ISSUE TITLE
Clicking on a feature with multiple versions doesn't update the title (browser tab)

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1221]
Go to https://openliberty.io/docs/ref/feature/#localConnector-1.0.html.
Click on Java Database Connectivity in the table of contents on the left.
You can see that the browser tab's title still says the old feature you were on:
![image](https://user-images.githubusercontent.com/6392944/59611003-25a2a180-90e0-11e9-9555-7240d01e8924.png)

**Comment by mbroz2** [comment]
Also, the ToC can disappear (when clicked on a feature with multiple versions) until the user scrolls
![image](https://user-images.githubusercontent.com/3076261/60068741-9bf16600-96d5-11e9-82e5-a91c06b6ef93.png)
