### ISSUE TITLE
Docs topic doesn't retain scrolling location when click to another tab and back

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1223]
If I've scrolled down the page in one of the doc topics (eg https://draft-openlibertyio.mybluemix.net/docs/ref/general/#rest_clients.html), then click to a different tab, then click back to the original tab, the topic jumps back to the top of the page. It doesn't happen *every* time but most times.

This has been observed on both Firefox and Chrome on Mac.

**Comment by mbroz2** [comment]
Might be related to #1211
