### ISSUE TITLE
Redirect server config pages to a hashed version

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1228]
https://openliberty.io/docs/ref/config/ssl.html should redirect to https://openliberty.io/docs/ref/config/#ssl.html just like https://openliberty.io/config/rwlp_config_ssl.html does.

**Comment by steven1046** [comment]
It's still in progress, we need to not continuously redirect if the new uri is the same as the old one.

**Comment by steven1046** [comment]
/docs/ref/config/*=/docs/ref/config/# does not work because the new uri is within the redirect so it keeps redirecting.

**Comment by steven1046** [comment]
Simply adding a wildcard redirect from /docs/ref/config/* to /docs/ref/config/# which is supposed to replace the url after /docs/ref/config prepended with a hash does not work since it causes a recursive redirect. I tried stopping the redirect at /docs/ref/config which loads the page but doesn't stop the server from redirecting the iframe href. So even though we set the iframe href correctly after the main page loads, it redirects the iframe to /docs/ref/config which contains the whole site in the iframe again.

**Comment by steven1046** [comment]
If we remove the iframe from config in the future, it will be easy to add this redirect in and stop the redirect before it reaches /docs/ref/config so it doesn't recursively redirect.

**Comment by steven1046** [comment]
This might be fixed by using Antora for docs.

**Comment by k8vance88** [comment]
This will be handled as part of #1243
