### ISSUE TITLE
Copy icon appears beside title

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/openliberty.io#1233]
@steven1046 

UI Issue:

- a copy icon appears beside the title that should not be there
- noticed issue on guide-rest-client-angular guide

![image](https://user-images.githubusercontent.com/46586499/59950639-887b9c00-9444-11e9-92ae-d5fe05cbe6fa.png)

When you click the icon, it copies a weird version of `artists.json` file (which is the first file listed on the right-pane):

```
1[
 2    {
 3        "name": "foo",
 4        "albums": [
 5            {
 6                "title": "album_one",
 7                "artist": "foo",
 8                "ntracks": 12
 9            },
10            {
11                "title": "album_two",
12                "artist": "foo",
13                "ntracks": 15
14            }
15        ]
16    },
17    {
18        "name": "bar",
19        "albums": [
20            {
21                "title": "foo walks into a bar",
22                "artist": "bar",
23                "ntracks": 12
24            }
25        ]
26    },
27    {
28        "name": "dj",
29        "albums": [
30        ]
31    }
32]
```

I have reproduced this problem a few times now.

Potential steps to reproduce problem:

- scroll all the way down
- click smiley face feedback
- randomly scroll up and down
- scroll back down, click the third file on the right-pane
- scroll all the way to the top, and the copy icon should be there

**Comment by steven1046** [comment]
The issue is with the hover-off code for sections where the copy icon appears and I think this issue exists in static and interactive guides.
