### ISSUE TITLE
A copy icon shows up beside the guide's title

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1234]
A copy icon appears beside the title that should not be there

![image](https://user-images.githubusercontent.com/46586499/59950639-887b9c00-9444-11e9-92ae-d5fe05cbe6fa.png)

When you click the icon, it copies a weird version of `artists.json` file:

```
1[
 2    {
 3        "name": "foo",
 4        "albums": [
 5            {
 6                "title": "album_one",
 7                "artist": "foo",
 8                "ntracks": 12
 9            },
10            {
11                "title": "album_two",
12                "artist": "foo",
13                "ntracks": 15
14            }
15        ]
16    },
17    {
18        "name": "bar",
19        "albums": [
20            {
21                "title": "foo walks into a bar",
22                "artist": "bar",
23                "ntracks": 12
24            }
25        ]
26    },
27    {
28        "name": "dj",
29        "albums": [
30        ]
31    }
32]
```

The problem was reproduced a few times now. Tested on Safari. The problem may be generic. 

Potential steps to reproduce problem on this guide: https://openliberty.io/guides/rest-client-angular.html. 

- scroll all the way down
- click smiley face feedback
- randomly scroll up and down
- scroll back down, click the third file on the right-pane
- scroll all the way to the top, and the copy icon should be there

**Comment by evelinec** [comment]
@steven1046 FYI

**Comment by steven1046** [comment]
Duplicate of #1233

**Comment by evelinec** [comment]
Didn't know that. Close dup.
