### ISSUE TITLE
Static guide command box overflow is hidden

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1235]
Copied from email:
On the Draft site, the green command boxes have a UI issue. When the command is really long, it goes past the scope of the box, and you can't scroll to see the rest. Previously, when the commands were really long, it would go onto the next line.
 
Here's the draft site that i noticed this issue on: https://draft-guides.mybluemix.net/guides/cloud-azure.html#creating-a-container-registry

![image](https://user-images.githubusercontent.com/46586499/60037339-4a1df100-967f-11e9-9854-2490af23694f.png)

**Comment by NimG98** [comment]
Issue also occurs on openliberty.io site, in addition to the draft site.

From https://openliberty.io/guides/docker.html#containerize-your-application
![image](https://user-images.githubusercontent.com/46586499/60523207-5544d280-9cb8-11e9-8741-33a67296283d.png)

**Comment by mbroz2** [comment]
For the solution, wrap text to next line (as necessary); don't add scrollbars.
