### ISSUE TITLE
Can't use left navigation as normal links

### ISSUE THREAD

**Issue by sdaschner** [OpenLiberty/openliberty.io#1240]
The links on the left side under "Features" can't be clicked as normal links, i.e. when using the middle mouse or Ctrl + click in Chrome this opens the link in a new tab. On the page, the only way to open up the feature is via normal click, which apparently triggers some JS functionality.

It would improve the usability of the page to use these links like normal links.

Example: https://openliberty.io/docs/ref/feature/#jpa-2.2.html

**Comment by steven1046** [comment]
Change the toc divs to <a> tags, and make sure the links direct to a hash instead of just the .html

**Comment by k8vance88** [comment]
Will be fixed by antora
