### ISSUE TITLE
"Cloud" does not appear on Tags section

### ISSUE THREAD

**Issue by NimG98** [OpenLiberty/openliberty.io#1247]
@steven1046 

`Cloud` is currently not a visible tag for the UI on all cloud guides. Specifying it in the `:page-tags:` field does not make it appear under the "Tags" section on the website.

On the readme for the cloud-aws guide, cloud-ibm guide, and upcoming draft cloud guides:
```
:page-tags: ['Kubernetes', 'Docker', 'Cloud']
```

On the openliberty site:

![image](https://user-images.githubusercontent.com/46586499/60391967-51eaf480-9ac8-11e9-9813-ac6f70ebef7d.png)

**Comment by kinueng** [comment]
Hi @NimG98,
Looks like the website needs to add `Cloud` tag to the whitelist that controls what tags are visible on the website.
https://github.com/OpenLiberty/openliberty.io/blob/eba40da63a812170af81de24fea7d2c04e9d2070/src/main/content/_includes/visible-tags.liquid#L5

**Comment by NimG98** [comment]
Thanks for your help! I've made a pull request to add the `Cloud` tag here: https://github.com/OpenLiberty/openliberty.io/pull/1248

**Comment by NimG98** [comment]
PR has been merged into master, `Cloud` tag is now visible on the site's UI
