### ISSUE TITLE
Location Bar in Code Pane/Source View for Guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1251]
Some users were not able to locate where certain files should go.  The information is in the instructions but it may not be easy to find unless you are in the right place in the guide.

Consider having a location bar indicating where each source file is or should be to make this easier and clearer for users.

![image (3)](https://user-images.githubusercontent.com/4803104/60608165-d2da1280-9d8c-11e9-88fd-a79768ae3ec5.png)

**Comment by yeekangc** [comment]
@mdenby @cajaygle @mbroz2 @steven1046, for your consideration/action.

**Comment by mbroz2** [comment]
another option is to make the hover over for the tab provide the 'full path' for the file, which is 'norm' in most IDEs & text editors.

**Comment by ellenwyllie** [comment]
Maybe we could do something like this:
<img width="973" alt="Screen Shot 2019-08-20 at 4 19 11 PM" src="https://user-images.githubusercontent.com/22085207/63385303-4a2c2b80-c366-11e9-874f-e3bb1f4c2b7c.png">

As Michal said, it's very common for text editors to show the full path when you hover over the file

**Comment by steven1046** [comment]
That seems like an easy solution that will address the issue for people that want to see the full path. And for accessibility we can have it read out the full path.

**Comment by mbroz2** [comment]
Unless @cajaygle @mdenby disagree, lets go with the above hover over behavior since we feel that's what developers would expect.

**Comment by ellenwyllie** [comment]
@yeekangc Do we want to show the path to the file in the `/start` or `/finish` directory? The content shown in the code pane is from `/finish`, but if the user is following along with the guide they would be working in `/start`, right? I'm not sure which way makes more sense.

**Comment by mbroz2** [comment]
My vote is to omit that directory level and just go with the child (so, for example, instead of /start/src/* just have /src/*).  This is similar to what we do in the instruction steps where we tell the user, for example, to ```Replace the ArtistResource class.
src/main/java/io/openliberty/guides/consumingrest/service/ArtistResource.java```

If we did have to choose between /start and /finish, than my vote is /start as that's what the user would be making the change to locally (aka, that's what we're asking them to update).

**Comment by yeekangc** [comment]
Sorry for the delay in response but I concur with Michal.  Don't think we need /start or /finish but if that's needed, /start.

**Comment by yeekangc** [comment]
FYI, @gkwan-ibm.

**Comment by steven1046** [comment]
This is live on the site now. I think Ellen removed the /start and /finish from the path shown.
