### ISSUE TITLE
Explore supporting hashes to a subsection of a doc

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1260]
You can't link to the variable substitution part of the config page overview using https://openliberty.io/docs/ref/config/#serverConfiguration.html#variable-substitution because each hash is treated as a feature name. We should explore to see if we are able to accommodate hashes to sections on the page.  

Edit: sometimes the hash jump works, but javascript gets in the way and the config breadcrumb appears which is wrong.

**Comment by steven1046** [comment]
We need to add javascript to first load the config page behind a hash in the iframe, and then check if a section exists on the page for the other hash in the URL.

**Comment by steven1046** [comment]
The solution should be for all doc pages, since all docs should be able to link to a section on a page.

**Comment by steven1046** [comment]
Some docs have iframes for the main content (config) and others do not so the solution would need to work for both types.

**Comment by k8vance88** [comment]
May be related to #1261 and #1268.  In Chrome, if you navigate to 'https://openliberty.io/docs/ref/config/#batchPersistence.html#batchPersistence/jobStore/dataSource/properties.datadirect.sqlserver&expand=true' does not navigate to the correct place, but seems to work in FF on the first load (only).  FF the second click takes to overview.

**Comment by steven1046** [comment]
This will be fixed by Antora. See https://antora.mybluemix.net/docs/ref/config/1/serverConfiguration.html#_config_merging as an example where you can get a link to each hash on the page. Antora generates a little anchor you can click on which adds it to the url.
