### ISSUE TITLE
Navigation bar needs to be consistent on all pages (except the homepage)

### ISSUE THREAD

**Issue by mdenby** [OpenLiberty/openliberty.io#1273]
The navigation bar should have the same look and behavior throughout the site

**Comment by mdenby** [comment]
So I've made two options--one white and one the same color gradient on the homepage. The tablet and mobile--the color would just change. For the hover issue in #1040 I'm okay with having the header pop down as the user scrolls back to the top of the page. 

<img width="1454" alt="Screen Shot 2020-01-28 at 11 53 02 AM" src="https://user-images.githubusercontent.com/26823018/73286630-e126ca80-41c5-11ea-8cca-59afe61787fc.png">
<img width="1455" alt="Screen Shot 2020-01-28 at 10 39 16 AM" src="https://user-images.githubusercontent.com/26823018/73286632-e126ca80-41c5-11ea-9274-6e91ff5b26ad.png">

**Comment by mbroz2** [comment]
@mdenby if I'm reading between the lines correctly, this issue is for applying our existing header to /docs* and /guides* pages?

**Comment by mdenby** [comment]
@mbroz2 This issue is for the styling of the header--not the navigation. I opened another issue for that because I'm trying to break it into small pieces. The header should be the same color on all of the pages (except the homepage). Next step is the navigation--but that seemed like a bigger thing with the Docs pages.

**Comment by mdenby** [comment]
@NottyCode @mbroz2 @lauracowen I've updated the navigation and reorganized the order of the items too. I think this should be the navigation on all pages and remove the Docs as a microsite. 

For now when the user navigates to Guides it should go here: https://openliberty.io/guides/ 
When they navigate to Docs it should go to the current docs landing page (https://openliberty.io/docs/)

In the future, the docs landing should be replaced by the new docs page. When that happens I'd also like to remove the breadcrumbs because they will be unnecessary then. 

What do you think?

<img width="1452" alt="Screen Shot 2020-01-30 at 3 36 41 PM" src="https://user-images.githubusercontent.com/26823018/73488451-f5f69000-4376-11ea-8cc8-88c9d103c2e8.png">

**Comment by mbroz2** [comment]
I have a small preference to have Guides before Docs as it seems like a more natural order:
Acquire (whether through 'get started' or 'guides'), try/learn (guide), get further information on a topic (docs), then get questions answered, whether prod or dev (Support), and finally stay up to date with updates/news (blog).

I could even see Guides move to the first spot in the header, however, I prefer this order as it seems more logical and 'get started' now has links to guides and especially once #1424 is delivered.

**Comment by lauracowen** [comment]
What @mbroz2 makes sense I think.

**Comment by mdenby** [comment]
@mbroz2 That makes sense to me too.

<img width="1458" alt="Screen Shot 2020-01-31 at 2 48 40 PM" src="https://user-images.githubusercontent.com/26823018/73569617-cdcf6580-4438-11ea-8d39-7848a32c2fb9.png">

**Comment by steven1046** [comment]
I agree with removing the breadcrumb. Guides aren't really under docs in the website navigation either once we release Antora. The /docs page will be replaced with just the overall Docs landing page and the guides won't be under Docs anymore so it doesn't make sense to have the breadcrumb that says docs->guides->guide name

**Comment by steven1046** [comment]
@mdenby can we remove the design needed label as it seems like we can replace the header for docs and guides with the white one that the whole site uses. What color should we use for the guides if we replace the header for guides with the same links that the rest of the site uses?

**Comment by mbroz2** [comment]
Given the current design and the redesign of /guides, I'm not sure the white header will look correct (concerned the white header next to the dark blue background will be jarring).  As such, I think we might need to use the blue header for /guides, or tweak the top portion of the /guides redesign (#1126).

**Comment by mdenby** [comment]
I agree with @mbroz2 to keep the darker header for the pages.

**Comment by mbroz2** [comment]
When we update the header to have both guides & docs (siblings), remove the breadcrumb from guides.

**Comment by ellenwyllie** [comment]
@mdenby I'm a little confused about the colors for the updated nav bar. Is the plan to have it be white on all pages except for the home page and /guides? What about the Get Started page which currently has a transparent background? This doesn't really seem to be addressing the concern that the nav bar isn't consistent

**Comment by mdenby** [comment]
The idea was for it to be purple everywhere. Plus, update the navigation.

**Comment by mbroz2** [comment]
Just to go on the record, I don't mind if the background (and text color) are different for different pages, as long as all other aspects of the styling, behavior, and content remain the same.  
In other words, I have no issues with /downloads, /support, and /blogs maintain their current color scheme of blending into the background (at least the first two) as long everything else remains consistent with the other header style, behavior, and content.

**Comment by ellenwyllie** [comment]
I began implementing this issue with the dark blue navigation across the whole site. However, Melissa and I felt that the dark blue didn't work well with some of the pages. We decided that it would be better to go ahead with the transparent nav bar across the site. The links, behavior and most of the styling will be the same everywhere. The only thing that will change is the background color and the link color.

With the additional links in the nav bar, the Getting Started page had some issues. The links would run into the dark blue section making them difficult to read:
<img width="1146" alt="Screen Shot 2020-04-22 at 2 42 55 PM" src="https://user-images.githubusercontent.com/22085207/80026320-91dff580-84a7-11ea-9084-9efc1548a5ae.png">
We decided to get rid of the green beam and just have a dark blue header similiar to what a lot of the other pages have
<img width="1141" alt="Screen Shot 2020-04-22 at 2 44 11 PM" src="https://user-images.githubusercontent.com/22085207/80026436-bfc53a00-84a7-11ea-8cd4-230ec50f36ae.png">

**Comment by ellenwyllie** [comment]
At certain screen widths in the guides, the breadcrumb contains a hamburger button that opens the table of contents. So we need a new design that has the hamburger button somewhere other than in the breadcrumb (since we are removing the it)
<img width="1154" alt="Screen Shot 2020-04-28 at 2 18 03 PM" src="https://user-images.githubusercontent.com/22085207/80528250-41f7a780-895b-11ea-9138-04f8f478e518.png">
<img width="1151" alt="Screen Shot 2020-04-28 at 2 24 14 PM" src="https://user-images.githubusercontent.com/22085207/80528694-f5f93280-895b-11ea-9de9-6154537d76b1.png">

**Comment by ellenwyllie** [comment]
We could do something similar to what the desktop view does after you click the x button to collapse the toc, but we need to make sure it's obvious how to open the toc:
<img width="1659" alt="Screen Shot 2020-04-28 at 2 40 07 PM" src="https://user-images.githubusercontent.com/22085207/80530658-f1824900-895e-11ea-8394-10e16a8b24c5.png">

**Comment by mdenby** [comment]
I mocked up a little prototype showing the "animation" that we'd like the arrow to do. What's everyone think? https://ibm.invisionapp.com/share/CVO003DZT2F

**Comment by mbroz2** [comment]
Just to make sure I'm following along correctly.... we like the idea of reusing the ToC behavior from full width and applying it this intermediate width (doing away with the breadcrumb ToC button) and we're just trying to figure out how to integrate it such that the interaction is clear to the user?
And if so, the proposal for that is to have the arrow animate a bounce upon resizing to (or first load of) the intermediate width?  And unlike in the first screenshot the ToC slides out like in full width, but it would actually overlay the instruction pane instead?
If yes to all those, then I think that should work well (and provides a better consistency then what we have today regarding the ToC's position & behavior)

**Comment by ellenwyllie** [comment]
@mbroz2 Yes, I think that is all accurate.

**Comment by ellenwyllie** [comment]
Steven pointed out that removing the breadcrumb means that users have no way to change between versions on javadocs since the version picker is inside the breadcrumb. We need to add back the version picker somewhere. @mdenby 

Current nav bar with breadcrumb:
<img width="1334" alt="Screen Shot 2020-05-15 at 2 37 02 PM" src="https://user-images.githubusercontent.com/22085207/82089618-9029dc00-96b9-11ea-8db4-edde949fe311.png">

New nav bar without breadcrumb: 
<img width="1678" alt="Screen Shot 2020-05-15 at 2 39 27 PM" src="https://user-images.githubusercontent.com/22085207/82089797-eb5bce80-96b9-11ea-818d-7eb0c98c1a64.png">

**Comment by mdenby** [comment]
Could we not put the version switcher that we're using for the other pages here?
