### ISSUE TITLE
Features scrollbar disappears when clicking certain features in the TOC

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1280]
Go to https://openliberty.io/docs/ref/feature/ and click on `Java Database Connectivity` or another entry below the first visible features in the viewport in the table of contents. The table of contents scrolls to the top so you can't see what you've selected in the TOC and the scrollbar disappears. It's possible to regain the scrollbar by scrolling down the main page and then the scrollbar reappears.

**Comment by steven1046** [comment]
This is only happening on features that have different versions. The javascript is probably doing something to the whole page refresh when choosing a version.

**Comment by k8vance88** [comment]
Likely fixed by antora
