### ISSUE TITLE
Clicking on a 2nd level config in the TOC doesn't update breadcrumb

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1285]
The reason is that the top of the page isn't yet touching the content under the anchor which it jumps to (just like when you scroll up and down on a config page it doesn't update the breadcrumb until you reach the content exactly). We need to discuss if we want to update the breadcrumb with what is clicked on (and will that affect the position at which we update the breadcrumb when scrolling too?).

**Comment by mbroz2** [comment]
working as designed.
