### ISSUE TITLE
Remove the iframe from the config pages

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1290]
Remove the main iframe for the config content on the /docs/ref/config page. We will need to update the javascript which had a lot of custom code to look into the iframe and update its href and does things when you scroll inside the iframe.

**Comment by steven1046** [comment]
Antora (#1243) may solve this issue by eliminating the iframe.

**Comment by k8vance88** [comment]
Moving to antora will fix this issue.
