### ISSUE TITLE
What third-party logos are we using on the Homepage?

### ISSUE THREAD

**Issue by mdenby** [OpenLiberty/openliberty.io#1300]
@NottyCode @mbroz2 

So this is the list from the Box Note:

(can't have Java EE cos not certified cos of licence)

elastic search
logstash
filebeat
kibana
prometheus
kubernetes
docker
grafana
microprofile
spring
maven
gradle
jenkins

Here's the current design:
![Screen Shot 2019-07-29 at 3.26.24 PM.png](https://images.zenhubusercontent.com/5c587f22df0733a30554ecb5/fa09041d-e479-42f9-aeab-c1536f88fa81)

**Comment by kinueng** [comment]
Closing this issue as aged and the end result was the home page having this design.
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/31117513/211637980-3845a8f7-721c-4e20-adfa-b99b5a38ab03.png">
