### ISSUE TITLE
Add daily Docker image command to Downloads>Development Builds page

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1331]
https://www.openliberty.io/downloads/#development_builds

In the text at the top, if no one objects (eg @NottyCode @gcharters ), can we add a short sentence saying something like "Try out the features in our latest development build in our daily Docker image by running `docker pull openliberty/daily`. " (or more concise if you can).

Maybe we should also rename "development builds" to "daily builds" too. But that's an aside.

**Comment by ellenwyllie** [comment]
Here are the designs showing the maven/gradle/docker commands above the Downloads table:
![Downloads_WideMonitor Copy](https://user-images.githubusercontent.com/22085207/64621854-0304e980-d3ac-11e9-94f9-89a2e946a81a.png)

**Comment by lauracowen** [comment]
Thanks - I don't think it should say "Install Open Liberty". "Get Open Liberty" would be better as it's not really about 'installing'.
