### ISSUE TITLE
Image files with same names fail to build

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/openliberty.io#1349]
We have 2 guides sharing one image file, the build script failed: 

```
Copying guide images to /img/guide

Copying draft guide images to /img/guide

cp: will not overwrite just-created 'src/main/content/img/guide/reactive-inventory-system.png' with 'src/main/content/guides/draft-guide-microprofile-rest-client-async/assets/reactive-inventory-system.png'

The command "if [ $JEKYLL_ENV == "production" ]; then

  cp robots.txt src/main/content/robots.txt      

  ./scripts/build_jekyll_maven.sh

else

  ./scripts/build_jekyll_maven.sh

fi

" exited with 1.
```

Probably need an image folder per guide, as there may be chance that the image files happen to be named the same by different developers.

**Comment by evelinec** [comment]
@steven1046 Thanks.

**Comment by steven1046** [comment]
https://github.com/OpenLiberty/openliberty.io/pull/1348 should fix the build break, but we want to further improve the build process to copy each guide's images to its own folder under /img/guide so that they will not collide if they have the same name. This will also require the guide's metadata to switch from `:imagesdir: /img/guide/` to `:imagesdir: /img/guide/{projectid}`.

**Comment by evelinec** [comment]
Ok, we'll make the corresponding changes when ready. Let us know. 

Current guides that have an image: 

- [ ] Http sessions

- [ ] MP Rest client async

- [ ] Reactive client

- [ ] Guide's template

**Comment by steven1046** [comment]
Checking the builds, the guides get cloned in an undetermined order (not alphabetical) so we can't rely on an image to stay the same if multiple guides have the same image name.

**Comment by ellenwyllie** [comment]
@evelinec I have the build script changes ready to go here: https://github.com/OpenLiberty/openliberty.io/pull/1488. Could you make the corresponding guide changes on the dev branch? Then we can test it out on http://qa-guides-dev.mybluemix.net/ before merging into master.
