### ISSUE TITLE
Small design issues with single pane guide

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#1360]
From @gcharters "FYI was just helping someone with a guide on the inline single column view and it wasn’t clear you had to click on the file section to expand it to see the code. The only indication was the cursor when you hovered over it. Also, the minimization afterwards seemed a little awkward having to click on a separate button. Ie not the inverse of the expand action."

**Comment by carrenelloyd** [comment]
@cajaygle @gcharters Please can you post a link or a screen grab to the screen you are referring to so I know exactly what to look for?

**Comment by cajaygle** [comment]
Go to https://openliberty.io/guides/rest-intro.html and shrink the browser window width until the guide is shown in a single column.

<img width="714" alt="Screen Shot 2019-09-09 at 10 33 27 AM" src="https://user-images.githubusercontent.com/27516391/64539889-4a787080-d2ed-11e9-9b26-c9990af47b72.png">

You click the Create section to see the code.

**Comment by carrenelloyd** [comment]
This is essentially an Accordion Pattern and can behave in a similar way to the Carbon pattern with a few modifications to align with the OL website design. 

https://www.carbondesignsystem.com/components/accordion/code

### **Collapsed**
Add icon: IBM Design Language Chevron Down 
size: 32 px 
HEX: #5e6c8c 
Padding along right margin: 32 px
Adjust the Copy icon so it aligns with the Chevron icon (move to the left so it's not so close to the browser's edge. This would be a global change that would apply to all the Copy icons in the Guide)
![image](https://user-images.githubusercontent.com/53481064/64557616-ee731380-d30f-11e9-87fd-b5eea0a177ed.png)

Full-screen view of Chevron
![image](https://user-images.githubusercontent.com/53481064/64557497-aa800e80-d30f-11e9-8cbe-6bd3ed93a15e.png)



### **Expanded**
In order for the Expanded area to feel like a complete unit, I suggest getting rid of the white horizontal bar that cuts the content area in half. This is the same white line that runs above SystemApplication.java button and below the Collapsable area. 

Remove the Back to Text button (the action will be available on the Chevron button)
example:
![image](https://user-images.githubusercontent.com/53481064/64558026-ef587500-d310-11e9-82be-148c22c49376.png)

Adjust the SystemApplication.java button so it aligns with the rest of the text making room for the green bar:
![image](https://user-images.githubusercontent.com/53481064/64557915-9a1c6380-d310-11e9-9bbe-dd40389f8e3c.png)

Expand the green bar so it runs the entire height of the Expanded area—so it looks like a cohesive unit. 
![image](https://user-images.githubusercontent.com/53481064/64557962-c59f4e00-d310-11e9-909e-9ec188993938.png)

Full Screen View
![image](https://user-images.githubusercontent.com/53481064/64557506-af44c280-d30f-11e9-82e2-8cf4272744cf.png)

**Comment by navaneethsnair1** [comment]
I think the above design will face problem especially in case of hotspot words. The full code might not be in the vicinity of the hotspot. User will have to scroll all the way up or down.
