### ISSUE TITLE
Alphabetical ordering of generated doc is odd

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1393]
Is it intentional that the generated docs are alphabetised with upper-case taking precedence over lower-case?

eg, I was looking for JSON Web Tokens after the features that start "Java..." ("a" is earlier in the alphabet than "S"):

![image](https://user-images.githubusercontent.com/3322532/65317832-72d95800-db94-11e9-98de-88d0178f9e2f.png)

@NottyCode (not sure whether this is set in the website code or in the generated navigation)

**Comment by k8vance88** [comment]
This will not need to be fixed if we move to antora.

**Comment by k8vance88** [comment]
Closing because antora will allow sorting to be configured
