### ISSUE TITLE
Investigate why Travis builds can take a long time to start

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1396]
Our Travis builds (https://travis-ci.com/OpenLiberty/openliberty.io/branches) can take up to a few hours to start once submitted which stalls progress when trying to verify/test something. This is probably since we are part of a shared open source build queue and during M-F peak hours there are not enough resources. We need to investigate if there's something further we can do to speed up the queue time.

**Comment by k8vance88** [comment]
We haven't seen this issue recently. Closing.
