### ISSUE TITLE
"Using Docker containers to develop microservices" page has broken link

### ISSUE THREAD

**Issue by blekione** [OpenLiberty/openliberty.io#1398]
https://openliberty.io/guides/docker.html#building-your-application section has broken link in the paragraph:
"Learn more about this goal on the official `Maven Liberty plug-in repository`. "

It shows 404 error.

Same goes for https://github.com/openliberty/guide-docker#building-your-application

**Comment by mbroz2** [comment]
Issue moved to [OpenLiberty/guide-docker #54](https://github.com/OpenLiberty/guide-docker/issues/54) via [**ZenHub**](https://www.zenhub.com/)
