### ISSUE TITLE
Update codebase to use EE8

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1406]
We had a pull request to do so https://github.com/OpenLiberty/openliberty.io/pull/764 but we had to back out the code due to the build failing to compile with a maven error:
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 1.8
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.418 s
[INFO] Finished at: 2019-09-25T18:55:09+00:00
[INFO] Final Memory: 8M/15M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project openliberty-website: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.8
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Once we can find out how to fix the compilation error then the code can be re-delivered.

**Comment by steven1046** [comment]
https://dzone.com/articles/how-to-fix-invalid-target-release-17-18-19-or-110

**Comment by steven1046** [comment]
The builds use Java 1.7 and our pom.xml specified target 1.8

**Comment by NottyCode** [comment]
Resolved as of #1604 we not only updated to Java SE 8, but also make use of Jakarta EE 8 and MicroProfile
