### ISSUE TITLE
Update "Get Open Liberty" instructions for Maven

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1420]
Currently, at https://openliberty.io/downloads/, we show the below for Maven:

```
<dependency>
    <groupId>io.openliberty</groupId>
    <artifactId>openliberty-runtime</artifactId>
    <version>[19.0.0.10,)</version>
    <type>zip</type>
</dependency>
```

Should show the portion for specifying the plugin.  And, with the latest LMP (3.x and above),  it's simpler to specify a specific version of runtime too.  Consider the below instead:

```
<build>
    <plugins>
        <plugin>
            <groupId>io.openliberty.tools</groupId>
            <artifactId>liberty-maven-plugin</artifactId>
            <version>3.1.0</version>
        </plugin>
    </plugins>
</build>
```

This would download the latest version of the runtime from Maven Central for you and use that by default.

If a particular version is needed, one can specify the below in addition to the above in their POM:

```
<properties>
    <liberty.runtime.version>19.0.0.10</liberty.runtime.version>
</properties>
```

@cherylking @chyt @lauracowen @yasmin-aumeeruddy @ellenwyllie @mbroz2

**Comment by yeekangc** [comment]
Or, instead of the doing it under <properties> in the POM file, one can do the below from command line too:

```
mvn liberty:dev -Dliberty.runtime.version=19.0.0.10
```

This would launch directly into dev mode -- the plugin obviously needs to be specified in the POM file already -- and use specified runtime version, which is 19.0.0.10 in this case.

**Comment by lauracowen** [comment]
Whatever we decide is the most usable/clear/concise approach, I'll use it in the release blog posts too.

**Comment by yeekangc** [comment]
Tagging @NottyCode @gcharters @sdaschner for their opinions.

**Comment by sdaschner** [comment]
:+1: for using Maven properties. As you wrote, folks can specify the version in either the pom.xml, via CLI, or leave it blank for the latest version, which I think is the perfect balance (minimalistic, yet flexible).

**Comment by lauracowen** [comment]
Call today:
- Maven and Gradle coordinates are fine on the Downloads page.
- Docker tab needs to be equivalent with the `FROM open-liberty` statement for users to include in their own dockerfile (`docker run` approach is not best practice; users should be adding image into their own dockerfile, not just running our image and mounting file system).
- @arthurdm  also suggested including a link to the github page for the docker file: https://github.com/OpenLiberty/ci.docker#docker-hub-images but @NottyCode has concerns about doing this.

**Comment by mbroz2** [comment]
Also, to match docker we would add link for maven to something like https://github.com/OpenLiberty/ci.maven 
and for gradle to something like https://github.com/OpenLiberty/ci.gradle

**Comment by mdenby** [comment]
How about something like this? The purple copy is just a placeholder.

<img width="1182" alt="Screen Shot 2019-12-09 at 5 04 28 PM" src="https://user-images.githubusercontent.com/26823018/70477106-1b1cff80-1aa6-11ea-9d2a-8c7351ba5945.png">

**Comment by ellenwyllie** [comment]
"Information about learning more about using Maven" sounds quite wordy to me. Maybe something like "Get more information about using Maven with Open Liberty" would work better?

**Comment by mdenby** [comment]
Sure! I'm fine with that :-)

**Comment by yeekangc** [comment]
I will link to https://openliberty.io/guides/containerize.html for Docker too.

**Comment by mbroz2** [comment]
I think we should also not display the actual link, but rather something like
"Get more information about using Maven with Open Liberty [here](https://openliberty.io/guides/containerize.html#building-your-docker-image)"

**Comment by ellenwyllie** [comment]
I also think it would make more sense to have the links after the code snippets.

**Comment by lauracowen** [comment]
> I think we should also not display the actual link, but rather something like
> "Get more information about using Maven with Open Liberty [here](https://openliberty.io/guides/containerize.html#building-your-docker-image)"

Yes, but not the word "here". The link text needs to be meaningful, eg "Find out [how to use Maven with Open Liberty]." or "Find out how to use Maven with Open Liberty in our [guide]." (not totally blown away by either of those examples tho...)

**Comment by mbroz2** [comment]
I like either making the entirety of "Get more information about using Maven with Open Liberty" a link, or @lauracowen first suggestion of "Find out [how to use Maven with Open Liberty]"

**Comment by mbroz2** [comment]
We'll do the latter choice of the two above.
