### ISSUE TITLE
Add "Learn More" button/link for graphs on homepage

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1425]
Add "Learn More" button/link for graphs on homepage that will link to a blog post regarding the performance test that led to said graphs.
![image.png](https://images.zenhubusercontent.com/59e8c568a468affe6df751e7/433476fc-f2cc-49fc-a312-1dc47464d983)
![image.png](https://images.zenhubusercontent.com/59e8c568a468affe6df751e7/04288d74-67bf-4d5b-9810-0279244a73f8)

**Comment by lauracowen** [comment]
When the blog post about the recent performance work is published, we'll paste the URL in here. The Learn more button can then point to that.

**Comment by jhanders34** [comment]
The blog post just published:  https://openliberty.io/blog/2019/10/30/faster-startup-open-liberty.html

**Comment by lauracowen** [comment]
Nice, thanks :)

**Comment by jhanders34** [comment]
I see the Learn more button added to the webpage now, but it doesn't look like the other ones on the front page.  It has:

    Learn
    more

instead of

    Learn more

**Comment by jhanders34** [comment]
From talking with Michal this appears to be an issue one  some browsers on some OSs.  I see on RHEL 7.7 Firefox, but Chrome is fine.  I had a colleague do it on Firefox on MacOS and did not see the same behavior.  All the other Learn more buttons on my firefox though look correct.

**Comment by mbroz2** [comment]
This is likely an issue specific to FF ESR on Linux, and probably similar or same to what was addressed in this commit: https://github.com/OpenLiberty/openliberty.io/commit/b9bec807289de64a02ad4ecd0ee76854bf1504b7
@ellenwyllie

**Comment by ellenwyllie** [comment]
I downloaded Firefox ESR on my mac and it's correct. It seems like a linux specific issue. I'm guessing that the font renders a bit differently which makes it stretch onto 2 lines. I think I have a solution and I'm going to put it on the dev site so we can test it out.
