### ISSUE TITLE
Custom tabs

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1426]
We would like to have customized tabs other than OS tabs but like OS tabs, like the following:

```
[.tab_link.centos_link]
`*CENTOS*`
[.tab_link.minishift_link]
`*MINISHIFT*`
[.tab_content.centos_section]
--
It is CENTOS.
--
[.tab_content.minishift_section]
--
It is minishift.
--
```
The first tab should be the default.

**Comment by gkwan-ibm** [comment]
@MaiHameed

**Comment by gkwan-ibm** [comment]
@yeekangc

**Comment by steven1046** [comment]
Lets programmatically detect the OS name from the tab_link_<os_name> and if javascript can't detect what os the user is on, then it will load the first tab supplied in the asciidoc.

**Comment by steven1046** [comment]
@gkwan-ibm this is in master of the website repo now. You can test the changes in the QA/draft environments using the schema you listed above.

**Comment by yeekangc** [comment]
This should come in handle for the Open Tracing update to support Jaeger too (if we can use this to keep Zipkin around).

**Comment by gkwan-ibm** [comment]
@steven1046 is the syntax same as what I suggested in the [description](https://github.com/OpenLiberty/openliberty.io/issues/1426#issue-513412833)?

**Comment by steven1046** [comment]
@gkwan-ibm yes.
