### ISSUE TITLE
Visual flag for the new and recently updated guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1427]
At the main page https://openliberty.io/guides/, 
suggest to have a visual flag/icon to show which guides are new and which are recently updated, e.g. for guides updated with dev mode, content updated for new version of mp feature.
The data can be put in a json file at guides-common repository, like guide_prereqs.json (or even the same json file)

**Comment by gkwan-ibm** [comment]
@yeekangc

**Comment by mbroz2** [comment]
Agreed, depending on the implementation this could influence #1126 (for example, separate section vs badge on guide card)

**Comment by mdenby** [comment]
I like the idea of a visual flag on the guide because there may be a new guide in a specific category (instead of having a new guides category). I'll mock up some ideas and post them here.

**Comment by mdenby** [comment]
So here are two options--one solid orange tag, and one outlined to match the interactive tag. I've also attached what that would look like with the interactive tag--in case it's both new and interactive.

<img width="1151" alt="Screen Shot 2019-11-21 at 2 01 03 PM" src="https://user-images.githubusercontent.com/26823018/69368188-a2c1dc00-0c67-11ea-9c1f-de99aa76f074.png">

<img width="1148" alt="Screen Shot 2019-11-21 at 2 01 11 PM" src="https://user-images.githubusercontent.com/26823018/69368196-a6556300-0c67-11ea-9f63-3dd8a5f7238e.png">

**Comment by mbroz2** [comment]
I like the design, and I have a strong vote for the "NEW" flag to have the same styling as the "INTERACTIVE" flag (so green text with white background).

As far as implementation, @steven1046 @yeekangc @gkwan-ibm I think we could just add this to be a hidden tag.  Alternatively, we could have a new file ('flags.json') and set these there.

A fancier, more upfront work, but less maintenance approach would be to get the creation date of the branch that is used to publish to the site ('master' currently) and 'automagically' add 'new' to any guide that is younger than X weeks/months.  I recommend we investigate the cost & feasibility of this approach first and only go with the first approach if this one is much more costly to implement.

**Comment by steven1046** [comment]
@mbroz2 do you mean orange text on white? 

Instead of a flag file we should just add a creation date to each adoc file and if a guide *has* a creation date attribute set and it's under a certain amount of days old then we can add the flag on the UI.

**Comment by steven1046** [comment]
We would only need to mark the current guides on openliberty.io/guides that we want to have new (and future guides).

**Comment by mbroz2** [comment]
Agree, we could add a 'creation-date' (and even 'last-update') attribute to the guides themselves.  The only drawback of doing that vs using a github API is that the developer of the guide has to remember to set it, whereas the github api would be automatic.  However, this does seem like an easier and quicker approach than using the github api.

**Comment by steven1046** [comment]
Does the github api use the repo creation date? Because guides start out named draft-guide-name and then just get renamed when ready?

**Comment by mbroz2** [comment]
No idea, hence the 'investigate' part :)

But I do like your idea as an interim approach, since it should be cheap to implement and needs no maintenance, outside of the developer knowing/remembering to provide it right before the guide gets delivered into the branch used for publishing to the site (currently 'master').

**Comment by steven1046** [comment]
We can update the guide template as such to have a creation date in it.

**Comment by mbroz2** [comment]
Yes, but my concern is that a it can take a substantial amount of time to create a guide, so if a user fills out that field when they start the guide, and takes them a month to complete it and get it published, than if they didn't update that attribute and we only consider something <4weeks old as new, it would never show up with the new flag.  
As such, guides team will need to make sure that part of the 'checklist' for delivering to master is to update/set that attribute, and not any earlier.

**Comment by mbroz2** [comment]
@gkwan-ibm @yeekangc does that seem like a reasonable expectation?

**Comment by gkwan-ibm** [comment]
@mbroz2 When we publish a guide, we have a checklist list. Updating the published date is one of them.

**Comment by yeekangc** [comment]
I am not so sure about "NEW" for guides with updates.  Good with "NEW" for guides that are brand new.  May be there can be another flag or badge for those that have been "UPDATED"?  Tagging @lauracowen for her thoughts.

In terms of impl, we have an attribute for when the guide was first published so that's good.  We should keep that and need that.  I can see us adding an attribute for "Last Updated On" (whether hidden or otherwise).  I would go by the dates that we set ourselves when the guides are first published and when they are last updated (i.e. when changes go live).

**Comment by mbroz2** [comment]
I think we should only focus first on "NEW" flag and scope this issue to that (exposing that to the end user).  If we find in the future that we also want to add "UPDATED" we can do that when the need arises under a different issue (as such, whether we do the attribute now or not for last-updated is largely irrelevant to this conversation).

To conclude, we're going to implement the orange text on white background design above for NEW flag using the attribute that provides the published date of the guide.

**Comment by yeekangc** [comment]
Thanks, team.

Yes, I am not sure if we need to be a searchable tag at the moment.

Selecting the last 3 or 4 as "NEW" or all those released in the last 4 weeks and going with whichever is greater sounds fine to me.
