### ISSUE TITLE
Update support page for multiple support offerings

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#1428]
The current openliberty.io support page points to a single product that provides support. However there are currently two products that provide such support so we need a design that allows for more options than just one.

**Comment by mdenby** [comment]
@NottyCode Could I have some more info about what the other product is that provides support? I see enterprise and community support on there now. Plus, open issue, and contribute. Maybe we can add this to the agenda for Thursday?

**Comment by mdenby** [comment]
@NottyCode What were the three different support sections that we wanted to have? I want to work on this before we're out for Thanksgiving.

**Comment by mdenby** [comment]
How about this for the Support page?
![SupportPage_Final_Desktop](https://user-images.githubusercontent.com/26823018/70265544-a75aba00-1768-11ea-993c-747e0ed81741.png)
