### ISSUE TITLE
Rendering of main page header in IE 11 is wrong

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/openliberty.io#1434]
See attached image. IE11 v 11.950.17134.0

![20191111_080005](https://user-images.githubusercontent.com/1999406/68592927-d75cb900-0459-11ea-8f27-6ee54d75bad6.jpg)

**Comment by ellenwyllie** [comment]
When debugging this issue, I noticed several other bugs only on internet explorer. The connected PR addresses all of these issues.

1. Reference background color not displaying properly.
<img width="793" alt="Screen Shot 2019-11-26 at 2 48 51 PM" src="https://user-images.githubusercontent.com/22085207/69671666-23178100-105c-11ea-96ab-25376f0ee43c.png">
2. Bunuelo fonts not loading.
<img width="1303" alt="Screen Shot 2019-11-26 at 2 49 07 PM" src="https://user-images.githubusercontent.com/22085207/69671667-23b01780-105c-11ea-9cd5-688e231d55ae.png">
3. Learn More button taking up full width of container
<img width="711" alt="Screen Shot 2019-11-26 at 2 50 07 PM" src="https://user-images.githubusercontent.com/22085207/69671668-23b01780-105c-11ea-9083-c23c0a62a6d1.png">
