### ISSUE TITLE
Suggest feedback / improvement button on website

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/openliberty.io#1435]
When a user wants to propose a change to the website, there is currently no button to easily take them to the https://github.com/OpenLiberty/openliberty.io/issues/new view. This issue exists to considering make the flow to propose changes easier.

**Comment by mbroz2** [comment]
Add 'this website is built using github' to the footer.  @mdenby for design.

**Comment by mdenby** [comment]
@mbroz2 How about this design?

<img width="1449" alt="Screen Shot 2019-11-25 at 10 25 35 AM" src="https://user-images.githubusercontent.com/26823018/69553347-0e5cbf80-0f6e-11ea-8d2a-9e5aa073d7c5.png">

**Comment by barecode** [comment]
The "built using github" is nice, but that doesn't exactly tell me I can open a discussion or issue item there. I'd prefer something like "Recommend improvement" or something to that affect. Perhaps I am the only one who wants that, but I was intending this issue to drive that discussion, less so a given design item.

**Comment by mbroz2** [comment]
We want to drive and promote user contributions to specific parts of the website (primarily guides and non-generated docs), but not necessarily to the overall site.  As such, closing this as not-strategic.
