### ISSUE TITLE
Unable to run server on debug

### ISSUE THREAD

**Issue by pierrepook** [OpenLiberty/openliberty.io#1438]
Since moving to 19.0.0.10 I have been unable to attach debugger. I have tried setting  WLP_DEBUG_REMOTE=n and y but still no luck. To run the server i run `server.bat debug test-server` . I am also on a windows 10 machine and trying to attach a debugger via intellij

**Comment by steven1046** [comment]
Issue moved to [OpenLiberty/open-liberty #9734](https://github.com/OpenLiberty/open-liberty/issues/9734) via [**ZenHub**](https://www.zenhub.com/)

**Comment by steven1046** [comment]
Moved to the real open liberty repo, this repo is to address issues on the website openliberty.io.
