### ISSUE TITLE
Move blog post tagging to 'blogs' repo

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1440]
Is it possible to move the blog post tagging file to the blogs repo? It would just help with workflow to be able to do the tagging updates as part of the same PR as the blog post publishing. Also I don't have merge access on the website repo so it's an extra step to do this part of publishing blog posts.

If there's a good/technical reason why that's not possible, np, I just wanted to ask to see if we could simplify the workflow slightly.

**Comment by mbroz2** [comment]
Agree, the file should be in the blogs repo (https://github.com/OpenLiberty/blogs).
