### ISSUE TITLE
Footer in /blogs/ is not always sticky/fixed to the bottom

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1446]
When there aren't many blogs (as a result of search on tag), the footer does not remain affixed to the bottom:
![image](https://user-images.githubusercontent.com/3076261/68968767-fe442380-07a8-11ea-89b1-b5f2b90c966a.png)

**Comment by steven1046** [comment]
This also occurs when there are no search results for a tag, the footer is high up near the header. https://openliberty.io/blog/?search=asdf
