### ISSUE TITLE
Highlight dev mode on homepage

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1447]
Highlight dev mode and relevant capabilities on the homepage to call out what Open Liberty offers developers to develop cloud-native Java microservices in "fast and efficient" ways.

There is a section on "Develop cloud-native Java microservices" today.  It can be improved/adjusted to highlight the latest innovations and capabilities.

@NottyCode @gcharters @lauracowen @mbroz2 @mdenby @cajaygle

**Comment by mdenby** [comment]
What new information would you like to add? Also, I see this goes to reference page today. Would changing the link to go to a blog about the latest innovations be a good idea too? Then as a new blog is written it could always point to new information.

**Comment by yeekangc** [comment]
Not sure about adding link to a blog post.

At least add a description and/or graphic highlighting dev mode speeding up and making iterative development easy.

**Comment by mbroz2** [comment]
The following updates will need to take place to the homepage:
Add section for dev mode
Integrate monitor into deploy
Place deploy last
Update the 'Learn More' link for the "Develop cloud-native Java microservices" section.

**Comment by mbroz2** [comment]
@yeekangc @gcharters for content for the sections.

**Comment by yeekangc** [comment]
If we will add to the existing section:

_Open Liberty is fast to start up with a low memory footprint and live reload for quick iteration. **Development mode for fast iteration - Focus on your code and we handle the rest for you.** Simple to add and remove features from the latest versions of MicroProfile and Jakarta EE. Zero migration lets you focus on what's important, not the APIs changing under you._

Or, a separate section:

_Dev mode for fast iterative development - Launch into Open Liberty's development mode and code away. We handle the rest for you. No more manual compile, package, and deploy. Only fast turnaround time and efficiency. With smarter testing too._

As mentioned above, if we can have a graphic (or update the existing one) to go along with it, that will be good.

**Comment by mbroz2** [comment]
In the first section, I'm concerned that "Development mode for fast iteration - Focus on your code and we handle the rest for you" doesn't actually tell you what it does, nor differentiate itself from the previous sentence's '**fast** to start up' and 'live reload for **quick iteration**'
I think having something like what's in the separate section "No more manual compile, package, and deploy" is key to explain what dev mode does, and the benefits it provides to the user.  
However, in its current iteration, parts of the proposed separate section feel a bit awkward to read to me, likely due to all the sentence fragments.

If we wanted a one-liner for the first section, I'd recommend something like "With dev mode, Open Liberty handles compile, package, and deploy so you can focus on code."

If we go with the second, seperate section for dev mode, I think the content overall is good just needs some wordsmithing (though I would expand on 'smarter testing' to be more concrete and remove 'and more too' as that is ambiguous and we'd have a "Learn More" button at the bottom of the section anyway.)

Agree that we'll need a graphic to go along with the content (if we go with the second option); perhaps something similar to what we had on /about regarding dynamic update capabilities.

**Comment by mdenby** [comment]
@yeekangc @mbroz2 Here are two versions keeping it in the first section.

1. This has YK's wording replacing the old wording.
<img width="1464" alt="Screen Shot 2020-02-04 at 2 06 40 PM" src="https://user-images.githubusercontent.com/26823018/73777595-c1f4e380-4757-11ea-880c-a601b45edfb3.png">

2. This has Michal's one-liner replacing the old first sentence. 
<img width="1477" alt="Screen Shot 2020-02-04 at 2 06 51 PM" src="https://user-images.githubusercontent.com/26823018/73777647-db962b00-4757-11ea-9212-162a58bada12.png">

I'll post a version with a new section shortly.

**Comment by mdenby** [comment]
@yeekangc @mbroz2 
Here's how it could look as a separate section. (Please ignore the graphic--I'm still working on it and we can talk about what it should be.)

![Homepage_Full_Scale Copy 20](https://user-images.githubusercontent.com/26823018/73781080-abea2180-475d-11ea-8ced-07a6bbd31edd.jpg)

**Comment by yeekangc** [comment]
I feel like the version with a new section is better.  Yes, we do need to work on the wording but a dedicated section does appear to convey the value better.  And, I think we should have it as the 2nd section (at least) instead of the last one.

As for the graphic, not so sure about the one in the proposed design myself.  May be we can have something that indicates fast iterative changes besides the editor window.

**Comment by mdenby** [comment]
@yeekangc I've reordered the sections--putting the new section 2nd. Does this order look right to you? I'm working on the graphic still but wanted to post for feedback asap.

![Homepage_Full_Scale Copy 20](https://user-images.githubusercontent.com/26823018/73875128-bb7f6e00-4822-11ea-8b5b-46dbab9dd277.jpg)

**Comment by lauracowen** [comment]
Dev mode wording suggested tweaks (open to further tweaking tho):

>Launch into Open Liberty's dev mode and get coding. No more manual compiling, packaging, and deploying—we handle that for you. Get a fast turn-around time in any editor, with smarter testing, and more besides.

**Comment by lauracowen** [comment]
Pretty logos - but should probably include Jakarta EE?

**Comment by mdenby** [comment]
Updated the copy and switched the logos back to how they currently are on the site.

![Homepage_Full_Scale Copy 20](https://user-images.githubusercontent.com/26823018/73942220-b111b280-48bc-11ea-829f-dc415cbea84e.jpg)

**Comment by mbroz2** [comment]
I like the latest graphic and I too like the separate section for dev mode (with my preference the current second spot, but 3rd would be fine as well).

I like the improved wording from @lauracowen 
> Launch into Open Liberty's dev mode and get coding. No more manual compiling, packaging, and deploying—we handle that for you. Get a fast turn-around time in any editor, with smarter testing, and more besides.

but I still don't like the ending "and more besides" as it lack substance and will be redundant with the 'Learn more' button below it (and something like 'and more' would be true for all 4 sections, not just dev mode).  As such, I would propose replacing that part with another concrete benefit of dev mode like IDE plugins or debugger support, producing something like
> Launch into Open Liberty's dev mode and get coding. No more manual compiling, packaging, and deploying—we handle that for you. Get a fast turn-around time in any editor, with smarter testing, and debugger support.

**Comment by mbroz2** [comment]
Speaking of the "Learn more" button, I'm assuming we're going to use that to link to the dev mode blog: https://openliberty.io/blog/2019/10/22/liberty-dev-mode.html ?

**Comment by yeekangc** [comment]
I am fine with "... with smarter testing, and debugger support" or "debugging support".  For "Learn more", yes, I think we link out to the blog for now.

As an aside, it will be nice if we can to the nice logos design soon.  =)

**Comment by mdenby** [comment]
Yes, that was my dream for the logos too :-)

**Comment by mbroz2** [comment]
The logo discussion should take place in #1300 (and since we know we're not going to be able to use all the logos for which we have pills today, we'd likely need a new design that has logos (for ones we can use) above pills (for logos we can't use, like docker).

**Comment by mdenby** [comment]
@ellenwyllie I'm attaching the graphic here. I believe thats all that's need (aside from fussing over the words).
[Archive.zip](https://github.com/OpenLiberty/openliberty.io/files/4172487/Archive.zip)

Title: Dev mode for fast iteration
Text: Launch into Open Liberty's dev mode and get coding. No more manual compiling, packaging, and deploying—we handle that for you. Get a fast turn-around time in any editor, with smarter testing, and more besides.

The Learn More button should link to https://openliberty.io/blog/2019/10/22/liberty-dev-mode.html
