### ISSUE TITLE
Add Gitter link to the support page

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1451]
Add a link to OL Gitter page (https://gitter.im/OpenLiberty/) on our support page (https://openliberty.io/support/) under the 'Community support' section.

We'll also want to add Gitter icon/link to the footer after the groups.io logo.

**Comment by ellenwyllie** [comment]
Do we want to add a gitter link in the nav bar hamburger menu as well? 
<img width="819" alt="Screen Shot 2020-04-23 at 3 04 31 PM" src="https://user-images.githubusercontent.com/22085207/80144330-ecdf1e80-8573-11ea-9e58-e85ea30c3214.png">

**Comment by mbroz2** [comment]
Yes
