### ISSUE TITLE
New interactive guide multi-pane design

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#146]
Related to https://github.com/OpenLiberty/openliberty.io/issues/145

Feb 15. - Design team started looking into a two column

**Comment by lauracowen** [comment]
What are the changes needed for the interactive guides?

**Comment by kevinwlau** [comment]
Issue moved to [OpenLiberty/iguides-common #141](https://github.com/OpenLiberty/iguides-common/issues/141) via [**ZenHub**](https://www.zenhub.com/)
