### ISSUE TITLE
OL Logos page, ala https://github.com/logos

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/openliberty.io#1463]
I want to use the Open Liberty logos, but I can't find them. The best I can do is copy images that are in use in the site. That's lame. Can you please make your logos available on a download page (like https://github.com/logos) so that I can reuse the official logos? Thanks!

**Comment by mbroz2** [comment]
Duplicate of https://github.com/OpenLiberty/openliberty.io/issues/1212
