### ISSUE TITLE
Long titles gets cut off in the `What's Next` section

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/openliberty.io#1468]
See screenshot here:
![image](https://user-images.githubusercontent.com/26514093/70251584-cbf56880-174d-11ea-9268-c23557151558.png)

**Comment by MaiHameed** [comment]
Shown at the bottom of guides to link to other related guides

**Comment by k8vance88** [comment]
Add extra whitespace to show a 3rd line.  Let's see how it looks. If it doesn't look 'right' then we can also look into placing the guides with longer names at the bottom, but that is changing the order.

**Comment by steven1046** [comment]
Which guide is this at the bottom of?

**Comment by MaiHameed** [comment]
@steven1046 Currently on my draft [OKD](https://draft-guides.mybluemix.net/guides/okd.html) guide

**Comment by ellenwyllie** [comment]
Here is a mockup of what it would look like with extra space to fit longer titles. I think it looks good, even  when it's next to a title that only takes up one line: 
<img width="755" alt="Screen Shot 2019-12-18 at 10 38 23 AM" src="https://user-images.githubusercontent.com/22085207/71105257-d9194b00-2182-11ea-8366-3e709bb5484d.png">

If there are no long titles, then it will look something like this: 
<img width="727" alt="Screen Shot 2019-12-18 at 10 41 48 AM" src="https://user-images.githubusercontent.com/22085207/71105356-0b2aad00-2183-11ea-8722-9415adfcd8e7.png">

**Comment by steven1046** [comment]
It looks better with more space anyways!
