### ISSUE TITLE
New configuration documentation

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#147]
**Design Needed:**
1.  Mobile view

**End Goal:**
New pages server configuration documentation.  The documentation is currently on knowledge center (KC).  KC's html is rendered from markdown files.  Lowest implementation resistance is to use the markdown files on openliberty.io.  Ideally, we should strive to use Asciidoc files.

**Example of configuration (think server.xml schema)**
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_config.html

**Comment by yeekangc** [comment]
Should consider how we can make available sample server configurations or configuration snippets to make it easier for users to get what they need going.  There is design needed for this too and may be a separate issue.  Noting it here for now.

**Comment by kinueng** [comment]
Hi @cbridgha,
@NottyCode mentioned he will follow up with you in person when he is in RTP.

**Comment by cbridgha** [comment]
Hey - @ewhoch has done the most on this so far.  We discovered the existing config doc gen tools depend on the featureList api, and it made some assumptions that breaks in the OL only environment.  With some refactoring we should be able to get this going.

**Comment by mbroz2** [comment]
[com.ibm.websphere.liberty.autogen.open.doc.jar.zip](https://github.com/OpenLiberty/openliberty.io/files/1831032/com.ibm.websphere.liberty.autogen.open.doc.jar.zip)
Uploaded a generated jar for config and features.

**Comment by ewhoch** [comment]
There's still vagueness of design here, so this is on hold until then. Questions of whether to output HTML, Markdown, or asciidoc and how. The current generator has the Markdown logic interleaved into an ant task in a way that isn't immediately easy to add a new writer without logic replication or a decent amount of refactoring, though an easy way may be to factor out the language-specific keys (like star star vs equals equals) and make that the control point since otherwise the line structure is pretty similar.

**Comment by yeekangc** [comment]
Also, it was discussed that we should link from from each feature to its appropriate server configuration references and vice versa.  Jotting this.

**Comment by kinueng** [comment]
Hello @megmulsy,
We are in need of some design guidance for how the features/config documentation will appear in a mobile view.  We currently are working on the desktop designs below:

- https://ibm.ent.box.com/file/284413515937
- https://ibm.ent.box.com/file/284588886696

**Comment by kinueng** [comment]
The configuration documentation will be delivered first.  Feature documentation has a completely different design and will be tracked with issue #397
