### ISSUE TITLE
Add logos to Support page

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1480]
We recently updated the Support page to reflect the 3 support offerings (#1428). It was suggested that we add logos for each of the 3 boxes so that they pop more. We need the logos themselves and designs for how the logos should be placed within the boxes. @mdenby 

![Screen Shot 2019-12-17 at 4.15.23 PM.png](https://images.zenhubusercontent.com/5ba54aeed542104d81ce6b5c/05d296b8-a605-4d68-8fa8-ccd76e1e4fa0)

**Comment by mdenby** [comment]
I'll get those for you today.

**Comment by mdenby** [comment]
If this looks okay I can give you the logo files--unless you'd like the full redlines.

![SupportPage_Final_Desktop v2](https://user-images.githubusercontent.com/26823018/71112459-88f9b300-2199-11ea-9ebb-2fed8071c61f.png)

**Comment by ellenwyllie** [comment]
No need for full redlines, just the logo files would be great!

**Comment by mdenby** [comment]
Logos!
[Archive.zip](https://github.com/OpenLiberty/openliberty.io/files/3980368/Archive.zip)

**Comment by ellenwyllie** [comment]
A couple comments from slack about this issue: @mbroz2 suggested that we use the product logo instead of the Red Hat logo. @NottyCode suggested that we use the WAS logo instead of the Open Liberty logo because elite support for OL was replaced by WAS support.

**Comment by mdenby** [comment]
Let me find the WAS logo for you.

**Comment by mbroz2** [comment]
ICPA Logo:
![_0000_CPA-Blue](https://user-images.githubusercontent.com/3076261/72454375-5afe9300-3786-11ea-96d4-7e875300b2be.png)

**Comment by mdenby** [comment]
Here's the WAS logo in purple. 
![generic-was-500](https://user-images.githubusercontent.com/26823018/72834126-2e4eed80-3c56-11ea-9d29-a39a62361caa.png)

**Comment by NottyCode** [comment]
that WAS logo looks very pixelated. I've got a higher res png that isn't that purple, can we use that and recolour it?

**Comment by mbroz2** [comment]
If it's sized to what we would actually use it at (around 100px), then it looks fine
![generic-was-500](https://user-images.githubusercontent.com/26823018/72834126-2e4eed80-3c56-11ea-9d29-a39a62361caa.png?s=100)

![image](https://user-images.githubusercontent.com/3076261/73014624-20c56f00-3de0-11ea-86f8-de2c4a962df5.png)

**Comment by mdenby** [comment]
I agree--it should look fine at the smaller size. Though if you have a larger size I'm happy to redo it.

**Comment by NottyCode** [comment]
ok, so I'm ok with that, it just scared me when looking at it vs the ICPA logo in the issue thread.

**Comment by mdenby** [comment]
Just looking through "design needed" issues. Is there something more to do with this? Or was the last news that we couldn't use one or more of the logos without permission?
