### ISSUE TITLE
Add light grey border to images in blog and docs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1496]
Putting light, light grey (not heavy/dark) borders around images usually makes them appear sharper/neater, especially for screenshots where the background is white. The border can be almost indistinguishable from the image/background but it sharpens otherwise ragged edges of images.

For example, in this draft blog post, the screenshots aren't easily distinguished from the background of the post:

![image](https://user-images.githubusercontent.com/3322532/72517841-fe65ab80-384b-11ea-9f97-ed459ab35d44.png)

This may require advice from Design about what shade/weight of border to use but I think we should look at doing this. Or look at providing a way for us to manually add a particular style to images where it's needed (eg in the example above).

**Comment by mbroz2** [comment]
I'm concerned that there is no one-color-fits-all approach for an image border.

Regarding "providing a way for us to manually add a particular style" you can do that today, and that's what I would recommend (at least in the interim), by simply adding a border to the image itself instead of adding it around the image via css.  Any basic image editor (even microsoft paint) should allow for this (could even be done via things like word or powerpoint).  If adding the border to the image itself is not adequate, than we could add custom attributes for maybe 2 borders (one for 'light' colored border when there's a dark image, and a 'dark' one for a light image, though the former would probably be unnecessary today since we already use a white background).

Tagging this with "design needed" to get @mdenby input.

**Comment by lauracowen** [comment]
Yeah, I'm not certain about colour, though a very light grey would work for most things reasonably well (though @mdenby's view on this would be useful).

I'd rather not do it in the original image because of the overhead for each image we add to a blog post.

If we were to have two CSS attributes (a dark and a light one), I'd use them the opposite way round. My intention is not to have a really visible border but to sharpen the edges of the image (it doesn't need to be a perfect match of colour/shade for it to work). So for a screenshot with a white background, I'd use a very light grey. For a dark image, I'd use a really dark grey.

I couldn't find a good example but here's one I did on WASdev.net. I seem to have used `img.screenshot {border: 1px solid #afafaf;}` but, looking at it now, I think I should have gone for an even lighter shade so it would be less obvious (for both the white and grey backgrounds).

**Comment by mdenby** [comment]
@lauracowen Do you mean all the images that are like this in Docs and Guides?

<img width="1171" alt="Screen Shot 2020-01-28 at 12 10 09 PM" src="https://user-images.githubusercontent.com/26823018/73287397-33b4b680-41c7-11ea-905c-c25c42060766.png">
<img width="480" alt="Screen Shot 2020-01-28 at 12 09 41 PM" src="https://user-images.githubusercontent.com/26823018/73287398-344d4d00-41c7-11ea-8f20-c3c9e127facc.png">

**Comment by lauracowen** [comment]
No. See the screenshot in the top comment for an example. And a similar example in the WASdev.net link in my subsequent comment.

**Comment by mdenby** [comment]
How about one of these two options--

1. D8D8D8
<img width="284" alt="Screen Shot 2020-01-29 at 2 36 13 PM" src="https://user-images.githubusercontent.com/26823018/73390767-ca0ada00-42a4-11ea-88da-b2c298a0c050.png">

2. C8D2D2
<img width="324" alt="Screen Shot 2020-01-29 at 2 34 56 PM" src="https://user-images.githubusercontent.com/26823018/73390822-e444b800-42a4-11ea-8435-d2db1ac58aa2.png">

**Comment by mbroz2** [comment]
From an implementation pov, we can define .img-dark-border and .img-light-border and assign them to the final color (and thickness) that we want.  Then either style can be referenced with an image to apply the corresponding border to it.

**Comment by lauracowen** [comment]
@mdenby The lighter one could probably be even lighter than that - from experience of doing this in presentation slides, the line needs to be barely perceptible for it to work.

**Comment by mdenby** [comment]
@lauracowen Sure, here's really light color and a little less light.

1. f3f3f3
<img width="247" alt="Screen Shot 2020-01-30 at 2 45 10 PM" src="https://user-images.githubusercontent.com/26823018/73484419-44a02c00-436f-11ea-8fee-6104f501e328.png">

2. dcdcdc
<img width="240" alt="Screen Shot 2020-01-30 at 2 45 06 PM" src="https://user-images.githubusercontent.com/26823018/73484443-5386de80-436f-11ea-9995-5a82fd48ead5.png">

**Comment by lauracowen** [comment]
@mdenby Thanks.
@mbroz2 Could we give it a go on the draft site and I'll apply it to a selection of blog posts and docs on there so we can see how it looks?

**Comment by mbroz2** [comment]
Given the above suggest class names (.img-border-dark &.img-border-light), I believe it would look something like:

for block images:
```[.img-border-dark] //only new part
image::/img/blog/image_name.png[I'm a block image with a dark border]```

for inline images (doubt we use these much):
```image:/img/blog/image_name.png[role=img-border-light,title="I'm an inline image with a light border"]```

Depending on who ends up implementing it, @ellenwyllie or @steven1046 can comment on what will need to be applied to the images.

**Comment by steven1046** [comment]
If i remember right, i think the first part of the attributes in asciidoc is the role/class but we can confirm. We may not have to write "role" and could just do [img-border-light]. We will test.

**Comment by ellenwyllie** [comment]
Here is an example of the image borders. The top image has the dark gray and the bottom has light gray.

<img width="1220" alt="Screen Shot 2020-02-02 at 11 00 07 PM" src="https://user-images.githubusercontent.com/22085207/73666097-da85d080-4667-11ea-9e0b-a00dd89b883e.png">
<img width="1204" alt="Screen Shot 2020-02-02 at 11 00 49 PM" src="https://user-images.githubusercontent.com/22085207/73666099-da85d080-4667-11ea-8218-04a03804ffaf.png">

To add the class in the adoc, I just added [.img_border_light] to the line before the image. For example: 
```
[.img_border_light]
image::/img/blog/prometheusAM_ui_status.png[Prometheus Status on UI, align="left"]
```

**Comment by mdenby** [comment]
Personally, I like the lighter gray one.

**Comment by lauracowen** [comment]
I agree with @mdenby - I like the lighter one.

I'd use the lighter one for most things. The only reason a darker one might be useful is if we have an image with a really dark background but I think that is rare so it's the really light one that I'd use mostly.

Thanks

**Comment by ellenwyllie** [comment]
@lauracowen The borders have been added to the css so you can add them to whichever images you like.

**Comment by lauracowen** [comment]
Thank you!
