### ISSUE TITLE
Convert the SVG titles to straight text using font-family

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#150]
Now that we have approval to use the font file (Bunuelo Clean Pro), we should consider changing the titles from SVG to using the font.

An example of a SVG that is of text in Bunuelo
https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/img/blog_page_title.svg

**Comment by steven1046** [comment]
The titles scale very nicely for all screen sizes using SVG's and not so much using text.

**Comment by steven1046** [comment]
Closing this issue to avoid a lot of complex styling for the title's text at different screen sizes. Using one fixed size is too small on a default screen size and when you shrink the browser it overflows. We will continue to use SVGs and get SVGs for the pages that don't have them.

**Comment by steven1046** [comment]
https://github.com/OpenLiberty/openliberty.io/issues/168 is the new issue to get more SVG titles.
