### ISSUE TITLE
Redirect /community to go to /support instead

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/openliberty.io#1505]
The link to the Community page, https://openliberty.io/community/, is missing.  There use to be a link on the About page, which was removed, to the Community page.   Where/Should a new link to the Community page be added somewhere?

**Comment by kinueng** [comment]
Blocks https://github.com/OpenLiberty/openliberty.io/issues/1451.  FYI @lauracowen

**Comment by lauracowen** [comment]
> Blocks #1451. FYI @lauracowen

I think it's maybe a bit more than that too. There's duplication of content between the two pages, yet they're both online. Did the Support page supercede the Community one?

**Comment by mbroz2** [comment]
We're going to make /community redirect to /support.
We'll also want to change any links to /community to instead point at /support (like in the /about page) and dockerhub
