### ISSUE TITLE
Fix jakartaee atom feed

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#1507]
The Jakarta EE blog feed is misformatting dates. They should be in RFC 822 format which is dd MMM yy and instead are in format MMM dd, yyyy. See:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Fjakartaee.xml

**Comment by chrisguindon** [comment]
Thanks for quickly fixing this!
