### ISSUE TITLE
Fix scrolling for hashes on downloads page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1510]
Currently we have multiple sets of tabs on the getting started / downloads page and when you click on a tab it updates the hash in the URL. If you reload the page it will load the tab for that set of tabs but not jump to it. Do we want to have the page jump to what is in the hash on page load? Also since there are multiple sets of tabs, clicking on one updates the hash and if you click on another table's tabs it deletes the hash and replaces it with the new hash clicked on. We should discuss if we want to keep this behavior or update it so the correct tabs clicked **all** load on page refresh and get bookmarked.

**Comment by dmorgant** [comment]
With the changes I made for accessibility, it appears that jumping to the tab associated with the hash is now working.....most of the time.  Sometimes when the selected tab is the first one it does not seem to jump to it as well.

**Comment by steven1046** [comment]
In this issue we will tackle just jumping to the right section when the page loads.
