### ISSUE TITLE
Align branch names across ol.io and its content repos

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1517]
**prod**: Production branch.  Should only ever contain content that is already or is ready to be on the live production site.  It should only have PRs from the staging branch (aka, is always equal to or behind the qa branch).  We should not allow direct pushes to this branch (only PRs).
**staging**: This is meant to be a staging branch before going live via a PR to the prod branch.  This is meant to be a final check (via a 'qa-site') to make sure everything is as expected, and it should not be used for active development.  Developers can push directly here or make PRs to it from their own branches or the draft branch.  If a problem is found here, it needs to be either resolved quickly and immediately or reverted.
**draft**: Meant for longer-term and/or collaborative development.
**demo**: No change, used to demo larger pieces of work; only used by openliberty.io

![image](https://user-images.githubusercontent.com/3076261/73389911-bfe3de00-429a-11ea-91c8-701070c5d661.png)

- [x] openliberty.io
- [x] guides-common
- [x] guide
- [x] iguides-common
- [x] iguide
- [x] docs
- [x] docs-playbook
- [x] blogs
- [x] certification

**Comment by steven1046** [comment]
Let's change the branch structure across all repos after Antora is rolled out.

**Comment by steven1046** [comment]
The antora playbook branches use the new schema.

**Comment by steven1046** [comment]
Once the staging-openlibertyio.mybluemix.net site uses the staging branch of the ui, we should point out that: If all of the staging content on https://staging-openlibertyio.mybluemix.net/ will have both staging changes of the ui and of guides/blogs we will have to be careful when the guides/blogs teams merge their changes into prod because they won't always automatically work if it depends on a new ui enhancement/bug fix so we will need to coordinate deliveries to prod in those special circumstances.

**Comment by steven1046** [comment]
Update the blog readme with the updated UI branch names once we change them.

**Comment by steven1046** [comment]
After ol.io, iguides will be converted next. We will need to separate the logic in build_clone_guides.rb to decouple the static/interactive guide branches so that the iguides can use prod before static guides do.

**Comment by steven1046** [comment]
The support for the new guide branches has been delivered into `draft`. I will update this when it makes it to prod.

**Comment by steven1046** [comment]
Support for the new guide branch structure is now in prod. Guides and iguides can be updated simultaneously and fallback to the existing branch structure if the new branches aren't there.

**Comment by steven1046** [comment]
@gkwan-ibm @yeekangc the guides can begin being converted over to the new branches now.

**Comment by steven1046** [comment]
After guides-common has been changed, please ping me to update the guides draft/staging pipeline to clone the new branches.

**Comment by steven1046** [comment]
The guides have been switched over, minus them not having any draft branch. The static guides have prod/staging/dev.

**Comment by steven1046** [comment]
Edit: The static guides *are* using a draft branch of guides still in development, but published guides only have prod/staging.
