### ISSUE TITLE
Cannot go to the section directly

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1524]
- hit this https://openliberty.io/guides/microprofile-jwt.html#securing-the-system-service
  - expect jump to the "Securing the system service" section of the JWT guide 
  - but the browser show the "Running the tests" subsection

**Comment by steven1046** [comment]
This likely has something to do with upgrading jQuery to version 3.0 in guides.

**Comment by steven1046** [comment]
Firefox warnings:
![image](https://user-images.githubusercontent.com/6392944/73016714-042b3600-3de4-11ea-8b13-84b5fa0ad69c.png)


Chrome warnings (doesn't occur there but still helpful):
![image](https://user-images.githubusercontent.com/6392944/73016743-14431580-3de4-11ea-8e1a-343f871cee3d.png)
