### ISSUE TITLE
Docs--select version

### ISSUE THREAD

**Issue by mdenby** [OpenLiberty/openliberty.io#1526]
The first two are with the current design and the next two are with the future Docs design.

![Current Select opt 1.png](https://images.zenhubusercontent.com/5c587f22df0733a30554ecb5/ea1d7834-f6e9-4158-bca9-29657c5a2bcd)![Current select opt 2.png](https://images.zenhubusercontent.com/5c587f22df0733a30554ecb5/71151945-23d3-448a-a0ce-70b317c49579)![Select Doc Version option 1.jpg](https://images.zenhubusercontent.com/5c587f22df0733a30554ecb5/f622b62a-2a38-435a-8095-b4500b6e6bf7)![Select Doc Version option 2.jpg](https://images.zenhubusercontent.com/5c587f22df0733a30554ecb5/a27f2b53-9633-47c0-8a63-190b356526a4)

**Comment by NottyCode** [comment]
@mdenby I am not keen on the all white look. Perhaps if the header was dark blue like in #1273 it wouldn't be so bad. It feels kind of cold and clinical

**Comment by mdenby** [comment]
Definitely--that's also an option :-)

<img width="1459" alt="Screen Shot 2020-01-28 at 12 19 37 PM" src="https://user-images.githubusercontent.com/26823018/73288177-8478df00-41c8-11ea-8a4c-4af124115a99.png">

**Comment by steven1046** [comment]
@mdenby what should the dropdown look like for the green version picker on the left?

**Comment by steven1046** [comment]
@mdenby do you have a tool that can produce redlines for the design by chance?

**Comment by mdenby** [comment]
<img width="688" alt="Screen Shot 2020-04-09 at 2 25 01 PM" src="https://user-images.githubusercontent.com/26823018/78928096-06f60880-7a6e-11ea-919d-d695f6b35055.png">

**Comment by mdenby** [comment]
@steven1046 I do! Here are the redlines.
[Archive.zip](https://github.com/OpenLiberty/openliberty.io/files/4457974/Archive.zip)
