### ISSUE TITLE
Design change for last 3 sections?

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1532]
I found the following sections are now 3 different sections in the guides.instead under "Nice work! Where to next?"? Or is there a regression?
- Great work! You’re done!
- Related Links
- Guide Attribution

![Screen Shot 2020-01-27 at 5 21 27 PM](https://user-images.githubusercontent.com/29576299/73219172-79bb3d00-4129-11ea-9b07-1ae7b53c9122.png)

**Comment by steven1046** [comment]
@gkwan-ibm which guide is this?

**Comment by steven1046** [comment]
I only see the "Nice work! Where to next?" section at https://openliberty.io/guides/rest-intro.html#running-the-tests

**Comment by ellenwyllie** [comment]
I see this bug on firefox some of the time. I think it will also be fixed by the PR I just opened: https://github.com/OpenLiberty/openliberty.io/pull/1530

**Comment by gkwan-ibm** [comment]
Yes, found it by using Firefox. Tried Safari and Safari has no problem.
