### ISSUE TITLE
Link to Jakarta content from homepage

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1551]
Currently, we do not have any links from the homepage to any Jakarta specific content on the site.  We'll need to identify the content we want to link to and how we want to link to it (an orange link in the paragraph text would likely look out of place, so we might need a different approach).

**Comment by ellenwyllie** [comment]
We could either do an orange link or a blue link. We may also want to make 'MicroProfile' into a link (although we'd probably want to make sure it doesn't link to the same microprofile doc that the 'Learn More' button links to).

1. Jakarta EE link with orange text:
![Screen Shot 2020-03-11 at 2 16 03 PM](https://user-images.githubusercontent.com/22085207/76454570-e66d5c80-63a2-11ea-9d5d-f4cc818f1f48.png)

2. Jakarta EE link with blue text:
![Screen Shot 2020-03-11 at 2 17 28 PM](https://user-images.githubusercontent.com/22085207/76454680-0ef55680-63a3-11ea-8821-e24c1ee1e11f.png)

3. MicroProfile and Jakarta EE links with orange text:
![Screen Shot 2020-03-11 at 2 17 52 PM](https://user-images.githubusercontent.com/22085207/76454749-1ddc0900-63a3-11ea-9967-57772b7bc6aa.png)

4. MicroProfile and Jakarta EE links with blue text:
![Screen Shot 2020-03-11 at 2 18 12 PM](https://user-images.githubusercontent.com/22085207/76454772-28969e00-63a3-11ea-8253-77e52e4d67ad.png)

**Comment by mbroz2** [comment]
We'll go with option 4 (both MP and Jakarta EE in blue).
MP will link out to: https://openliberty.io/docs/ref/general/#microprofile.html
For Jakarta EE, we need a docs page to be created, until then, this issue is blocked.

**Comment by mbroz2** [comment]
Blocked by https://github.com/OpenLiberty/docs/issues/3271
