### ISSUE TITLE
About page: "Download Open Liberty" button does not work

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#1557]
## Problem
The About page (https://openliberty.io/about/) has a "Download Open Liberty" button at the bottom of the page.  The button is broken.  When clicking on the bottom, the page is scrolled to the top of the About page.

![image](https://user-images.githubusercontent.com/31117513/74552325-95408900-4f1a-11ea-9d9c-3e181dbab1c1.png)

## Debugging
I found this error because I was noticing developers are still visiting the About page, even though there are no links to `/about/` on the homepage.

The button is missing any kind of `href` value.  I looked at the Downloads page (https://openliberty.io/downloads/) and did not see any obvious existing buttons that mimic the "Download Open Liberty".  My assumption is that there is not a default "download" behavior, rather the user is the one to choose how they want to Download (maven, ..., Jakarta EE 8, ..., etc).

## About page download button code is here 
https://github.com/OpenLiberty/openliberty.io/blob/0239caccdb32f7c7dad453014a8a1ec4f2323dd7/src/main/content/about.html#L193

**Comment by mbroz2** [comment]
We are removing the /about page and redirecting it to the homepage under #939
