### ISSUE TITLE
Docs paragraphs have different line spacing

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1565]
@dmuelle brought up that the different paragraphs have different sized line spacing as seen on this page: https://openliberty.io/docs/ref/general/#microprofile.html

Should we consider making them consistent?

**Comment by dmuelle** [comment]
concern is that the tighter line spacing makes the H3 content look like "fine print"

**Comment by k8vance88** [comment]
![image](https://user-images.githubusercontent.com/29546393/75378467-5b1ba380-5899-11ea-9ff0-c6b22b0c3692.png)

**Comment by steven1046** [comment]
Let's have one consistent styling for paragraphs between blogs and docs

**Comment by steven1046** [comment]
The different line spacing comes from this css which i'm not sure how it gets applied:
![image](https://user-images.githubusercontent.com/6392944/78796035-68897a80-797b-11ea-88e2-8cd2875c9154.png)

**Comment by steven1046** [comment]
Likely fixed by Antora #1243

**Comment by steven1046** [comment]
@dmuelle do you know if this is fixed now?

**Comment by dmuelle** [comment]
@steven1046 - yes it appears to be fixed now-Thanks!

**Comment by steven1046** [comment]
Awesome 🎆 . Closing this until there are any further issues.
