### ISSUE TITLE
Guides: remain in multi-pane view for smaller widths by adding a scroll bar to code pane.

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/openliberty.io#1569]
It was confusing to me when I resized to a single pane view.  First off, I didn't mean to go single pane, I was just trying to fit my window next to my editor.  But what really confused me was where did the files go?  So much so that I made my browser larger again, so I wouldn't miss anything.  It would be great if I had some kind of notification that the code wasn't gone it was just inline in the guide text.

**Comment by steven1046** [comment]
It would be helpful to show a tooltip at first over the code hotspots like this to show that you can interact with them and view the code:

![image](https://user-images.githubusercontent.com/6392944/75391670-2535e980-58b0-11ea-9ae2-8bccdddf4b8b.png)

This tooltip could go away after the user interacts with any blue code snippet.

**Comment by k8vance88** [comment]
This is related to #1344 but still a separate issue.

**Comment by steven1046** [comment]
See if this makes sense at all for making the same change to interactive guides at the same time or just make it to static guides.

**Comment by mbroz2** [comment]
Maintain multi-pane (with the added scrollbar in code pane as necessary) to at least 550px viewport and no lower than 500px (so 499px is the latest we'd want to switch to single pane).
