### ISSUE TITLE
Macros in OL docs don't resolve in RHR builds

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1573]
For example, in the [feature overview topic](https://raw.githubusercontent.com/OpenLiberty/docs/master/ref/feature/featureOverview.adoc), a macro is used to generate a link (with the feature's name as text) to the generated feature doc; eg `feature:appClientSupport-1.0[]`.

These macros are used in a few of the doc topics to link to the generated feature and config doc topics. However, when we build those OL doc topics with the RH build for RHR releases, the build has problems because the macros can't resolve.

We need to fix this before we can build the new version of the OL docs for RHR.

**Comment by Charlotte-Holt** [comment]
After speaking with @mbroz2 and @NottyCode, we determined that we'll host separate docs in [the PurpleLiberty repo](https://github.com/PurpleLiberty/docs) that work with the RHR build, so this issue doesn't need to be resolved at this time.
