### ISSUE TITLE
Enable specific article content in Twitter cards for docs instead of generic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1574]
If you post links to the guides in Slack or on Twitter, they generate ‘Twitter cards’ with the relevant title and abstract in them; eg https://openliberty.io/guides/getting-started.html 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3322532/76071921-fcd47c00-5f8e-11ea-8d14-b007a9960d9a.png">

Same for a blog post; eg https://openliberty.io/blog/2020/02/14/preview-microprofile-3-3-20002.html
<img width="606" alt="image" src="https://user-images.githubusercontent.com/3322532/76071969-0d84f200-5f8f-11ea-931e-3b3332f7adc4.png">

But if I paste in a link to a doc topic, I get the old generic OL.io card; eg https://www.openliberty.io/docs/ref/general/#microprofile.html and https://www.openliberty.io/docs/ref/general/#microservice_observability_metrics.html

<img width="606" alt="image" src="https://user-images.githubusercontent.com/3322532/76072012-1d9cd180-5f8f-11ea-96ac-1ce9b8483b00.png">

Both of those have `seo-title` and `seo-description` front matter but I assume it’s not enabled to render for the docs. Would it be possible to enable it in the docs template too (I can raise an issue if so)? Then we can post links to particular topics on, say, social media or just on slack and it would be clear what all the preview cards are pointing to. I guess for files that are missing the `seo-` values it would just default back to the generic card?

**Comment by mbroz2** [comment]
This will be fixed under #1243
