### ISSUE TITLE
Our html minifier can't always handle the \ char

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1587]
Go to https://draft-guides.mybluemix.net/guides/reactive-messaging-sse.html#subscribing-to-server-sent-events and hover over `EventSource` and you can see it duplicate the line in the code that should be hotspotted:
![image](https://user-images.githubusercontent.com/6392944/77687366-4439a100-6f6c-11ea-87bd-efed70696c8f.png)

This isn't due to there being two hotspots for the same thing because I removed one of them and it still happened.

**Comment by gkwan-ibm** [comment]
same issue in https://github.com/OpenLiberty/guide-microprofile-metrics/issues/91

The UI cannot handle `\` char correctly

**Comment by steven1046** [comment]
It looks like the minify_html option in config.yml is causing some source formatting to break in the code panel: 
![image](https://user-images.githubusercontent.com/6392944/77766470-b0201600-700d-11ea-8de5-dec930c6c4a1.png)

**Comment by steven1046** [comment]
The escape character is already removed before any javascript runs so it's an issue with the minifying or something during build time.

**Comment by steven1046** [comment]
The root issue is that we use the octopress-minify-html gem which uses html_press under the covers which is deprecated and there have been some known issues (including the backslash escape char) but are no longer worked on due to being deprecated: https://github.com/stereobooster/html_press/issues/21.

**Comment by steven1046** [comment]
This will be fixed by #742
