### ISSUE TITLE
[Antora] Design needed for a page that doesn't exist in a given version of docs

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1607]
By design the version picker will show all of the doc versions. If you click on a version, it will take you to the same page that you're on, in that version that you clicked. If that page doesn't exist in the version you select then it takes you to the version but you land on the "Docs Overview" page. The user might get confused by this. Should we display a banner telling the user once they land on the new version overview that the page doesn't exist in this version? Should we display a popup when a user clicks a version that the page doesn't exist on *before* the page switches to the new version telling them that it doesn't exist and ask if they would like to proceed?

This isn't needed before the Antora release because we won't have any pages yet that aren't in the latest version but should need it by the next few releases.

**Comment by mdenby** [comment]
So weird question--why would one doc be an older version?

I would definitely show a message saying something like, “This version doesn’t exist please select an older version.” instead of taking the user back to the overview page.

**Comment by steven1046** [comment]
One case where this would happen is if a feature doesn't get released until a later Liberty version then it wouldn't exist on older Liberty versions. So if they click on a different version in the version picker where the page doesn't exist, should we stop it the first time and put a popup with that message?

**Comment by steven1046** [comment]
"This page doesn't exist in version X"

**Comment by mdenby** [comment]
I would put that message in the body of the page, where the content would be.

"This page doesn't exist in the version selected. Please make another selection and have a nice day!"

**Comment by mbroz2** [comment]
This is an issue because we've removed the second version picker, specific to the the current doc that's displayed.  We now have on of 3 options:
1) Take user to the doc overview 
2) Provide a generic 'page doesn't exist in version x'
3) Notify user (or prevent) that the doc doesn't exist in the version they're trying to switch to (for example, with a modal)

**Comment by mdenby** [comment]
I like option 2. Option 3--seems like it would be a never ending loop. Option 1 feels like it would confuse the user because they wouldn't know why the went to the overview page.
