### ISSUE TITLE
Support redirects in docs and blogs repo

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#1615]
Currently there is a single redirects.properties file living in the openliberty.io repo at /src/main/webapp/WEB-INF/redirect.properties however it handles redirects mainly for docs, secondly for blogs and 3rdly for the main website. This split has some unfortunate consequences. For example when delivering new versions of Jakarata EE and MicroProfile Javadoc we have to deliver the javadoc to the docs repo, and then once that is live update redirects.properties. If the redirects.properties could be made up of files in docs, blogs and openliberty.io which get merged during the build it would make maintenance much simpler and keep related info in related repositories.

**Comment by mbroz2** [comment]
The redirect file for docs should be in docs-playbook repo.

**Comment by steven1046** [comment]
This will allow us to have `latest` in docs for `draft` and `staging` to point to the newer doc version instead of the latest live version on the prod site.

**Comment by steven1046** [comment]
As part of this issue i will add the current blog/doc redirects to their own repo.

**Comment by steven1046** [comment]
Docs: https://github.com/OpenLiberty/docs-playbook/pull/63

**Comment by steven1046** [comment]
Blogs: https://github.com/OpenLiberty/blogs/pull/1053

**Comment by steven1046** [comment]
Certifications redirects in that repo will be done by @mbroz2
