### ISSUE TITLE
Enable HTTP Compression (gzip)

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1623]
As of 20.0.0.4, support for http compression has been added:
https://openliberty.io/blog/2020/04/22/http-response-compression.html

In order to enable this, we'd need to add the necessary compression element to httpEndpoint.  However, we currently do not specify our server.xml when pushing using cf (we push a stand-alone app), so we'd need to switch to doing something like using the `-p` flag and provide a server directory, which would allow us to include our own custom server.xml.  Another option would be to push a packaged server, but that would have extra overhead.
For documentation, see here: https://cloud.ibm.com/docs/runtimes/liberty?topic=liberty-options_for_pushing

**Comment by steven1046** [comment]
I did this for the starter. It is kind of a pain to manage, every time you want to update the starter you have to build the war, then repackage the server, and upload that server in a commit to the repo. It would make making changes to the website more cumbersome.

Edit: found a way to use the server.xml in src/main/wlp and to copy the .war from the build, so we do not have to manually package the .war.
