### ISSUE TITLE
YAML file code view in guides has weird looking document separator highlighting

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/openliberty.io#1634]
See screenshot:
![image](https://user-images.githubusercontent.com/26514093/81102061-0cb00400-8edd-11ea-818b-962914fa8724.png)

I included a `YAML` file in the right side code pane, but it highlights the `---` document separator weird. I included the file like so:

```
deploy.yaml
[source, YAML, linenums, role='code_column hide_tags=replicas']
----
include::finish/deploy.yaml[]
----
```

Do you have `YAML` specific code highlighting enabled? Or should I treat the file as plain `TEXT`?

**Comment by steven1046** [comment]
@mdenby  Should we style the three dashes in another manner? It's a special character in yaml to separate another yaml section from the previous section.

**Comment by steven1046** [comment]
@MaiHameed do you have a link to the guide where it's highlighting it purple? In https://openliberty.io/guides/microprofile-istio-retry-fallback.html#building-and-running-the-application traffic.yaml the separator is not purple.

**Comment by MaiHameed** [comment]
Hey @steven1046, my mistake, I wrote it out as `YAML` instead of `yaml` in the file inclusion. I updated it and it looks fine now. Is there a list of supported file types that I can quickly look at and add to our docs? Thanks :)

**Comment by steven1046** [comment]
That's odd that all caps `YAML` doesn't work. I see some guide using `YAML` currently. I would think based off all of the includes we currently have that all caps or the first letter capitalized would work: `Text, text, Java, java, XML, xml, yaml, JSON, gradle, groovy, properties`.

**Comment by steven1046** [comment]
I think just using lowercase for the full file type is the safest option for file includes @MaiHameed.

**Comment by steven1046** [comment]
It was actually a specific casing in the CSS we have to override the colors that coderay outputs. This is just for yaml. We can edit it so it supports all caps "YAML" too.

**Comment by MaiHameed** [comment]
Ah, perfect, thanks for the updates!

**Comment by steven1046** [comment]
The UI now supports file sources highlighting for "YAML", "Yaml", and "yaml" so I'll close this issue.
