### ISSUE TITLE
Add TM (Trademark) to the Open Liberty logo and first mention on homepage

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1665]
Add the ™ symbol to the SVG logo on the homepage:
![image.png](https://images.zenhubusercontent.com/59e8c568a468affe6df751e7/a9ac7189-e362-469f-a119-82d2bc7353f6)
and the first mention of Open Liberty on the homepage:

> Build cloud-native apps and microservices while running only what you need. Open Liberty™ is the most flexible server runtime available to JavaTM developers in this solar system.

**Comment by mdenby** [comment]
[OL_Logos_1.2.svg.zip](https://github.com/OpenLiberty/openliberty.io/files/4690301/OL_Logos_1.2.svg.zip)
