### ISSUE TITLE
Change all tags to be lowercase, no spaces

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1676]
Change all our tags to instead be all lowercase letters with no spaces, this includes blogs and guides.
Need to make sure that old tags continue to resolve/map to the new ones (for example, "Jakarta EE" in query param maps to "jakartaee")

**Comment by steven1046** [comment]
Why do they need to be lowercase?

**Comment by steven1046** [comment]
Is this still needed @mbroz2?

**Comment by mbroz2** [comment]
yes, we should still pursue this.  It's common practice to have tags be all lower case (it also looks odd to have some upper and some lowercase)

**Comment by steven1046** [comment]
Need to update https://github.com/OpenLiberty/guides-common/blob/prod/guide_tags.json and 
 https://github.com/OpenLiberty/blogs/blob/prod/blog_tags.json.

**Comment by natalie-bernhard** [comment]
This will also require updates to each of the language files here: https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/_i18n/en.yml#L256 (the value on the left needs to be equal to whatever the tags are listed as in blog_tags

**Comment by steven1046** [comment]
![Image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/765c0426-4978-4845-8b67-1dc688bbe1f7)

Some tags would look strange with all lowercase and no spaces, like "javase" and the user wouldn't know it's two words necessarily.

**Comment by steven1046** [comment]
After a site discussion, here is what we want to change the tags to:


Old | New
-- | --
Maven | maven
Jakarta EE | jakartaee
MicroProfile | microprofile
Kubernetes | kubernetes
Docker | docker
Cloud | cloud
Reactive | reactive
Getting Started | getting-started
Microservices | microservices
Gradle | gradle
Security | security
OpenTracing | opentracing
``@Traced`` | ``@traced``
OpenTelemetry | telemetry
``@WithSpan`` | ``@withspan``
Testing | testing
Interactive | interactive
``@Bulkhead`` | ``@bulkhead``
``@Asynchronous`` | ``@asynchronous``
``@Fallback`` | ``@fallback``
Concurrent requests | concurrentrequests
Circuit Breaker | circuitbreaker
``@CircuitBreaker`` | ``@circuitbreaker``
Fault Tolerance | faulttolerance
Config | config
``@Inject`` | ``@inject``
``@ConfigProperty`` | ``@configproperty``
ConfigSource | configsource
``@Retry`` | ``@retry``
``@Timeout`` | ``@timeout``
Run in cloud | runincloud
deprecated | deprecated
  |

**Comment by mbroz2** [comment]
I think we need to be consistent with regards to what we do with regards to spaces in the original tags.  I suggest we use '-' instead, like is being done in getting-started.  That means we'd have 'concurrent-requests', 'circuit-breaker', 'fault-tolerance' and 'run-in-cloud'.

@lauracowen for her input
