### ISSUE TITLE
Add SVG titles for the Docs page and reference header title

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#168]
Please answer the following if applicable
  - What is the priority?
  - Are designs ready? (attach screenshots and link to the redlines) Need SVG's
    - Are there mobile designs?
  - Is this a new page? If so, what is the permalink? No

**Comment by kinueng** [comment]
Found that using SVG for the titles is easier when needing to resize versus using straight text with CSS styling.

**Comment by megmulsy** [comment]
@kinueng - What are the issues with resizing the straight text at different breakpoints? Why are SVGs considered a better option? (Just trying to understand, thanks)

**Comment by steven1046** [comment]
Design created the svg titles for /Docs and also the docs header, so everything is available to finish this work item.
