### ISSUE TITLE
Zero Migration link from homepage to doc

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1685]
Once the [zero migration doc](https://github.com/OpenLiberty/docs/blob/draft/ref/general/zero-migration-architecture.adoc) is published, the two instances of 'zero migration' on the homepage should become links to the doc.  The styling of the links should follow the decision that was made for the Jakarta EE & MP links in #1551

**Comment by dmuelle** [comment]
The zero migration doc is now published: https://www.openliberty.io/docs/latest/zero-migration-architecture.html
