### ISSUE TITLE
Provide an obvious way to jump to the guide repo

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1694]
Based on the discussion in https://github.com/OpenLiberty/guides-common/issues/462
The guide UI should address following:
- provide an easy/obvious way to allow jump to the guide repo without the need scroll back to the Getting started section where will provide a link to the guide repo

**Comment by steven1046** [comment]
I think it would make the most sense to change for the code to go to the guide's repo and also change the verbiage to make it clear you are not `forking` the code and instead just going to view the code on Github.

**Comment by mbroz2** [comment]
Link to the repo will be added in the prereq section of the guide.  'Fork the code' will be addressed under #1722
