### ISSUE TITLE
"Tags" heading disappearing for guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1697]
<img width="302" alt="image" src="https://user-images.githubusercontent.com/4803104/84829237-6a179480-aff5-11ea-83e4-aff1b1a97422.png">

There should be a "Tags" heading above the tags in the TOC pane for the guides.  Looks like the heading is disappearing.  You can see it there when the page first loads but it is gone after a moment.

@gkwan-ibm

**Comment by ellenwyllie** [comment]
I don't see this issue on chrome or safari, but sometimes I can reproduce it on firefox

**Comment by yeekangc** [comment]
Thanks, @ellenwyllie.  I should have noted it -- Yes, I was using Firefox.

**Comment by gkwan-ibm** [comment]
I could reproduce too when I switched the guides by
- visit a guide
- click to the Guides at the banner
- visit another guide
- Tags will be disappeared occasionally when TOC is redrawing/rebuilding
