### ISSUE TITLE
Hotspot tag issue

### ISSUE THREAD

**Issue by DannyS03** [OpenLiberty/openliberty.io#1716]
Perhaps UI implementation needed to address the following use case: https://github.com/OpenLiberty/guides-common/issues/478

**Comment by mbroz2** [comment]
For the `draft-guide-rest-client-reactjs`, the `data` and `columns` hotspots were not highlighting when using tags in the README.adoc: **[hotspot=prop-posts file=1]`data`**  & **[hotspot=prop-columns file=1]`columns`** 
```
The [hotspot=return-table file=1]`return` statement returns the paginated table where you have defined the properties for the [hotspot=table file=1]`ReactTable`. The [hotspot=110 file=1]`data` property corresponds to the consumed data from the API endpoint and is assigned to the `data` of the table. The [hotspot=113 file=1]`columns` property corresponds to the rendered column object and is assigned to the `columns` of the table.
```
<img width="1360" alt="image" src="https://user-images.githubusercontent.com/25497083/85791633-29f49800-b700-11ea-83be-bfbb90e61c98.png">


They should be highlighting the `data={posts}`  & `columns={columns}` lines, respectively. 

Perhaps it is something to do with the hotspots in `ArtistTable.js` being declared inside the `<ReactTable>` JavaScript syntax. **Using line numbers for now.**

```
  // tag::return-table[]
  return (
    <div>
      <h2>Artist Web Service</h2>
      {!isLoading ? (
        // tag::table[]
        <ReactTable
          // tag::prop-posts[]
          data={posts}
          // end::prop-posts[]
          // tag::prop-columns[]
          columns={columns}
          // end::prop-columns[]
          defaultPageSize={4}
          pageSizeOptions={[4, 5, 6]}
        />) : (
        // end::table[]
          <p>Loading .....</p>
        )}
    </div>
    );
    // end::return-table[]
```

**Comment by steven1046** [comment]
Is this still an issue?

**Comment by gkwan-ibm** [comment]
close
- cannot see the problem or the problem was addressed
