### ISSUE TITLE
UI issue regarding "copy to clipboard"

### ISSUE THREAD

**Issue by TiagoF99** [OpenLiberty/openliberty.io#1718]
<img width="1440" alt="Screen Shot 2020-06-29 at 9 43 18 AM" src="https://user-images.githubusercontent.com/45250015/86013333-088bf880-b9ed-11ea-99ca-72bfa9235a25.png">

- Guide-cloud-IBM, mac, fullscreen, firefox
- As seen in the above photo, the "copy to clipboard" button shows up outside of the command box instead of in the top right corner like in the other guides. When I move my mouse towards to button, it disappears and makes it really hard to click it because I have to move my mouse before it disappears.
- I think this may be an issue with guides that do not have hotspots for whatever reason

**Comment by mbroz2** [comment]
Seems as though this might be limited to a window being resized.
