### ISSUE TITLE
Remove "Fork the code" button from the header

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1722]
-  Readers may confuse that the "Fork the Code" button in banner to mean taking them to the repo for the guide instead of Open Liberty instead.

**Comment by mbroz2** [comment]
If we implement # does the issue go away since the header (and the "Fork the Code" button) would only appear at the start of the guide and if the user scrolls back up?

**Comment by yeekangc** [comment]
Should make it clear that this button is for forking the Open Liberty code base.

**Comment by mbroz2** [comment]
We're going to remove the 'Fork the Code' button from the header.
