### ISSUE TITLE
Improper scrolling on load for sections in guides (URLs with hashes)

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1726]
When navigating to a guide section via URL (first load or reload), for example https://openliberty.io/guides/microprofile-reactive-messaging.html#creating-the-producer-in-the-system-microservice, the user scrolled to an incorrect place.  Instead of having the header at the top, it appears lower.  On chrome it looks like: ![image.png](https://images.zenhubusercontent.com/59e8c568a468affe6df751e7/0720dccd-800e-40c1-837b-2f5a8feb5f13)

And on Firefox it's even worse as it renders it so low that it causes the previous section to be displayed instead:
![image.png](https://images.zenhubusercontent.com/59e8c568a468affe6df751e7/b5a6333e-b3d7-4fe7-9203-5fac437165e3)

Note, when clicking on the sections in the ToC, we have the correct behavior.

**Comment by steven1046** [comment]
This must be a timing thing, it works fine for interactive guides: https://openliberty.io/guides/microprofile-config-intro.html#configuring-as-an-appproperties-element-scoped-by-application
