### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by mehmetanbaki** [OpenLiberty/openliberty.io#1732]
It's won't work with my os and I tried everything in google, stackoverflow and youtube

**Comment by k8vance88** [comment]
Hi @mehmetanbaki, sorry you are having problems.  Can you provide more information on what product you are trying to use?  Are you trying to get an Open Liberty web server running?  Or are you trying to use the openliberty.io website and/or guides?

**Comment by mbroz2** [comment]
@mehmetanbaki can you provide more information regarding what you're trying to do

**Comment by mbroz2** [comment]
Hi @mehmetanbaki, we can't make progress on this issue until we receive more information as requested in the previous comments.  As such, I'm closing this issue, but we're happy to reopen it when more information is provided.
