### ISSUE TITLE
Links to features no longer default to the most recent version

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/openliberty.io#1755]
Two issues I've noticed since the transition:

* Links to features now require that you specify a version number or they won't resolve. Previously, if you didn't specify a feature version in the link, the page would default to the latest version. This is helpful because it means the current doc will also default to the latest version when you link to a feature, though you can still specify a particular version if needed.

For example, previously
`link:docs/ref/feature/appSecurity.adoc` 
would resolve to 
`docs/ref/feature/appSecurity-3.0.adoc` (latest version)

But with the antora syntax
`xref:reference:feature/appSecurity-3.0.adoc`
if you don't specify `appSecurity-3.0`, the link doesn't resolve at all. 

So, in the future, when appSecurity-4.0, comes out, all our docs will still link to 3.0, instead of defaulting to the new version.

**Comment by steven1046** [comment]
It should be fixed soon, but i think the syntax would be `link:reference/feature/appSecurity.html[Feature name]`, right @dmuelle? When i used .adoc in my testing it just resolved to .adoc in the link as well but we want .html.

**Comment by dmuelle** [comment]
@steven1046 actually antora uses a different [page reference syntax](https://docs.antora.org/antora/2.3/navigation/xrefs-and-link-text/)

`xref:reference:feature/appSecurity-3.0.adoc`

We haven't been using the `link:/docs...` syntax since the transition, though it might still work.

Will the fix support the antora syntax?

**Comment by steven1046** [comment]
This won't work with the antora syntax i believe, because the `appSecurity.adoc` file doesn't exist. `link:reference/feature/appSecurity.html` works because we have an html without the version that redirects to the latest version. `link:/docs/ref/feature/appSecurity.html` also works with this sytax.

**Comment by steven1046** [comment]
The feature:appSecurity[feature name] macro should also work, i'm testing that now.

**Comment by dmuelle** [comment]
ok- makes sense. I think  the macro is the best option if we can get it to work

**Comment by steven1046** [comment]
@dmuelle The macro `feature:appSecurity[Feature link]` did work for me to take me to `/docs/20.0.0.8/reference/feature/appSecurity-3.0.html`

**Comment by dmuelle** [comment]
^^ @Charlotte-Holt ^^

**Comment by dmuelle** [comment]
Hi @steven1046 - Just tested this out in a doc and realized there's a blocker. Our style guide specifies to use the plain text names of features in a doc (eg. "the Application Security feature"). However, using the macro just gives you the code name for the feature, (eg appSecurity). 

I thought I might be able to specify the plain text name of the feature in the square brackets after the macro like
`feature:appSecurity[Application Security feature]`, but when I tried that it just prints as [appSecurity](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.8/reference/feature/appSecurity-3.0.html). 

Is it possible to specify the plain text name from the macro? If not, they're not going to be much use in the doc

**Comment by steven1046** [comment]
@dmuelle do you have an example on the draft site where it displays the camelCased title?
