### ISSUE TITLE
Long feature versions on mobile should only scroll the versions and not the Feature name

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1768]
![image](https://user-images.githubusercontent.com/6392944/88939658-6611a000-d24c-11ea-917c-07277abcac70.png)
Right now the title of the page will scroll with the version marquee in mobile and we want it to only scroll the versions.

**Comment by mbroz2** [comment]
![image](https://user-images.githubusercontent.com/3076261/90051782-d6351280-dc9d-11ea-9835-8e4e4e85c997.png)
