### ISSUE TITLE
Write an extension for Antora's version sorter

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1820]
Right now we use `X.0.0.X` as our version schema, and Antora only seems to support `X.X.X` following the convention https://semver.org/. This messes up our canonical urls and version picker sort order because Antora doesn't recognize our version ordering with the third period `.` in the version. We need to write an extension to the tooling to handle sorting versions with this many version components.

**Comment by steven1046** [comment]
We wrote a custom helper (#1849) to sort our versions so they are in order. In the future, Antora might expose a version extension here: https://gitlab.com/antora/antora/-/issues/454.

**Comment by steven1046** [comment]
Look up how to extend the node_module that Antora pulls in called "semver".

**Comment by k8vance88** [comment]
Closing this issue as it's already working.  I see no reason to change it.
