### ISSUE TITLE
Javadoc modules shouldn't be visible or redirect you to the javadoc page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1832]
https://openliberty.io/docs/modules/reference/microprofile-3.3-javadoc/javax/enterprise/inject/spi/InjectionPoint.html  shouldn't be accessible, but it has to exist to be able for the iframe to show the javadocs. We should make it not accessible or redirect to the javadoc page that contains the javadoc in frames.

**Comment by steven1046** [comment]
~Try adding `/docs/modules/reference/*=/docs/ref/javadocs/` to the redirects.~

**Comment by mbroz2** [comment]
The above also redirects our iframe; as a ~temporary workaround, we could change our iframe url to include a `./` in the path, so something like `src="/docs/./modules/reference/*"` which should then not match our redirect string above.

**Comment by steven1046** [comment]
Adding a period didn't prevent the backend from redirecting the iframe. I wonder if we could just add `<meta name="robots" content="noindex">` to the javadoc iframe so they can't be indexed in search engines.

**Comment by steven1046** [comment]
The above would probably lower the SEO ranking of Javadocs on the website as search engines wouldn't crawl iframe and discover the contents. The only SEO rankings showing up on Google for the javadocs are the individual modules from Antora and not the entire site's frame. Adding noindex would prevent all of this, but have less linking to the javadocs.

Another solution could be to tell the redirect filter to not redirect any paths containing `/./`.

**Comment by steven1046** [comment]
Even with no redirects containing "/./", the following redirects don't work well enough:
/docs/modules/reference/*=/docs/ref/javadocs/
/docs/modules/reference/microprofile*=/docs/latest/reference/javadoc/microprofile
/docs/modules/reference/liberty-javaee*=/docs/latest/reference/javadoc/liberty-javaee
/docs/modules/reference/microprofile-3.3-javadoc/*=/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html

because the real javadoc urls are way different than the modules stored in Antora.
