### ISSUE TITLE
Update description of /guides to be specific to the guides page

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#1833]
We have a generic description for the page today.

Consider a description like the below:

Guides, tutorials, examples on developing cloud-native Java microservices and applications with Open Liberty, Eclipse MicroProfile, Jakarta EE, containers, Kubernetes and cloud deployments and more.

@lauracowen @mbroz2

**Comment by yeekangc** [comment]
Tagging @gkwan-ibm in case he has thoughts too.

**Comment by mbroz2** [comment]
I wouldn't be opposed adding "REST" (or "RESTful") and "Reactive" to that list

**Comment by yeekangc** [comment]
I was wondering about those.  =)
