### ISSUE TITLE
Certifications: add a landing page for /certifications

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1838]
Currently, the certifications can only be accessed at their file location (as laid out in [certifications repo](https://github.com/OpenLiberty/certifications)), for example:
https://openliberty.io/certifications/jakartaee/platform/8/TCKResults.html
https://openliberty.io/certifications/jakartaee/webprofile/8/TCKResults.html
https://openliberty.io/certifications/jakartaee/servlet/4.0/TCKResults.html

We want to add a landing page at /certifications that will list all the various certifications.  One way to do this would be to reuse the layout of /docs, antora and all.  Another option would be to leverage the /guides ToC.  However, we could just do a simple page that lists the various certifications (almost similar to /blogs).

Currently this is a want, but it could become a must if the Jakarta Committee makes it required (waiting for result)

**Comment by kwsutter** [comment]
Although it's a "want", I'd like to have an example for our discussions with the Spec Committee.  So far, only Open Liberty have multiple Certification Requests.  The discussions are too abstract to make sense for everyone on these calls.  So, it would be great if we could have the Open Liberty landing page available for our discussions.  I would rather not wait until the Spec Committee requires it before we do this effort.  My two cents worth...

**Comment by mbroz2** [comment]
openliberty.io/certifications exists now as an dynamically generated page listing all the certifications.
