### ISSUE TITLE
News Feed regarding Open Liberty

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#184]
Population of content: automatic vs manual

**Comment by kinueng** [comment]
@mbroz2 Please add some more details for this issue

**Comment by kinueng** [comment]
In the new redesign proposal of the homepage, there was an introduction of the idea of having a news feed at the bottom.  There will be more discussions on the details of that news section and we will use this issue to track that ongoing work.

A snapshot of the designs (subject to change, of course)
![image](https://user-images.githubusercontent.com/31117513/41108532-62ffe01a-6a3a-11e8-8b4f-79d91dde6935.png)

**Comment by mbroz2** [comment]
For designs, see: https://github.com/OpenLiberty/openliberty.io/issues/342#issuecomment-480006782

**Comment by mbroz2** [comment]
For the "latest" blog post, the flow should be to always show the latest one.  If there's two or more blog posts with the same date, than look for a flag to determine which one to show.  If no flag is present, we'll either want to fail the build (force a flag to be provided) or just pick one.

**Comment by mdenby** [comment]
I think this will be addressed in the new homepage design.

**Comment by mbroz2** [comment]
This has already been done as part of the homepage redesign.
