### ISSUE TITLE
Ecosystem Tools Representation on OpenLiberty.io

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/openliberty.io#185]
Spinning off #136, we need to figure out how we are going to represent the tools around the OpenLiberty "ecosystem". I originally made the suggestion for a landing page for the ecosystem tools. Also see https://github.com/OpenLiberty/openliberty.io/issues/136#issuecomment-366324343

**Comment by mbroz2** [comment]
New home page design will reflect this: #342
