### ISSUE TITLE
Improve Search field in guides

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#186]
The current search seems to be implemented as a .contains() on the input string against the fields we search, which is far too restrictive.  Instead, it should consider each word in the search field as a separate keyword to search and show any guides that have searchable fields with the keywords.  For example, if the user searches for "rest angular" the search should first search for "rest" and then perform a search on the results of that for "angular" and end up with the "Consuming a RESTful web service with AngularJS"

**Comment by kinueng** [comment]
This is the method that needs enhancements
https://github.com/OpenLiberty/openliberty.io/blob/9c60c043ac32d835df8b24f9b7e89721a44f62cb/src/main/content/_assets/js/guides.js#L18

**Comment by steven1046** [comment]
This work is on the main site now, so closing it.
