### ISSUE TITLE
Move blogs imagesdir attribute to a common place

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1862]
Each blog sets `:imagesdir: /` in the asciidoc front matter variables. We can probably set it in a common file like post.html so each blog doesn't need to set it. Also, we should look into if we even need it because https://raw.githubusercontent.com/OpenLiberty/blogs/prod/posts/2020-06-05-asynchronous-programming-microprofile-fault-tolerance-part-2.adoc has images and doesn't even need to set imagesdir.

**Comment by k8vance88** [comment]
Steven to discuss this this blog team on slack
