### ISSUE TITLE
Guide Pages Display Error

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/openliberty.io#1878]
On any of the guides at https://openliberty.io/guides/, the menu on the left side of the screen displays incorrectly on both Firefox (vers. 80.0.1) and Safari (vers. 13.1.2) on 13" MacBook Pro 2019 machines (macOS Catalina vers. 10.15.6). The menu bar, within the `<div>` element with `id=background_container` hangs over the `<div>` element with `id=end_of_guide`, which makes the items within the `end_of_guide` container difficult to access. I suspect this is due to the resolution of the Mac - 2560x1600. See the attached image for reference. 

<img width="1438" alt="Screenshot 2020-09-21 at 13 52 38" src="https://user-images.githubusercontent.com/41568419/93769969-7ffbad80-fc13-11ea-8b9a-c5bde31e8ac8.png">

This issue did not persist on a Windows 10 (vers. 1903) machine in my possession, with a resolution of 1920x1080 on both Firefox (vers. 80.0.1), and Chrome (vers. 85.0.x).

**Comment by steven1046** [comment]
Hi @scottcurtis2605, I am unable to produce this bug on Safari or Firefox (on Mac). Do you have any tips on how you saw this?

**Comment by steven1046** [comment]
Nevermind, i was able to reproduce while zoomed in far enough and at the bottom of the guide, the table of contents is overlaid wrong.

**Comment by dmorgant** [comment]
I believe this is fixed with issue #1924.   Will review again once the fix makes it to prod.

**Comment by dmorgant** [comment]
With the fix for issue #1924 Steven and I are no longer able to recreate this problem.   

Closing this issue.  If it still occurs, please reopen with details.  Thank you.
