### ISSUE TITLE
Docs H2/H3 look too similar in (Firefox only)

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1885]
Docs H2/H3 look too close to each other. I think the H2/H3 in posts are good so we should really just move the post css into the whole website css so they are aligned.

Example:
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/authentication.html
![image](https://user-images.githubusercontent.com/6392944/94562642-328eca00-022b-11eb-954d-d114b5f29a16.png)

**Comment by ellenwyllie** [comment]
The font size for h2 and h3 in docs is the same as in posts. Both are 24px for h2 and 20px for h3. I don't see any problem here, so I'm going to close this issue.
