### ISSUE TITLE
Update dev mode link on homepage

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1896]
Currently the Lear More link for dev mode points at https://openliberty.io/blog/2019/10/22/liberty-dev-mode.html
![image](https://user-images.githubusercontent.com/3076261/96010275-3c0d5a00-0e07-11eb-9e30-8e47a7d09392.png)

Now that we have a doc page for dev mode, we should point at it instead:
https://openliberty.io/docs/20.0.0.10/development-mode.html

**Comment by steven1046** [comment]
The link should point at /docs/latest/development-mode.html
