### ISSUE TITLE
Split up single Build Job into multiple in IBM Cloud

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1915]
Our builds use the public build infrastructure, which can vary in performance since they're shared resources.  A single job can only run for at most 60 minutes, and we're starting to hit that limit when the infrastructure is running slower (due to our additional docs each release).

We should split the single build job into multiple.

Another option is to use Delivery Pipeline Private Workers: https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-install-private-workers

**Comment by mbroz2** [comment]
Turns out that not only do jobs not share environments (each job run in its own container), but you also can't pass any artifacts from one job to another, as documented here: https://cloud.ibm.com/docs/ContinuousDelivery?topic=ContinuousDelivery-faq_delivery_pipeline

If we wanted to split the build up, it would need to be done in multiple Stages in the pipeline.  Perhaps we could split it into:
1) Clone all the necessary repos (shouldn't need any environment setup overhead) (but note this wouldn't include docs/docs-generated which is a lot of the content)
2) Jekyll build
3) Antora build

Since I think 2 & 3 would likely have some overlapping environment setup necessary, perhaps at least at the begging, we can keep them combined and just split out the git clones.

**Comment by steven1046** [comment]
One thing to *potentially* reduce some time in the builds is to `exclude` the new generated javadocs directory in the jekyll config. Because jekyll doesn't need to look at those and are processed by Antora. I'm unsure how much time it would save but it will be >0 for sure.

**Comment by mbroz2** [comment]
Another approach is to clone docs-javadoc after jekyll runs..... but if we're cloning everything first then this won't help

**Comment by k8vance88** [comment]
Needs more investigation

**Comment by mbroz2** [comment]
Split the builds into 2 stages, which is enough for now; we'll need to revisit in the future and either split further or completely change the build and/or infrastructure for the site.
