### ISSUE TITLE
Dynamic code snippets for "narrow" version of multipane layout

### ISSUE THREAD

**Issue by chyt** [OpenLiberty/openliberty.io#1916]
My understanding is that the current implementation of the "narrow" multi-pane layout (for smaller screen sizes) will display the entire file inline and then reference specific portions of it in the text. However, this is bad for usability as it requires the user to scroll up and down between the code and the text, and they can easily lose track of where they were in the guide.

I propose a solution using dynamic code snippets, similar to Github's implementation in their PR review system. When discussing a specific portion of code, include a snippet by referencing the file path and line number range. By default, only the snippet in the line number range will be shown. 

The user can then click an expand button, which I think can do one of two things: 

1. Increase the surrounding context of the snippet by a fixed amount, similar to what the Github PR review implementation.

2. Pop up a full screen view with the entirety of the file displayed, scrolled to the highlighted snippet range. A separate button can exist on this view to close it. 

Personally I lean towards the second option. Either way, this implementation allows for the code to correspond more directly with the text, and eliminates the need for scrolling back and forth between the two. It also still retains flexibility for being able to easily get context for the code snippet when it is desired.

**Comment by gkwan-ibm** [comment]
Transferred this issue from guides-common repo, because I think it is about the guide UI style instead of guide content.

**Comment by mbroz2** [comment]
We do number 2 now.
