### ISSUE TITLE
Update antora to version 3.0

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/openliberty.io#1923]
Upgrade antora to 3.0 once it is released. Antora hasn't announced a release date yet, but you can check the release schedule here: https://docs.antora.org/antora/3.0/project/release-schedule/.

As part of this upgrade you will need to undo some temporary changes made for the generated docs updates. There are comments in the code (in `build_jekyll_maven.sh` and `build_antora_ui.sh`) explaining the changes needed. I left the original code commented out so it should be easy to add back in. Here are the steps you need to take:
1. Delete custom-include-processor.js
2. Revert build_antora_ui.sh to how it was and update the version to 3.0 in the step that clones the antora site generator. It should look like the code below:
```
echo "Building the Antora UI"
pushd src/main/content/antora_ui
echo "Installing Antora UI dependencies"
npm install -g @antora/site-generator-default@3.0
npm install gulp -g
npm install node-sass gulp-sass --save-dev
npm install
gulp sass:convert
SOURCEMAPS=true gulp build
gulp bundle:pack
popd
```
3. Update the antora build step in build_jekyll_maven.sh so that it no longer uses a local copy of antora. You should be replacing "antora/node_modules/.bin/antora" with "antora".

You can reference this pr to see the before and after: https://github.com/OpenLiberty/openliberty.io/pull/1922/files

**Comment by steven1046** [comment]
Estimated GA of 3.0 is this month per the release schedule

**Comment by kinueng** [comment]
Antora 3.0.1 is now available at the time of this writing
https://docs.antora.org/antora/latest/whats-new/

**Comment by kinueng** [comment]
We need the docs team to look around the docs for regression. 
We need to see if the build is faster/slower with Antora 3.0.
We need to socialize new features in Antora to the docs team.
