### ISSUE TITLE
At certain small browser widths, the TOC indicator arrow doesn't work

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1924]
![image](https://user-images.githubusercontent.com/6392944/98015972-04208380-1dc3-11eb-82f0-6c7b733b1453.png)
If you click the orange arrow, you expect the TOC to open up but at certain widths in 2 column view it animates to the same section you're on and doesn't open the TOC.

**Comment by steven1046** [comment]
So it does open the TOC, but the TOC is stickied to the top of the guide and you can't see it from where you're at.

**Comment by steven1046** [comment]
It might be a gap in the css @media ranges

**Comment by dmorgant** [comment]
For me, I am having problems with the TOC in a different way.    When I scroll down pass the nav header, I see the following, where the guide content is shifted to the left and a blank column, about the width of the TOC, is in the middle of the page.

![image](https://user-images.githubusercontent.com/29490139/109863327-20281a80-7c27-11eb-99d1-ab34c6ae71bc.png)

Then, when you get to the end of the guide the TOC displays again, although looks transparent as it is written on top of the guide end.

![image](https://user-images.githubusercontent.com/29490139/109863229-fff85b80-7c26-11eb-9293-a75f2a6fc27a.png)

---------------------------------------

I also see a problem that when scrolled all the way to the top of the guide the TOC header (where it says 'Contents' and the 'x' to close the TOC) is not viewable.  It is hidden under the nav bar.

![image](https://user-images.githubusercontent.com/29490139/109863475-4b126e80-7c27-11eb-8af5-cee1e4b838d0.png)

It should look like this

![image](https://user-images.githubusercontent.com/29490139/109863513-56fe3080-7c27-11eb-881e-16cbd4736a92.png)

**Comment by dmorgant** [comment]
This may also fix the problem described in #1878
