### ISSUE TITLE
Copying from Code-blocks broken on all guides

### ISSUE THREAD

**Issue by austin0** [OpenLiberty/openliberty.io#1932]
Both in-guide code-blocks and the linked files are not copied when the copy button is pressed, i.e:

<img width="287" alt="Screen Shot 2020-11-10 at 10 57 10" src="https://user-images.githubusercontent.com/23284299/98665490-a7354800-2343-11eb-85e8-fa7beb60f16a.png">

This seems to be a site-wide issue, for example trying to copy the `git clone` statement from https://openliberty.io/guides/getting-started.html#getting-started does absolutely nothing.

This has been tested on multiple guides with both Chrome and Safari.

**Comment by steven1046** [comment]
Should be fixed now
