### ISSUE TITLE
Jakarta EE feed doesn't pull in all of the "Jakarta EE" tagged blogs

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#1934]
This is because we externalized our blog tags to a single file in the blogs repo (https://github.com/OpenLiberty/blogs). Jekyll doesn't know about the tags from each blog anymore since it uses site.tags to process the feed and site.tags is emptied now that blogs don't have tags in each file.

https://openliberty.io/jakartaee.xml only has one post because one file https://raw.githubusercontent.com/OpenLiberty/blogs/prod/posts/2019-05-08-jakarta-ee-naming.adoc still has a tag in the post by mistake.

**Comment by lauracowen** [comment]
The consequence (adding to help with prioritisation) is that the Jakarta.ee blog isn't syndicating all the Jakarta EE blog posts that we publish and tag with `Jakarta EE` - so potentially losing additional audience from the syndication.

**Comment by steven1046** [comment]
I'm going to parse the blog tags file and add it to the individual blog files during build time so jekyll knows those blog posts have those tags when jekyll builds.

**Comment by steven1046** [comment]
It's fixed now. https://openliberty.io/jakartaee.xml
