### ISSUE TITLE
Docs version picker missing hover over 

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#1937]
Currently the version picker in docs does not provide a hover over behavior:
![image.png](https://images.zenhubusercontent.com/59e8c568a468affe6df751e7/f7a1d54c-587e-4cbe-b346-9c3220051de0)

We should either have a border (green) around the hovered over version, or add an underline.

**Comment by steven1046** [comment]
Use the same orange text as the TOC
