### ISSUE TITLE
Travis (draft and staging) builds are really slow

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#1938]
Each takes about 40 mins to run. It makes publishing a blog post very cumbersome because 40 mins is too long to sit and wait, but switching tasks means we might forget to check the build has run (or we're constantly checking back) and then come back to it an hour or so later to then kick off the next build. It can take a whole day in elapsed time just to publish a blog post after completing an edit, so it's really inefficient.

I know there are problems with the prod build and the possibility of breaking up the build into chunks, which might help here too (eg it'd be great to just rebuild the blog section and nothing else, or at least not to rebuild the docs every time we publish a new blog post). But I wanted to make sure this was on the backlog too.

**Comment by dmuelle** [comment]
This is a problem for the docs team as well- our draft builds are failiong repeatedly so in some cases it can take several attempts (and several hours) just to verify an update

**Comment by mbroz2** [comment]
The builds have been moved to IBM Cloud, and split into 2 stages (jekyll, followed by antora + mvn), followed by the deploy stage.
Furthermore, content specific sites have been created that only build the ui (openliberty.io repo) and blogs, certifications, guides, or docs:

- [draft site](https://draft-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to any draft branch from the following repos: openliberty.io, docs, docs-playbook, docs-generated, docs-javadoc, blogs, certifications, guides-common (and contains docs-generated content only for the upcoming/next release).
- [staging site ](https://staging-openlibertyio.mybluemix.net/) It will automatically rebuild from changes to any staging branch from the following repos: openliberty.io, docs, docs-playbook, docs-generated, docs-javadoc, blogs, certifications, guides-common
- [blogs-draft site](https://blogs-draft-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the draft branch in blogs repo, and only include the blog content.
- [blogs-staging site](https://blogs-staging-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the staging branch in blogs repo, and only include the blog content.
- [docs-draft site](http://docs-draft-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the draft branch in docs* repos, and only include docs* content (and contains docs-generated content only for the upcoming/next release).
- [docs-staging site](http://docs-staging-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the staging branch in docs* repos, and only include docs* content.
- [guides-draft site ](https://guides-draft-openlibertyio.mybluemix.net/) It will automatically rebuild from changes to the dev branch in guides-common repo, and only include guide content (including draft guides).
- [guides-staging site](https://guides-staging-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the qa branch in guides-common repo, and only include guide content
- [certifications-draft site](https://certifications-draft-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the draft branch in certifications repo, and only include the certifications content.
- [certifications-staging site](https://certifications-staging-openlibertyio.mybluemix.net/)  It will automatically rebuild from changes to the staging branch in certifications repo, and only include the certifications content.

The content specific sites should help the content teams iterate quicker, as the build+deploy for those sites takes ~15-25min depending on the amount of content.
