### ISSUE TITLE
Add confirmation message for copy button in code pane in Guides

### ISSUE THREAD

**Issue by griffinhadfield** [OpenLiberty/openliberty.io#1939]
When you copy a command from the pane on the left, a "Copied to clipboard" message appears. However, when the copy button is used to copy code from the right-hand pane, no confirmation message is displayed. The addition of this feature was given as a recommendation as part of a user review. 

<img width="132" alt="Screenshot 2020-11-13 at 11 23 29 AM" src="https://user-images.githubusercontent.com/38739044/99095101-b239e380-25a2-11eb-9f4e-435fd234f3b4.png">

**Comment by mbroz2** [comment]
I agree that we need to be consistent in the behavior of our copy button; either always provide a confirmation that copy has happened, or never.
We could move to using a tooltip as a confirmation, or change the 'copy' button into a 'checkmark' for 1sec.

**Comment by mbroz2** [comment]
We could move to using a tooltip as a confirmation, or change the 'copy' button into a 'checkmark' for 1sec.

**Comment by steven1046** [comment]
I'd vote using a confirmation message, because sometimes when you move your mouse out of a code block you can copy, it vanishes. So changing the icon to a checkmark wouldn't be that helpful when someone moves their mouse after clicking copy.

**Comment by natalie-bernhard** [comment]
If the confirmation message is added, do we need design to weigh in on placement? Since there's no space above the button, I could see having it show up to the left of the button after it's clicked, but I'm not sure if design has any other ideas for placement of the confirmation

**Comment by steven1046** [comment]
Maybe below, so in mobile it also fits? 
![image](https://user-images.githubusercontent.com/6392944/121544633-7f888a00-c9cf-11eb-8ba3-86884c201671.png)
