### ISSUE TITLE
Revisit the "Update" actions in guides

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#1940]
Following is from https://github.com/OpenLiberty/draft-guides-template/issues/37 (opened by Laura):

**"Update" actions in guides**
https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles#code-command (option 3 "update")

I don't like the way that we have the action boxes with the leaky green line - I'm pretty sure they weren't designed to be used like this, or usability tested like this:

![image](https://user-images.githubusercontent.com/3322532/93601826-b2aa6980-f9b9-11ea-8b13-2c29b8a1c108.png)

It looks as if the site style sheet has rendered badly and I don't think that's what the intention of the design was for these action arrows.

On occasions when it's necessary to do an "update" action, can't the instruction just come before the arrow?

I'm not sure it's actually necessary to have a specific style for how to present an "update" action because it should be _really_ rare that any guide has an "update" action anyway (only when it makes sense like changing the configuration from one implementation to another, like say moving a Spring Boot app from Tomcat to Open Liberty where that's an actual process that a real person might need to go through). Enabling trace is just something you do as part of your application code, like adding fault tolerance or metrics annotations (you have to recompile your code - it's not like making some external config change) - just assume they're writing the app (ie "create") and they're adding the relevant annotations. It would be a much simpler story.

**Comment by k8vance88** [comment]
@mdenby is this how it is supposed to behave?  Or is this a bug?

**Comment by mbroz2** [comment]
Only place I can find this in is https://openliberty.io/guides/microprofile-opentracing.html, need to check if this is a css bug or an issue with the adoc for the guide.

**Comment by k8vance88** [comment]
@steven1046 Can you take a look at the guide and see if something in there is triggering this?

**Comment by steven1046** [comment]
That's just the design, we could definitely change it. There are more instances of it: https://openliberty.io/guides/docker.html#testing-the-container 
https://openliberty.io/guides/microprofile-fallback.html#try-what-youll-build

**Comment by k8vance88** [comment]
@mdenby can you take a look at this?

**Comment by mdenby** [comment]
Sure, I'll look at this for our meeting tomorrow.

**Comment by mdenby** [comment]
What if we changed the actions to match the existing code blocks but add a heading to note an action?

<img width="867" alt="Screen Shot 2020-12-02 at 8 51 43 PM" src="https://user-images.githubusercontent.com/26823018/100953533-c6f20300-34e0-11eb-9409-2f2a2cd69e51.png">

**Comment by gkwan-ibm** [comment]
Probably need to prototype it to see how it really being look
