### ISSUE TITLE
Highlighted text in topics is more difficult to see than other types of highlighting.

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/openliberty.io#1942]
**Problem**: Currently, highlighted text in topics displays as gray text with a gray background, which makes the text more difficult to see than other highlighting such as monospace font. For example, the following topic has terms such as server.xml, and featureManager highlighted with this gray text and background: https://openliberty.io/docs/20.0.0.11/reference/feature/spnego-1.0.html
**Request**: Change the highlighting to something that is easier to read, such as black monospace font with no added background.

**Comment by k8vance88** [comment]
@mdenby can you take a look at this one?

**Comment by mdenby** [comment]
Sure! I'll look at this for our meeting tomorrow.

**Comment by mdenby** [comment]
Gathering examples for ideas of styling here. Wondering if it's a contrast issue?

<img width="370" alt="Screen Shot 2020-12-02 at 9 04 21 PM" src="https://user-images.githubusercontent.com/26823018/100955018-c0b15600-34e3-11eb-98bd-0c876ce072c6.png">


<img width="513" alt="Screen Shot 2020-12-02 at 9 15 01 PM" src="https://user-images.githubusercontent.com/26823018/100955014-c018bf80-34e3-11eb-891f-a0117470c666.png">
<img width="573" alt="Screen Shot 2020-12-02 at 9 06 29 PM" src="https://user-images.githubusercontent.com/26823018/100955016-c0b15600-34e3-11eb-9593-24c4bcbf07e0.png">
<img width="342" alt="Screen Shot 2020-12-02 at 9 06 17 PM" src="https://user-images.githubusercontent.com/26823018/100955017-c0b15600-34e3-11eb-9b6c-0631fb494fca.png">

**Comment by steven1046** [comment]
Using the IBM Equal Access Accessibility Checker, the gray on blue/gray background doesn't fail for accessibility.

**Comment by mbroz2** [comment]
I think a larger contrast between the text and the background would help, however, I'll also mention that the one we have today does pass a11y.
@mdenby do you have a suggestion on the change in the contrast?

**Comment by k8vance88** [comment]
Closing this specific issue because we opening an issue to do another a11y scan and fix violations.
