### ISSUE TITLE
Every latest build is not being shown on the downloads page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#196]
Only up to 3/2 are being shown.

**Workaround**: rebuild openliberty.io to refresh the build list.

**Comment by lavenal** [comment]
The original implementation allows the fetching of the builds once only. Change logic to allow builds to fetch if an hour has elapsed. An hour is chosen to take care of multiple builds done in a single day but disallow fetching builds continuously if the Download tab is kicked more often by a user.

**Comment by steven1046** [comment]
#271 fixed the updating problem, but I just tested viewing the builds page on the test server and it took a few refreshes before any builds came up at all.
