### ISSUE TITLE
Improve site performance (consider minify resources)

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2]
Website performance can be improved by minifying CSS, HTML, and JavaScript files.  

[Google PageSpeed ](https://developers.google.com/speed/pagespeed/ ) results showing how much improvements can be gained if files are minified.

Results:
https://developers.google.com/speed/pagespeed/insights/?url=openliberty.io
Current values at this time: mobile 59, desktop 76

Jekyll plugin that may aid in compressing files:
http://jekyll.github.io/jekyll-assets/

**Comment by gindik** [comment]
@kinueng thanks for the links / suggestions. We actually do have some of the performance items lined up for the implementation, I'll incorporate the ones above.

**Comment by gindik** [comment]
Adding a second performance benchmark in order to better measure impact of changes before/after implementation. https://tools.pingdom.com/#!/cyj8qP/https://openliberty.io/

**Comment by gindik** [comment]
<img width="990" alt="screen shot 2017-09-22 at 1 07 43 pm" src="https://user-images.githubusercontent.com/17207930/30756173-8aff23f0-9f97-11e7-84a5-6038807cbd38.png">

**Comment by gindik** [comment]
I looked into Jekyll assets. It's definitely something we want to incorporate into the site. However, it does not appear to handle HTML minification. For that we'll have to resource to a different tool such as https://github.com/octopress/minify-html.

**Comment by gindik** [comment]
I tested octopress html minify and it works fine in the development environment. However, when pushing it to production it's not working right. After trying several times I found that other people also reported the same issues: https://github.com/octopress/minify-html/issues/13. For now I'll remove the dependency and look for other ways to achieve HTML minification.

**Comment by gindik** [comment]
First optimization steps: minify CSS, JS and compressed largest images (that do not require transparent background) to JPEG. Results:
 - Page size went from 583.2kB  to  499.2kB
 - Load time went from 1.34s to 1.25s
 - Site went from 83% to 85% faster than tested sites

**Comment by gindik** [comment]
Further optimization:
 - Optimized SVG images (combined with the previous compression optimization, images in the site went from 890KB to 582KB)
 - Replaced centralized image cache (preloading to avoid flickering) with a distributed one.
 - Added HTML minification

Impact so far:
 - Page size went from 499.2KB to 459.1KB (originally was 583.2KB)
 - Load time went from 1.25s to 1.23s (originally was 1.34s)

**Comment by gindik** [comment]
Caching is in place (for images)

**Comment by gindik** [comment]
<img width="975" alt="screen shot 2017-09-25 at 5 04 11 pm" src="https://user-images.githubusercontent.com/17207930/30831011-ef7741f4-a213-11e7-8e75-037e4f6a70fd.png">

**Comment by gindik** [comment]
The Google based benchmarks have also improve: mobile went from 59 to 69, and desktop went from 76 to 86. Some of the optimizations highlighted by the tool that we are not implementing include making the CSS load asynchronously. The issue with that approach is that we risk showing the UI with a broken layout just to then be fixed a second or so later. Given that the overall loading time is just over a second, it seems keeping the CSS loading synchronously would be preferable.

**Comment by gindik** [comment]
The performance achieved with the improvements described above ensures the site loads fast. @NottyCode was also looking into adding compression which should also help. There is always room to explore performance improvements but in principle this seems like a good start.
