### ISSUE TITLE
Downloads page: 'Eclipse developer tools' should probably be 'Open Liberty Tools'

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#20]
We say 'Open Liberty Tools' everywhere else and the description further down the page says that they're for Eclipse. Also, WDT is also tools for Eclipse so it using Open Liberty Tools would clarify that it's not WDT.

Two occurrences I think:

* The download button
* The heading further down the page

(Maybe needs confirmation with Megan? And I haven't checked further through the site for other occurrences.)

**Comment by lauracowen** [comment]
Having discussed with Jay and @yeekangc, we think About page looks fine. But on the ‘Contribute’ page, maybe the link should say “View the Open Liberty Tools repository”?

**Comment by ellenwyllie** [comment]
Are we still interested in changing this? This issue is well over a year old... @lauracowen @cajaygle

**Comment by lauracowen** [comment]
No. I'm fine with using 'Eclipse developer tools' instead of 'Open Liberty Tools' as long as that's consistent (which it seems to be throughout the site so far).
