### ISSUE TITLE
Sentence case table headers

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/openliberty.io#2045]
See Karen's first bullet in https://github.com/openliberty/docs/issues/1568#issuecomment-782922258. Right now, table headers default to all caps. Can we adjust this so that they can be sentence case?

**Comment by natalie-bernhard** [comment]
@Charlotte-Holt do you want the headers to be sentence case or show the text as it is written in the documentation? I can implement either.  It seems there are only a few cases where the headers in the documentation are not written in sentence case (instead they show up lowercase in the select cases I have found), so I wasn't sure if the headers were written that way on purpose or not and whether they should be kept that way.

**Comment by dmuelle** [comment]
@natalie-bernhard - I think this is fixed now. Looking at the tables across the docs (for example: https://www.openliberty.io/docs/21.0.0.6/logstash-events-list.html), I now see the headings in sentence case, as we were hoping for. The style here is what I would expect for all headings on the site as well. If you see any that are all lowercase thatr is most likely an error so please let me know! Thanks

**Comment by natalie-bernhard** [comment]
@dmuelle  Thank you for your response! The original issue was specifically in reference to the table headers, which are still in all caps (as seen in the screenshot below).  Please let me know if this should be changed or if I should close this issue.
<img width="808" alt="Screen Shot 2021-06-16 at 10 31 36 AM" src="https://user-images.githubusercontent.com/84740311/122238330-0afd9180-ce8e-11eb-99dc-aa11743d3c3d.png">

**Comment by dmuelle** [comment]
oops- sorry! I mis-remembered this as being about table titles, not headers. Yes please, the headers should be in sentence case.
