### ISSUE TITLE
literal formatting for table cells isn't applied correctly

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/openliberty.io#2065]
In asciidoc, you should be able to use the `l` attribute on a table row or cell to preserve line spacing in content, such as indentation in code examples. We recently discovered this option doesnt work on the OL site because although the antora framework seems to process the attributes, the OL site CSS allows the lines to break arbitrarily. Tried various workarounds, no luck.

Comments from @Azquelt via slack:

"I can see that when the `l` option is used, the text goes in a `<pre>` block and the CSS is setting
```
word-wrap: break-word
white-space: pre-wrap
```
and that combination appears to let it wrap text anywhere in the line and that lets the table shrink"

I don't have an example tom share at the moment because I removed the attribute from the table when it didn't render properly. I can restore it for demonstrations sake if needed. 

There are tables [here](https://www.openliberty.io/docs/21.0.0.3/external-configuration.html#_default_configuration_sources) and [here](https://www.openliberty.io/docs/21.0.0.3/reference/metrics-1-dif.html#fault) on the site that would benefit from being able to preserve proper spacing and indentation in code examples.

**Comment by mbroz2** [comment]
@dmuelle can you provide a screenshot of the bad behavior?

**Comment by steven1046** [comment]
We should look into if we can make that specific css more specific, or make it that antora's css overrides what we have for the site if that's the case.

**Comment by dmuelle** [comment]
for example, the following codeblock for the fault tolerance table:

```
base_ft_retry_calls_total{
    method="<name>",
    retried=["true"|"false"],
    retryResult=["valueReturned"
                |"exceptionNotRetryable"
                |"maxRetriesReached"
                |"maxDurationReached"]
}
```


renders like this in the table on the site:
<img width="391" alt="Screen Shot 2021-05-19 at 3 57 57 PM" src="https://user-images.githubusercontent.com/48686014/118876270-0e1b5700-b8bb-11eb-9593-cc424eeb328c.png">


more details in @Azquelt coment here: https://github.com/OpenLiberty/docs/issues/3440#issuecomment-780458030

The content he provided in that issue shows how the table would render if the `l` attribute was applied

**Comment by natalie-bernhard** [comment]
@dmuelle I should be able to modify the css to remove those rules from the table cells with the `l` attribute, but it would first have to be put back into the documentation/asciidocs so I can ensure that the CSS rules applied work correctly with the literal formatting.  Would you be able to add the `l` attribute back into the documentation, maybe on a draft or temporary branch?

**Comment by dmuelle** [comment]
Hi @natalie-bernhard - I've restored the literal formatting in this table on the draft site:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.7/reference/metrics-1-dif.html#fault

In this table the 1st, 2nd, 4th, and 5th columns apply the  literal formatting attribute `l`. You can see in the current draft that the lines break randomly in these columns. If we can get it to render properly  there is at least one other table that I need to add it to. But for now we can use this one as a test case on the draft site. Let me know if you need anything else- thanks!

**Comment by natalie-bernhard** [comment]
Great, thank you so much!

**Comment by natalie-bernhard** [comment]
@dmuelle The styling has been updated for tables using the literal tag, which can be seen on the draft site in the table you implemented the `l` attribute on.  Did you want to modify any more of the documentation before I move the change forward?

**Comment by dmuelle** [comment]
@natalie-bernhard looks great thanks so much! There is one other table I need to update. I'll make that change today and let you know when it's ready

**Comment by dmuelle** [comment]
@natalie-bernhard my edits are complete- thanks again for your help with this!

**Comment by natalie-bernhard** [comment]
@dmuelle this change has been released to prod so the docs that use literal formatting should now have the correct formatting
