### ISSUE TITLE
Firefox Guide CSS bug

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2072]
This happens on Firefox only for me at 133% Zoom. Browser dimensions 1440px by 664px.
![image](https://user-images.githubusercontent.com/6392944/113157510-93aa5100-9200-11eb-8f88-679ab104fefe.png)

**Comment by dmorgant** [comment]
This particular problem only occurs at a width of 1440.   At 1441 all is fine!   And I was able to recreate on Chrome as well as FF.
