### ISSUE TITLE
Safari has a lot of white space to the right of the screen on the home page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2119]
![image](https://user-images.githubusercontent.com/6392944/119879211-9a97cc00-bef0-11eb-9c36-9225efc3862e.png)

![image](https://user-images.githubusercontent.com/6392944/119879144-8358de80-bef0-11eb-8811-c3ba9c7dccfc.png)

The culprit is one of the clouds that extends the whole page and adds a lot of white space.

**Comment by natalie-bernhard** [comment]
Is this still an issue? I can't seem to reproduce this on my computer in Safari. I'm not sure if my monitors are too small to cause this issue (the max browser window size on one of my monitors is is 1920 x 890).

**Comment by steven1046** [comment]
I see the bug while on my mac and not doing anything special, but when i view it on monitors i don't see the bug.
