### ISSUE TITLE
Untranslated page banner

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2127]
Untranslated page banner
(considered a hard prereq as without UX would degrade significantly)
**Size: 1pw**

**Comment by kinueng** [comment]
Done, some examples
https://openliberty.io/ja/blog/


![Image](https://user-images.githubusercontent.com/31117513/214629140-b382a850-66a8-473a-9aa1-1b951cb3c697.png)


https://openliberty.io/zh-Hans/blog/


![Image](https://user-images.githubusercontent.com/31117513/214629103-dcdae058-0d01-4d38-86ba-28d4472c9aba.png)
