### ISSUE TITLE
Make Github logo on docs toolbar a clickable link to the docs repo main page

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2133]
I was thinking it may be useful to turn the github logo on the docs toolbar (circled below) into a link that goes to https://github.com/OpenLiberty/docs.  It would create a more general, direct link to the repo for someone who isn't necessarily interested in opening an issue or editing one of the docs.  I'm not sure if I'm the only one but a few times I've tried to click it before realizing it's just the logo.
<img width="262" alt="Screen Shot 2021-06-04 at 4 12 32 PM" src="https://user-images.githubusercontent.com/84740311/120858232-82f3bf80-c550-11eb-9434-a20fc67d1a67.png">

**Comment by k8vance88** [comment]
@mdenby thoughts on this?  On today's Thursday morning call the only concern with this was that you might accidentally click on the icon when trying to open an issue.  Would adding a separator bar help with that?

**Comment by mdenby** [comment]
Could we add a hover state in addition to a bar that shows where the link goes? For example:

<img width="217" alt="Screen Shot 2021-08-30 at 2 44 41 PM" src="https://user-images.githubusercontent.com/26823018/131388939-1d5b515c-ca60-4a77-a908-f4f7b81fde9a.png">

**Comment by k8vance88** [comment]
Closing this issue because you can get a link to the github docs from the overview page of the docs.
