### ISSUE TITLE
Blogs: text in bulleted lists is smaller than body text

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/openliberty.io#2166]
I only see this problem in the blogs. Text that is part of an unordered list (bullets) is several pts smaller than the rest of the body text on the page. This has the effect of making bulleted content less prominent and harder to scan. This does not happen with numbered lists, just bullets. Example from https://www.openliberty.io/blog/2021/06/04/database-ssl-primer.html

<img width="1235" alt="Screen Shot 2021-06-16 at 10 14 32 AM" src="https://user-images.githubusercontent.com/48686014/122235404-a93c2800-ce8b-11eb-961b-7d1eaa5be5bb.png">

**Comment by k8vance88** [comment]
The font sizes at the moment are 16px and 14px.  If I make them both 16px, I think it looks odd.  To me the bullets look larger even if they are the same size.

![image](https://user-images.githubusercontent.com/29546393/122270348-d4cb0c80-cea3-11eb-9a3b-ddd4f5b3f71e.png)

**Comment by dmuelle** [comment]
I see what you mean- though I still think it's an improvement. Could we cheat it back some so that it's 16px-15px? I know one px is hardly any difference but the bullets should stand out, particularly for readers who are scanning the text rather than reading through. As they are now, they almost seem de-emphasized, particularly on a small laptop screen.
