### ISSUE TITLE
New header redesign

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#218]
A new thin header should be applied to all of the static guides, interactive guides, javadocs, all guides view, and the docs page.

Example
![image](https://user-images.githubusercontent.com/31117513/37720329-105276de-2cf5-11e8-8715-fd7d31c9c52f.png)

**Comment by steven1046** [comment]
The new header redesisn has been delivered as part of the new MicroProfile 1.3 delivery, was this issue meant for something else or can we close it?

**Comment by kinueng** [comment]
@steven1046 is it true that we want the thin header for all doc pages?  This includes the `Docs & Guides`, `Guides`, `JavaDoc`, and single guide view?

**Comment by steven1046** [comment]
@kinueng The doc header is currently in the redlines for all of those pages mentioned, but we are waiting to see if we want that "microsite" feel.

**Comment by kinueng** [comment]
Let's use this issue to track if we want to deliver the new header to al of the doc pages.
