### ISSUE TITLE
Switch java download in guides prereq to use semeru site

### ISSUE THREAD

**Issue by k8vance88** [OpenLiberty/openliberty.io#2234]
adoptopenjdk is moving to https://developer.ibm.com/languages/java/semeru-runtimes/downloads

**Comment by steven1046** [comment]
This is the guides prereqs at the top right

**Comment by mbroz2** [comment]
Update the [java link in guides prereq](https://github.com/OpenLiberty/guides-common/blob/32d66ee7e8021df359f6611ce5f77b62b1f1548a/guide_prereqs.json#L5) to point at [Semeru downloads](https://developer.ibm.com/languages/java/semeru-runtimes/downloads)

**Comment by mbroz2** [comment]
Issue moved to [OpenLiberty/guides-common #703](https://github.com/OpenLiberty/guides-common/issues/703) via [**ZenHub**](https://www.zenhub.com/)
