### ISSUE TITLE
starter configuration API broken

### ISSUE THREAD

**Issue by FrankGrimm** [OpenLiberty/openliberty.io#2240]
The starter configurator on [openliberty.io/downloads/](https://openliberty.io/downloads/) seems broken at the moment. It cannot download [the API endpoint](https://start.openliberty.io/api/start/info), the client-side error message is CORS related but the endpoint itself shows that the SSL certificate for start.openliberty.io itself is simply invalid so cloudflare won't forward requests.

Tested in current Firefox and Chrome on Linux.

**Comment by mbroz2** [comment]
Hi Frank, we're unable to reproduce this.  Could you try this again and let us know if it's still an issue, and whether this was intermittent or consistently failing? If still an issue, can provide us with the CORS/cert info error that you're seeing.

**Comment by FrankGrimm** [comment]
Hi, thanks for the response. Just tested it again in Firefox and the API endpoint seems to be fixed at this time, closing the issue.
