### ISSUE TITLE
Add a 'Next steps' or 'What's next' section after generate project in the starter

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2261]
Continues on #2260

After the user clicks "Generate Project' on the starter, display a small section after the button that tells the user what to do next depending on what they selected in the starter.  For example:
unzip
run [mvnw/gradlew command, depending on what was chosen in starter]
link to guides

**Comment by steven1046** [comment]
Is a design needed?

**Comment by k8vance88** [comment]
@mdenby can you take a look at this?

**Comment by mdenby** [comment]
Yes, my first thought is a modal...I'll bring this up in the Thursday meeting tomorrow. I just tried it on the site and I remember this--you get a zip file and no 'success' message or instructions (or link to a guide). 

'Your zip file has been beamed to your computer! Unzip it and follow the README instructions or run this command. For more help visit our helpful guides. Button--Guides. Button--Got it! or just the X to close in the top corner.'

Happy to mock this up too.

**Comment by mdenby** [comment]
Here is what the modal could look like. @lauracowen I'm sure the wording could be much better!

<img width="921" alt="Screen Shot 2021-10-14 at 1 07 15 PM" src="https://user-images.githubusercontent.com/26823018/137368424-d3106be5-2395-4baa-9c47-3756b0a21243.png">

**Comment by mbroz2** [comment]
We'll also want to add the actual command to run, and then reference the README.md for more information.

**Comment by steven1046** [comment]
Should we link to the blog post (https://openliberty.io/blog/2021/08/20/open-liberty-starter.html) in the modal as well?
