### ISSUE TITLE
Enable no_copy ([source, role="no_copy"]) in all code blocks on the website

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2263]
This is currently only applied to guides, and we should make it available site-wide.

**Comment by kinueng** [comment]
@steven1046 
May I have more details on what the end goal is for this issue?  I found code blocks outside of the guide pages that have the "copy to clipboard" functionality.  What are the criteria for when code blocks should/shouldn't have `no_copy`?

At the moment, the issue looks like a request to move the logic from https://github.com/OpenLiberty/openliberty.io/blob/75de7861e3dba87a12fe9c93323a18e0da6ec2d0/src/main/content/_assets/js/guide-static.js#L158-L160 to a `.js` file that is used on all the website pages (i.e. a top level Jekyll layout).

**Comment by steven1046** [comment]
We want any code block that is shown on the website to not be  copyable if the asciidoc author adds the class `no_copy` to their code block. Right now, i think the copy to clipboard icon shows up for all of the code blocks.

**Comment by steven1046** [comment]
It is a request to move the logic from just the guides javascript to site-wide such as openliberty.js.

**Comment by steven1046** [comment]
The docs have their own css/js so we'll need to make sure they get the logic too
