### ISSUE TITLE
[Safari] Switching OS tabs on a guide can jump the guide a lot

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2270]
Investigate what we can do to improve the guide not jumping around. Switching OS tabs updates *all* of the os content on the guide, and it shouldn't jump the page a lot.

**Comment by steven1046** [comment]
https://openliberty.io/guides/kubernetes-microprofile-config.html#tearing-down-the-environment on Safari at the last guide step has a couple of bugs when switching around OS tabs.

**Comment by kinueng** [comment]
Problem still exists for Safari on macOS 12.6
