### ISSUE TITLE
Expose "Run in cloud" tag

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2271]
We have previously created the 'Run in cloud' tag to expose guides with the 'Run in cloud' functionality:
https://openliberty.io/guides/?search=run%20in%20cloud&key=tag or accessed via the shortlink ibm.biz/HostedLibertyGuides

We're now going to move forward and make this tag visible, with the following:

1. No aliases added for the tag (we can always add them later if we feel the need to do so)
2. The tag "Run in cloud" will be made visible
3. The tag "Run in cloud" will become a suggested tag on /guides (after 'Jakarta EE' and before 'Interactive')
4. We will add a badge to the guide cards on /guides for "Run in cloud" similar to the existing "New" and "Interactive" badges

For 4, we're just going to use the existing styling we have for badges (orange pill).  We can open up a new issue (and reach out to design) if we want a different badge, like a blue cloud instead of a pill.

**Comment by steven1046** [comment]
long term we want to put suggested tags in the json, but for now we will add it in html/js
