### ISSUE TITLE
Support cloud-hosted guides to use SkillNetwork courses

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#2272]
Skill Network deprecated the way what we did to create cloud-hosted. The old way calls **guided-project**. The new way calls **course**. We need to migrate our cloud-hosted guides to courses, and change the url to launch the SN lab. So, we need to update the cloud-hosted-guides.json, and the ol.io sites need to support. I suggest adding the following data. so that the sites can support both.
```
   "skillNetworkDomain": "https://openliberty.skillsnetwork.site",
   "stagingSkillNetworkDomain": "https://ol-staging.skillsnetwork.site",
   "courses" : {
     "kubernetes-intro"               : "url1...",
     "kubernetes-microprofile-health" : "url2...",
     "kubernetes-microprofile-config" : "url3...",
     "microprofile-health"            : "url4...",
     "microprofile-config"            : "url5..."
   }
 ```

If it is the draft ol.io site and the guide in the “courses”, e.g. kubernetes-intro, its cloud-hosted url will be `<stagingSkillNetworkDomain>/<courses.kubernetes-intro>` -> `https://ol-staging.skillsnetwork.site/url1… `. 

If it is the production site, the cloud-hosted url will be `<skillNetworkDomain>/<courses.kubernetes-intro>` -> `https://openliberty.skillsnetwork.site/url1…` .

If the guide is not in the “courses”, do the existing way to construct the url by using `stagingSkillNetworkUrl` or `skillNetworkUrl` .

**Comment by gkwan-ibm** [comment]
An alternative is different site uses the cloud-hosted-guides.json under its corresponding branch. Then the cloud-hosted-guides.json in dev branch for the draft site will be:

```
   "courses" : {
     "kubernetes-intro"               : "https://ol-staging.skillsnetwork.site/url1...",
     "kubernetes-microprofile-health" : "https://ol-staging.skillsnetwork.site/url2...",
     "kubernetes-microprofile-config" : "https://ol-staging.skillsnetwork.site/url3...",
     "microprofile-health"            : "https://ol-staging.skillsnetwork.site/url4...",
     "microprofile-config"            : "https://ol-staging.skillsnetwork.site/url5..."
   }
```

The cloud-hosted-guides.json in prod  branch for the production site will be:
```
   "courses" : {
     "kubernetes-intro"               : "https://openliberty.skillsnetwork.site/url1...",
     "kubernetes-microprofile-health" : "https://openliberty.skillsnetwork.site/url2...",
     "kubernetes-microprofile-config" : "https://openliberty.skillsnetwork.site/url3...",
     "microprofile-health"            : "https://openliberty.skillsnetwork.site/url4...",
     "microprofile-config"            : "https://openliberty.skillsnetwork.site/url5..."
   }
```

**Comment by steven1046** [comment]
Since we already have code that determines whether to use the real skills network site vs. the staging, I would say the first method is better and shouldn't take too long to implement. And if different branches of guides-common have different content, it would be harder to merge other changes in to that repo.

**Comment by steven1046** [comment]
@gkwan-ibm the first has been implemented on draft.

**Comment by steven1046** [comment]
this has been completed

**Comment by gkwan-ibm** [comment]
closed
- this is on live now
