### ISSUE TITLE
Javadoc TOC links are broken when navigating from another javadoc package/class

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2283]
If you go to https://openliberty.io/docs/21.0.0.9/reference/javadoc/microprofile-4.0-javadoc.html and click on the javax.annotation package and then try to navigate to the MicroProfile 3.3 javadoc in the left-most TOC then the URL is not correct.

**Comment by mbroz2** [comment]
Seems like we have different redirect behavior for MP javadocs (which breaks us) and Java EE javadocs (which redirect to 'latest') and Jakarta EE javadocs (which don't do any redirecting).  We should have consistent behavior if possible.

**Comment by kinueng** [comment]
Closed as fixed and in production
