### ISSUE TITLE
Add support for "UPDATED" label/badge in guides

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2286]
In the guide README.adoc read-in a new attribute ":page-majorupdateddate: 2021-10-10" 
Based of of the date from the attribute compute whether an "UPDATED" label/badge should be added to guide (similar to NEW label/badge).  The rule will be to add "UPDATED" to any guide with a date that occurs in the last 12 weeks.

Guides that received the UPDATED label should be externally socialized (twitter, linkedin, etc) and any UPDATED guides in the last release should be include in a new section in the release blog post.   Once this is complete, we can move forward with https://github.com/OpenLiberty/blogs/issues/1748

**Comment by steven1046** [comment]
The multimodules guide will have this property first and will be updated next week.

**Comment by steven1046** [comment]
The attribute is available at https://raw.githubusercontent.com/OpenLiberty/guide-maven-multimodules/prod/README.adoc now
