### ISSUE TITLE
How to show EE8 features alongside EE9 features

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2287]
Today, the openliberty.io/docs groups feature versions by name, for example https://openliberty.io/docs/21.0.0.9/reference/feature/jaxrs-2.1.html

Some Jakarta EE9 features are named differently then Jakarta EE8 features.  How do we display those new features?

~~1. Continue to do what we're doing - this would cause a bunch of new features to appear and it would not be clear to the user how they correlate to the previous version of the feature, especially since features are in alphabetical order
2. Keep the ToC as is today (using EE8 feature names), and add the Jakarta EE9 feature version to the list.  When clicked, the doc name/title would change to reflect the name for that version (ToC would remain on the old name)~~
**3. Use Jakarta EE9 naming for the features in the ToC.  When an older version of a feature is picked, the doc name/title changes to the EE8/EE7 name (ToC remains on Jakarta EE9).**

Related question: for features whos name did not change but have a new version to support the Jakarta EE9 namespace, how do we make it clear to users that the namespace has changed to jakarta?

**Comment by mbroz2** [comment]
@kwsutter @jhanders34 thoughts?

**Comment by NottyCode** [comment]
Another option would be to inject Java EE versions into the TOC, so it would be something like this:

```
Java EE 7
  - servlet-3.1
Java EE 8
  - servlet-4.0
Java EE 9
   - servlet-5.0
```

My only concern with this is I like how easy it is to switch versions and I'm not sure that would still be possible

**Comment by kwsutter** [comment]
I like option 3 and use the Jakarta names in the TOC on the left, with the exception of the Platform and Web Profiles.  In that case, I would list both Java EE and Jakarta EE Platform and Web Profiles.  This would allow us to show the javaee7, javaee8, jakartaee8, jakartaee9, etc names along with their content (when you click on one).  And, then just get everyone used to the "Jakarta" names for all of the other features.  If we don't have it already, we should mention this general name change "Java EE " -> "Jakarta EE" in an opening section.

**Comment by mbroz2** [comment]
After further discussion, a merge of Alasdair's option 4 with option 3 was also considered.  In other words, having the Java/Jakarta EE versions in the ToC, but have the feature page still list all versions, like we do today.  For example (where each version number remains a link to the appropriate feature-version): 

- Java EE 7
    - Java Servlets &nbsp; &nbsp; &nbsp; &nbsp;(Java Servlets   &nbsp;5.0 &nbsp; 4.0 &nbsp;  **3.1**)
- Java EE 8
   - Java Servlets &nbsp; &nbsp; &nbsp;&nbsp;(Java Servlets  &nbsp; 5.0 &nbsp; **4.0** &nbsp;  3.1)
- Java EE 9
   - Jakarta Servlets &nbsp; (Jakarta Servlets  &nbsp; **5.0** &nbsp;  4.0&nbsp;   3.1)


This (and any approach that does grouping of features) leads to the following questions:
1. Is this only meant to include the features that are part of the spec, and not all features compatible with a particular EE version?
2. If we're doing this for EE, should we then also do this for MP?

**Comment by steven1046** [comment]
Go with option 3 for now

**Comment by mbroz2** [comment]
For 21.0.0.12, we'll hardcode a map of EE8->EE9 feature names based on the following mapping:

```
ejb -> enterpriseBeans
 ejbHome -> enterpriseBeansHome
 ejbLite -> enterpriseBeansLite
 ejbPersistentTimer -> enterpriseBeansPersistentTimer
 ejbRemote -> enterpriseBeansRemote
 el -> expressionLanguage
 jacc -> appAuthorization
 javaee -> jakartaee
 javaeeClient -> jakartaeeClient
 jaspic -> appAuthentication
 javaMail -> mail
 jaxb -> xmlBinding
 jaxrs -> restfulWS
 jaxrsClient -> restfulWSClient
 jaxws -> xmlWS
 jca -> connectors
 jcaInboundSecurity -> connectorsInboundSecurity
 jms -> messaging
 jpa -> persistence
 jpaContainer -> persistenceContainer
 jsf -> faces
 jsfContainer -> facesContainer
 jsp -> pages
 wasJmsClient -> messagingClient
 wasJmsSecurity -> messagingSecurity
 wasJmsServer -> messagingServer
```

Note webProfile-9.1 needs special attention to make sure its versions are properly ordered as its version (8->9.1) and name (Java EE Web Profile->Jakarta EE Web Profile) changed, but the shortname remained `webProfile`
And similarly for Managed Beans, WebSocket, and Servlet
In other words, for instances where a feature shortname has remained the same between 8 and 9.1 (like `webProfile` and `managedBeans`), we need to make sure that the ToC uses the Jakarta name in the Toc, and that the version order is correct (and as outlined previously in this issue, if a user clicks on a previous EE8 version, the name on the feature page properly reflects that.)

**Comment by dmuelle** [comment]
is it possible to make the new Jakarta features pull in the config examples from the corresponding Java feature pages? Or do those example files need to be duplicated for any renamed features?

**Comment by mbroz2** [comment]
> is it possible to make the new Jakarta features pull in the config examples from the corresponding Java feature pages? Or do those example files need to be duplicated for any renamed features?

I don't think that would be appropriate.  These aren't just feature renames; the package namespace was changed as well for all the features (along with some other minor changes in certain features).
Instead, someone should go through all the included files to make sure that their content is appropriate to be linked to from the Jakarta EE 9.1 feature as is, or if an update needs to be named because it either references the old name, or the old namespace.
For example, https://github.com/OpenLiberty/docs/blob/vNext/modules/reference/pages/feature/javaMail/examples.adoc references `javax.mail.Session` which I'm guessing is not correct for the mail feature in Jakarta EE 9.1.
Another example is https://github.com/OpenLiberty/docs/blob/vNext/modules/reference/pages/feature/jaxrs/examples.adoc which references `JAX-RS` which would need to be updated.

I'd suggest reaching out and working with @jhanders34 to see which of the [feature includes](https://github.com/OpenLiberty/docs/tree/vNext/modules/reference/pages/feature) can be kept as-is, and which ones need to be updated.

**Comment by dmuelle** [comment]
ok, created https://github.com/OpenLiberty/docs/issues/4980 to track the necessary doc updates
