### ISSUE TITLE
Catch SRVE0190E 500 Error and redirect to 404 page

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2299]
Since gzip was added, if a file is requested that doesn't exist the server returns:

`Error 500: javax.servlet.ServletException: com.ibm.ws.webcontainer.exception.IncludeFileNotFoundException: SRVE0190E: File not found: /docs/21.0.0.10/reference/config/server-configuration-overview.html.gz`

It should instead redirect to our 404 page

**Comment by mbroz2** [comment]
From #2517 

> It should look like this: https://openliberty.io/404, or we could at least customize the 404 page in this case to point to something more useful, maybe redirect to the latest docs?

**Comment by kinueng** [comment]
done
