### ISSUE TITLE
Support signed zips on download site

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/openliberty.io#2305]
Open Liberty Released package zips will now also have a separate signed *.sig file that can also be downloaded to verify with IBM's provided public key (WebSphereLiberty.pem)

I envision a new column with links to the *.sig files for each package, and a url link to a doc page(maybe in page footer erea) explaining how to verify packages, and also where to download the public key.

**Comment by cbridgha** [comment]
FYI - We are targeting this to be complete for 21.0.0.12 eGA release.

**Comment by cbridgha** [comment]
Edit 22.0.0.1 release....    Has this been sized/assigned?

**Comment by mbroz2** [comment]
It's prioritized in the backlog; once the items before it are complete, work on this will begin (targeted for delivery by 22.0.0.1 GA)

**Comment by mbroz2** [comment]
When implementing this, note that we'll also want to add support for Checksums in the future as defined in #1734

**Comment by cbridgha** [comment]
Adding the link to the OL doc (this should be linked from downloads page regarding the signatures and verifying them). https://github.com/OpenLiberty/docs/issues/4842

**Comment by mbroz2** [comment]
Note that the signature file will be in the same directory as the archives, and its name will be the name of the archive with `.sig` appended to it.
For example, the following archive:
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2021-11-17_1256/openliberty-javaee8-21.0.0.12.zip
if it had a signature it would be:
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2021-11-17_1256/openliberty-javaee8-21.0.0.12.zip.sig

Yes, both extensions (.zip.sig) are present in the file name.

**Comment by mbroz2** [comment]
info.json for 22.0.0.1 and beyond will be updated to also include the following fields:
`driver_signature_location` - the location of the sig for the driver (should be 1:1 mapping to the `driver_location`)
`package_signature_locations` - an array of signatures for the other packages (should be n:n mapping to the `package_locations`

An example json would therefore look like:
```
{
    "test_passed": "15171",
    "total_tests": "15171",
    "tests_log": "open-liberty.unitTest.results.zip",
    "build_log": "gradle.log",
    "driver_location": "openliberty-21.0.0.12.zip",
    "driver_signature_location": "openliberty-21.0.0.12.zip.sig",
    "package_locations": ["openliberty-javaee8-21.0.0.12.zip","openliberty-jakartaee9-21.0.0.12.zip","openliberty-webProfile8-21.0.0.12.zip","openliberty-webProfile9-21.0.0.12.zip","openliberty-microProfile4-21.0.0.12.zip","openliberty-kernel-21.0.0.12.zip"],
    "package_signature_locations": ["openliberty-javaee8-21.0.0.12.zip.sig", "openliberty-jakartaee9-21.0.0.12.zip.sig","openliberty-webProfile8-21.0.0.12.zip.sig","openliberty-webProfile9-21.0.0.12.zip.sig","openliberty-microProfile4-21.0.0.12.zip.sig","openliberty-kernel-21.0.0.12.zip.sig"],
    "version": "21.0.0.12"
}
```

We can have logic that checks that the length of `package_locations` and `package_signature_locations` is the same, and if so, just goes through each item in package locations and makes sure that the nth item in `package_signature_locations` is equal to the nth item in `package_locations` with `.sig` appended to it.
In the event the above is not true, then we fallback to a more expensive (but realistically still extremely cheap given how few and short these arrays are) flow where for each item in `package_locations` we search through `package_signature_locations` for a matching signature.

**Comment by kinueng** [comment]
I have finished and tested the code changes that are based on the new `info.json` from  https://github.com/OpenLiberty/openliberty.io/issues/2305#issuecomment-996888694.

FYI @cbridgha if you see that the proposed changes to `info.json` in https://github.com/OpenLiberty/openliberty.io/issues/2305#issuecomment-996888694 are not feasible, please let me know so I can change my code.

For now, I think it is best I keep the code in a branch and merge once we get closer to having `.sig` files in DHE.

Code changes can be found in branch https://github.com/OpenLiberty/openliberty.io/tree/2305-zip-sigs

**Comment by kinueng** [comment]
The new code to expose the signature files are now live on https://ui-draft-openlibertyio.mybluemix.net/start/
