### ISSUE TITLE
Code block does not show the file content consistently

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#2307]
In single pane or mobile view, clicking on the code block to show the file content doesn't work consistently or didn't work after first use

- visit https://openliberty.io/guides/docker.html
- reduce the browser size to show single pane 
- scroll down to https://openliberty.io/guides/docker.html#getting-started
- click the green box 
![Screen Shot 2021-10-14 at 4 56 25 PM](https://user-images.githubusercontent.com/29576299/137394243-6f2bb57e-3fb6-4ad5-b310-4f89f141c771.png)
- code text pane show up as 
![Screen Shot 2021-10-14 at 4 57 13 PM](https://user-images.githubusercontent.com/29576299/137394343-9895a55e-43d0-4edb-be87-ba0732bdb6b7.png)
- click "Back to text"
- click the green box again
- a flash happens and code text pane does not show up
- the content cannot be scrolled anymore
- after resize the window a little, the text pane shows up again

**Comment by steven1046** [comment]
It looks to be intermittent, and if you wait long enough before clicking the hotspot again it seems to work. It's probably a timing condition in the code to dismiss the code panel and waiting on the page to adjust.

**Comment by steven1046** [comment]
It seems as though when the hotspot is near the top of the table of contents overlay when you dismiss it, is when you're not able to click the hotspot again so maybe something is blocking the click.
