### ISSUE TITLE
Download links for 21.0.0.11 are broken on the https://openliberty.io/start/ page

### ISSUE THREAD

**Issue by dmytro-bilokha** [OpenLiberty/openliberty.io#2335]
If you go to the page https://openliberty.io/start/ and click a link to download ZIP for 21.0.0.11 instead of getting download started you get `404 The requested URL was not found on this server.` I've checked following links and niether of them works:

https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2021-10-19_1900/openliberty-21.0.0.11.zip
https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2021-10-19_1900/openliberty-microProfile4-21.0.0.11.zip

Links for 21.0.0.10 seem to work fine.

**Comment by steven1046** [comment]
Hi @dmytro-bilokha,

I tested accessing the build results from the UK, Germany, and the US and I was able to download the builds from each. Could you please try once more and see if it is still an issue for you? Thanks!

**Comment by dmytro-bilokha** [comment]
Now it works perfectly. I am accessing from the Netherlands, it could be some temporary CDN glitch or something else. Anyway, I'm able to download now. Thank you very much!
