### ISSUE TITLE
Investigate moving off of Cloud Foundry for site deployments.

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2340]
Consider alternatives like: ICCE, IKS, ROKS

**Comment by mbroz2** [comment]
Change the build architecture while we're at it:
Product Containerized images of openliberty.io and start.openliberty.io
Don't rebuild things that haven't changed
Move to Tekton for builds
COS Bucket for storing previous builds, or perhaps GitHub releases.

**Comment by kinueng** [comment]
This is now done. The chosen destination was IBM Code Engine.
