### ISSUE TITLE
kernel-slim-java17-openj9-ubi: not found

### ISSUE THREAD

**Issue by bcoveny** [OpenLiberty/openliberty.io#2351]
When creating a starter app @ https://openliberty.io/start/ when you select Java SE Version 17, JAVA EE/JakartaEE Version 8 and MicroProfile 4.1 the Dockerfile created will not build due to missing image.

Create Starter application
![image](https://user-images.githubusercontent.com/8987322/141848199-7212d482-73e6-4ba4-852b-93af2296bdf2.png)

Dockerfile
```
FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi

COPY --chown=1001:0 /src/main/liberty/config /config

RUN features.sh

COPY --chown=1001:0 target/*.war /config/apps

RUN configure.sh
```

Powershell 
```
docker build --no-cache --progress=plain `
    --tag my-liberty `
    .
```

Failure
```
#1 [internal] load build definition from Dockerfile
#1 sha256:d710ef143573cbcaf6f6987289ae75cc3098fe4dcdfac574c98eccc3a0a14289
#1 transferring dockerfile: 32B done
#1 DONE 0.6s

#2 [internal] load .dockerignore
#2 sha256:6ba3eece23ba1c0d0f9e1382a8c22ad5cb1ba9b862a1fd6280ed7a607606dd1b
#2 transferring context: 34B done
#2 DONE 1.0s

#3 [internal] load metadata for icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi
#3 sha256:2f08f8036c258e02d365782dac21a5711e017647b6c047fca5f51b0b7133a999
#3 ERROR: icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi: not found
------
 > [internal] load metadata for icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi: not found
```

**Comment by mbroz2** [comment]
Currently, there is no java17-openj9-ubi image.  Until one is made available, one option would be to remove the dockerfile from the Java 17 starter.

**Comment by steven1046** [comment]
Issue moved to [OpenLiberty/start.openliberty.io #29](https://github.com/OpenLiberty/start.openliberty.io/issues/29) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kinueng** [comment]
Hello @bcoveny , I wanted to follow up on this issue.  The `kernel-slim-java17-openj9-ubi` is now available.  

I confirmed by doing the following command:
`docker pull icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi`
