### ISSUE TITLE
[Safari] Delay when code block shifts to top of screen after resize

### ISSUE THREAD

**Issue by erica-banda-03** [OpenLiberty/openliberty.io#2356]
This issue is specific to Safari and it only happens when you resize your browser from single pane view to multi-pane view. After the resize to multi-pane, the code block looks like it shifts from about 150px down the page to the very top of the browser window. The delay in the shift is about 0.5 second and it's noticeable on my machine. 

_Image after resize and right before code block shifts to top:_
![image](https://user-images.githubusercontent.com/6720263/142076264-499e2838-599e-4c50-afcb-dc727beab006.png)

**Steps to recreate:** _(use the draft site)_
1. Go to the **Guides** page 
2. Select any guide with a code block (ex: https://draft-openlibertyio.mybluemix.net/guides/docker.html)
3. Resize your browser to single pane view 
4. Click a code hotspot and the code block should show up below the hotspot 
5. Resize your window to full screen
6. Notice how the code block shifts to the top of the browser window slowly

**Comment by kinueng** [comment]
Was not reproducible on two different macOS using Safari. Closing this issue.
