### ISSUE TITLE
Guide tags get shown whether "visible" is set to true OR false.

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2361]
See https://github.com/OpenLiberty/guides-common/blob/prod/guide_tags.json. Setting the run in cloud tag to visible is new for guides. We had to remove it for a couple of days, and reverting the ui code did that. When re-delivering the ui code to make it visible, it reappeared. The guide_tags.json was still set to visible: false though, so we should actually honor that boolean to show or hide the tag on the guide cards. Right now, it is showing the tag even if `visible` is an attribute of a tag, whether it is false or true.

**Comment by Sreejith-Websphere** [comment]
Fixed
