### ISSUE TITLE
Regenerate the javadoc using latest javadoc

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2362]
Our current javadoc was generated using Java SE 8/11.  Look into regenerating them using latest Java SE version to pick up latest versions of dependencies (like jQuery) as well as various fixes (like a11y).

**Comment by steven1046** [comment]
Support for frames was removed in Java SE 13 (https://bugs.openjdk.org/browse/JDK-8215599), so we might need to investigate if we're going to remove iframes from the javadocs on the site.

**Comment by kinueng** [comment]
@steven1046 thank you for bringing attention to the removal of framed javadocs. We certainly will need to think about what we will do long term.

In the past, I used JDK 11 to genereate the MicroProfile 5.0 javadocs in framed mode. Let's take a look at the MP5 javadocs and see how different its third party dependencies (e.g. jquery) are to some of the older javadocs on the website to get a sense of what we would be gaining from regenerating the old javadocs.

FYI @hlhoots about the removal of "framed" javadocs in JDK 13 and later for issue #1550

**Comment by SteveSamJacob19** [comment]
@mbroz2 @steven1046 @kinueng The newly created frameless javadocs are generated using JDK 17, is this issue still relevant or can i close it once the frameless javadocs are published into production site

**Comment by mbroz2** [comment]
closing it
