### ISSUE TITLE
Change latest doc version in URL from numerical to 'latest'

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2363]
Currently, we redirect /latest/ to the latest numerical version (like 21.0.0.12).  Instead, do the opposite where the latest version is always under the /latest/ URL and the latest numerical version (like 21.0.0.12) redirects to /latest/ for as long as it's the newest version.

The reason for this change is to help prevent search engines from incorrectly pointing at older versions of the docs (even though we already set the canonical to the latest version).

I expect this would half code change and half documentation/process change.

**Comment by steven1046** [comment]
This would require changing the docs repo `branch` to be `latest`, instead of the numerical `22.0.0.1` for example.

**Comment by steven1046** [comment]
and in the playbook, we would pull in `latest`

**Comment by steven1046** [comment]
We want to:
1. Change the playbook from 22.0.0.1 to latest
2. Create a docs repo (https://github.com/OpenLiberty/docs) branch called latest that is basically a copy of 22.0.0.1
3. Create a docs-generated (https://github.com/OpenLiberty/docs-generated) branch called latest that is basically a copy of 22.0.0.1
4. Update the instructions of the README to tell them to continue using latest, but to merge whatever is in vNext into latest during each doc release on the website.

The docs team will continue delivering new doc changes into `vNext` and during the release, they will create another doc version for the previous version:
So if doing the 22.0.0.2 doc release:

In the staging playbook:
1. Create a `22.0.0.1` branch off of the `latest` branch in both docs repo and docs-generated repo.
2. Add `22.0.0.1` to the docs-playbook for both docs repo and docs-generated.
2. Merge `vNext` into `latest` for both of these repos.
3. Test on staging website.
4. If all is good, then merge the staging playbook into prod playbook.

Now 22.0.0.2 will actually be latest on the website after these changes.

**Comment by steven1046** [comment]
We'll want to remove the latest redirect in the https://github.com/OpenLiberty/docs-playbook/blob/prod/doc-redirects.properties

**Comment by kinueng** [comment]
The code has been merged into all the branches.  The last piece of work is to update the READMEs to remove any steps that are no longer needed now that `latest` can be hardcoded in various files.
