### ISSUE TITLE
Allowlist approach for displaying zips from DHE on /start

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2377]
Our code that grabs the zips from DHE to display on /start is too greedy.  It should instead only expose the archives that we expect and not everything that it finds in the folder.

For example, today, we show the MP5 beta (https://openliberty.io/start/#runtime_betas) in the betas tab, but call it 'All Beta Features'.  Instead, we should have had only a single entry for All Beta Features pointing at https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/beta/2021-11-17_1256/openliberty-22.0.0.1-beta.zip and ignored the unexpected MP5 beta.

**Comment by kinueng** [comment]
Closed as fixed
https://openliberty.io/start/#runtime_betas
![image](https://user-images.githubusercontent.com/31117513/145278228-1eb85ce1-71b6-4bec-9d35-04a7dff2d2a6.png)

**Comment by kinueng** [comment]
We need a cleaner fix that applies to all of the tabs.  Reopening to attach more PRs to this issue

**Comment by kinueng** [comment]
There are some conversations within PR #2406 that may interest anyone looking for history on the v1.0 allowed list logic implementation
