### ISSUE TITLE
Row highlighting on /start is wrong

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2378]
See: https://openliberty.io/start/
![image](https://user-images.githubusercontent.com/6392944/144087833-cdbeeb17-df30-47b3-94fb-66064c291651.png)

Each release should have a different background color and alternating.

**Comment by mbroz2** [comment]
Should look like it use to:
![image](https://user-images.githubusercontent.com/3076261/144088592-0b02d955-ee1c-4756-ac73-5490b2bebf9e.png)

**Comment by kinueng** [comment]
Fixed in production, https://openliberty.io/start/
![openliberty io_start_](https://user-images.githubusercontent.com/31117513/145597315-16a83d54-d03e-4cba-92c1-909192cfb60c.png)
