### ISSUE TITLE
Remove guide labels from /guides cards and suggested filters when the tag is set to visible: false

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2393]
See https://github.com/OpenLiberty/guides-common/blob/prod/guide_tags.json. Setting the run in cloud tag to visible is new for guides. We had to remove it for a couple of days, and reverting the ui code did that. When re-delivering the ui code to make it visible, it reappeared. The guide_tags.json was still set to visible: false though, so we should actually honor that boolean to show or hide the tag on the guide cards. Right now, it is showing the tag even if visible is an attribute of a tag, whether it is false or true.

https://github.com/OpenLiberty/openliberty.io/issues/2361 will be delivered just to remove the tag from the actual guide page itself.

This issue is to resolve:
1) Removing the visible: false guide tags from the cards
2) Remove the suggested search terms when the guide tag is set to visible: false

**Comment by Sreejith-Websphere** [comment]
Done
