### ISSUE TITLE
Should the H2 headings be easier to spot when skimming down a blog post?

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#240]
Looking at our recent blog post announcing 18.0.0.1 (https://openliberty.io/news/2018/03/16/distributed-tracing-microservices-18001.html), it occurred to me that the headings maybe aren't that easy to spot when skimming down the page. As it happens, there are links to each in this blog post but if you just scroll down the page it's not so easy to spot when a new section starts. I think it's a combination of there not being that much extra space before the heading (compared to a normal paragraph), and the eye-catching link colours and syntax highlighting which seem to stand out more.

I don't really have a good suggestion (or spent much time thinking about this - and others may feel it's not really a problem, which is fine) but wanted to see what Design think.

**Comment by steven1046** [comment]
I agree, I mostly noticed the orange and green text and didn't see the titles because they were the same color as the text in paragraphs.

**Comment by cajaygle** [comment]
@megmulsy please take a look and comment

**Comment by megmulsy** [comment]
Thanks for raising this issue - now that we've been approved to use Bunuelo in the text of the website itself, I will update this page with the new font pattern/structure. This will make the flow of content more natural - I will specifically focus on making the h2 headings/new sections more clear to readers.

**Comment by TreeHanh** [comment]
We've addressed the H2 headings in the new design for blog posts. 

New design can be seen here: https://github.com/OpenLiberty/openliberty.io/issues/458#issuecomment-463308797
