### ISSUE TITLE
Handle blog posts with no author/co-author Github ID

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2400]
If an author has no Git id, we should not link to anything from their picture or name on the /blogs page and in the actual blog. Default to showing https://avatars3.githubusercontent.com/u/28316667 as a stock photo if there is no author or co-author image added:
![image](https://user-images.githubusercontent.com/6392944/145249624-b88c8c3e-8efe-464c-9268-89a94bef0de2.png)

**Comment by kinueng** [comment]
The work to make the name unclickable when there is no github ID is in production. However, we do not have the logic to force the image to be the UFO if the image link is missing for the author.
