### ISSUE TITLE
HTTP 404 links on Nightly Builds

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2412]
# Problem
There are nightly builds shown on openliberty.io that no longer exist on DHE.  These builds have 404 links.

![image](https://user-images.githubusercontent.com/31117513/146064237-9124ea17-d125-4ad8-b7fd-57917e22f648.png)
![image](https://user-images.githubusercontent.com/31117513/146064301-c447c747-8399-4f28-a509-f0ebb9aa0be4.png)

# Endpoint
https://openliberty.io/api/builds/data

Response
[data.txt](https://github.com/OpenLiberty/openliberty.io/files/7714171/data.txt)

**Comment by kinueng** [comment]
This might be the related to https://github.com/OpenLiberty/openliberty.io/issues/2335

**Comment by navaneethsnair1** [comment]
Currently, all nightly builds exist on DHE. We are good to close this issue
