### ISSUE TITLE
Add a link to the public key used for verifying packages

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2446]
Related to #2305 

We need to give a direct link to visitors wanting to verify downloaded packages from https://openliberty.io/start/.  

The direct link is 

> https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/WebSphereLiberty_06-02-2021.pem

From the hip suggestion (will reach out to docs team for guidance on wording)
Learn how to verify the release files by downloading the public key and following these instructions.

**Comment by kinueng** [comment]
Hi @dmuelle,
Can you help me find any improvements to the sentence that starts with "Learn how to..." in the image below.  The `this public key` links to https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/WebSphereLiberty_06-02-2021.pem and `instructions` links to https://openliberty.io/docs/22.0.0.1/verifying-package-signatures.html.

![image](https://user-images.githubusercontent.com/31117513/150370469-97fb94ff-661f-4df7-ace6-98b7526dc6be.png)

**Comment by dmuelle** [comment]
I think we should provide a little more info, because the public key is tricky. Maybe:

```
Signature files are produced for every package of an Open Liberty release. You can use these signature files and the corresponding public key to verify the authenticity and integrity of an Open Liberty release package. For more information,
see [Verifying Open Liberty release packages].

[Obtain the public key from this link]. Save the file from your browser as a `.pem` file.
```

if you don't have that much screen real estate, could do

```
To learn how to verify release files, see [Verifying Open Liberty release packages].
[Obtain the public key from this link]. Save the file from your browser as a `.pem` file.
```

**Comment by kinueng** [comment]
Hi @dmuelle,

I prefer the long version since it speaks to both new and experienced developers on how to verify the downloaded files.

In the long version, we need to avoid saying `every package of Open Liberty release` because only `22.0.0.1` and future have signature files.  We display older releases that do not have signature files.  Do you have a suggestion on how to adjust your long version suggestion in https://github.com/OpenLiberty/openliberty.io/issues/2446#issuecomment-1017646288?

**Comment by dmuelle** [comment]
Starting with version 22.0.0.1, signature files are produced for every package of an Open Liberty release. You can use these signature files and the corresponding public key to verify the authenticity and integrity of an Open Liberty release package. For more information, see [Verifying Open Liberty release packages]. 

[Obtain the public key from this link]. Save the file from your browser as a `.pem` file.

**Comment by aknguyen7** [comment]
![image](https://user-images.githubusercontent.com/30509453/150415416-251f3546-6d4c-4d69-b5ed-c001467a4440.png)
