### ISSUE TITLE
Traces do not take LogRecordContext into account

### ISSUE THREAD

**Issue by sdehors-ibm** [OpenLiberty/openliberty.io#2454]
When a trace is printed in json, it goes through a log record created in com.ibm.ws.logging.internal.WsLogRecord#createWsLogRecord. It seems in that case the LogRecordContext is not taken into account and no extensions are logged along with the trace log.

Unless there is a way to configure the trace to take into account the log context this is an important feature to investigate problems from logs.

**Comment by kinueng** [comment]
Hello @sdehors-ibm,
Is this issue intended for the Open Liberty runtime?  The runtime GitHub repo is here https://github.com/OpenLiberty/open-liberty.  This issue is currently opened against the source code for the https://openliberty.io website

**Comment by kinueng** [comment]
Hi @sdehors-ibm,
I am closing this issue.  This repository is for openliberty.io website.  If you want to report this issue against the Open Liberty runtime, please use one of the templates on the Open Liberty runtime repo (e.g. Bug report).  Here is a link for your convenience https://github.com/OpenLiberty/open-liberty/issues/new/choose
