### ISSUE TITLE
Update javadoc canonicals to include query params

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2484]
Currently, the canonical points to just the .html file without any query params.  For example, for
[https://openliberty.io/docs/22.0.0.1/reference/javadoc/microprofile-5.0-javadoc.html[…]activation/package-summary.html&package=allclasses-frame.html](https://openliberty.io/docs/22.0.0.1/reference/javadoc/microprofile-5.0-javadoc.html?class=jakarta/activation/package-summary.html&package=allclasses-frame.html)
the canonical is just
https://openliberty.io/docs/22.0.0.1/reference/javadoc/microprofile-5.0-javadoc.html

This means that as far as crawlers are concerned, there is only page per javadoc that should get indexed, instead of all of them.

**Comment by kinueng** [comment]
Google Search Console was scheduled to crawl the Javadoc pages and this issue was discovered.

**Comment by kinueng** [comment]
Please see if Google Search Console is honoring the new query parameters in the canonicals field.  The changes are in production.

**Comment by mbroz2** [comment]
No it doesn't see like doing the canonical update on the client side is affecting results in Search Console (likely they're either grabbing canonical prior to js running, or directly out of the html).  Seems like this will need to be injected at build time or server side at run time.

Also, there seems to be URLs at https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc which are not being redirected. For example:
https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc/index.html?jakarta/batch/runtime/context/package-summary.html
https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc/jakarta/faces/component/NamingContainer.html not getting redirected

**Comment by steven1046** [comment]
I think we need to add Jakarta logic here: https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/_assets/js/javadoc-redirect.js

**Comment by Sreejith-Websphere** [comment]
i created liberty-jakartaee not redirecting as a seperate issue 
 #2574

**Comment by kinueng** [comment]
We will explore creating a new Servlet filter to add the correct canonicals to the HTML content served by a redirect request.

Edit June 14: When trying to add a new Servlet filter, there was a roadblock on getting the new filter to run (e.g. ordering of the filters) correctly. We want the filter to add the query parameter to the HTML that is returned as a response to the redirect HTTP request.

**Comment by kinueng** [comment]
The `canonical` HTML metadata now contains the query parameters. The last step to closing this issue out is to look at Google Search Console and see if the crawlers are seeing the new `canonical` containing the params.

**Comment by kinueng** [comment]
Google Search Console shows the URL in the issue description is now indexed. A google search of the URL shows 
<img width="880" alt="image" src="https://user-images.githubusercontent.com/31117513/196725104-38168506-6081-42cf-bc50-e61fef3b2f4e.png">

Closing this issue as fixed
