### ISSUE TITLE
Scan for Word Matters terms

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#2500]
Scan for prohibited terms under Word Matters initiatives and lay a plan to address them.  This should cover all content on openliberty.io including guides.

@kinueng @gkwan-ibm @dmuelle @GraceJansen @atosak 

Cc @mbroz2

**Comment by yeekangc** [comment]
We should also ensure that future content will follow what is needed here (and the contributors/reviewers will check for them).

**Comment by gkwan-ibm** [comment]
The guides already have automation (PR checker) to check prohibited terms.

**Comment by kinueng** [comment]
@gkwan-ibm can you point me to how the the guides automated the prohibited terms check?  I would like to learn how the automation works.

**Comment by gkwan-ibm** [comment]
In each guide repo, we define a github action, like https://github.com/OpenLiberty/guide-getting-started/blob/prod/.github/workflows/test.yml. The action will be run for any PR change. In line 24 to 32, we trigger the superlinter to check the java, yaml, and js files, etc. In line 21 to 23, we trigger our own checker to check the license year and prohibited words. 

The source of our checker is located at https://github.com/OpenLiberty/guides-common/tree/prod/pr-checker. The checker is a [python script](https://github.com/OpenLiberty/guides-common/blob/prod/pr-checker/checker.py). 

The [deny_list.json](https://github.com/OpenLiberty/guides-common/blob/prod/pr-checker/deny_list.json) defines the prohibited words and the [warning_list.json](https://github.com/OpenLiberty/guides-common/blob/prod/pr-checker/warning_list.json) defines the warning words.

**Comment by kinueng** [comment]
Lets target this to be done by June 30

**Comment by kinueng** [comment]
We should also include OpenLiberty/start.openliberty.io

**Comment by atosak** [comment]
@kinueng based on Gilbert's comments the guides already have automation (PR checker) to check prohibited terms. Is there a separate issue for openliberty.io or we will be reusing this issue?

**Comment by kinueng** [comment]
@atosak We will use this issue to track any work (manual or automated) for checking prohibited terms for openliberty.io and the Liberty Starter.  It will make tracking work all in one place.  FYI @aknguyen7

**Comment by kinueng** [comment]
@aknguyen7 you will have to also cover the interactive guides since those are maintained by us
https://github.com/OpenLiberty?q=iguide

**Comment by aknguyen7** [comment]
done
