### ISSUE TITLE
Bad error message when requesting docs for a version that doesn't exist

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#2517]
If request docs for a release that doesn't exist you don't get a pretty 404 error, but a pretty nasty servlet one.

Goto: https://openliberty.io/docs/1/overview.html

and you get:

`Error 500: javax.servlet.ServletException: com.ibm.ws.webcontainer.exception.IncludeFileNotFoundException: SRVE0190E: File not found: /docs/1/overview.html.gz`

It should look like this: https://openliberty.io/404, or we could at least customize the 404 page in this case to point to something more useful, maybe redirect to the latest docs?

**Comment by mbroz2** [comment]
Closing as dup of https://github.com/OpenLiberty/openliberty.io/issues/2299
