### ISSUE TITLE
Update docker pull to include icr.io

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2524]
Consider updating the section to something along the lines of:
![image](https://user-images.githubusercontent.com/3076261/154606622-929240d7-d43a-44b1-9d87-a86907ee8af3.png)

**Comment by kinueng** [comment]
We would promote only one container registry rather than two choices.  The preference is to have `icr.io` (IBM Cloud Container Registry).  Before the change is made, we want to have documentation ready to describe the container image tags for users who want an image other than the one tagged as `latest`.

This issue depends on https://github.com/OpenLiberty/docs/issues/5233

**Comment by dmuelle** [comment]
https://github.com/OpenLiberty/docs/issues/5233#issuecomment-1058441426

**Comment by dmuelle** [comment]
^ also need to get betas added to ICR

**Comment by kinueng** [comment]
There is now a doc page for the container images https://openliberty.io/docs/latest/container-images.html

**Comment by natalie-bernhard** [comment]
Just to confirm sentiments from earlier comments, we are replacing the current docker pull command, not adding a second docker pull command to the section, correct?

**Comment by kinueng** [comment]
Hi @natalie-bernhard
`docker pull open-liberty` should be replaced with `docker pull icr.io/appcafe/open-liberty`. The end result is to only promote one container registry, `icr.io`.

**Comment by kinueng** [comment]
Additionally, we want to make sure we promote this page that documents the `open-liberty` images in `icr.io` https://openliberty.io/docs/latest/container-images.html. This will require reworking the wording around the code block containing `icr.io/appcafe/open-liberty`

**Comment by natalie-bernhard** [comment]
This is the wording we are thinking of using (Reviewed by ID), waiting for final review


![Image](https://user-images.githubusercontent.com/84740311/220648652-74b4bb41-dd6b-4e57-8333-640ac50adbab.png)
