### ISSUE TITLE
More emphasis on the Build Tool field in starter

### ISSUE THREAD

**Issue by turkeylurkey** [OpenLiberty/openliberty.io#2544]
The "Build Tool" field doesn't get the same visual emphasis as the others near the top of the site: openliberty.io/start/

The eye is drawn to the five fields with green boxes around them: "Group," "Artifact" etc.  Using the site I did not notice the "Build Tool" field at first and the tool generated a Maven project when I actually wanted a Gradle project. 

Could you draw a green box around the selected radio button to give this field the same emphasis as the others?

**Comment by kinueng** [comment]
Link to UI in question: 

- https://openliberty.io/start/

Snapshot of the UI (Note: I had set the Java SE to a non-default choice in the picture)
- ![image](https://user-images.githubusercontent.com/31117513/156807628-374c21a6-2cad-4321-8f6e-f8d685a98a2d.png)

**Comment by mdenby** [comment]
My suggestion is to change the selected radio button to have green. Here are two options:

 <img width="417" alt="Screen Shot 2022-03-04 at 1 30 52 PM" src="https://user-images.githubusercontent.com/26823018/156821472-b445d6ad-c170-4933-8735-b23de9ae74d1.png">

<img width="403" alt="Screen Shot 2022-03-04 at 1 30 47 PM" src="https://user-images.githubusercontent.com/26823018/156821476-b14bf2f4-8743-43c0-ac5e-4b5793db6849.png">

**Comment by kinueng** [comment]
@mdenby What about having the two circles always be green and the dot always be black?
![image](https://user-images.githubusercontent.com/31117513/156826881-c9bfc36d-4d44-4165-874d-adc64198bf2e.png)

**Comment by mdenby** [comment]
That works too! It looks good.

**Comment by turkeylurkey** [comment]
Sure. 👍

**Comment by kinueng** [comment]
Hi @mdenby, please help us edit these two SVG files to have a green circle while keeping the dot black.

https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/img/radio-button.svg
https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/img/radio-button--checked.svg

**Comment by kinueng** [comment]
FYI @mdenby, I got the images updated.
I hand edited the XML file of the SVGs to add the green and increase the stroke with to 2px like the other input fields.
