### ISSUE TITLE
Make the doc version switcher scrollable

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#2562]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/6392944/158658185-3634f2e9-31b9-4fb5-8391-06d3c5e54771.png">

With small browsers / even laptops you can't reach the full list of versions. You can still see the whole list if you scroll the rest of the page but it might be good if the reader doesn't have to scroll the page to see the dropdown list.

**Comment by kinueng** [comment]
Done in production

Using Chrome
![image](https://user-images.githubusercontent.com/31117513/166698556-e2af0fa0-9a8c-44a8-8826-43863762e005.png)
