### ISSUE TITLE
liberty-jakartaee is not redirecting

### ISSUE THREAD

**Issue by Sreejith-Websphere** [OpenLiberty/openliberty.io#2574]
URLs at https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc which are not being redirected. For example:
https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc/jakarta/batch/runtime/context/package-summary.html
https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc/jakarta/faces/component/NamingContainer.html not getting redirected

**Comment by kinueng** [comment]
Hi @Sreejith-Websphere,
I see the redirect is now partially working in production. What I am noticing is the query parameters are not being honored after the redirect happens for the two URLs in the description

https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc/index.html?jakarta/batch/runtime/context/package-summary.html

https://openliberty.io/docs/modules/reference/liberty-jakartaee9.1-javadoc/jakarta/faces/component/NamingContainer.html

**Comment by kinueng** [comment]
Closed as resolved, but added additional unrelated problems to #2665
