### ISSUE TITLE
Release builds should provide link to test results

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#2591]
It should be possible to navigate to the test results for a release build as well as the nightly ones. I know it should be complete pass, but we should still do it.

**Comment by steven1046** [comment]
Is this order of columns good:
<img width="1188" alt="image" src="https://github.com/OpenLiberty/openliberty.io/assets/6392944/1de9c5a9-f166-4c7c-b229-9b5019bd2291">

**Comment by steven1046** [comment]
The unit tests are the same for each release, so we probably don't need one per row and can move them next to the PEM download.

**Comment by steven1046** [comment]
Here is a mockup of the tests only once per release:
<img width="929" alt="image" src="https://github.com/OpenLiberty/openliberty.io/assets/6392944/6b73fccf-3410-4df5-8b35-972ca9377d02">
