### ISSUE TITLE
Create container images for openliberty.io

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2595]
Create container images for openliberty.io.  Have multiple images to accommodate the various site configurations documented here https://github.com/OpenLiberty/openliberty.io/wiki/Websites-&-branch-breakdown

**Comment by yeekangc** [comment]
This should be helpful.  If we can make one available for development purposes (for blog authors), that is useful too?

**Comment by kinueng** [comment]
This work is being done on branch `docker` https://github.com/OpenLiberty/openliberty.io/tree/docker
