### ISSUE TITLE
Ensure that the ol.io layout remains the same if social media widgets are not loaded

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/openliberty.io#2600]
Blocking tracking cookies on a browser can prevent some widgets from loading (e.g. twitter timeline). If the widget does not load then the rest of the layout can be broken. This can be avoided using a fixed sized outline in the place that the widget would load. If the widget does not load then a helpful message can be displayed to make it clear that something is missing and the likely reasons why.

**Comment by kinueng** [comment]
Recreation steps
- Use Firefox
- Turn Firefox Strict Tracking protection on (default is Standard)
- Observe Strict removes the Twitter tiles
- Observe double scrollbars on openliberty.io
- Notice the background cloud is shifting out of place

Picture from Firefox with Strict policy enabled
![image](https://user-images.githubusercontent.com/31117513/166705375-ab1e106c-481e-4d4b-81e6-2c4f332106b3.png)
