### ISSUE TITLE
Guide TOC does not scroll up automatically

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#2636]
For a guide with long TOC like `https://openliberty.io/guides/liberty-deep-dive.html`, when scroll the main content, the TOC can highlight the current section/subsection. When scroll the main content further down, the TOC does not scroll up automatically, users may not know which is the current section. Like the following screenshot, the main content at the "Securing RESTful APIs" section, but the TOC shows the top sections and not show that section. Users need to scroll the TOC downward to find out which is the current section for the TOC perspective. 

![Screen Shot 2022-05-04 at 9 24 39 AM](https://user-images.githubusercontent.com/29576299/166690362-186d5db1-0d21-488a-a807-d22662ddbec5.png)

**Comment by kinueng** [comment]
Hi @gkwan-ibm, is this a regression or a feature request?

**Comment by kinueng** [comment]
Or maybe this is a bug that just happened to be discovered now because this is our first time having a very long TOC?

**Comment by gkwan-ibm** [comment]
Yes, it is the first time to have long TOC
