### ISSUE TITLE
Update feature names in "Develop cloud-native Java microservices" homepage section

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2709]
Look through the names used in section https://openliberty.io/#develop_container and update ones to their latest name.
![image.png](https://images.zenhubusercontent.com/59d7b56bb0222d5de47a9368/66c965c1-a85a-4fa4-8c5d-4c9dd89b0626)

**Comment by kinueng** [comment]
I reached out to @Emily-Jiang and here was my take away actions

1. All occurrences of `Eclipse MicroProfile` should be updated to be `MicroProfile`.
1. `JWT Propagation` can be shortened to `MicroProfile JWT`.
1. There is a request to change `JAX-RS` to `Restful WS`. Do you agree with this change? 
     1. Emily: JAX-RS is still in use. There was not an agreement on the new acronym. I think JAX-RS is still fine. 
     1. FYI @mbroz2

**Comment by kinueng** [comment]
Hi @dmuelle, can you help assist in rewriting the paragraph so that the two links in `Jakarta EE. Zero migration` are not next to each other. Right now the two unique links visually look like one link.
<img width="519" alt="image" src="https://user-images.githubusercontent.com/31117513/176268131-604a9001-39f1-4310-b283-a1fbaee6fab4.png">

**Comment by dmuelle** [comment]
Here are a couple options. I prefer the first- 

Open Liberty starts up fast, with a low memory footprint and live reload for quick iteration. Adding and removing features from the latest versions of [MicroProfile](https://openliberty.io/docs/latest/microprofile.html) and [Jakarta EE](https://openliberty.io/docs/latest/jakarta-ee.html) is simple.  And with [zero migration](https://openliberty.io/docs/latest/zero-migration-architecture.html), you focus on what's important, not the APIs changing under you.

or

Open Liberty is fast to start up with a low memory footprint and live reload for quick iteration. Simple to add and remove the latest versions of [MicroProfile](https://openliberty.io/docs/latest/microprofile.html) and [Jakarta EE](https://openliberty.io/docs/latest/jakarta-ee.html) features. And [zero migration](https://openliberty.io/docs/latest/zero-migration-architecture.html) lets you focus on what's important, not the APIs changing under you.

or

Open Liberty is fast to start up with a low memory footprint and live reload for quick iteration. [Zero migration](https://openliberty.io/docs/latest/zero-migration-architecture.html) lets you focus on what's important, not the APIs changing under you. Simple to add and remove features from the latest versions of [MicroProfile](https://openliberty.io/docs/latest/microprofile.html) and [Jakarta EE](https://openliberty.io/docs/latest/jakarta-ee.html).

**Comment by kinueng** [comment]
This issue is done. The outcome is openliberty.io will continue to use `JAX-RS`. The other changes can be found in #2743
