### ISSUE TITLE
Expand blog search query to handle multiple tags and negation of tags

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#2751]
For example, to list all GA release blog posts but not the beta blog posts: https://openliberty.io/blog/?search=release&search!=beta

Listing all the beta blog posts is currently easy because they exclusively use the `beta` tag: https://openliberty.io/blog/?search=beta&key=tag
Listing the GA release blog posts without the beta blog posts is not possible at the moment because all GA and beta blog posts use the `release` tag.

I want to be able to add a standard sentence in all beta release blog posts saying something like: “For capabilities added to previous GA releases, see our previous beta release blog posts." and in all GA release blog posts saying something like “For capabilities added to previous GA releases, see our previous GA release blog posts.". And then link each to their respective tag so that the reader can see the reverse chronological list of applicable release blog posts.

Discussed briefly with @mbroz2 on slack.

**Comment by kinueng** [comment]
Hi @lauracowen,
This work is now live on openliberty.io. Thanks @natalie-bernhard for the work here!

**Comment by mbroz2** [comment]
@lauracowen we should consider updating the GA and beta post templates to add links to previous corresponding release posts.

**Comment by lauracowen** [comment]
I'll update them.

**Comment by lauracowen** [comment]
@kinueng @natalie-bernhard What is the syntax to use for all release posts excluding beta release posts?

**Comment by mbroz2** [comment]
https://openliberty.io/blog/?search=release&search!=beta
