### ISSUE TITLE
CSS for videos embedded in blog posts (or docs potentially too)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#2779]
In this [draft blog post](https://blogs-draft-openlibertyio.mybluemix.net/blog/2022/09/19/app-server-crafters-makers.html), I've got a couple of YouTube videos embedded in the page, using the [Asciidoctor macros](https://docs.asciidoctor.org/asciidoc/latest/macros/audio-and-video/).

As you can see in the draft, the photos are all centred on the page but the videos are left-aligned. Would it be possible to set the video CSS to be similar to the images CSS, please?

**Comment by kinueng** [comment]
Example of left align YT embedded video
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/31117513/186441492-8cbf02c6-9563-4c27-9201-3c5a734c851a.png">
