### ISSUE TITLE
additional tests need for starter

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/openliberty.io#2791]
Now we have an option to select 
1.  any MicroProfile Version when Java EE/Jakarta EE Version is selected as None
2. any Java EE/Jakarta EE Version when MicroProfile Version is selected as None

We'll need to add the following tests for starter to testOLStarterAllGradle.js & testOLStarterAllMaven.js:

Jakarta None - MP 4.1, 3.3, 2.2, 1.4

MicroProfile None - JKT 8.0, 7.0

**Comment by kinueng** [comment]
Done
