### ISSUE TITLE
Blog posts not syndicating to Jakarta EE blog

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#2793]
The blog posts tagged `Jakarta EE` aren't syndicating to the Jakarta EE aggregator blog any more. Not sure how long it's been like this (I can't find any recent screenshots) but I'm fairly sure it was working a few(?) weeks ago as I checked.

According to #1934 , this is the feed: https://openliberty.io/jakartaee.xml and it doesn't seem to contain any posts at the moment ([should be several](https://openliberty.io/blog/?search=Jakarta_EE&key=tag)).

/cc @Emily-Jiang

**Comment by kinueng** [comment]
We will need to interrogate file https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/jakartaee.xml

**Comment by lauracowen** [comment]
Works now. Thank you!

**Comment by kinueng** [comment]
@lauracowen can you give an example of a syndicated EE blog? Maybe we can write a test to always check that those syndications are looking as expected

**Comment by lauracowen** [comment]
The most recent one is https://openliberty.io/blog/2022/09/21/history-maker-projects.html and it appears on the scrolling page here: https://jakarta.ee/blogs/

However, I don't think older posts are loaded automatically on the page...I don't know if that matters? Manually, I've just been going to that URL and then doing a find in page for the word "liberty" - most, but not all, instances are our posts.
