### ISSUE TITLE
Bold style looks fuzzy?

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#2794]
I keep noticing that certain bits of text in the blog post and/or guides looks slightly blurred/fuzzy compared with the surrounding text.

For example, in this guide, the boldened text ("Replace the server.xml file.") doesn't look as sharp as the normal weight text (or as the bold header):

![image](https://user-images.githubusercontent.com/3322532/186680672-c53f19b9-4d1e-4c31-a831-6f85869df0b6.png)

**Comment by kinueng** [comment]
Are you experiencing the fuzziness on an external monitor?
What operating system and browser are you using?

**Comment by lauracowen** [comment]
Hmm, I realise that screenshot isn't so helpful (it was the "Replace..." sentence that was definitely blurry compared with the "Modifying..." header. So maybe it is the monitor in some weird selective way.

Yes, external monitor (but not this one in the office, apparently). Firefox on Mac.

Okay, next time I notice it I'll check it on different monitors.

**Comment by kinueng** [comment]
You may want to try comparing the text on the laptop screen.

I recall that macOS removed the anti-aliasing feature for external monitors many versions ago. I think sometimes it is called "font smoothing". Without anti-aliasing, text can become fuzzy.

The only way that I know to fix the fuzzy text for external monitors on macOS is to meet a minimum required pixel per inch (PPI). Essentially the external monitor needs to meet the "Retina display" specs, which is having more than 200 PPI. Not many monitors have this many PPIs and if they do, they are expensive.

This blog post was insightful to me when I really wanted to tackle the fuzzy text on my external monitors with macOS.
https://taylorpalmer.co/blog/finding-the-right-external-macbook-pro-monitor/#-resolution

**Comment by lauracowen** [comment]
I've just checked on my home external monitor. You're right that it's the monitor - it's fine on my laptop screen. It's really weird how it's just a certain size of bold text that's slightly fuzzy - the headings and the normal (unboldened) text are fine. I'll close the issue.
