### ISSUE TITLE
CSS style for guides

### ISSUE THREAD

**Issue by gindik** [OpenLiberty/openliberty.io#28]
The mechanism to apply CSS to guides should be revised to make sure their content appears the way its intended. This work should be performed in collaboration with the design team and the guide authors. As a starting point, there is an issue with the tables in the CORS guide currently available for preview here: https://openlibertydev.mybluemix.net/guides/cors.html

**Comment by yeekangc** [comment]
@kinueng, what do you think of the style for the tables?  Do you think we can address that soon?  Thank you.

**Comment by kinueng** [comment]
There is a complete redesigns happening to the guides through #145.
