### ISSUE TITLE
`22.0.0.10` release build not sorted to the top of table

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2854]
![image](https://user-images.githubusercontent.com/31117513/192594625-e6ada273-e3f6-48a4-9038-f68164ccb85c.png)

**Comment by NottyCode** [comment]
This is caused because the info.json for the releases has the version set in date_time since 22.0.0.2 rather than the release date. The date_time in the json needs to be the date.

**Comment by kinueng** [comment]
Here is the `date_time` in question from `GET` https://openliberty.io/api/builds/data
![image](https://user-images.githubusercontent.com/31117513/192600470-b64cb347-5133-49f9-815e-b17f09625fab.png)
