### ISSUE TITLE
Add alt text field for open graph images from Blog posts

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/openliberty.io#2858]
[Open graph](https://ogp.me/) provides preview images for our blog posts in social media posts. The protocol provides a means to specify alt text for the images to improve accessibility, but the OL blog post metadata doesn't currently support it.

the `open-graph-image:`  metadata field is only for `property="og:image"`

`<meta property="og:image" content="{{ page.open-graph-image }}" />`

We can add `property="og:image:alt"` and `name="twitter:image:alt"` (unless we decide to remove twitter-specific metadata)

**Comment by kinueng** [comment]
From [Open graph](https://ogp.me/)

> `og:image:alt` - A description of what is in the image (not a caption). If the page specifies an `og:image` it should specify `og:image:alt`.
