### ISSUE TITLE
Handling old guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#286]
Over time and even now, we will have guides that are old or out-of-date.  Need proper handling for such guides.

Consider:
- Keep the old guides published but not have them show up in All Guides page
- Instruction or comment at the beginning or end of these guides to refer to the newer guides
- Attributes etc that are necessary to identify such guides for the web site and infrastructure to handle appropriately and accordingly

**Comment by steven1046** [comment]
![image](https://user-images.githubusercontent.com/6392944/39018166-d97b37ce-43ea-11e8-8118-a304ba8a6ee7.png)

Add this tag:
:page-archived: true
if you want to archive a guide
