### ISSUE TITLE
Open Graph and Twitter metadata are different between non-Antora and Antora pages

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2862]
The Twitter and Open Graph metadata have deviated. Should the Liquid tags be consolidated?

Non-Antora pages
https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/_includes/head.html

Antora pages
https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/antora_ui/src/partials/head-meta.hbs

**Comment by steven1046** [comment]
Hi @kinueng, can you help clarify what needs to be changed here?

**Comment by kinueng** [comment]
@steven1046 the social media metadata is different between page generated by Jekyll and pages generated by Antora. I created this issue to make them consistent

**Comment by steven1046** [comment]
![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/afa9dfd7-a5c5-4829-86a0-951787f9bd3b)


![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/7e06cb03-7639-4b65-b08f-b67a5bb0fbda)

![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/55ba0d21-221b-40f5-a640-8f22378af278)

![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/66d37414-f1ea-4080-9045-d9ff928e9c71)


![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/714738b2-fa58-4d18-970a-00b0477a32bc)

Each page has its own SEO string and falls back to a generic string if not present on the page. The docs have a different SEO string on purpose.

**Comment by kinueng** [comment]
Closing based on feedback from @steven1046
