### ISSUE TITLE
Categories: Better organization of the all guides view

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#287]
Provide a way to organize the guides on the site, so that:

* It's easier to find guides
* It's easier to find guides on a particular topic or category
* For a given topic, a user is presented with an introductory set of guides making it easier to get started
* For a guide, a set of related guides or suggested next guide is presented

Current code found on this branch https://github.com/OpenLiberty/openliberty.io/tree/guide_page_redesign
![image](https://user-images.githubusercontent.com/31117513/44598710-82bc1800-a799-11e8-98fa-00b21bbfcbe8.png)

**Comment by megmulsy** [comment]
* Make the homepage feel less intimidating/overwhelming on load 
* To have a pleasant exploratory experience - in addition to having something that is easily searchable
* To put a spotlight on the guides that we really don't want people to miss 
* To have meaningful descriptions/titles 
* To have meaningful sections

**Comment by megmulsy** [comment]
Guides (Home) - Sections/Segments
PNGS

    On Laod - https://ibm.box.com/s/kf3xch5ovr0i5q67ob3uepucczi9gexm

    Expanded - https://ibm.box.com/s/3jlvxv8d74fg9t96t42p4thf39w1tfwk

Redlines - https://ibm.box.com/s/7p9gba9mrb7sk58kp8sl6q0ofm0kvjdt
Assets- 

    Lightning bolt: https://ibm.box.com/s/1ui8f6t68pg86p4ui3aienr4vbpya0wl

    Search - https://ibm.box.com/s/ompdedsih0i8h9eokj1yyqe5ns4o9dqt

**Comment by kinueng** [comment]
Thank you for designs, moving this issue to prioritize for development.
