### ISSUE TITLE
IDE tools section

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2888]
A new development which will add a section to the start page promoting the liberty IDE plugins

**Comment by dmuelle** [comment]
proposed update for text to introduce the extensions:

> Liberty Tools is a set of intuitive extensions for the Eclipse, Visual Studio Code, and Intellij development environments. These extensions integrate with Open Liberty dev mode and provide helpful, time-saving features such as code completion, hover descriptions, and configuration diagnostics. For more information, check out the Liberty Tools overview. [link TBD]

**Comment by kinueng** [comment]
I have added the following issues that we will be dependent on
- Docs https://github.com/OpenLiberty/docs/issues/5823
- Blog post https://github.com/OpenLiberty/open-liberty/issues/23604

**Comment by kinueng** [comment]
We are targeting this work to be merged into production with the release of `22.0.0.13`

**Comment by natalie-bernhard** [comment]
New target date is June 9th, which we will align with posting the new section to the starter

**Comment by natalie-bernhard** [comment]
This is how the section looks currently:
<img width="1340" alt="Screenshot 2023-05-22 at 12 01 10 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/84740311/29320db9-ee62-49d9-a99f-7280a0dc690a">

**Comment by yeekangc** [comment]
LGTM.
