### ISSUE TITLE
Change javadocs to share the jQuery version from the website.

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#289]
This will reduce the number of downloads of jQuery and ensure that the version is secure.

**Comment by steven1046** [comment]
Need discussion of how much maintenance will be required to update all of the jquery paths every time they are updated or new ones are added.

**Comment by steven1046** [comment]
We could update the build script to automatically copy our version over, but then it would require a lot of testing to confirm nothing broke when using a different JQuery version.

**Comment by mbroz2** [comment]
Although this would have the stated benefits, the drawback is that it would force the site to use the jquery version that javadoc uses, otherwise, the version mismatch would likely cause issues in the javadoc.  As such, closing this issue.
