### ISSUE TITLE
Need design for table styling in guides

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#29]
We need to add some CSS styling for tables that are rendered by AsciiDoc in the CORS guides.  The current styling isn't even acceptable.  To get the CORS guide publish quicker, we can first add a simple table styling and redesign it with a nicer look&feel later.

Current table rendering:
------
![image](https://user-images.githubusercontent.com/31117513/31504745-cd74acf4-af38-11e7-8087-ee94b7c27884.png)
------

Try getting something simple like this:
------
![image](https://user-images.githubusercontent.com/31117513/31505050-985370f4-af39-11e7-9efc-4deb972b6f81.png)
------

**Comment by kinueng** [comment]
I am first looking into why the default Asciidoc table styling isn't being applied.

**Comment by kinueng** [comment]
We have an initial solution to give the table a simple styling.  Using this issue to make sure we follow up with design team for more refined styling.

**Comment by gindik** [comment]
The default asciidoc stylesheet is included in the project code. However, given that we have custom styles from the design team (custom fonts, custom headings, custom margins, etc) we don't apply it and instead rely on our own CSS. This is the first time that a table is used in a guide, so it reveals the need for more CSS rules that what we had before.

**Comment by gindik** [comment]
I temporarily applied the set of rules for tables from the default asciidoc stylesheet into the custom guide stylesheet. This is so that we don't delay the publication of the guide and provides both the development and the design team sufficient time to come up with a permanent solution.

**Comment by gindik** [comment]
Closing this item as we have a solution for the new guide. The new work would be encapsulated in https://github.com/OpenLiberty/openliberty.io/issues/28
