### ISSUE TITLE
Table of content in guides not working properly whilst chrome window is not in fullscreen

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/openliberty.io#2914]
Not able to scroll through the table of content and also doesn't move as scrolling through the guide. See screen recording attached. 

https://user-images.githubusercontent.com/56261244/199512382-e14c7a3f-fd70-4459-977d-afb199157ce9.mov

**Comment by kinueng** [comment]
Possibility related to https://github.com/OpenLiberty/openliberty.io/issues/2636

The description is using https://openliberty.io/guides/liberty-deep-dive.html

**Comment by kinueng** [comment]
The TOC is not scrollable in mobile resolution, which means users cannot see the bottom of the TOC. On desktop it is fine.

**Comment by kinueng** [comment]
Fixes #2927

Make sure GitHub closes the duplicate issue!

**Comment by natalie-bernhard** [comment]
Closed via #3303
