### ISSUE TITLE
Show authors for translated blog posts

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#2915]
Highlight who are the translators for translated blog posts like how we highlight authors.  Only the original authors are listed at the moment.

**Comment by kinueng** [comment]
At the moment, we ask the non-English blog posts to accredit the translator within the next. An example of this is https://openliberty.io/zh-Hans/blog/2022/10/16/microprofile-spring-comparison.html



![Image](https://user-images.githubusercontent.com/31117513/211642597-3bd8512b-aab2-4cc4-acce-f36ca891fab6.png)

**Comment by kinueng** [comment]
Whatever we decide, we need to update the instructions https://github.com/OpenLiberty/blogs/wiki/i18n

**Comment by kinueng** [comment]
We are thinking of doing the following:
- Add the translator as an additional author to the post
- Ask the author to tag their full name to indicate they are the translator. For example: Kin Ueng (translator)

Here are some mock ups on how it would look when comparing between a English post and its Japanese translation

# Preview card

## English 


![Image](https://user-images.githubusercontent.com/31117513/220699849-715843cb-c32a-4800-a449-ef50bc6fe976.png)

## Japanese 


![Image](https://user-images.githubusercontent.com/31117513/220700082-ee39fd5b-4d50-4476-aac0-dd42bf1a8cc4.png)

# Full blog post page

## English



![Image](https://user-images.githubusercontent.com/31117513/220700387-41c6a342-2040-4384-8793-6d727a306975.png)



## Japanese



![Image](https://user-images.githubusercontent.com/31117513/220700461-61c48720-587a-4ec4-87da-3d123477bf6a.png)

**Comment by una-tapa** [comment]
Sorry wrong PR!
