### ISSUE TITLE
Translated blog posts contain incorrect links to other pages

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#2921]
There's several links on the jap blog page that incorrectly link to various /ja/* pages that don't exist.

For example, the Open Liberty logo in the header links to https://openliberty.io/ja instead of just https://openliberty.io/.  There are more examples in the footer.

**Comment by kinueng** [comment]
Also links in the footer 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/31117513/200387523-571eab16-e933-4f92-94da-b6d7d092f80b.png">

**Comment by kinueng** [comment]
Used the following JavaScript code to scan for any `/ja/` URLs that are unsupported
```
var arr = [], l = document.links;
for(var i=0; i<l.length; i++) {
  arr.push(l[i].href);
}
console.log(arr)
```

**Comment by kinueng** [comment]
Tested on 
- https://openliberty.io/ja/blog/2022/09/01/openliberty-guides-in-japanese.html
- https://openliberty.io/ja/blog/
