### ISSUE TITLE
Canonical is incorrect for URLs that use Liberty version instead of `latest`

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2930]
1. Visit https://openliberty.io/docs/22.0.0.2/reference/feature/ssl-1.0.html
2. Observe the DOM has `<link href="https://openliberty.io/docs/latest/reference/feature/ssl-1.0.html" rel="canonical">`

Impact
Google does not index the URL in step 1
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/31117513/200942613-9fc3f1f6-30eb-47f1-a322-934b8db8e547.png">

**Comment by kinueng** [comment]
I think the server side code that is updating the `canonical` metadata is always assuming the incoming URL request is `latest`.

**Comment by NottyCode** [comment]
Please do not do this. We want the canonical url to point to the most recent version of the page so google only pushes to the first one.
