### ISSUE TITLE
Blog posts aren't reliably syndicating to the Jakarta EE blog

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#2934]
I count 15 blog posts under the `Jakarta EE` tag for 2022 at: https://openliberty.io/blog/?search=Jakarta_EE&key=tag

However, only two of those posts are syndicated at Jakarta EE blog: https://jakarta.ee/blogs/
https://openliberty.io/blog/2022/11/04/liberty-tools-eclipse-jakarta-ls.html
https://openliberty.io/blog/2022/10/27/22.0.0.12-beta.html

![image](https://user-images.githubusercontent.com/3322532/205330109-6fbe5fc5-422d-4612-b841-232cd46fd3f5.png)

**Comment by kinueng** [comment]
Here is openliberty.io's RSS feed for Jakarta EE blog posts
https://openliberty.io/jakartaee.xml

Oddly, there are more than 2 blog posts in the RSS feed.

**Comment by kinueng** [comment]
I suspect the XML for the Jakarta EE RSS XML contains some syntax issues
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Fjakartaee.xml

Our default blog feed is fine
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Ffeed.xml

**Comment by kinueng** [comment]
Thought: Is there something we can do to automatically verify our feed.xml files as this is not the first time we had a bug in this area

**Comment by natalie-bernhard** [comment]
Update 12/14/22: Removing GUID/making the GUID unique makes the feed valid again. GUIDs were not guaranteed to be unique due to redirected blogs having the same site.url.  Next step is to figure out if GUID is needed, and if it is, what do we want to use for the GUID?

**Comment by lauracowen** [comment]
What's the GUID for? Where's it used?

**Comment by natalie-bernhard** [comment]
It's used to give each item in the feed a unique identifier/ID. I'm not sure if the Jakarta EE blog uses this parameter/attribute when rendering the posts from the feed, hence why it can't just be removed.  

Currently our feed still produces all of the Jakarta EE posts, so I'm wondering whether the Jakarta EE website is having it's own issues or choosing to limit how many blog posts to render from the feed.

**Comment by lauracowen** [comment]
cc @NottyCode In case you have any insights into this, as you set up the original aggregation?

**Comment by kinueng** [comment]
I noticed that there is still only two Open Liberty blogs showing up on the Jakarta EE blog feed. The difference is the two blogs are now our two most recent blogs found at the top of our `jakartaee.xml` feed.
- Jakarta EE 10 Platform and MicroProfile 6 in Open Liberty 23.0.0.1-beta
- Fast iterative cloud-native Java application development with Liberty Tools

I noticed the `jakartaee.xml` is now valid per w3's validator, but there are some recommended changes that do not show up on our `feed.xml`. I am thinking we try to fix those recommendations.
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Fjakartaee.xml

> Recommendations
> This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.
> 
> Your feed appears to be encoded as "UTF-8", but your server is reporting "US-ASCII" [[help](https://validator.w3.org/feed/docs/warning/EncodingMismatch.html)]
> 
> 
> [line 95](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Fjakartaee.xml#l95), column 12: description should not contain relative URL references: /blog/2022/12/06/22.0.0.13-beta.html (690 occurrences) [[help](https://validator.w3.org/feed/docs/warning/ContainsRelRef.html)]
> 
> &lt;/div&gt;</description>        
>             ^
> [line 2821](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Fjakartaee.xml#l2821), column 0: description should not contain iframe tag (3 occurrences) [[help](https://validator.w3.org/feed/docs/warning/SecurityRisk.html)]
> 
>         <title>Open Liberty: A brief history in maker projects of a cloud-na ...
> [line 6292](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fopenliberty.io%2Fjakartaee.xml#l6292), column 0: Invalid HTML: End tag (code) violates step 1, paragraph 3 of the adoption agency algorithm. [[help](https://validator.w3.org/feed/docs/warning/NotHtml.html)]
> 
>         <description>&lt;div id=&quot;preamble&quot;&gt;

**Comment by kinueng** [comment]
Here is the repository I think handles the Jakarta blog posts https://github.com/jakartaee/jakartablogs.ee. There are some instructions to setup local development that may be helpful in debugging whether there is an issue on the Jakarta website side.

**Comment by natalie-bernhard** [comment]
In December of 2021, the Jakarta site made a change to the configuration of their aggregated blogs, which limited each feed to only aggregate the 2 newest posts for the Jakarta blog page.  Our Jakarta EE feed is now valid, but https://jakarta.ee/blogs/ will still only show the two newest Jakarta posts.  Closing this issue as it has been resolved. (Jakarta site change here: https://github.com/jakartaee/jakartablogs.ee/commit/98501ddd020c5513cc9911bf1d05b36ccc64d8cb) (Explanation of this configuration here:https://github.com/rubys/venus/blob/9de21094a8cf565bdfcf75688e121a5ad1f5397b/docs/config.html#L107-L108)

Tagging @lauracowen to see the update
