### ISSUE TITLE
Date format for blog posts needs to match the language

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2947]
The date format does not match the language of the post.

![image](https://user-images.githubusercontent.com/31117513/206280214-334f6c68-c28f-46d9-9c24-0a47fe892f28.png)

A possible example of a localized date in Chinese
<img width="299" alt="image" src="https://user-images.githubusercontent.com/31117513/206280448-1114d367-f020-4c9f-98d4-fc83081dfbbc.png">

**Comment by steven1046** [comment]
convert a date to localized date
const date = new Date();
const localizedDate = date.toLocaleString();

also handle RTL vs. LTR

**Comment by natalie-bernhard** [comment]
Options: 

`author` on `date` (adds に to the end of the date, direct translation from English wording):

![Image](https://user-images.githubusercontent.com/84740311/220724991-bb777a3e-c75f-4bd5-a7f8-49fd77b8d0bd.png)
![Image](https://user-images.githubusercontent.com/84740311/220724990-3e60cc67-269c-422f-826d-8ef6398841a1.png)


`author` `date` (remove any preposition from translations):

![Image](https://user-images.githubusercontent.com/84740311/220725078-7a82bf05-85f1-49b5-b5bf-4f74bc22b0da.png)
![Image](https://user-images.githubusercontent.com/84740311/220725077-55285a9f-3ff5-4800-8853-c3135b088200.png)
![Image](https://user-images.githubusercontent.com/84740311/220725079-a10e55a8-cedd-4440-a8f6-4d4caeb1cb60.png)
![Image](https://user-images.githubusercontent.com/84740311/220725080-9f9e9db9-6e81-4452-ac68-394c4c83f404.png)


`author` posted on `date` (translation given by @una-tapa ):

![Image](https://user-images.githubusercontent.com/84740311/220725109-25caddc2-f482-44b2-b87a-05f865e0f2ff.png)
![Image](https://user-images.githubusercontent.com/84740311/220725110-4e64cb62-85d4-4bc0-980f-0dd14fe76a16.png)
