### ISSUE TITLE
External blog posts are not being tagged

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2957]
Blog posts that are hosted on external sites are not being properly tagged via the blog_tags.json file.  They also do not show up when searching by tag on the website.  These posts still show up in our feeds that are built with Liquid variables.

**Comment by kinueng** [comment]
@natalie-bernhard Can you add an example of the problem to the issue description? Thanks

**Comment by natalie-bernhard** [comment]
![Image](https://user-images.githubusercontent.com/84740311/211583422-3d0cf7d8-e5b6-4759-977e-079cf37137b9.png)

The blog post in the center does not have any tags, but the post title is under three different tags in blog_tags.json ("develop-user-feature"). This should be tagged with Maven, community, and developer experience.
