### ISSUE TITLE
Blog XML feeds for different available languages

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#2958]
Would it be helpful at all to users in different countries to have RSS/XML feeds available that syndicate all blogs from a certain language?

**Comment by kinueng** [comment]
We do have unique RSS feeds for each of the languages. This was free from the i18n jekyll plugin, which essentially builds the website multiple times.

Examples
- https://openliberty.io/ja/feed.xml
- https://openliberty.io/zh-Hans/feed.xml
