### ISSUE TITLE
Enable OL Starter on QA sites

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#2975]
Enable the Open Liberty Starter for the Code Engine QA sites.

A few sites I noticed having problems with the OL Starter due to CORS network failures
- https://draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/start/
- https://ui-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/start/

**Comment by amyreit** [comment]
Both of these links seem to be working so closing for now.
