### ISSUE TITLE
The link to open issues on https://openliberty.io/support/ opens an issue on the website repo and not the open-liberty repo.

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#3019]
The link to open issues on https://openliberty.io/support/ opens an issue on the website repo and not the open-liberty repo.

![Image](https://user-images.githubusercontent.com/6392944/217040387-768c281a-c16a-4546-8bd1-a186a6ccbbfd.png)

takes you to https://github.com/OpenLiberty/openliberty.io/issues

_Originally posted by @steven1046 in https://github.com/OpenLiberty/openliberty.io/issues/1850#issuecomment-1419446149_

**Comment by kinueng** [comment]
Closed as dupe of #3017
