### ISSUE TITLE
Fix clicking area for Featured Tags and Posts in other languages lists

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3031]
When the blogs page is in tablet size, the clicking area for the featured tags or other languages is not accurate and easy to miss.  This is due to interference from the image in the blogs header.

**Comment by kinueng** [comment]
![Image](https://user-images.githubusercontent.com/31117513/218186402-acb07785-37a9-400a-bb63-670e1eb45286.png)
