### ISSUE TITLE
External links in blog posts should be orange

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3041]
External links in blog posts should match the styling of other external links on the website (orange)

**Comment by kinueng** [comment]
# Goal
When there are links on openliberty.io that have an `href` that does not start with `https://openliberty.io`, that link is considered an "external" link. External links are suppose to be styled as orange per the stylebook for the website.

---

Examples of orange links can be found on https://openliberty.io/blog/.

Example of a link that needs to be fixed:
https://openliberty.io/blog/2022/08/24/open-liberty-with-cargo-tracker.html#try-out-cargo-tracker-with-open-liberty

![Image](https://user-images.githubusercontent.com/31117513/222483145-7aa3c359-2a61-4bb9-9b7c-9376717592bb.png)

**Comment by kinueng** [comment]
The best way to fix this issue is to add the class for external links during build time. One good place to put this code is like how `_blank` and other HTML attributes are added to links via the custom Ruby gem https://github.com/OpenLiberty/openliberty.io/blob/prod/gems/ol-target-blank/lib/ol-target-blank.rb

**Comment by natalie-bernhard** [comment]
@SteveSamJacob for this issue, focus on doing this in post.js rather than Ruby code as mentioned above; using Jquery and JS, assign the orange link class to external links (AKA any link that does not start with openliberty.io/...).  This info about getting the window URL should help: https://www.w3schools.com/js/js_window_location.asp
