### ISSUE TITLE
Fix specific code blocks in guides

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3049]
Tracking bug fix for rendering of specific guide code blocks with accessibility code
Example: https://openliberty.io/guides/rest-client-reactjs.html#creating-the-default-page
<img width="1177" alt="Screenshot 2023-02-23 at 11 55 22 AM" src="https://user-images.githubusercontent.com/84740311/220989999-4c070e27-dd92-4f5f-954c-f5eb97b718c8.png">

**Comment by kinueng** [comment]
This issue is related to https://github.com/OpenLiberty/openliberty.io/issues/2885
