### ISSUE TITLE
List continuation renders differently (smaller) from the principal text

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#3076]
https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/#list-continuation

For example, the unordered list used for bugs in release blogs uses list continuation:
![image](https://user-images.githubusercontent.com/3076261/223471107-7dd6330b-6218-41a5-99c9-9e639ffb0016.png)

Note that the GH preview renders it normally: https://github.com/OpenLiberty/blogs/blob/prod/posts/2023-02-07-23.0.0.1.adoc

**Comment by kinueng** [comment]
Post in question
https://openliberty.io/blog/2023/02/07/23.0.0.1.html

CSS selector in question
`div.sectionbody div.ulist>ul>li p`

font-size should be 16px, not 14px.

**Comment by steven1046** [comment]
File in question: post.scss
