### ISSUE TITLE
Create translation template on GH for blogs repo

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3082]
Create a Github template for the blogs repo that would include the [translation checklist](https://github.com/OpenLiberty/blogs/wiki/i18n#blog-review-checklist) for reviewers and authors to reference.

Need to decide if this should be a PR template or issue template

**Comment by kinueng** [comment]
GitHub templates are difficult to update as the changes to the template has to be merged into the default branch of the repo. The default branch is often the production branch. Let's rely on the GitHub wiki for now as it is easier to make changes to the instructions.
