### ISSUE TITLE
Make clicking PEM download show the file in a new tab

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3095]
![Image](https://user-images.githubusercontent.com/31117513/225654145-37c0b770-ad9e-44b6-850c-4b1205bd377f.png)

Clicking this button leads to 

![Image](https://user-images.githubusercontent.com/31117513/225654262-f08d64f7-da86-4a4a-a8cd-3ee5b9741307.png)

---
We want this click to just download the file.

**Comment by dmuelle** [comment]
opened https://github.com/OpenLiberty/docs/issues/6781 to track doc updates once this is implemented

**Comment by zakhaev26** [comment]
I think setting the response-header to ```Content-Disposition``` whenever client clicks the button would help stopping the redirects and straight up download the .pem file

**Comment by navaneethsnair1** [comment]
- This issue comes up in chrome only. It works fine in safari.
- `Content-Disposition` was not able to be incorporated since it requires the exact click event to be obtained. It was not possible when tried.
-

**Comment by natalie-bernhard** [comment]
The work required to force a download does not seem to justify the improvement.  However, I will use this issue to make the link open in a new tab instead of opening in the same tab and taking people away from the website.  This will still improve the UX with significantly less time cost.

**Comment by natalie-bernhard** [comment]
Closed via #3452
