### ISSUE TITLE
Update the descriptions for the Jakarta packages to state that it includes MicroProfile code

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3096]
Item 2:
Need to follow up on whether MP can be excluded from Jakarta packages. My confusion is most likely due to my lack of understanding on how MP 6 is packaged.

**Comment by kinueng** [comment]
Question: Does Jakarta include MP? If yes, we need to manage expectations on what you get when MP is included in Jakarta. Is this the first time Jakarta includes MP related assets?

Edit: This is not the first time Jakarta includes MicroProfile.

**Comment by kinueng** [comment]
@natalie-bernhard is evaluating some designs to add a tooltip that can help users understand certain packages include things from other packages. For example, Jakarta includes MicroProfile stuff.

**Comment by natalie-bernhard** [comment]
Closed via #3131
