### ISSUE TITLE
Support page - Gitter link returns 404 page

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3099]
<img width="281" alt="image" src="https://user-images.githubusercontent.com/31117513/226974889-3c134b5a-9fe5-44b5-8d97-d95ae1aafb50.png">
https://gitter.im/OpenLiberty/

**Comment by natalie-bernhard** [comment]
https://blog.gitter.im/2023/02/13/gitter-has-fully-migrated-to-matrix/
