### ISSUE TITLE
Support for role="no_copy" for guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#31]
We have all blocks or snippets in the guides showing the "Copy button" today.  This shouldn't be the case since not all blocks or snippets are meant to be copied by the users.

We have gone through the guides to tag those that don't need a "Copy button" with _role="no_copy"_.  We need the website to support it.

**Comment by gindik** [comment]
Work is complete and has been reviewed in the pre-production environment. https://github.com/OpenLiberty/openliberty.io/pull/32 will be used to make it live.
