### ISSUE TITLE
Only show Web Profile 10 download package when possible

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3109]
If Web Profile 10 is available for download from DHE, make that the only visible download package choice for Web Profile.

Filename for WP10 on DHE will be 
`openliberty-webProfile10-<release version>.zip`

**Comment by natalie-bernhard** [comment]
Existing logic for JEE10 and MP6 is here: https://github.com/OpenLiberty/openliberty.io/blob/prod/src/main/content/_assets/js/builds.js#L238-L254

**Comment by kinueng** [comment]
Plan to comment out defensive logic that is not required and monitor if we need to bring it back in the near future.

**Comment by kinueng** [comment]
Close this issue as not needed as DHE will only have the necessary files for the releases. No need to have extra web logic to hide files.
