### ISSUE TITLE
Easy submission of new/updated Guide content

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/openliberty.io#311]
Customer is drawn to our [Open Liberty Guides page](https://openliberty.io/guides/).  They love the content.  But, then they search for a guide on "bean validation" and nothing shows up.  They really wanted a guide on Bean Validation.  Instead of directing them to open an issue, could we instead provide a simple "Can't find what you are looking for?" prompt and allow them to provide a short description of the "missing" guide?  We could collect this information and periodically create issues on behalf of these customer requests.

I'm just thinking of making the user experience easier.  We've already somehow drawn these users to Open Liberty.  Can we make it easier for them to request some missing Guides instead of creating an Issue?

**Comment by yeekangc** [comment]
@cajaygle @megmulsy, what do you think?  This is a good idea to consider.

**Comment by steven1046** [comment]
Keeping this in new issues until there is discussion on the idea on the biweekly website meeting.

**Comment by kinueng** [comment]
We are making a small change that will work towards this issue.  When someone searches for a guide and no results are found, we show a GitHub link where someone can open a new issue.

![image](https://user-images.githubusercontent.com/31117513/44935330-def0e000-ad35-11e8-909a-5650160fc472.png)

My thoughts are that we can do more than above, but at least this is a small step forward

**Comment by megmulsy** [comment]
Hey all - the link shown here will go to the priority list:  https://github.com/OpenLiberty/guides-common/projects/1

I think that having users create an issue makes the user part of the process. They're making a request in the same way that everyone else working on OL does. Having us make the issues creates more of an ‘us vs. them’ dynamic which doesn't feel very true to the spirit of Open Source. 

Plus, linking them to the priority list gives them a view of what is to come. There might be an issue that covers a similar topic to what they want, just classified slightly differently

**Comment by megmulsy** [comment]
Plus, Michal has mentioned that we will be keeping a list of the searches inputted here - that will also be a super easy way to keep track of what users are looking for, and ensure that we're meeting their needs
