### ISSUE TITLE
Clean up DNS records specific to Cloud Foundry - Deadline June 1

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3110]
Now that `*openliberty.io` domains are off Cloud Foundry, we need to also delete the DNS records associated with routing traffic to Cloud Foundry.

**Comment by kinueng** [comment]
Be mindful what happens to undefined subdomains once `CNAME *` is removed. Look to see if we need to have that traffic be redirected to openliberty.io

**Comment by natalie-bernhard** [comment]
(this is more specific to azure) 
https://learn.microsoft.com/en-us/azure/security/fundamentals/subdomain-takeover

**Comment by kinueng** [comment]
This needs to be completed before June 1

**Comment by natalie-bernhard** [comment]
How do we get CE to catch all subdomains (aka `CNAME *`)? Must figure this out before deleting `CNAME *` record in CloudFoundry.  Other records can be deleted as they will reroute to `*`.

**Comment by natalie-bernhard** [comment]
How to handle undefined subdomains (multiple levels deep), look into how to redirect bad traffic rather than accept it. Also look into edge functions.

**Comment by natalie-bernhard** [comment]
Edge functions were used to correct redirects.  Multi-level subdomains require a cert for each level, and our current certs only cover 1st level subdomains (aka *.openliberty.io)
