### ISSUE TITLE
Confusing Open Liberty Starter UX when using choice `None`

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3117]
When users choose `None` for MicroProfile or EE version, the `None` chosen by the user can be overwritten. It is frustrating for the UI to change the `None` choice when it is a supported choice.

Steps to recreate
1. Go to https://openliberty.io/start/
1. Pick `None` for MicroProfile Version
1. Pick `8.0` for EE Version
1. Observe MicroProfile Version is changed from `None` to `4.1`
1. Pick `None` for MicroProfile Version to prove the code allows for EE 8.0 be paired with None MicroProfile Version

**Comment by amyreit** [comment]
New design documented in the pull request - [https://github.com/OpenLiberty/openliberty.io/pull/3183](url)
