### ISSUE TITLE
HTML Minification

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3118]
This most impactful place to minify is the HTML pages generated by Antora. At this moment, we do compress those files to be sent over the network.

Compression is already happening on HTML files from Antora here https://github.com/OpenLiberty/openliberty.io/blob/prod/scripts/build/gzip.sh

Could extend this to minify HTML first then compress.

**Comment by steven1046** [comment]
I found one way to minify Antora pages:

`gem install asciidoctor-html-minifier`

Create a file called minify.rb in your Antora project directory with the following contents:
```
require 'asciidoctor'
require 'asciidoctor-html-minifier'

Asciidoctor::Extensions.register do
  postprocessor do
    process do |document, output|
      output = Asciidoctor::HTMLMinifier.minify(output)
      output
    end
  end
end
```

add this to the playbook:
```
extensions:
  - ./minify.rb
```

The asciidoctor-html-minifier gem will be used to minify the HTML output of Asciidoctor during the build process, resulting in smaller page sizes and faster load times.

**Comment by kinueng** [comment]
Could not find the gem `asciidoctor-html-minifier`, maybe this gem was renamed?

**Comment by steven1046** [comment]
The above gem doesn't seem to exist, ignore it
