### ISSUE TITLE
The command and output boxes are not indented in mobile mode

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#3141]
When visit a guide by mobile or resize the browser window to very small, the guide displays as following, but the command and output boxes are not indented.
<img width="455" alt="Screenshot 2023-04-13 at 9 20 39 AM" src="https://user-images.githubusercontent.com/29576299/231771611-5dd99d68-0838-4c1b-9e93-77a8c089d808.png">

<img width="621" alt="Screenshot 2023-04-13 at 9 13 17 AM" src="https://user-images.githubusercontent.com/29576299/231770397-a174c2ea-00d0-441b-b5ec-e2ced342e107.png">

**Comment by natalie-bernhard** [comment]
This will require a change in the width and margins of the `.code_block_wrapper` within the `guides-common.scss` file.  You will likely have to use a `@media` selector to ensure this is only changing the CSS for mobile view.  Double check that the copy_to_clipboard button loads in the correct place.
