### ISSUE TITLE
Upgrade container images to latest Open Liberty version

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3145]
Upgrade Dockerfiles for both openliberty.io and start.openliberty.io repositories

**Comment by natalie-bernhard** [comment]
Useful reference for this upgrade being done before: https://github.com/OpenLiberty/openliberty.io/issues/3033

**Comment by amyreit** [comment]
openliberty.io repository is ready to be pushed to prod as of 6/30/23

**Comment by navaneethsunil38** [comment]
Fixed via #3254

**Comment by navaneethsunil38** [comment]
Fixed via #3254

**Comment by amyreit** [comment]
Still need to add change the levels in the starter.openliberty.io repo

**Comment by amyreit** [comment]
Natalie finished with pr 201 in starter.openliberyt.io
