### ISSUE TITLE
Remove dead code from builds.js

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3146]
Ended up not needing all this extra logic in the code. Let's delete it
https://github.com/OpenLiberty/openliberty.io/commit/0d02b885e32d507a6af1548c53e012e20d202df7

**Comment by steven1046** [comment]
Delete all of the code in the commit above

**Comment by kinueng** [comment]
Avoid reverting commits as these sets of changes were many layers and complicated :)

**Comment by natalie-bernhard** [comment]
Thank you @punitkr03 for your contribution!
