### ISSUE TITLE
Make javadoc classes and packages use the same URL schema when copying their link

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#316]
Currently in the MicroProfile 1.3 javadoc if you copy the link of a package you would get https://openliberty.io/javadocs/microprofile-1.3-javadoc/javax/annotation/package-frame.html when the URL is actually https://openliberty.io/docs/ref/microprofile/1.3/#package=javax/annotation/package-frame.html&class=overview-summary.html so there is an inconsistency. If the user goes to the former URL then they would not see the Open Liberty header.

**Comment by mbroz2** [comment]
Need to also make sure that the 'bad' urls don't get exposed to web crawlers.

**Comment by natalie-bernhard** [comment]
This was fixed by the solution for Issue #1832
