### ISSUE TITLE
Update iguides-common files to accommodate deprecated iguides

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3166]
Extend logic from #3028 to the [iguides-common](https://github.com/OpenLiberty/iguides-common) repo

**Comment by steven1046** [comment]
@SteveSamJacob19 confirmed that the iguides just need the tag added in guides-common repo and the deprecation message shows up on the iguide. Is this issue needed still?

**Comment by steven1046** [comment]
This issue is to also track when the interactive guides are deprecated.

**Comment by steven1046** [comment]
Closing this as @SteveSamJacob19 saw that interactive guides can already be deprecated
