### ISSUE TITLE
Remove PR items from GH Projects board

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3172]
Remove pull requests from the kanban board to reduce clutter

**Comment by kinueng** [comment]
This can be done via the settings of the Project
<img width="405" alt="image" src="https://github.com/OpenLiberty/openliberty.io/assets/31117513/b578a48a-7bbe-47db-97f2-6c1a16d94841">

**Comment by natalie-bernhard** [comment]
Sorry, should have been more specific, I meant the separate items on the board that look the same as an issue but are actually PRs

**Comment by natalie-bernhard** [comment]
Closed via #3214
