### ISSUE TITLE
Syndicated blog posts: Orange text inconsistent bold styling

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3180]
Some syndicated blog posts have bold orange text while others do not.
![image](https://github.com/OpenLiberty/openliberty.io/assets/31117513/fd9314bb-9872-486a-859b-a0713ebbc9b7)
![image](https://github.com/OpenLiberty/openliberty.io/assets/31117513/9adb4bd8-6629-4b02-8174-ed68ddad939d)

**Comment by natalie-bernhard** [comment]
This is the intended look as bolding is not used for blog posts under `Latest Posts`.  However, I will open another issue to remedy the missing hover behavior for entries under `Latest Posts`.
