### ISSUE TITLE
Apply correct hover behavior to orange links in Latest Posts

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3181]
The first three blog post entries on the blog page under `Latest Posts` are missing the expected hover behavior of darkening the orange link text as well as the blog title.  As far as I know, it is only this specific case that is missing the expected hover behavior, and the behavior is implemented correctly elsewhere.

Apply similar fix as #2550

**Comment by martinyis** [comment]
Hey, can I work on this issue?

**Comment by natalie-bernhard** [comment]
Yes, as we are open source, we allow outside contributions.  Please make sure to follow these directions for contributions: https://github.com/OpenLiberty/openliberty.io/wiki/How-to-contribute. Along with these directions, the wiki on this repository has additional helpful information as well.

**Comment by natalie-bernhard** [comment]
Currently setting myself as assignee to watch this issue.  When the review process begins, I'll add @martinyis as an assignee as well.
