### ISSUE TITLE
The line under the tabs in /start is wider then its parent elements

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#3263]
For example:
![image](https://github.com/OpenLiberty/openliberty.io/assets/3076261/906a8ba7-6c61-491e-8996-a670cb1e4f7e)
 
This seems to stem from a -15px margin set on the tabs; using 0px seems to fix the issue.

**Comment by natalie-bernhard** [comment]
Closed by #3318
