### ISSUE TITLE
API/SPI no version - should list the versions that it exists

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/openliberty.io#3284]
API/SPI started going into 23.0.0.6, when changing the ver to previous version it should list the version that api/spi is in

For example if you go to 23.0.0.6 for api/spi 
https://openliberty.io/docs/latest/reference/javadoc/api/restConnector-2.0.com.ibm.websphere.filetransfer.html?path=23.0.0.6/com.ibm.websphere.appserver.api.restConnector_1.3-javadoc/com/ibm/websphere/filetransfer/package-summary.html

then change version to 23.0.0.5 it should list the 23.0.0.6 version in this page

![image.png](https://images.zenhubusercontent.com/59dbe44ab0222d5de47af1b0/a3f13df3-6edd-465f-a66c-fb6b549294ef)

**Comment by aknguyen7** [comment]
code that need to look at is 09-noversion.js to handle the correct link to api/spi javadoc
![image](https://github.com/OpenLiberty/openliberty.io/assets/30509453/1aedcfdd-8731-4a9e-9b64-1bf3421d95c8)

**Comment by steven1046** [comment]
Fixed on production.
