### ISSUE TITLE
API/SPI: update CSP to allow links out to oracle's javadocs for Java SE classes/methods

### ISSUE THREAD

**Issue by aknguyen7** [OpenLiberty/openliberty.io#3289]
Click on links to oracle javadocs from api/spi is prevented/blocked due to CSP

![image](https://github.com/OpenLiberty/openliberty.io/assets/30509453/e154c884-dbe2-4d7c-ba42-9f6f92715e52)

**Comment by SteveSamJacob19** [comment]
This issue has been fixed with the integration of frameless javadocs
