### ISSUE TITLE
Docs page redesign

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#331]
Redesign the /docs page according to designs here: https://ibm.ent.box.com/file/293256639198
![image](https://user-images.githubusercontent.com/6392944/40734313-ab8a176c-63fd-11e8-9bca-c17f0568084b.png)

---
### End Goal
**Docs and Guides Table of contents - stage 1 - MAY 2018 UPDATE**
As the content team gives us more to work with, we will "beef up" and iterate on this page. 
Redlines: https://ibm.box.com/s/o9ks9uo90n4dq8qfjny1v61qdsqaetk0
(for some reason, it exported a lot of 'headers' but the main item in these redlines works, it's just at the bottom of the list) 
PNG: https://ibm.box.com/s/t8fk3g8ys3gzmw6v9mfppp30m9jjr4d9
Assets/icons 

- 1x icons: https://ibm.box.com/s/36mntgwcw9lmhn52v0nxuqole1qvdnwr
- 2x icons (for retina - pls use): https://ibm.box.com/s/ajqc8ghdfckpdf5i21s9f0kdipass0zx

**Comment by kinueng** [comment]
Hi @wexantis,

- [ ] Mobile view:  More spacing below the title to be consistent with the other pages and the original Doc page.  Example of the current Doc page spacing
![image](https://user-images.githubusercontent.com/31117513/41118336-3eaa415e-6a55-11e8-8006-8076940d31cc.png)
