### ISSUE TITLE
Remove Twitter widget from homepage

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/openliberty.io#3322]
Most likely due to changes on the twitter side, the widget on the homepage is no longer pulling content and shows a "Nothing to see here" message, despite the fact that we have Tweets from the past week. Rather than fix it, we can remove it- per @NottyCode.
   
![2023-08-02_08-42-51](https://github.com/OpenLiberty/openliberty.io/assets/48686014/0304c214-c71a-4381-b84e-84800ecc21cf)

**Comment by natalie-bernhard** [comment]
We have decided to replace it with the latest release blog post for now

**Comment by natalie-bernhard** [comment]
Goal: fully remove the Twitter widget from the website and replace that section with the latest release blog post.  This will also require code to make sure that the latest blog post and the latest release blog post are not the same post.  If they are, the next most recent blog post should be selected.
