### ISSUE TITLE
The Add to an existing application section in the Get Started page is out-dated

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#3329]
What is the purpose of the [Add to an existing application](https://openliberty.io/start/#getOL) section?

Nowadays, use LMP to get the OL for development.

If this section want users to know how to specify the OL version for LMP, the Maven and Gradle dependency are out-dated.

If this section is for other purpose, suggest to make it clear.

Also this section points users to Maven and Gradle guides. Both guides do not have `dependency` for OL.

**Comment by cherylking** [comment]
I think it is better for this doc to just point to the plugins and the guides and not suggest that they add the dependency for the Liberty runtime to their build file, as that is not how it is usually done. If it is for the end user to know the coordinates, then document it that way. These are the coordinates that can be used in the Liberty Maven/Gradle plugin configuration to use the Liberty runtime.

**Comment by cherylking** [comment]
Here are good starting points for both Maven and Gradle plugins.

Maven: 
https://github.com/OpenLiberty/ci.maven#configuration first, then https://github.com/OpenLiberty/ci.maven#liberty-installation-configuration.

Gradle: 
https://github.com/OpenLiberty/ci.gradle#adding-the-plugin-to-the-build-script and https://github.com/OpenLiberty/ci.gradle#liberty-installation-configuration.

**Comment by steven1046** [comment]
Note: Long thread in slack with more information

**Comment by cherylking** [comment]
Liberty Maven plugin configuration - no need to configure the Liberty runtime as it gets the latest `openliberty-kernel` release automatically:

```
<plugin>
    <groupId>io.openliberty.tools</groupId>
    <artifactId>liberty-maven-plugin</artifactId>
    <version>3.8.2</version>
</plugin>
```

The `3.8.2` version should be replaced with the latest version found in Maven Central [here](https://search.maven.org/artifact/io.openliberty.tools/liberty-maven-plugin).

**Comment by cherylking** [comment]
Liberty Gradle plugin configuration - no need to configure the Liberty runtime as it gets the latest `openliberty-kernel` release automatically:

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.openliberty.tools:liberty-gradle-plugin:3.6.2'
    }
}
```

The plugin also needs to be applied in the build file in order to be utilized.
```
apply plugin: 'liberty'
```

The `3.6.2` version should be replaced with the latest version found in Maven Central [here](https://search.maven.org/artifact/io.openliberty.tools/liberty-gradle-plugin).

**Comment by mbroz2** [comment]
The blog post release templates have been updated to reflect the above.

**Comment by natalie-bernhard** [comment]
@dmuelle

**Comment by steven1046** [comment]
Existing design: https://staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/start/#getOL

**Comment by dmuelle** [comment]
we could break then out into 2 separate calls to action for each tool

- Ready to get started using Maven with Open Liberty? Try the [Building a web application with Maven] guide.
- Looking for information about Open Liberty Maven configuration, goals, and more? Check out the [Liberty Maven plugin documentation on GitHub].
---
- Ready to get started using Gradle with Open Liberty? Try the [Building a web application with Gradle] guide.
- Looking for information about Open Liberty Gradle configuration, tasks, and more? Check out the [Liberty Gradle plugin documentation on GitHub].

**Comment by dmuelle** [comment]
We might want to add some kind of intro statement for the plugin just under the **Add to an existing application** header. As it it now, we have this sentence between the two examples:

> The plugin also needs to be applied in the build file in order to be utilized.

but we haven't said anything about a plugin or introduced it in any way. Something like

> Open Liberty provides build plugins for Maven and Gradle that simplify the installation and operational control of  the Liberty runtime and servers. 

and i think this sentence could be improved

The plugin also needs to be applied in the build file in order to be utilized.
--->
You must also apply the plugin in the build file before you can use it:

**Comment by natalie-bernhard** [comment]
Opened Issue #3449 to improve the wording as the code snippets have now been updated. Closing this issue as complete.
