### ISSUE TITLE
Add the latest release blog post to the bottom of the home page.

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#3338]
This comes after #3322, removal of the Twitter widget.
Replace the previous Twitter section with the latest release blog post. This will also require code to make sure that the latest blog post and the latest release blog post are not the same post. If they are, the next most recent blog post should be selected. 

The most release blog post and non-release blog post should be displayed side by side.

**Comment by steven1046** [comment]
On https://staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/, the 2 blogs aren't the same height and it would look better if we specified a minimum height for those cards so they are consistent

**Comment by natalie-bernhard** [comment]
Closed via #3452
