### ISSUE TITLE
Patch to allow renabling documentation for older Open Liberty versions

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3344]
The website had an issue with the volume of files being gather during build time. The quick fix was to temporary remove documentation for the oldest Open Liberty versions on openliberty.io using https://github.com/OpenLiberty/docs-playbook/pull/307

This problem should be resolved now with https://github.com/OpenLiberty/openliberty.io/pull/3339.

This issue is to track removing the temporary fix and republish the oldest Open Liberty documentation to openliberty.io

**Comment by steven1046** [comment]
The fix is to add the oldest doc version back into the docs-playbook repo, see https://github.com/OpenLiberty/docs-playbook/pull/307 for which doc versions were removed, but make sure not to have more than 24 versions total.

**Comment by natalie-bernhard** [comment]
Closed via #3439
