### ISSUE TITLE
Update plugin versions under `Add to an existing application` programatically

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3346]
Use an API request to get the latest maven/gradle plugin versions for the `Add to an existing application` section on the start page.

**Comment by steven1046** [comment]
This will have to happen on the backend due to rate limiting by Github.

**Comment by natalie-bernhard** [comment]
Maven plugin versions API call: https://search.maven.org/solrsearch/select?q=g:io.openliberty.tools+AND+a:liberty-maven-plugin&core=gav&rows=20&wt=json

**Comment by natalie-bernhard** [comment]
Gradle plugin versions API call: https://search.maven.org/solrsearch/select?q=g:io.openliberty.tools+AND+a:liberty-gradle-plugin&core=gav&rows=20&wt=json

**Comment by natalie-bernhard** [comment]
We cannot make an API request to the above links due to CORS issues.  Try to see if there is another source for us to pull the version numbers from.
