### ISSUE TITLE
Add download links for 2 new zip runtime packages in 18.0.0.2

### ISSUE THREAD

**Issue by patricktiu** [OpenLiberty/openliberty.io#336]
We will have 2 additional openliberty runtime zip archive package for download in 18.0.0.2, which need to have additional buttons or links in the downloads page (https://openliberty.io/downloads/).  

- openliberty-webProfile8-18.0.0.2.zip
   - openliberty runtime with Java EE 8 Web Profile features and as well as some other features such as monitoring, LDAP Registry and Micro Profile 1.3. 
- openliberty-javaee8-18.0.0.2.zip.
   - openliberty runtime with Java EE 8 Full Platform features and as well as some other features such as monitoring, LDAP Registry and Micro Profile 1.3.

We also need to indicate the current button in the downloads page or the home page is for downloading the openliberty runtime with all features.

**Comment by kinueng** [comment]
If we are enhancing this Downloads page, we should also incorporate a way to indicate which build is a Release candidate (RC) documented in Issue #89 Changes needed for "RC" driver publishing.

**Comment by cbridgha** [comment]
Also need to ensure we change the info.json file format on DHE to allow these additional packages - probably an additional "package" field.  for example: 

{
    "test_passed": "7190",
    "total_tests": "7190",
    "tests_log": "open-liberty.unitTest.results.zip",
    "build_log": "gradle.log",
    "package": "javaee8",
    "driver_location": "openliberty-javaee8-18.0.0.2.zip",
    "version": "18.0.0.2"
}

**Comment by cajaygle** [comment]
Capturing discussion from June 7 meeting:
* Download button on homepage should continue to download full zip
* Download button at top of Downloads page should continue to download full zip
* In the Releases section, each row should have downloads for Full Zip, JavaEE8, and Web Profile.  In the future there may be more options

**Comment by cbridgha** [comment]
We should start planning for a minimum requirements before 18.0.0.2 eGA's on June 29th

The Releases section @cajaygle mentions above is all we should need  - can we at least signoff on the design for this?  I have confirmed we will only have the three zips Jay mentions.

After we confirm the design, we'll need to change the endpoint json payload schema coming from the DHE downloads area.

**Comment by steven1046** [comment]
Update: I have worked on the release downloads page table and have added 2 more columns with the 2 new downloads.
