### ISSUE TITLE
Blog post headings (H3) are not very distinctive

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#339]
In the following draft blog post, the lines marked with red blotches on the left-margin are H3 headers but they don't look very distinctive and aren't easy to spot when skimming down the page ("What's in MicroProfile 1.3?" is an H2):

![image](https://user-images.githubusercontent.com/3322532/41107873-20420402-6a6b-11e8-8faf-4682d7309e1f.png)

Is there something we can do with the design to make them more distinctive? (I may have raised a similar issue in the past but I can't find it anywhere - sorry if this is a dupe.)

**Comment by TreeHanh** [comment]
We've addressed the headings in the new design. 

New design can be seen here: https://github.com/OpenLiberty/openliberty.io/issues/458#issuecomment-463308797
