### ISSUE TITLE
Make sure all of the content repos have an EPLv2 license

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#3400]
Ensure that each repo has a contributing MD like https://github.com/OpenLiberty/openliberty.io/blob/prod/CONTRIBUTING.md and a license like https://github.com/OpenLiberty/openliberty.io/blob/prod/LICENSE.
- [ ] https://github.com/OpenLiberty/docs-playbook
- [ ] https://github.com/OpenLiberty/docs
- [ ] https://github.com/OpenLiberty/docs-javadoc
- [ ] https://github.com/OpenLiberty/docs-generated
- [ ] https://github.com/OpenLiberty/guides-common
- [ ] https://github.com/OpenLiberty/iguides-common
- [ ] https://github.com/OpenLiberty/sample-getting-started
- [ ] https://github.com/OpenLiberty/certifications
- [ ] https://github.com/OpenLiberty/start.openliberty.io

**Comment by SteveSamJacob19** [comment]
Only Iguides-common and certifications repo left to be reviewed and merged
