### ISSUE TITLE
New homepage design

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#342]
Demo of the new home page design:
https://pages.github.ibm.com/was-design/OpenLiberty_Homepage/OLHompage_Revamp.html

Redlines:
(Older copy) ~~https://ibm.box.com/s/71569ald8apgs5l57rc4x4m9fp2xzwg8~~
(Old copy) ~~https://ibm.box.com/s/n1pclw4aqulpqjrq5vm7pwwecohxyiin~~
(Newest copy) https://ibm.ent.box.com/folder/61448618826
(Even newer copy) See April 4th comment.

Minor updates to come but the flow will be the same.

**Comment by kinueng** [comment]
Hello @megmulsy,
When we have a finalized redesign, we can use this issue to implement the changes.

**Comment by steven1046** [comment]
The design is still evolving, and some parts of the page will have intermediate designs until the final ones are flushed out.

**Comment by steven1046** [comment]
https://github.com/OpenLiberty/openliberty.io/tree/Homepage_Revamp

**Comment by mdenby** [comment]
Here is a jpg of the new homepage design. I can post the redlines shortly.
 
![Homepage](https://user-images.githubusercontent.com/26823018/55577878-95f57580-56e2-11e9-8437-620922919eeb.jpg)

**Comment by mbroz2** [comment]
@ellenwyllie For this issue, update everything on the home but do not add the "Open Liberty News" section.  That section will be added under #184 .

**Comment by mbroz2** [comment]
Blockers that need to be addressed before this issue can move to development.
1) Github contributions 
2) Wording/Content (currently no mention of key technologies)
3) Featured blogs (blocker for #184 not this issue)

**Comment by mdenby** [comment]
This is the newest wireframe. Going to update the visual design and add logos of open source projects that we integrate with.
 
![OL_Home_Wireframe](https://user-images.githubusercontent.com/26823018/58270213-3bc67780-7d57-11e9-8137-98be72388d91.jpg)

**Comment by mdenby** [comment]
![Homepage_Full_Scale Copy 16](https://user-images.githubusercontent.com/26823018/61306965-70850700-a7bb-11e9-87db-c7f85fb51f93.jpg)

**Comment by mdenby** [comment]
Here is the latest updated homepage. I know we need to update the two performance graphs, but I think this can begin being built in dev. I've kept the 'Download' at the top. I've opened a new issue for the 'Getting Started' page. 

Also, here are the redlines. Please let me know if you need anything more with them.
[OL_Home 0725.zip](https://github.com/OpenLiberty/openliberty.io/files/3432150/OL_Home.0725.zip)

![OL Home](https://user-images.githubusercontent.com/26823018/61885399-c64c6400-aecb-11e9-86ee-98d5fa6db1ad.jpg)

**Comment by mdenby** [comment]
@ellenwyllie Just adding notes from today here:

1. For the twitter section--show the three most recent tweets, including retweets
2. For the contributor section--rotate/update the contributor images on page refresh. The image should link to that person's github.
3. For the top section 'Learn More' buttons:

Develop Cloud-native Java micorservices should link here: https://openliberty.io/docs/ref/general/#microprofile.html

Deploy in containers to any cloud: should perform a search and return any guides with the tag 'Cloud'

Monitor microservices in the cloud: Laura is writing a new doc/guide on Promethus that we will link to
