### ISSUE TITLE
Address accessibility errors on the /start page

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#3425]
There are 4 errors when you scan with the latest ruleset.
IBM Equal Access Accessibility Checker (Extension available for [Chrome](https://chrome.google.com/webstore/detail/ibm-equal-access-accessib/lkcagbfjnkomcinoddgooolagloogehp) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/accessibility-checker/))

**Comment by natalie-bernhard** [comment]
Closed via #3452
