### ISSUE TITLE
Add redirect text to README.adoc and hide it in the guide on openliberty.io

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#346]
Some users arrive at README.adoc on github and do not know that they should instead go to openliberty.io to view the guide.  We want a statement at the top of the README.adoc that tells them that they should instead consume the guide on openliberty.io.  This statement needs to be excluded in the actual guide on openliberty.io.

**Comment by steven1046** [comment]
If you specify this in the guide's asciidoc:
:repo-description: Visit the https://openliberty.io/guides/{projectid}.html[website] for the rendered version of the guide. 
= Injecting dependencies into microservices

Learn how to use Contexts and Dependency Injection to manage and inject dependencies into microservices.

[.hidden]
{repo-description}

Asciidoc will automatically hide it on the guide on the website but it will show up in the Github README.

**Comment by steven1046** [comment]
This way, it can be done the same way for all guides and also update the template to have this format so new guides will have it as well.

**Comment by steven1046** [comment]
No code changes to the website are required for this approach.

**Comment by steven1046** [comment]
Closing this issue because no work is required in this repo.
