### ISSUE TITLE
Interactive Guides table of contents isn't fully appearing in Chrome

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#3463]
https://openliberty.io/guides/microprofile-config-intro.html
As you can see the toc is hidden somewhat on the initial load:
![image](https://github.com/OpenLiberty/openliberty.io/assets/6392944/af76907f-54fa-4372-be78-e8de4e3d3573)

**Comment by steven1046** [comment]
Try scrolling to 0 after the page is ready

**Comment by natalie-bernhard** [comment]
The new changes helped this issue but there is still a bug when the user scrolls at all on an iguide, where the TOC becomes cut off again.  Putting this back into development for the other part of this issue that needs to be addressed.

**Comment by SteveSamJacob19** [comment]
With reference to the bug mentioned by @natalie-bernhard , its actually a common bug that occurs for both static and interactive guides and occurs when the toc is longer than the window, in which case, on scrolling the guide content, a scrollbar is generated for the toc too and hence the guides is scrolled back up, the toc does not return to its original state unless it is also scrolled back up.

https://github.com/OpenLiberty/openliberty.io/assets/142385295/8399ce28-b73d-4979-9897-4fd2cf5a3cc2

**Comment by SteveSamJacob19** [comment]
As this bug is not related to this specific issue, I'm closing this issue.
