### ISSUE TITLE
Evaluate permalink for guides

### ISSUE THREAD

**Issue by gindik** [OpenLiberty/openliberty.io#35]
The permalink values in guides have been set to /guides/{projectid} where projectid is an asciidoc variable with the name of the project. As a result, the finalized location of the guide with a projectid value of test would be /guides/test.html. If instead a slash is added at the end of the permalink value, Jekyll will make the guide available at /guides/test (by generating /guides/test/index.html). Part of the evaluation should include the fact that previously linked/bookmarked URLs to the guides would be affected by this change. However, if the decision is to switch the format, the sooner the better (while the number of guides is still relatively low). If this change is carried out, in addition to changing the permalink values in the guides, line 44 in guides.html would need to be updated to remove the .html extension. If on the other it is decided not to carry out this change, the canonical link defined in the page header would need to be adjusted.

**Comment by gindik** [comment]
@NottyCode please let us know if you have a preference for the URL style for the guides.

**Comment by kinueng** [comment]
I brought this topic up to a group that included Alasdair on Nov 29th.  The feedback is that the URL looks nicer without `.html`, but we do not want to break any bookmarks.

If we want to remove `.html`, we need to implement some kind of redirect that can support both `https://openliberty.io/guides/cors.html` and `https://openliberty.io/guides/cors/` for example.

**Comment by kinueng** [comment]
@steven1046 discovered a jekyll plugin that may help us handle redirects.
https://github.com/jekyll/jekyll-redirect-from

**Comment by steven1046** [comment]
The only issue with the redirect is, that going to the initial page brings up a spinning icon on the page that says redirecting to <url> so it might not be the best user experience.

**Comment by steven1046** [comment]
According to https://github.com/jekyll/jekyll-redirect-from, we can provide a redirect template in _layouts, which sounds like we can customize the look of the redirect page but it isn't clear from the short description.

**Comment by k8vance88** [comment]
We're sticking with .html.
