### ISSUE TITLE
Provide links directly to specific versions in downloads table

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3520]
In order to reduce the page size and improve the UX, we should allow users to enter or select a version number at the top of the downloads table that would then reduce the table to only show downloads from that version/the user search criteria.

Original idea from @NottyCode

**Comment by NottyCode** [comment]
Hi, I think my thought was a little different from this. What I was wanting was to be able to have a link for the GitHub release page that goes directly to a download page listing our downloads for a particular release. So not so much adding a visible control, but just allowing linking in. I do understand there is a link and the idea from @natalie-bernhard is worth exploring too, but I wanted to capture what initiated my discussion with @natalie-bernhard.

**Comment by natalie-bernhard** [comment]
Ah, I understand now.  We should be able to add IDs to these cells in each section (highlighted in the picture below) based on the version to improve linking.  

![Image](https://github.com/OpenLiberty/openliberty.io/assets/84740311/1a002821-0bb8-466e-9c9c-56509f0b7a24)

**Comment by natalie-bernhard** [comment]
Changing title to more accurately reflect the core of the issue (Original Title: Allow users to filter downloads table by version)
