### ISSUE TITLE
Build Failure with `configure.sh` step when using Open Liberty 23.0.0.12

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#3547]
When moving the openliberty.io containers to the newest Open Liberty driver via PR (https://github.com/OpenLiberty/openliberty.io/pull/3530), the builds are failing when the application is being bundled with an Open Liberty driver. The Open Liberty Starter does not exhibit this problem, so this likely is an issue specifically to the openliberty.io container.

```
#25 [runtime 4/5] COPY --from=war --chown=1001:0 target/openliberty-website-1.0-SNAPSHOT /config/apps/openliberty.war
#25 DONE 0.5s

#26 [runtime 5/5] RUN [configure.sh](http://configure.sh/)
#26 ERROR: executor failed running [/bin/sh -c [configure.sh](http://configure.sh/)]: exit code: 1
------
 > [runtime 5/5] RUN [configure.sh](http://configure.sh/):
------
WARNING: current commit information was not captured by the build: git was not found in the system: exec: "git": executable file not found in $PATH
ERROR: failed to solve: executor failed running [/bin/sh -c [configure.sh](http://configure.sh/)]: exit code: 1
```

**Comment by natalie-bernhard** [comment]
@mbroz2

**Comment by natalie-bernhard** [comment]
Caused by lack of permissions when copying over `server.xml` in Dockerfile.  Added `chown` option to increase permissions.  Fix can be found on branch `reduce-build-files` until it is delivered, and is currently built on demo1.
