### ISSUE TITLE
Updated instructions, and now publishing the combined Liberty certificate + public key

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/openliberty.io#3563]
Currently for open liberty releases, we provide a link to the public key (*.pem) used to sign the packages published on the website.

The instructions link is here: https://openliberty.io/docs/latest/verifying-package-signatures.html

Starting with 24.0.0.1 - we will also provide the certificate + public key file (*.pem.cer) file that will allow users to verify the Certificate used, and the fact that IBM has signed these packages...

The only change that should be required here is now pointing to the above file here: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/OpenLiberty_02-13-2023.pem.cer

**Comment by natalie-bernhard** [comment]
Just to verify, we are changing the PEM link to now lead to the .PEM.CER file, correct? Or do we need to add a new, separate column for this file? @cbridgha

**Comment by cbridgha** [comment]
Yes to keep it simple - we are changing the instructions in 24001 and beyond - David M will add more detail. - The file link should change to *.CER file

**Comment by dmuelle** [comment]
suggested update to the text:

In version 22.0.0.1 and later, to verify the authenticity and integrity of an Open Liberty release package, use the provided signature file (SIG) and public key (PEM). For more information, see [Verifying Open Liberty release packages.](https://openliberty.io/docs/latest/verifying-package-signatures.html)

--->

In version 22.0.0.1 and later, to verify the authenticity and integrity of an Open Liberty release package, use the provided signature (SIG) and certificate (CER) files. For more information, see [Verifying Open Liberty release packages.](https://openliberty.io/docs/latest/verifying-package-signatures.html)


However, the linked instructions wont include details about the CER until the 24.0.0.1 doc release

**Comment by steven1046** [comment]
If we are adding the link to the .pem.cer file in 24.0.0.1 and beyond, should we keep the original instructions for 22.0.0.1 through 23.0.0.12 and also add the new instruction for 24.0.0.1 and later to use the new file?

**Comment by cbridgha** [comment]
> If we are adding the link to the .pem.cer file in 24.0.0.1 and beyond, should we keep the original instructions for 22.0.0.1 through 23.0.0.12 and also add the new instruction for 24.0.0.1 and later to use the new file?

Yep you got it - only show the *.cer file link 24.0.0.1 and beyond. - The instructions David is providing does mention the new method does work on past releases (23.0.0.1 and newer) but we shouldn't go back and change our past release links....    all should keep working, and the old pem files are still available
