### ISSUE TITLE
Jakarta EE blog aggregator feed broken by change of `jakartaee` to `jakarta-ee`

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#3624]
The `jakartaee` tag was part of the URI used by the Jakarta EE planet (aggregator) blog to automatically pull in the latest two Open Liberty blog posts to the planet.

Changing the `jakartaee` tag to `jakarta-ee` has broken the feed so our posts aren't being aggregated any more. If you CTRL-F for "liberty" on this [planet.ini file](https://github.com/jakartaee/jakartablogs.ee/blob/master/planet/planet.ini), you'll see what it's looking for. 

You can get the file updated to look for the new feed URI by following their [instructions to create a PR in GitHub](https://github.com/jakartaee/jakartablogs.ee).

**Comment by natalie-bernhard** [comment]
Unless we want to do so to be more consistent between the tag and the feed, it shouldn't be necessary to change the URI as we have custom logic that builds the feed.  @lauracowen let us know if you prefer the URI and tag name to match or if it is okay to maintain the same URI.

**Comment by lauracowen** [comment]
I don't really mind how we do it but the blog posts currently aren't appearing in their blog list, so something's not working any more: https://jakarta.ee/blogs/

**Comment by lauracowen** [comment]
Thanks. Seems to work now: 
<img width="1296" alt="image" src="https://github.com/OpenLiberty/openliberty.io/assets/3322532/e55ca2a2-a9e3-46c8-aeed-0f5b393ebda9">
