### ISSUE TITLE
Save guide ratings

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#365]
We need to save the guide ratings when the user clicks on these faces at the bottom of a guide:
![image](https://user-images.githubusercontent.com/6392944/41418273-01e913c0-6fb5-11e8-99af-0c2a33925f2c.png)

**Comment by kinueng** [comment]
I am evaluating if hotjar can help us capture the rating data

**Comment by mbroz2** [comment]
Moving this into Ice Box until we know how we're going to implement this (google analytics, hotjar, etc)

**Comment by kinueng** [comment]
This work needs to be done.  The test guide rating is now on openliberty.io.

**Comment by steven1046** [comment]
We need to figure out how we are going to store the ratings.
