### ISSUE TITLE
Remove Twitter link from /blog page

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3662]
Replace `Be sure to follow @openliberty.io on Twitter or subscribe to our RSS feed.` with `Be sure to subscribe to our RSS feed.`

**Comment by SteveSamJacob19** [comment]
Also have to remove twitter from Header, Support page, Blog post page, Starter page

<img width="1728" alt="Screenshot 2024-03-19 at 12 00 01 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/9f786408-04cd-495e-9efa-f546d5e1e1eb">
<img width="855" alt="Screenshot 2024-03-19 at 12 01 18 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/1423
<img width="1728" alt="Screens
<img width="1510" alt="Screenshot 2024-03-12 at 12 53 23 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/9fa21b7f-a598-44de-8422-3e0adbf1a8db">
hot 2024-03-12 at 12 53 34 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/0d5b1a93-70d6-47b3-8ae2-371547323930">
85295/e4ae64ce-9d97-4e00-8b30-611577c6498c">

**Comment by SteveSamJacob19** [comment]
Also have to remove twitter from Header, Support page, Starter page, Blog post page.

**Comment by SteveSamJacob19** [comment]
<img width="855" alt="Screenshot 2024-03-19 at 12 01 18 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/0c3c524d-ad9a-4e1e-824b-2b82b84793dd">
<img width="1728" alt="Screenshot 2024-03-19 at 12 00 01 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/faa9f209-4953-4e23-8ee6-0f67ae9eacfb">
<img width="1510" alt="Screenshot 2024-03-12 at 12 53 23 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/284e95ac-fc4d-4ba9-8a81-c084fab3d6ac">
<img width="1728" alt="Screenshot 2024-03-12 at 12 53 34 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/3604a53f-14aa-4335-ab15-be4787501b6b">
