### ISSUE TITLE
Toc Line Does not respond to dynamic change of end of guide section

### ISSUE THREAD

**Issue by SteveSamJacob19** [OpenLiberty/openliberty.io#3670]
With reference to [https://github.com/OpenLiberty/openliberty.io/issues/2270](url) , on changing the OS tabs nearing to the end of guide section results in the dynamic movement of the end of guide section with respect to the OS tab content. However the TOC line does not respond to the same change.
<img width="1728" alt="Screenshot 2024-03-11 at 8 01 25 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/10924ebf-6af9-4bc6-8403-d5278c0294c4">

**Comment by navaneethsnair1** [comment]
setting toc-line position to absolute seems to solve the issue.
