### ISSUE TITLE
Unexpected highlight of package when entering docs page using a link.

### ISSUE THREAD

**Issue by navaneethsnair1** [OpenLiberty/openliberty.io#3687]
When we open our page using a link ([like this](https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.0-javadoc.html?package=javax/annotation/package-frame.html&class=overview-summary.html))which already has a package selected from left toc, its highlight(of previously selected package) is locked. Even after changing to a new package, the highlight always remains.
<img width="392" alt="Screenshot 2024-03-28 at 1 42 14 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142485870/b1194018-5d88-4c87-995c-a2f8d477a7ac">

1. javax.annotation - package which was selected in default in the link
2. javax.enterprise.context.spi - new package selected by user
3. javax.enterprise.inject.se - effect when another package hovered by user

**Comment by natalie-bernhard** [comment]
Progress will be tracked via https://github.com/OpenLiberty/openliberty.io/issues/3706
