### ISSUE TITLE
Different css effect after selection for different toc sections in docs page

### ISSUE THREAD

**Issue by navaneethsnair1** [OpenLiberty/openliberty.io#3688]
package section over selection: orange text
other toc over selection : orange highlight, no orange text

<img width="162" alt="Screenshot 2024-03-28 at 1 55 58 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142485870/e1998477-ef68-43e1-a1ba-be34e1905dd8">

**Comment by natalie-bernhard** [comment]
Progress will be tracked via #3706
