### ISSUE TITLE
Explore automatically triggering website builds for static guides

### ISSUE THREAD

**Issue by gindik** [OpenLiberty/openliberty.io#37]
A set of branches/review policies should be setup in the repositories in order to allow people to push changes and check them online in the pre-production environment. Once the reviews are complete, with the required approvals the changes would be then pushed to production. This might require branch coordination between guides and the website.

**Comment by kevinwlau** [comment]
Currently I've setup a test environment that builds daily for `master` branches of the static guides. The static guides will need to switch to using a development branch separate from the master branch which is for production.

I've looked into a couple options for triggering the website builds off static guide repo updates. So far, the options require a lot of setup/maintenance per repo, making them unfeasible.

I found this travis documentation which may look promising and need to test.
https://docs.travis-ci.com/user/private-dependencies/

**Comment by kevinwlau** [comment]
For TravisCI, one option to set an environment variable throughout the organization is to use a script, as mentioned in this Travis issue: https://github.com/travis-ci/travis-ci/issues/2069#issuecomment-300425169

**Comment by evelinec** [comment]
@Ahmad-Ayyoub Take a look at this issue. We can do something for the guides too.

**Comment by kinueng** [comment]
Hi @Ahmad-Ayyoub,
@kevinwlau and I have a lot of history with this work.  Here is a working `.travis.yml` to do the cross GitHub repo request in Travis.

https://github.com/OpenLiberty/iguide-circuit-breaker/blob/dev/.travis.yml

**Comment by kevinwlau** [comment]
The `GITHUB_TRAVIS_TOKEN` environment variable is a personal access token from GitHub (https://github.com/settings/tokens/)

It needs these permissions set: 
![image](https://user-images.githubusercontent.com/689163/41489060-27516360-70b4-11e8-93e9-7753392d3c90.png)

**Comment by mbroz2** [comment]
Follow up with YK

**Comment by k8vance88** [comment]
Closing because this is an older item and has changed since written.
