### ISSUE TITLE
Javadocs TOC intended behavior

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3706]
The intended behavior of the javadocs TOC is shown in screenshots below.  Please implement this behavior in the TOC.

When a package is selected (from any frame):
![Image](https://github.com/OpenLiberty/openliberty.io/assets/84740311/1e41f445-7ab1-47b1-a85e-9c86d345849c)

When a Class/Enum/etc is selected (from any frame):
![Image](https://github.com/OpenLiberty/openliberty.io/assets/84740311/567f90cf-4745-4062-bf1e-41bb8abfa2bc)

**Comment by SteveSamJacob19** [comment]
This issue does not exist anymore with the new frameless javadocs
