### ISSUE TITLE
Multiple pill labels show outside of guide cards for certain screen sizes

### ISSUE THREAD

**Issue by SteveSamJacob19** [OpenLiberty/openliberty.io#3711]
There is a bug on the tags in the guides page when the screen size is reduced as shown below.

<img width="1429" alt="Screenshot 2024-04-24 at 6 25 58 PM" src="https://github.com/OpenLiberty/openliberty.io/assets/142385295/b33fce61-425b-4e20-9ec3-5f714e1a7b79">

**Comment by navaneethsnair1** [comment]
@SteveSamJacob19 It seems to be working fine. I tried them in chrome and safari.

**Comment by SteveSamJacob19** [comment]
Actually when I looked in the morning, it looked fine to me too, but I played around with the screen size and the issue popped up again randomly. I've shared a recording of the same.

https://github.com/OpenLiberty/openliberty.io/assets/142385295/1fa0d32a-b903-499c-bae9-210efc84d580

**Comment by SteveSamJacob19** [comment]
It apparently only affects some boxes

**Comment by natalie-bernhard** [comment]
It's dependent on whether the guide has multiple pill labels or just one (set in `guides.html`).  We will probably have to limit the labels to one label per card at this time.  Make sure to confirm with guides team which labels should be prioritized.

**Comment by SteveSamJacob19** [comment]
@natalie-bernhard actually if you watch the recording, you can see that some boxes with multiple labels (eg: run in cloud and updated tag together) don't have the bug while some do.

**Comment by natalie-bernhard** [comment]
@SteveSamJacob19 The initial screenshot submitted from the issue clearly shows a bug when these two tags (run in cloud and updated) are both present in a card.  The only cards that don't seem to be affected are the ones with the `New` label since that is a shorter label.

**Comment by SteveSamJacob19** [comment]
@natalie-bernhard I thought the same too at first but actually if you go through the recording at around the 2 second timestamp, you can see a card with run in cloud and updated tags having no bug in it.

**Comment by SteveSamJacob19** [comment]
@natalie-bernhard So I played around with the screen width right from full screen to the least width possible. I noticed that issue happens only when the window.innerWidth is between 1400 and 1435 px, Because below 1400 breakpoint the window only shows 3 cards at a time while above 1435 the 4 cards have enough space between them.
