### ISSUE TITLE
Add filter to docs TOC

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3719]
Allow users to filter article titles in the TOC using text input.  Originally requested by @ayoho .

**Comment by natalie-bernhard** [comment]
Possible alternative: provide `Expand All` button for TOC to expand all nested sections, so users could use page search (Ctrl + F) to find TOC titles with keywords

**Comment by natalie-bernhard** [comment]
> Possible alternative: provide `Expand All` button for TOC to expand all nested sections, so users could use page search (Ctrl + F) to find TOC titles with keywords

This approach is not a solution.  We will implement a text input filter.

**Comment by natalie-bernhard** [comment]
As the user types in a filter query, remove titles from the TOC that do not match the query, similar to the function of the filter on the guides page.  See if reusing code from guides filter is possible.  If title matching query is nested, show in TOC expanded under it's parent topics.

**Comment by natalie-bernhard** [comment]
Design: 

Important Notes:
- Search bar color: #EEEFF3
- Search bar font: Asap
- Corner radius for rectangle: 3

![Image](https://github.com/OpenLiberty/openliberty.io/assets/84740311/31107f06-79dd-48ec-908b-125ddcbb57c9)

**Comment by SteveSamJacob19** [comment]
It would be good to keep the filter bar visible even during scrolling just like the version dropdown, so that it can be accessed anytime

**Comment by ayoho** [comment]
Changes made for this are exactly what I was hoping for. Thank you!
