### ISSUE TITLE
Add a new email address to the openliberty.io domain

### ISSUE THREAD

**Issue by natalie-bernhard** [OpenLiberty/openliberty.io#3743]
Look into setting up a developer@openliberty.io email address to include in public READMEs as contact information.

Originally requested by @lauracowen

**Comment by lauracowen** [comment]
This is done (moreorless). This internal doc lists the alisases we have and the process for the future: https://ibm.box.com/s/jwcgi3l57f2tlwla8t44xgc0e0pfyt95
