### ISSUE TITLE
Prevent non production environments from being crawled

### ISSUE THREAD

**Issue by gindik** [OpenLiberty/openliberty.io#38]
Non production environments should automatically incorporate robots.txt in order to ensure that the pages are not crawled/indexed. This is so that people using a search engine to find Open Liberty will land on the actual site and not a temporary/dev/test site.

**Comment by gindik** [comment]
Note that the scope of this work should prevent any environment that is not the production one from being crawled. The issue referenced above only addresses one particular development environment. Others, like openlibertydev.mybluemix.net are still being crawled. 
With regards of the implementation, rather than adding the robot.txt file if a development variable is present, I would suggest instead adding robot.txt always unless a production variable is present. This fall-safe behavior would be more reliable, preventing future development environment instances from being crawled if they happen to be missing that variable. It would also be better aligned with the built-in production variable being used by Jekyll, which is used to control which environment instances should submit analytic information.

**Comment by kevinwlau** [comment]
I agree that the robots.txt should always be added unless production variable is present. I had this change in mind but haven't gotten to it yet. Will be changing this shortly.

**Comment by kinueng** [comment]
I noticed that we actually wanted `robots.txt` to be added when setting the environment to PRODUCTION.  In pull request #54, we are looking for `${ENVIRONMENT} = "DEVELOPMENT"`,  I will leave this issue opened and make a second pull request to invert the current logic for adding `robots.txt`.  For now, the end result is complete

https://openlibertydev.mybluemix.net/robots.txt
https://qa-guides.mybluemix.net/robots.txt

**Comment by gindik** [comment]
@kinueng in the last comment you mentioned this issue would be kept open until the logic is updated. Looking at the code, that doesn't appear to be the case.

**Comment by kinueng** [comment]
Pull request #67 is merged in `master`
