### ISSUE TITLE
[Intermittent] Missing builds on Downloads page

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#384]
# Problem
For some *unknown reason*, the download page occasionally will have no builds listed.  Refreshing the page does not fix the problem.

# Browser/Version
Chrome Version 66.0.3359.181 (Official Build) (64-bit)
MacOS

# What to look into
Java code might be hiding an exception

**Comment by steven1046** [comment]
I think the builds do load eventually, if you inspect the network tab the call to get the data takes awhile but eventually comes back. The real issue is why it takes a long time to return the data.

**Comment by steven1046** [comment]
![image](https://user-images.githubusercontent.com/6392944/43222223-2a4402aa-9015-11e8-9ab5-f6eced08344b.png)

I reproduced it locally and it takes ~38 seconds sometimes.

**Comment by kinueng** [comment]
This may be fixed by #501

**Comment by kinueng** [comment]
We can reopen this issue if we find that the new backend code fails to fix the blank list of download links from DHE.
