### ISSUE TITLE
Remove use of Google Web Fonts for Open Liberty.io

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/openliberty.io#3850]
We need to remove the use of google web fonts from open liberty.io. It seems every web page has a reference so I took a look in the git repository and there are 5 files referencing `fonts.googleapis.com`. These can be seen [here](https://github.com/search?q=repo%3AOpenLiberty%2Fopenliberty.io%20fonts.googleapis.com&type=code).

**Comment by gkwan-ibm** [comment]
hi @NottyCode 

Do the guides and samples also need to remove? Their apps use the `fonts.googleapis.com` in the .css file too?
- `@import url("https://fonts.googleapis.com/css?family=Asap:300,400,500");`

**Comment by NottyCode** [comment]
@gkwan-ibm yes we are expected to cease any reference to google fonts across the site. That includes the guides.

**Comment by gkwan-ibm** [comment]
I created an [issue](https://github.com/OpenLiberty/guides-common/issues/1083) for the guides

**Comment by gkwan-ibm** [comment]
It affected ccs, html, js or other files
