### ISSUE TITLE
Doc version dropdown renders too long on tall screens

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#3879]
On taller screens, the doc version dropdown doesn't vertically wrap properly, rendering longer than necessary, leaving a bunch of white space at the bottom (tested on chrome and safari).  This doesn't happen on short displays.

![image](https://github.com/user-attachments/assets/4634cfab-8164-479d-9a17-5d95a8fcac43)

**Comment by SteveSamJacob19** [comment]
Hi @mbroz2 , can you elaborate on what you mean by taller screens, like what size because i'm not able to recreate this with my desktop full window.

**Comment by mbroz2** [comment]
Here's an example with a height of 1275 pixels:
![image](https://github.com/user-attachments/assets/14a9d0c0-0489-4341-a19c-c934c56a3c6a)

But anything over a height of 860 pixels (given our current 16 versions) starts to add the white space to the bottom of the drop down (fyi, I see the same behavior on mac and windows on chrome, as well as on safari on mac)

**Comment by mbroz2** [comment]
This [`height: 75%`](https://github.com/OpenLiberty/openliberty.io/blob/62bb7f82d7373ec925b6a654e7ed28b7d2c7aa76/src/main/content/antora_ui/src/sass/nav.scss#L399) might be to blame. I would suggest trying `max-height: 75%` instead

**Comment by SteveSamJacob19** [comment]
Alright thanks, will look into it.
