### ISSUE TITLE
Config docs have nested scrollbars

### ISSUE THREAD

**Issue by aguibert** [OpenLiberty/openliberty.io#427]
Looking at this link on Chrome: https://openliberty.io/docs/ref/config/#rwlp_config_logging.html

I notice that the table gives nested scroll bars, since the primary scroll area doesn't do much, it would be better if there was just 1 layer of scrollbars on the right hand side:
![screen shot 2018-07-05 at 10 44 17 am](https://user-images.githubusercontent.com/5427967/42333459-68d3a9ba-8040-11e8-8311-0ef0535a6ea0.png)

**Comment by kinueng** [comment]
@lavenal mentioned she is looking into the multiple scrollbar issue

**Comment by lavenal** [comment]
Fixed.
