### ISSUE TITLE
Multipane design doesn't display long section names well

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/openliberty.io#442]
In the new multipane design, if the section has a long name and it must drop to a second line, the title may not display well, depending on the browser configuration.

For example, 
![longnamegood](https://user-images.githubusercontent.com/29490139/42650275-f66d02c8-85d9-11e8-9ebd-2464131689ce.PNG)

but it may also appear as the following when the title slips to  two lines:
![image](https://user-images.githubusercontent.com/29490139/42650241-e0a733be-85d9-11e8-855b-49d15827c22b.png)

--------------------------------------------------------
The CSS that creates the "greenish" header  at the top of each section is actually a box-shadow for each section.  It belongs to the section div, not to the \<h2> header.

    #guide_content div.sect1:not(#guide_meta) {
        box-shadow: inset 0px 94px 0px 0px #F7F9E5, 0px 5px 11px -3px rgba(0,0,0,0.27);
        border-top: 3px solid #d4d7e3;
    }

The \<h2> header is not centered within this "greenish" section.  Instead, the \<h2> header text  is simply appended to the #guide_content div itself and appears centered within the "greenish" section provided the text is not too long.  The height of this "greenish" section is always constant.

This poses a big problem with the interactive guides as many of the section titles are long.

**Comment by steven1046** [comment]
It looks good, i think we should use `padding: 48px 60px 21px 60px;` to match the existing top/bottom yellow spacing around the text.
Right now the section titles will look really skinny:
![image](https://user-images.githubusercontent.com/6392944/47796768-fe36ca00-dcf2-11e8-862d-c2f6f4ab445b.png)
