### ISSUE TITLE
Multipane layout: scrolling in IE moves site header off the page

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/openliberty.io#443]
I have IE 11 installed.

The guide appears normal at first....

![image](https://user-images.githubusercontent.com/29490139/42653252-edb75be8-85e2-11e8-9a51-c950b5ff6ef1.png)

....except for the weird scroll bar on the right which is for the WHOLE page (attempted to circle that in red in the pic above).

However, as you scroll, the site header scrolls off the page.  By site header I mean the dark blue part at the top of the page with the Guides and Reference menus and the breadcrumb.  The space where the site header was turns blank.  The #guide_column text which is normally hidden by the site header is seen.  The #toc_column and #code_column now look abandoned as they are still beginning about the height of the site header down the page.

![image](https://user-images.githubusercontent.com/29490139/42653349-3adf7bc6-85e3-11e8-8a78-ecceb03c298f.png)

**Comment by steven1046** [comment]
Fixed by #504
