### ISSUE TITLE
Multipane guide feedback

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#449]
This is an issue to track the multipane guide details that still need to be addresed.
Things to be fixed:

- [x] - Arrows text cut off
- [x] - Github popup vanishes too quickly
- [x] - Hover over guide snippets to highlight those snippets in the code pane on the right.
- [x] - Highlight of code isn't full width
- [ ] - Orange table of contents drawer slide out
- [x] - Inertial scrolling

**Comment by steven1046** [comment]
@evelinec Do you have an example of "Some output on middle got cut off"?

**Comment by steven1046** [comment]
@evelinec The new designs don't have any copy buttons in the guide anymore. There is a button to copy the entire file's contents in the right column.

**Comment by evelinec** [comment]
@steven1046 hm, that's interesting. Not even for the clone command?

**Comment by steven1046** [comment]
At the top of the page, a popup appears over the right column where the user can copy the git clone:
![image](https://user-images.githubusercontent.com/6392944/44053423-3b95993e-9f05-11e8-9eae-07c02a55f8c3.png)

**Comment by evelinec** [comment]
Ah ok, we'll check it out as we're working transforming the guides to the new design. Thanks for the example. We'll review this issue soon for closure.

**Comment by andrewdes** [comment]
- [ ] Arrow (indicating to scroll down) isn't centered if side panel is closed
![image](https://user-images.githubusercontent.com/22628575/44418993-e8b16100-a547-11e8-8358-026c0de1ccac.png)

- [ ] If you expand or minimize the content bar, your position in the guide changes (note: works fine at the top or bottom of the guide, issue only arises if you are somewhere in the middle)

- [ ] Text goes off the screen if too long when using hotspots: 
![image](https://user-images.githubusercontent.com/22628575/44423297-c7567200-a553-11e8-9b7b-ee275b60ce15.png)

- [ ] There should be a way to copy commands in the middle panel (i.e. `mvn clean install` commands)
- [ ] Hotspot lines are hard-coded in the readme.adoc (could be problematic if code file changes)
- [ ] In some sections/sub-sections text in `backticks` are displayed differently than others:
![image](https://user-images.githubusercontent.com/22628575/44423806-0afdab80-a555-11e8-9ad2-2a9fee2bb105.png)
- [ ] Backticks shouldn't be displayed in code_commands: 
![image](https://user-images.githubusercontent.com/22628575/44424389-fd492580-a556-11e8-98a4-dcb863ad2fa5.png)
- [ ] Text in backticks should be styled differently in code_commands to help differentiate the file paths from actual text.
- [ ] When there are two files to be displayed in the right pane in the same section of the guide, the first first file gets skipped over (see: https://qa-guides.mybluemix.net/guides/cdi-intro.html, the InventoryManager.java file switches to the InventoryResource.java file once subsection is reached)

**Comment by steven1046** [comment]
>When there are two files to be displayed in the right pane in the same section of the guide, the first first file gets skipped over (see: https://qa-guides.mybluemix.net/guides/cdi-intro.html, the InventoryManager.java file switches to the InventoryResource.java file once subsection is reached)

I think the new design intended upon having one code section per guide section or subsection `(=== Injecting a dependency)`. Having multiple code files on the right in one subsection would make it impossible to determine which to show on the right. The only way to switch the code files would be hovering over the hotspot snippets in the guide, which someone asked about on Slack and the design team said they didn't want it that way.

**Comment by evelinec** [comment]
Regarding @steven1046 comment above, it's not a good practice to have the guide to adjust its section to work in the multipane, ie, breaking the section of topic because it involves more than one classes of code.

**Comment by steven1046** [comment]
For backticks in code commands, use **subs="quotes"** in the attribute list of the code block and I will update the code to style these file names inside of the code commands:

highlight_lines=7-9
[role="code_command hotspot",subs="quotes"]
----
Create the JAX-RS application class in the `src/main/java/io/openliberty/guides/rest/SystemApplication.java` file:
----

**Comment by kinueng** [comment]
Closing this issue.  The remaining work items are captured in other issues according to @steven1046
