### ISSUE TITLE
Docs page - small fixes

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#466]
- Bottom of the page should fade to white and not be completely blue. this is so the orange links in ‘Contributor Docs’ are readable
- Spacing between the cards and ‘Contributor Docs’ main text incorrect
- Footer should not span the whole window. It should be centered like the other website pages.
- The gradient in the top section doesn’t look quite right.  Try below.

```
background-image:radial-gradient(58% -36%, #5e6b8d 44%, #2c2e50 100%);
width:1440px;
height:515px;
```

**Comment by kevinwlau** [comment]
New design:
![image.png](https://images.zenhubusercontent.com/5612bad3638e718c995d8d60/47fb5fb8-68f1-4969-94f1-b86197c1c0ac)

Changes: 
- static blue background -> linear-gradient of blue to white
- shortened footer to match the rest of the website
- some footer links are green

>Config and Features need to have ‘Open Liberty’ in front of their names because both of the API buttons have qualifiers (Java EE and MicroProfile). When we have all 6 buttons and Open Liberty stuff takes precedence, we can drop ‘Open Liberty’ from the buttons because the user will be able to assume. But for now we need to be extra clear

Current design:
![image.png](https://images.zenhubusercontent.com/5612bad3638e718c995d8d60/c30ae113-9756-491e-8181-c9e5d72a4979)
