### ISSUE TITLE
SEO Issues - Config documentation page

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#479]
# Description
We are getting undesirable search results for our configuration pages.  Web crawlers can see the hidden urls that directly hit the `html` files through the file structure in our website application.  

openliberty.io uses custom code that handles how the `html` files are displayed and manages a custom URL structure that is different from the file system layout of the website application.

# Problem
1.  Google does not index our custom URL structure for config documentation
2. What is indexed by Google is giving users an incomplete user experience (missing navigation frames, etc)

# URL comparison
Both these URLs get the same page

From openliberty.io
https://openliberty.io/docs/ref/config/#rwlp_config_activationSpec.html

From search results (assuming due to web crawling)
https://openliberty.io/config/rwlp_config_activationSpec.html

# Google search
![image](https://user-images.githubusercontent.com/31117513/43430603-66e02c48-942f-11e8-89c4-5b3bb202b87e.png)

# Page from Google search results above
![image](https://user-images.githubusercontent.com/31117513/43430647-8ff64eb4-942f-11e8-9144-8a479d77f0f7.png)

**Comment by kinueng** [comment]
Additionally, here is what our Java EE API search results show
![image](https://user-images.githubusercontent.com/31117513/43432848-7405c68e-943a-11e8-92f5-c714e498e548.png)

**Comment by lavenal** [comment]
wouldn't it be the same problem for any openliberty ee doc and microprofile doc? 

![screen shot 2018-08-01 at 10 15 11 am](https://user-images.githubusercontent.com/25039033/43530690-cfd0d91a-9573-11e8-8a92-99962975a131.png)

**Comment by kinueng** [comment]
@lavenal 
My lack of SEO knowledge is apparent.  I am not sure what our next action should be to help improve our search presence.  I've been having the questions below floating in my head without any answers.

1.  Is it because we use `iframe`?
2.  Is it because we use `#` in our URLs?
3.  Is it because we use HTTP `302` temporary redirects rather than a `301` permanent move redirect?
4.  Is there something we need to set in `web.xml` to hide internal files in our `war`?
5.  Do we need a `robot.txt` in production to avoid unnecessary indexing of all our files?

**Comment by steven1046** [comment]
We can redirect /config/* to /docs/ref/config/# and it should handle loading the entire page.

**Comment by steven1046** [comment]
For reference, if you search for a "general" doc page on Google all it finds is the main /docs/ref/general page. We do *not* use an iframe on the general docs so that might be a clue for fixing this issue.

**Comment by k8vance88** [comment]
Related to #1228

**Comment by k8vance88** [comment]
This should be fixed by #1243
