### ISSUE TITLE
Enable "Welcome Page" for Server Features

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#489]
Just like we have the landing/overview page for the server config page (https://www.openliberty.io/docs/ref/config/) and server commands (https://www.openliberty.io/docs/ref/command/) we need one for the features page (https://www.openliberty.io/docs/ref/feature/)

**Comment by steven1046** [comment]
This should fix #497

**Comment by mbroz2** [comment]
@NottyCode provide the content for the server config overview page, but I don't believe anyone has been identified to provide the content for this page.  Until the content is provided, this work is blocked.

**Comment by lauracowen** [comment]
I've raised this doc issue for the content: https://github.com/OpenLiberty/docs/issues/132

**Comment by sdaschner** [comment]
Any updates on this?

**Comment by lauracowen** [comment]
Sorry, it's going slowly. I meant to ask, when you have a sec, @sdaschner, pls could you list off what you would expect in this topic (what questions it would answer)?

**Comment by steven1046** [comment]
The features overview is in the draft branch of docs. I'm enabling it on the UI side.

**Comment by sdaschner** [comment]
@steven1046 Sounds good, where can I have a look? :)

**Comment by lauracowen** [comment]
@sdaschner In draft at: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#featureOverview.html (will appear at top of the navigation when fixed). Any feedback (additions, changes, clarity, suggestions) welcome.

**Comment by sdaschner** [comment]
Very cool and helpful, thanks for putting this together! I like especially that it's explained how Liberty loads the features and configuration, which makes users understand the whole process better.

Two remarks:
- Clicking on "Features" in the top navigation ends up on the first one, "Admin Local Connector". This will still change, right? We should either directly link to "Feature overview" and/or move this one to the top.
- The table of compatible EE 7 & 8 features is not really clear. Maybe some cell background colors (in alternating shades, etc.) would help

**Comment by steven1046** [comment]
Yes, the overview page will be at the top and we can add some cell borders to the table. I can show it off tomorrow when I'm in the office.

**Comment by steven1046** [comment]
http://9.41.108.255:4000/docs/ref/feature/

@lauracowen @sdaschner

**Comment by sdaschner** [comment]
@steven1046 I can't reach that page / IP address unfortunately, is it possible to release it under that draft / bluemix domain?

With regards to tables: If that's a big effort to make the huge table fit into the page, maybe one solution could be to just have a small snippet / teaser / link which expands to an overlay / lightbox-like popup that spans the whole page, if people click on it. While I think this information is helpful, folks probably don't need to see it the whole time, WDYT?

**Comment by mbroz2** [comment]
The code to enable this has been delivered; once the content is delivered into the master branch for the docs repo, it will appear on the site.
