### ISSUE TITLE
Community and Contribute pages

### ISSUE THREAD

**Issue by gindik** [OpenLiberty/openliberty.io#49]
@kinueng as we agreed, here are the pending items on the Community and Contribute pages so we don't lose track.

- [x] Each page contains an invisible div with images. This is done to pre-load the images and avoid delays/flicker issues on hover effects that require them. It appears that those divs were not updated with the new pages. As a result the Community page has some of the issues described above, and the Contribute page might be unnecessarily loading images that are not being used.

- [x] All page titles (images) use the same font size set by the design. They can be made smaller for responsiveness, but they should not be made larger/inconsistent. The Community page title (in the smallest break point) is larger than the rest of the pages:

![title](https://user-images.githubusercontent.com/17207930/32227316-72673898-be21-11e7-9d61-3ac4d1f2c53b.png)

- [x] There appears to be some text flow issues:
![textflow](https://user-images.githubusercontent.com/17207930/32227916-02a537b0-be23-11e7-9461-3b04b89855d8.png)

- [x] Buttons stretching in Community and Contribute pages. Note how these compare to the button on the About page:

![button](https://user-images.githubusercontent.com/17207930/32227974-380dcc3c-be23-11e7-8ff9-59986006e323.png)

- [x] The button need some left and right padding.  Fixed with commit 
01587f3
![image](https://user-images.githubusercontent.com/31117513/32844070-0c482b5e-c9e7-11e7-99e2-e6c1d4bd1833.png)

**Comment by kinueng** [comment]
I have not pushed this fix to production, reopening.

**Comment by kinueng** [comment]
Adding a new issue to the description with button needing padding.
