### ISSUE TITLE
Javadocs: No way to reset the all packages / all class lists

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#495]
Currently there is no way to get back to All Packages / All classes.  For example, the breadcrumb would be ‘Java EE API > javax.batch.api’ and ‘Java EE API’ would become clickable, and that’s basically the ‘reset’ for this whole section.

Example of the left iframes getting stuck with no way to get out:
![image](https://user-images.githubusercontent.com/6392944/43652207-25fa7e1c-970a-11e8-9702-ea67778f2f64.png)

**Comment by kinueng** [comment]
The behavior of the two left frames are from javadocs.
