### ISSUE TITLE
Server Features missing title in the left nav

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#497]
Missing a title in the list of features:
https://openliberty.io/docs/ref/feature/
![image](https://user-images.githubusercontent.com/6392944/43659481-c8b33d26-9721-11e8-9349-8e880291ea14.png)

It should match Server Config, where there is a title in the nav menu:
https://openliberty.io/docs/ref/config/
![image](https://user-images.githubusercontent.com/6392944/43659516-e4e8ebda-9721-11e8-8e59-08c36bfa3cea.png)

**Comment by lavenal** [comment]
An overview is going to be there once it is ready.

**Comment by lavenal** [comment]
See issue #489. I am going to close this one.
