### ISSUE TITLE
Date for the development builds is wrong on 10/31

### ISSUE THREAD

**Issue by josephca** [OpenLiberty/openliberty.io#50]
The build date for 10/31 is listed as 11/01. The timestamp for the zip files are correct though. 

2017-11-01, 00:30 | 109 / 109 | View logs | Download (.zip)
2017-10-30, 00:30 | 108 / 109 | View logs | Download (.zip)

https://openliberty.io/downloads/

Addition: 
The timestamp looks fine again on 11/01. However, the builds listed are little mixed as build on 10/31 is listed as 11/01 as well. I think it still needs to be fixed.

**Comment by kinueng** [comment]
I found that the server side is sending back this information for the mislabeled 2017-11-01, 00:30 build.  Note that all the dates look fine in the JSON.  I will take a look at the Javascript code to see what is happening there.
```
{
    "test_passed": "6313",
    "total_tests": "6313",
    "tests_log": "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2017-10-31_0200/open-liberty.unitTest.results.zip",
    "build_log": "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2017-10-31_0200/gradle.log",
    "driver_location": "https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/nightly/2017-10-31_0200/openliberty-all-17.0.0.3-201710310152.zip",
    "version": "17.0.0.3-201710310200",
    "date_time": "2017-10-31_0200",
    "size_in_bytes": "104374944"
}
```

**Comment by kinueng** [comment]
I suspect there is a timezone conversion issue that is causing timestamps from the last day of a current month to be shown as the first day of the next month.  I am not seeing any GMT information with the timestamps used in the JSON or on the DHE server.

**Comment by gindik** [comment]
Other date issues were observed by @jgwest. After looking into the code, the issue appears to be caused by the months in the JavaScript date methods being indexed at 0. As a result, when date calculations take place (for sorting/display purposes) this was causing, in certain scenarios, the dates to be shifted. The solution consists of ensuring that the months are 0 indexed when dealing with the JavaScript Date methods.

**Comment by cbridgha** [comment]
Thanks - was about to ping you guys  :)


Thanks - Chuck

Open Liberty Project development, Eclipse WTP PMC
IBM Software Lab - Research Triangle Park, NC
