### ISSUE TITLE
CSS colour is wrong for text in `<code>` tags in the guides

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#51]
I'm not sure what the colour should be (need to ask Design) but it was pointed out on a call pre-release but I can't find an issue for fixing it.

Taking the REST guide, for example, the text in red with the pink background needs styling properly:

![image](https://user-images.githubusercontent.com/3322532/32274767-636ecb1e-bf00-11e7-8c7c-1097e4b9b45d.png)

Similarly, the text strings in the code snippets:

![image](https://user-images.githubusercontent.com/3322532/32275301-a26d7e8a-bf02-11e7-8861-8f71c1a4267a.png)

**Comment by kinueng** [comment]
I have started a conversation with the design team about this issue.

**Comment by kinueng** [comment]
I received new designs on what colors to use for syntax highlighting.  Removing tag.

**Comment by kinueng** [comment]
I thought it may be too verbose to put all the details below in the commit message.
- Per design, change bold to medium (font-weight 500)
- Per design, use the color scheme for the java snippet example in the design mockups.
- Per design, avoid using any red colors that are currently showing in the guides at this time of writing.
- Per discussion that changed the design, avoid using orange in the code block for the package name.  The package name is typically colored like the import names.  Additionally, orange is reserved for clickable link in the overall website look and feel.
- Per discussion that changes the design, avoid highlighting the strings in the code blocks.
