### ISSUE TITLE
Open Liberty site header's menu items

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/openliberty.io#581]
1) When tabbing from the URL to the guide header, at a window width sufficient to show the 'Guides' and 'Reference' menu items (not the hamburger), the 'Guides' menu item will display with an outline, but the text remains dim when it is focused:
![image](https://user-images.githubusercontent.com/29490139/45057371-11af1700-b05b-11e8-9d4a-bd30752eaa62.png)

The 'Reference' menu item, when focused, will display without  an outline, but the text is made white so it appears bright:
![image](https://user-images.githubusercontent.com/29490139/45057477-58047600-b05b-11e8-8767-4d3f28f4447e.png)

The inconsistency for an active, selected state should be the same for the two menu items.

2) When the 'Reference' menu item is selected a dropdown menu appears.  However, if you tab out of or away from the 'Reference' menu item the dropdown menu is not dismissed.
![image](https://user-images.githubusercontent.com/29490139/45057653-cc3f1980-b05b-11e8-86bb-f76ecb4edb41.png)

**Comment by kinueng** [comment]
Dupe to #589
