### ISSUE TITLE
Scroll through a guide produces white flicker

### ISSUE THREAD

**Issue by hughesj** [OpenLiberty/openliberty.io#59]
Pick https://openliberty.io/guides/cors.html scroll down fairly quickly (I use mouse scroll wheel). The lower portion of the window flickers white then back to purple. Scrolling back up and the top flickers. Fixing this would produce a smoother site.

**Comment by steven1046** [comment]
This will be fixed by the double pane redesign coming in #112 where there will not be a floating TOC, so no need for a scroll listener.

**Comment by kevinwlau** [comment]
Closing because design changes will likely mean this is irrelevant with the new code base.
