### ISSUE TITLE
Build guides from repos by naming convention

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#63]
Consider building the guides to be published on the website by cloning from repos following a particular naming convention.

This simplifies the build process for the guides.  At least, the process to publish new guides.

This allows for repos of draft guides to co-exist with repos of completed guides too -- The live site will only pick up the completed guides while the test site can include all.

**Comment by kinueng** [comment]
Hello @yeekangc,
I have finished a script that looks for OpenLiberty repositories that start with `guide` or `iguide` when building for production.  

What would a the GitHub repository name for guides that are still in progress?  Maybe `draft-guide-*`?

**Comment by yeekangc** [comment]
I am good with `draft-` as the prefix for repos with draft guides (static or interactive).

So, the script will skip anything that is `draft-guide-*` or `draft-iguide-*`.  Automation aside, this convention will certainly help with our development work too.

We will have to rename the `draft-*` repos when they are ready to go live.  This should be do-able as Chuck once told me.

Tagging @cbridgha @NottyCode to see if they have any thoughts.  @lauracowen @charters too.

**Comment by kinueng** [comment]
# New ruby build script to integrate guides
https://github.com/OpenLiberty/openliberty.io/blob/ee68a48dbfc1e17c4ac8284dabf780b65f494211/scripts/build_clone_guides.rb

# How script works
1.  Script looks thorough all repositories under [OpenLiberty](https://github.com/OpenLiberty) GitHub organization.

2.  https://openliberty.io guides must have repo name starts with `guide` or `iguide`

3.  https://openlibertydev.mybluemix.net draft guides must have repo name starts with `draft-guide` or `draft-iguide`
