### ISSUE TITLE
[Guides] Try using CSS Snap Points - Low priority

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#676]
Per the feedback here https://ibm.ent.box.com/notes/316890076367?s=dzr3wdl9w9c814344fhd1wsn5vyzkeqv: 

Snap Scrolling
Currently it works fairly well (but not perfectly) on Chrome but on Safari and Firefox it doesn't work at all and makes scrolling worse.  Unless you think it can be made to work cross-browser, I suggest to use CSS snap scrolling, even though it's not supported everywhere.  It is now supported in the latest Chrome.

Use snapping for the last Nice Work section.

**Comment by steven1046** [comment]
If we stick with our current implementation, consider adding debounce to the scrolling so that on a trackpad it isn't trying to calculate snapping too often.

**Comment by steven1046** [comment]
This could benefit users that use a trackpad for scrolling.

**Comment by mbroz2** [comment]
Need to discuss with design if we still want to have snap scrolling for guides.

**Comment by mbroz2** [comment]
We're removing all snap scrolling from the site instead.
