### ISSUE TITLE
[Static/Interactive guides] Nav bar should fade away when scrolling down - Low Priority

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#678]
Nav scroll away and reappear.

**Comment by steven1046** [comment]
I can't find any redlines/animations for the navbar dissapearing while scrolling, design do you know where they are located?

**Comment by mdenby** [comment]
https://ibm.box.com/s/qeh1fso2dkowaiu8get98tualppsgji5

^^ Scrollable nav mockup can be seen in the 2nd half of this video (pls ignore the first half, has old navigation details)

**Comment by mbroz2** [comment]
Duplicate of #1040
