### ISSUE TITLE
Replicate US South pipeline in another region

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#720]
We currently have US South hosting our Pipeline.  Once we feel like the pipeline is ready (ping me @kinueng to check), we need to replicate the pipleline in another region.

**Comment by steven1046** [comment]
If we replicate the pipeline to another region, like Washington, then it could be turned off for automatic rebuilds and sit idle for when we need to use it. The only time we would really need to use it is if the South region data center went down and we couldn't rebuild the website that way.
