### ISSUE TITLE
Change Travis test environment based on feedback from static guide team

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#729]
![image](https://user-images.githubusercontent.com/31117513/51495103-c3d44a80-1d80-11e9-8e79-bc0b83a41f37.png)

**Comment by kinueng** [comment]
FYI @gkwan-ibm

**Comment by kinueng** [comment]
@steven1046 we should also see if the static guide team would like for these environments to rebuild automatically through a cronjob in Travis.

**Comment by gkwan-ibm** [comment]
Following is what we want from our discussion/powerpoint:

1. Public OpenLiberty guides (POLG) site = https://openliberty.io/guides (As is)
    - The UI is from the master branch of the openliberty.io repository
    - The guides are from the master branch of published guide repositories (guide-xxxx)
1. OpenLiberty guides QA (OLGQA) site = https://qa-guides.mybluemix.net/guides (To be determined)
    - The UI is from the master branch of the openliberty.io repository
    - The guides are from the qa branch of published and publishing guide repositories  (guide-xxxx)
1. OpenLiberty guides draft (OLGD) site = https://draft-guides.mybluemix.net/guides (To be determined)
    - The UI is from the master branch of the openliberty.io repository
    - The guides are from 
       - the dev branch of draft guide repositories  (draft-guide-xxxx)
       - the dev branch of published guide repositories (guide-xxxx) if the dev branch exists, otherwise the master branch
    - The non-IBM contributors can access to this site so that they can see their contributions and continue to contribute before publish.

Regarding when/how to refresh the sites,
- it is ok for us to request a refresh for POLG site
    - is it possible to be refreshed daily or twice a day?
- we prefer a way to refresh OLGQA and OLGD sites by a trigger, e.g. TRAVIS rebuild

**Comment by steven1046** [comment]
I'll have to look into automatically rebuilding ol.io twice a day but for "we prefer a way to refresh OLGQA and OLGD sites by a trigger, e.g. TRAVIS rebuild" there will be an option in Travis to rebuild the master branch of openliberty.io and it will automatically build those 2 sites.

**Comment by steven1046** [comment]
OLGQA and OLGD will also get rebuilt when the openliberty.io master branch is updated.

**Comment by steven1046** [comment]
I don't see a way in the IBM Cloud UI to automatically rebuild our site daily. The only options are when a change is pushed to the branch it is listening on and manually.
