### ISSUE TITLE
Replace target="new" and add noopener

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#741]
Consider using `target="_blank"`

Consider using security flags `rel="noopener"`

**Comment by kinueng** [comment]
We began replacing `target="new"` to `target="_blank"` with the new nav bar bootstrap4 work.

**Comment by steven1046** [comment]
According to https://developers.google.com/web/tools/lighthouse/audits/noopener:
```rel="noopener" prevents the new page from being able to access the window.opener property and ensures it runs in a separate process.```
