### ISSUE TITLE
SEO title and description need to be set explicitly for each page of site

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#75]
We need to set the SEO title and descriptions explicitly on each page of the website. Currently:

* The SEO title (`<title>`) appears to be set automatically by taking the content of the `<h1>` tag and appending " - Open Liberty". This is not great because the SEO title should be more active and engaging (and 'clickable') than some page and guide titles are.
* The SEO description (`meta name="description" content="description goes here"`) is set to the overall website description on every page: "Open Liberty is the most flexible server runtime available to Earth’s Java developers.". This is really bad because Google etc will either consider all the guides as the same or will dig around for what to use and we can't control it.

For example:

![image](https://user-images.githubusercontent.com/3322532/33389194-f61b16fe-d529-11e7-8bc4-e7d49faf13d8.png)

![image](https://user-images.githubusercontent.com/3322532/33389209-026cfd14-d52a-11e7-9d3a-9658d5d41b10.png)

I think we need:

1. Two new tags (for SEO title and SEO description) adding to the front matter of the Jekyll templates for all the pages.
2. Transform these two tags to the relevant HTML tags (see above).
3. Write SEO title and SEO description for each page.

**Comment by lavenal** [comment]
Steven and I have added set-title and seo-description tag support to the front matter.

**Comment by lavenal** [comment]
After Steven consulting Laura on the twitter:title, it is agreed that seo-title should be used as twitter:title too.
