### ISSUE TITLE
Blog card text needs setting explicitly

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#76]
On the main Blog page, is the list of 'blog cards' which contain previews of the blog post (https://www.openliberty.io/blog/).

Currently, they contain some number of characters from the start of the blog post, regardless of what that is. This is a pain to author/edit (especially when there are illustrations or links in that text and you have to add more sentences to force the images further down the page).

The guides have a tag in the Jekyll template front matter (`:page-description:`) which effectively creates the equivalent abstracts on the guides main page (https://www.openliberty.io/guides).

We should have a similar/same tag in the blog posts template and set the blog cards using that (though with a higher character limit than the guides use).

**Comment by kinueng** [comment]
This sounds reasonable and now we have experienced a need for this change.  

This topic was discussed before.
```
Dedicated preview message via Front Matter
     vs. 
Taking words from the blog content as the preview
```

I think the pain points speak to the need to have an option to for blog posters to specify exactly what goes into the blog card preview.  If blog posters don't want to specify preview text, then the preview can fall back to pulling text form the blog content.
