### ISSUE TITLE
Manually add third-party hosted blog posts to /blog

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#768]
Could we enable adding cards here: http://openliberty.io/blog as if they were blog posts but actually linking to the original article/post on another domain?
 
For example, Adam Bien has created some videos about Open Liberty and other community people have written blog posts or sample apps in GitHub about OL and I'd like to be able to promote them without having to write a separate dedicated blog post. I would want to write the card text/abstract and title (to ensure good SEO), and to set the correct author (with GitHub picture I guess).

In terms of implementation, the old MP.io blog approach would work fine for me. They had a .yaml file in the repo. You just add an entry in the yaml file with title, abstract, URL, tags and it adds an entry to the blog with the summary text and details from the yaml file and a link that links out to the blog posts hosted elsewhere (eg we’ve added our MP-related blog posts from OL.io to the MP.io blog in this way). I’d be happy to work like that if it was feasible.

**Comment by lauracowen** [comment]
Where are we up to with this? I think Design was looking at it fairly recently but I don't think there was much still to do?

**Comment by kinueng** [comment]
We are pushing this issue along.  My apologies for dropping the ball on this one

**Comment by cajaygle** [comment]
<img width="786" alt="screen shot 2019-01-31 at 1 36 25 pm" src="https://user-images.githubusercontent.com/27516391/52141201-ef79ef00-2622-11e9-9b27-b94f85242426.png">

Mockup showing how we'll link to third-party blog posts. Format may be "Continue reading on ibm.com", or "Continue reading on John Smith's blog" if more appropriate.
