### ISSUE TITLE
Consider whether guide titles should be changed to imperative (eg Create) instead of gerund (Creating)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#77]
I did a quick bit of research on the internet. It seems the internet-jury is out and opinion is that either can work. It's just a matter of house-style and the important bit is to be consistent (see [1](https://writers.stackexchange.com/questions/1545/verb-tense-for-technical-document-titles), [2](https://www.cherryleaf.com/blog/2015/06/the-decline-of-the-gerund-in-technical-documentation/), [3](https://ffeathers.wordpress.com/2013/10/12/death-of-the-gerund-in-technical-documentation/)). Some sites use the imperative (Create a RESTful web service) and many continue to use the more common gerund (Creating a RESTful web service).
 
I agree with Jay that the imperative (in this context) feels more active and engaging. I'm not sure how much the guide title itself impacts on the SEO of the guide. I suspect Google is capable of mapping the two, though it's hard to know.

However, alongside the changes requested in #75 to help support better SEO practices, it might be best to go with the imperative form for our guides. Partly because I agree with Jay that they feel more engaging and active. Partly because if we have authors setting the SEO title with an imperative but the guide title differently, we could end up with a mess.

Some questions to consider:

* Is it appropriate for all the guides we have so far? (does it work or does it look weird/misleading?) We must do the same for all guides so it has to work for them all.
* What about sub-headings within the guides?
* Is it appropriate elsewhere in the site or should it be constrained to the guides?
* Have we got the best wording for all the guide titles? Is it clear what the user gets from it or are we focusing on the technology rather than what they can achieve? This isn't directly relevant but might be when deciding how to change the titles (if we decide to do that).

**Comment by lauracowen** [comment]
I think we should probably close this now as I think we've moved on from this. Anyone disagree?

**Comment by kinueng** [comment]
This topic came up again during the playback of the Retry interactive guides.  I will reopen this issue so we can continue to see if we can decide want to change how we word the guide titles.

FYI @cajaygle
