### ISSUE TITLE
Backticks should not be displayed in code_commands - Low priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#770]
![](https://user-images.githubusercontent.com/18709242/48277573-14423a00-e419-11e8-9d2c-2ac3b34b9956.png)

**Comment by justineechen** [comment]
![](https://user-images.githubusercontent.com/18709242/48222096-bb639a80-e361-11e8-93b4-347d6cea034a.png)

**Comment by steven1046** [comment]
Design said to remove the backticks since there isn't a styling for them. They recommend the following phrasing:
![image](https://user-images.githubusercontent.com/6392944/48362951-64640b00-e66a-11e8-9f97-a553b2664576.png)

**Comment by steven1046** [comment]
A different color is needed for the file name inside of these arrows from design.

**Comment by justineechen** [comment]
Thank you Steven for showing us how to display the backticks, we are deciding how we want to show the names and we may change it to what the design team suggested.
