### ISSUE TITLE
[Guides] Table of Contents behavior after collapsing once - Low priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#772]
When the page is initially loaded, the Contents section has an [x] to collapse the left side, it is located on the upper right hand side of the section before you collapse it for the first time. When you expand the section again, the [x] is now located on the top left hand side of the panel. I'm not sure if it's intentional or not but it's slightly inconsistent. I also feel like [x] implies that we might not be able to get the contents section back so maybe an arrow < that shows that it can be expanded/put back would be more intuitive?

<img width="392" alt="screen shot 2018-11-12 at 12 01 18 pm" src="https://user-images.githubusercontent.com/18709242/48362905-aee98580-e672-11e8-952b-408a1068a5db.png">

**Comment by justineechen** [comment]
"The table of contents will change behavior soon so when you hover near the left side of the page it will pop out and then close when you move your mouse away so the current implementation will change." - @steven1046 

The change will be implemented soon for this issue.

**Comment by steven1046** [comment]
The new toc animation has been delivered. There might be some updates to it being in 2 column view as well depending on design's feedback.

**Comment by justineechen** [comment]
Will the middle pane always have this scrolling animation when the TOC is collapsing/opening? I don't think that was there before the TOC update.

**Comment by steven1046** [comment]
No, I think we will improve upon the design to make it not adjust so much.

**Comment by steven1046** [comment]
The animation is there because closing/opening the toc changes the width of the guide text so it would be at a different spot.

**Comment by mbroz2** [comment]
@justineechen @steven1046 please confirm that the original reason this issue was opened has been addressed.
Regarding the scrolling of the center pane on expanding/collapsing the toc, I agree, it doesn't feel right.  I think we should open a new issue for that and instead just rerender the center pane without the scroll animation (the animation is confusing because the user thinks they're going elsewhere, but they're not).

**Comment by steven1046** [comment]
There's still an 'X' in the design for closing the TOC but at least when you close it there's an arrow pointing to the right indicating it can open again.

**Comment by steven1046** [comment]
@justineechen do you know if the initial issue was resolved? We can open another issue to remove the animation that moves the guide text when closing and opening the TOC.
