### ISSUE TITLE
[Static guides] Copy and Paste button in code panel is not apparent - Low priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#773]
<img width="780" alt="screen shot 2018-11-12 at 12 03 43 pm" src="https://user-images.githubusercontent.com/18709242/48363049-05ef5a80-e673-11e8-8795-8b94883a1f51.png">

"@megmulsy do you think we could increase the size?" - @steven1046

**Comment by gkwan-ibm** [comment]
Also, if possible, when mouse is hovering on the image, a text `Copy to clipboard` should show up (just as after clicked, there is a text `Copied to clipboard`

**Comment by TreeHanh** [comment]
The copy icon has been increased in the code and center panel. 

![CopyPaste](https://user-images.githubusercontent.com/18586040/54222596-1ce07500-44cc-11e9-8285-772600268ea8.png)
![CopyPaste2](https://user-images.githubusercontent.com/18586040/54222604-2073fc00-44cc-11e9-8a5c-f1a7c95667ad.png)
