### ISSUE TITLE
Two files in one subsection, only one file is displayed - High priority 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#774]
When there are two files to be displayed in the right pane in the same section of the guide, the first first file gets skipped over (see: https://qa-guides.mybluemix.net/guides/cdi-intro.html, the InventoryManager.java file switches to the InventoryResource.java file once subsection is reached)

**Comment by justineechen** [comment]
"I think the new design intended upon having one code section per guide section or subsection `(=== Injecting a dependency)`. Having multiple code files on the right in one subsection would make it impossible to determine which to show on the right. The only way to switch the code files would be hovering over the hotspot snippets in the guide, which someone asked about on Slack and the design team said they didn't want it that way." - @steven1046

**Comment by steven1046** [comment]
The files do switch under the https://qa-guides-multipane.mybluemix.net/guides/cdi-intro.html#managing-scopes-and-contexts section, but the first part of the section is so small that it is almost never the majority of the page so InventoryResource.java only shows up for a small window of that step.

**Comment by justineechen** [comment]
That's true, the behavior is different based on how much text is between the files. For example:
https://qa-guides-multipane.mybluemix.net/guides/microprofile-jwt.html#testing-the-application
We can only see the JWT test java file.

**Comment by steven1046** [comment]
Closing this since the subsection needs to be larger in the asciidoc to allow more time for the file on the right to be shown.

**Comment by gkwan-ibm** [comment]
Reopen, either
- the UI can handle multiple files in a subsection
- there is a good workaround. Make the subsection larger is not good, e.g.
  - adding more empty lines to make the subsection larger
  - create each subsection to only contain 1 file

**Comment by steven1046** [comment]
The tabbing should help address more than one file.

**Comment by steven1046** [comment]
Waiting on feedback from using the tabs on if it addresses this issue.

**Comment by justineechen** [comment]
@steven1046 There are still some issues with multiple files in one subsection.

In the CDI guide under handling dependencies in the application: https://qa-guides-multipane.mybluemix.net/guides/cdi-intro.html#handling-dependencies-in-the-application 

- The hotspots don't work for `InventoryManager.java`

In the JWT guide under tests: https://qa-guides-multipane.mybluemix.net/guides/microprofile-jwt.html#testing-the-application

- The `SystemEndpointTest.Java` and `InventoryEndpointTest.java` aren't showing up on the right panel at all

**Comment by steven1046** [comment]
Ok, I can update the code to track multiple files per subsection in tabs but i don't think we'll be able to automatically switch to more than 1 file in a subsection. They will be able to click on the tab though or we can have a hotspot that they hover over to reveal that tab.

**Comment by steven1046** [comment]
The code is ready, just waiting on a code review.

**Comment by justineechen** [comment]
Great! Will the hotspots work for these tabs?

**Comment by steven1046** [comment]
Yes

**Comment by steven1046** [comment]
It will load all of the files into tabs and the hotspots will switch to the correct file when hovering. Clicking on tabs will still work of course. When scrolling, there isn't a good way to detect what file to switch to when scrolling into a subsection with multiple files so it will show the first one and they can click on another tab or a hotspot will switch to the other file.

If more than one file is in a subsection in the guide's .adoc file, all of the hotspots above where the file is placed in the subsection will map to that file. Guide authors can override this behavior by putting [hotspot=14 file=1] for inline hotspots to specify that the hotspot should belong to the second file in that section.

I tested the changes on the cdi intro guide, which I can make a pull request to update.

**Comment by justineechen** [comment]
Would it be possible to have the file that was last hotspotted/mentioned in a code_command to persist on the right panel if the user scrolls? Right now if you scroll it goes back to the first file in the section like you mentioned.

**Comment by steven1046** [comment]
Yes, let me try to implement it.

**Comment by justineechen** [comment]
Yes! Thank you @steven1046
