### ISSUE TITLE
Firefox browser copy and paste produces two extra lines. 

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#775]
When using the copy & paste button with code files, after pasting there are two extra lines at the top of the file. This seems to be a browser specific issue because with Safari and Chrome on both the current OL site and the multipane site no extra lines are produced. But with Firefox on both the current OL site and the multipane site, two extra lines are produced.

**Comment by ellenwyllie** [comment]
It seems like this is a known issue with Firefox, but I haven't been able to find any fixes for it

**Comment by steven1046** [comment]
It should be fixed now by the PR.
