### ISSUE TITLE
Investigate issues with javadocs on iPad

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#781]
There is feedback that when clicking on `servlet.annotation` package a `batch` package is opened instead.  Another report is that when loading the `WebServlet` class, another class from the top of the list is loaded instead.

**Comment by k8vance88** [comment]
@natalie-bernhard please see if this is still an issue

**Comment by natalie-bernhard** [comment]
Could not recreate this behavior on iPad (tested on Safari and Chrome), closing this issue
