### ISSUE TITLE
Windows vs Mac: Panes are not the same width- Low priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#784]
Not sure if this is a huge issue or something preventable, but the actual size (100% zoom) on Windows and Mac are different (regardless the browser). 

<img width="1680" alt="screen shot 2018-11-14 at 12 32 45 pm" src="https://user-images.githubusercontent.com/18709242/48500676-6b754f80-e809-11e8-86df-7ed267908a73.png">

![image-3](https://user-images.githubusercontent.com/18709242/48500425-d6725680-e808-11e8-82d8-8a9b4ab81186.png)

**Comment by steven1046** [comment]
I just tested it on Chrome on Mac and Chrome on Windows and the columns were the same width for me.

**Comment by justineechen** [comment]
On Linux - Firefox at 100% zoom:
<img width="1680" alt="screen shot 2018-11-14 at 12 44 22 pm" src="https://user-images.githubusercontent.com/18709242/48505796-e5abd100-e815-11e8-8378-319c35dab263.png">

**Comment by justineechen** [comment]
On Linux - Chrome at 100% zoom:
<img width="1680" alt="screen shot 2018-11-14 at 4 12 31 pm" src="https://user-images.githubusercontent.com/18709242/48513698-72f92080-e82a-11e8-9cb7-4157c3fe4732.png">

**Comment by steven1046** [comment]
I could reproduce this yesterday but now for some reason I don't see the content overflowing the viewport on Windows anymore.

**Comment by steven1046** [comment]
I can't seem to reproduce it now, maybe it was fixed by another issue being fixed.
