### ISSUE TITLE
Hotspots should work for one line of code - High Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#799]
```
[role="code_command hotspot=1", subs="quotes"]
----
Action
----
```
and inline hotspot
```
[hotspot=7]Text
```

Hotspots with one line don't work, the code_command arrow does not get highlighted when the cursor is hovered over it and the code in the file in the code_column does not get highlighted.

**Comment by justineechen** [comment]
@steven1046 Would it be possible for the hotspots to support the tags that use for static guides?
So instead of hotspot=7-7, it could be hotspot=[tagname].

**Comment by steven1046** [comment]
Yes, it will be possible to just specify one line. Waiting until Friday to deliver fix to not update qa-guides-multipane.

**Comment by steven1046** [comment]
```The application module is defined by [hotspot=1]`consumeRestApp`.``` will work after the fix.

**Comment by gkwan-ibm** [comment]
@steven1046  how's about hotspot=[tagname]?

**Comment by steven1046** [comment]
The javascript doesn't know about tag names since we have to convert the whole asciidoc file into html to get it to show the whole file on the right side so I don't think we'll be able to use tag names for it.
