### ISSUE TITLE
Inconsistent new lines and words that are cut off in code_command arrow - Low priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#800]
```
[role="code_command hotspot=53-76", subs="quotes"]
----
The `docker-image` profile uses the `dockerfile-maven` plug-in, which automatically builds a Docker image from a `Dockerfile` that is located in the same directory as the `pom.xml` file.
----
pom.xml
[source, XML, linenums, role="code_column"]
----
include::finish/pom.xml[tags=**]
----
```

Shows:
<img width="824" alt="screen shot 2018-11-22 at 12 39 00 pm" src="https://user-images.githubusercontent.com/18709242/48917252-d2bb8100-ee53-11e8-9d8f-d74613632842.png">

**Comment by justineechen** [comment]
Based on the call today, this will be addressed @steven1046

**Comment by steven1046** [comment]
Another example from #820:
![image](https://user-images.githubusercontent.com/3322532/49295177-07ab8180-f4ad-11e8-9886-adb7c069bcd3.png)
"create" should go to the next line if it doesn't fit.

**Comment by steven1046** [comment]
@justineechen do you have any current examples of this bug? It seems like the text has changed in all of the code_command arrows since the creation and I'm having trouble finding an instance of the bug.

**Comment by ellenwyllie** [comment]
I looked through all the guides and couldn't find any examples of this bug so I'm going to close this issue.
