### ISSUE TITLE
The current implementation of code_command is not same as the design - Medium Priority

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/openliberty.io#801]
Based on the design at https://github.com/OpenLiberty/openliberty.io/issues/145 the code_command should be as following. The font of the word "Create" is different than the file path:
![screen shot 2018-11-23 at 11 24 07 am](https://user-images.githubusercontent.com/29576299/48953578-4ae97b80-ef14-11e8-9d0f-a12a43ec72b5.png)

But, the current implementation looks as following:
![screen shot 2018-11-23 at 11 36 21 am](https://user-images.githubusercontent.com/29576299/48953596-59379780-ef14-11e8-810d-78eb54e26288.png)

Can it be updated as the design? The font should be proportional by default. If the text is quoted by backtick, the font can be changed to monospaced.

**Comment by gkwan-ibm** [comment]
@lauracowen would you confirm the original design?

**Comment by lauracowen** [comment]
I think it's @megmulsy or @cajaygle you want.

**Comment by gkwan-ibm** [comment]
Consider this
![screen shot 2018-11-23 at 12 13 59 pm](https://user-images.githubusercontent.com/29576299/48954896-5e4b1580-ef19-11e8-9537-66c68ba7caf2.png)

**Comment by cajaygle** [comment]
Please use the following style for the code action boxes:

**Create the test class file.**
src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java

or:

**Update the server configuration file as shown.**
src/main/liberty/config/server.xml

Because the file paths are long it doesn't work well to use sentence phrasing.  Also, placing the file path on its own line will make it less likely that the line wraps and splits the path.

**Comment by cajaygle** [comment]
Regarding the snippet above to add the Health-1.0 feature, with the multi-pane design we no longer instruct users to modify the code one snippet at a time.  Instead changes are made at the entire file level so that they can copy and paste the entire updated file.

**Comment by gkwan-ibm** [comment]
> Regarding the snippet above to add the Health-1.0 feature, with the multi-pane design we no longer instruct users to modify the code one snippet at a time. Instead changes are made at the entire file level so that they can copy and paste the entire updated file.

It should pending on the situation. If need to add multi-lines in either one or multiple places in a file, we may consider to instruct user to replace the entire file. If just want user to add a line into a file (e.g. the above example), it makes sense to update/modify the existing file.

**Comment by gkwan-ibm** [comment]
> Please use the following style for the code action boxes:
> 
> **Create the test class file.**
> src/test/java/it/io/openliberty/guides/inventory/InventoryEndpointTest.java
> 
> or:
> 
> **Update the server configuration file as shown.**
> src/main/liberty/config/server.xml
> 
> Because the file paths are long it doesn't work well to use sentence phrasing. Also, placing the file path on its own line will make it less likely that the line wraps and splits the path.

@cajaygle May I assume the design should be like this for my example in above?  
![screen shot 2018-11-27 at 1 38 54 pm](https://user-images.githubusercontent.com/29576299/49103653-f31b7f00-f249-11e8-8779-082052277ba8.png)

There is still have a box to embed the instruction. The font of the text "Add ..."  will be proportional and the path "src\..." will be monospaced.

**Comment by justineechen** [comment]
In the meeting today, we discussed that the guides-dev team will look into having different fonts for the code_command.

**Comment by justineechen** [comment]
I don't think we intend on using bold in the commands for the guides but it'd be great if we can support multiple fonts.

**Comment by megmulsy** [comment]
@steven1046 
We should use font-family:Asap-SemiBold; font-size:14px;' for the top 'action' line 
and ' font-family:Courier-Regular; font-size:14px;' for the second 'code' line (s)

**Comment by steven1046** [comment]
Thank you!

**Comment by steven1046** [comment]
The first line can now be styled by using hashtags around it:
```
[role="code_command hotspot=18-106", subs="quotes"]
----
#Create the `ConsumingRestTest` class#
`src/test/java/it/io/openliberty/guides/consumingrest/ConsumingRestTest.java` 
----
```

![image](https://user-images.githubusercontent.com/6392944/50838735-59ed8700-1324-11e9-98d7-5c9f9ea2ecce.png)
