### ISSUE TITLE
Features reference docs has no scrollbars on embedded frames in Chromium/Linux

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#802]
Reported by @sdaschner. Running Chromium on Linux.

There are no visible scrollbars and the content is cut off:

![openliberty-screen1](https://user-images.githubusercontent.com/3322532/48954249-9d409180-ef40-11e8-9f21-1b22a0b312aa.png)

**Comment by kinueng** [comment]
@cajaygle and @megmulsy do you think we should add scrollbars per the description?

**Comment by mbroz2** [comment]
This needs to be addressed consistently across the site (scroll bars and their behavior).

**Comment by kinueng** [comment]
This is a really bad bug.  You have zero workaround to seeing the cut off content.

**Comment by lauracowen** [comment]
@NottyCode

**Comment by kinueng** [comment]
Related #865

**Comment by mdenby** [comment]
@cajaygle Melissa's notes (on Mac--working on PC tomorrow):

1. Server Config
• Sidebar scrollbar overalls into main copy
• Main copy cut off on the right
• No scrollbar shows for main copy

2. Server Features
• Main copy cut off on the right
• Scrollbar does show up for main copy
• No scrollbar for sidebar

3. Server Commands
• No scrollbar needed for sidebar
• Scrollbar shows for the main copy

4. JAVA and Microprofile
• Bottom sidebar scrollbar starts above section
• Scrollbar shows for main copy

It's odd that the page scrolls the area the user is in, until the scroll gets to the bottom--then the main page scrolls to footer. Wondering if main area should scroll the page--longer content--or if we were trying to keep the page a specific size--if so why not keep the footer visible all the time then?

**Comment by lauracowen** [comment]
I've seen the "scrolls the area the user is in, until the scroll gets to the bottom--then the main page scrolls to footer." behaviour on other sites and I don't have a problem with it, such as here: https://openliberty.io/docs/ref/config/ - I think that works nicely (I only find it annoying when the page is infinitely loading and the footer can never stay on the page, which isn't relevant here). I don't think we should keep the footer visible all the time because no one cares about the footer most of the time. Yes, it's important to be able to get to it for certain bits of info, but if we were to fix the footer on the page, we're restricted the amount of screen area that displays actual useful content (we already lose a chunk for the header), which gets frustrating when you're there primarily to read the content.

**Comment by cajaygle** [comment]
On Config, the footer is partially displayed when the page is loaded.  (I updated Melissa's comment above.)
<img width="1368" alt="screen shot 2019-02-19 at 10 03 04 am" src="https://user-images.githubusercontent.com/27516391/53024789-bf598b00-342d-11e9-8b1e-db354df7f5ca.png">

**Comment by mdenby** [comment]
So after meeting yesterday we would like to:

1. Remove the iframe from the main body copy. Having three scrollable areas is confusing. When the user scrolls through the main content it should just scroll the page.

2. In the sidebar, if it is scrollable, show a scrollbar all the time. 

3. For the footer, Jay likes the way it works on the Feature page. I'll double check the details on this one because I don't see exactly how it's different right now...

**Comment by ellenwyllie** [comment]
@mdenby @cajaygle Are the 4 items in the comment above for all docs pages or just for the config docs?

**Comment by mdenby** [comment]
@ellenwyllie For all the docs pages please.

**Comment by sdaschner** [comment]
Is this supposed to be online already? I still can't see scrollbars in my browser (what was the original issue)...

**Comment by ellenwyllie** [comment]
The scroll bar issues are being addressed as part of separate issues (#1128 - #1133). The original issue of the content being cut off was addressed here.

**Comment by sdaschner** [comment]
Got it, thanks! I've originally submitted the issues b/c it wasn't clear to me that the content is scrollable (due to missing bars), that's why I'm asking :-)
