### ISSUE TITLE
Overview pages for sections of doc

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#804]
Request from @sdaschner:
It would be very helpful to have small "homepages" for docs & references. E.g. when following Docs -> Features, users should see an overview page which briefly explains the features, what they are, what they do, etc.

**Comment by lauracowen** [comment]
> Hi @lauracowen,
> We now have overview pages for server config doc and server command doc. Is there a need for more overview pages?

Yes - as Sebastian says, we need one on the Features section too but we need to write it. (cc @NottyCode )

**Comment by mbroz2** [comment]
Duplicate of #489
