### ISSUE TITLE
Include current page heading in HTML titles

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#805]
Request from @sdaschner:
Can we include the name of the current page in the html title; it always only says "Open Liberty".

Particularly on docs pages. This is important for bookmarks etc.

**Comment by sdaschner** [comment]
The current page is still not included in the header, e.g. "Server Features" -> "Admin REST Connector". It would be nice if that simply could be concatenated; makes it easier if users have multiple tabs open (e.g. "Admin REST Connector - Server Features - Open Liberty").

@ellenwyllie I can't reopen the issues :(
