### ISSUE TITLE
Add tabs to the static multipane guides code pane

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#807]
See https://github.com/OpenLiberty/openliberty.io/issues/777#issuecomment-440749916 for the motive.

We want to add tabs to the code column for each file, so more than one file could be shown and switched to on a given guide section. Initially, the first tabs shown would be the first guide step a user goes to (initial step or a different step if using a hash value). The tabs will persist after they are added, and when scrolling to different steps with different files those tabs would be added to the code panel.

**Comment by gkwan-ibm** [comment]
What is the target?

**Comment by steven1046** [comment]
Probably Friday.
