### ISSUE TITLE
Server config overview page too wide

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#816]
Safari
iOS 12.x
iPhone Xs

![image](https://user-images.githubusercontent.com/31117513/49240967-21c16300-f3cc-11e8-9b50-ca172c3ca8c6.png)

**Comment by steven1046** [comment]
I can't reproduce the original problem.

**Comment by steven1046** [comment]
There is some white space to the right of the content and header but the content lines up with the header on my safari and ios emulator.

**Comment by steven1046** [comment]
The original problem seems fixed, probably by someone else changing the page for something else.
