### ISSUE TITLE
Update list of visible tags

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/openliberty.io#817]
We have a set of guides around EE technologies.  We need to add 'Java EE' to the list of visible tags so it is visible and can be found in search.

**Comment by ellenwyllie** [comment]
Java EE is already on the list of visible tags. Which guides should show that tag?

**Comment by yeekangc** [comment]
Sorry, @ellenwyllie, I misread the code.  You are correct; 'Java EE' is there.

I updated the adoc files for the guides to ensure that the tag is there for the relevant guides.  They should be picked up in the next refresh then.

By the way, I noticed that for a guide without any visible tags, we will still show the title, "Tags", but it will be an empty section.  Is that intentional?  Or, we should not show the title if there is no visible tag for a guide?
