### ISSUE TITLE
[Guides] Different triggers for section change for ToC and code panes - Low priority

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#818]
This is the point where the ToC highlight moves down to the next section:

![image](https://user-images.githubusercontent.com/3322532/49291707-21e06200-f4a3-11e8-95b8-db2360f73e97.png)

It feels like the code pane should've caught up by now:

![image](https://user-images.githubusercontent.com/3322532/49291766-4b998900-f4a3-11e8-9765-c3c4aa302d95.png)

But it doesn't until now:
![image](https://user-images.githubusercontent.com/3322532/49291795-5b18d200-f4a3-11e8-9aa4-a5259444acbf.png)

I *think* (but happy to be convinced otherwise) that the ToC highlight is changing far too soon. And then the code pane highlight is changing a couple of lines later than necessary (it's bang on where the heading reaches the top but my first scrolling instinct was to stop scrolling once the section heading was *near* the top of the screen and I wondered why the github command was still showing).

**Comment by mbroz2** [comment]
@lauracowen I tried to recreate and was unable to, can you verify if you're still seeing this behavior?  If you are still seeing the behavior, can you comment what browser and OS you're using (it might be a mac specific issue due to the scrolling code).

**Comment by lauracowen** [comment]
Sorry, missed this. I'm on Mac with Firefox.

I'm not sure if this happens any more but when I was testing it just now I noticed the ToC highlighting was updating oddly still. Scroll down the guide and the headings highlighted are not necessarily the heading coming up or currently displayed - it seems to jump ahead and back oddly:

![image](https://user-images.githubusercontent.com/3322532/56278845-e87d5b80-60fe-11e9-9f2d-f58d48b1f3de.png)

![image](https://user-images.githubusercontent.com/3322532/56278861-eddaa600-60fe-11e9-81cb-8aa935b46a64.png)

![image](https://user-images.githubusercontent.com/3322532/56278869-f4691d80-60fe-11e9-9440-23d76fd930b5.png)

![image](https://user-images.githubusercontent.com/3322532/56278879-f92dd180-60fe-11e9-966b-f99263bdee0c.png)

![image](https://user-images.githubusercontent.com/3322532/56278894-fe8b1c00-60fe-11e9-8cd6-d5e09c4e153c.png)

![image](https://user-images.githubusercontent.com/3322532/56278900-03e86680-60ff-11e9-826f-ed1d9ef9d2f7.png)

![image](https://user-images.githubusercontent.com/3322532/56278915-09de4780-60ff-11e9-9d45-6d3a2eacffcd.png)
