### ISSUE TITLE
[multipane] server.xml should not say 'replace' in the 'getting-started' guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#819]
https://qa-guides-multipane.mybluemix.net/guides/getting-started.html#updating-the-server-configuration-without-restarting-the-server 

The action of editing the `server.xml` file here is part of the learning experience. I don't think it's appropriate to tell them to "replace the server.xml". The whole point of the step (here: https://openliberty.io/guides/getting-started.html#updating-the-server-configuration-without-restarting-the-server) is for the user to change an entry in the server.xml and know how much of it has/hasn't changed. Replacing the whole file negates the learning part of this step.

I see this was changed for the multipane format. Can the `server.xml` show the updated version and the text label just give the same instruction as the old format guide "add the mpHealth feature"?

(This comment is specific to this guide; see also: https://github.com/OpenLiberty/openliberty.io/issues/815#issuecomment-443200012)

**Comment by lauracowen** [comment]
Comment for Design @megmulsy @cajaygle  (I've not been involved in the discussions so this may have been talked about and rejected):

I noticed when hovering over the arrow that it highlighted and the content of the code pane is highlighted:

![image](https://user-images.githubusercontent.com/3322532/49292641-c2378600-f4a5-11e8-988b-b318ec0b6e71.png)

Would it make sense, in this context, to just highlight the line that's been added?

I know that might be opening a floodgate of implications/problems so it's just a question. Also, I don't want the guides in general to get into the practice of each step adding a new line. I think we need to stick to the style we currently have in general. But there are specific places where making a specific change is something the developer would have to do in real life (such as this server.xml change or the changes in the Spring migration guide).

**Comment by lauracowen** [comment]
Oo... [Laura's adventure of discovery continues!]

I just found that you do have some interaction between the middle and code panes already, like when you click the file and element names here:
![image](https://user-images.githubusercontent.com/3322532/49294946-4bea5200-f4ac-11e8-80ce-e2b89d2c8adb.png)

That's cool. Though I wonder if the normal <code> tags should have such prominent background highlighting (the clickable filename/elementname don't stand out as different from them)?

Also, the `pom.xml` click didn't do anything but I think that's maybe related to the #815 display thing.

**Comment by lauracowen** [comment]
Though the `<looseApplication>` element highlights two lines in the code pane - I think I'd expect it to highlight only the `<looseApplication>` line:

![image](https://user-images.githubusercontent.com/3322532/49295090-c4511300-f4ac-11e8-9b85-713dd8d45882.png)

**Comment by lauracowen** [comment]
Sorry - I can split this into separate issues if you want me to?

**Comment by justineechen** [comment]
Thanks Laura! We have an issue open for hot spotting one line here: https://github.com/OpenLiberty/openliberty.io/issues/799

**Comment by justineechen** [comment]
> Would it make sense, in this context, to just highlight the line that's been added?
We can actually edit this ourselves, so when I created the code_command, I put in all the lines of code from 1-end of file. But you're right, if we're asking users to add in one line I shouldn't be using the word `replace` and I should only be highlighting that one line. I'll update the multipane branch on that guide now.

**Comment by justineechen** [comment]
I've updated the README for 'getting-started': https://github.com/OpenLiberty/guide-getting-started/commit/4c2daf6b679bcd00eaeef49937bc44247b1038c8
