### ISSUE TITLE
[multipane] Minor wordwrap problem

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#820]
![image](https://user-images.githubusercontent.com/3322532/49295177-07ab8180-f4ad-11e8-9886-adb7c069bcd3.png)
"create" should go to the next line if it doesn't fit.

**Comment by justineechen** [comment]
There is a similar/duplicate issue here: https://github.com/OpenLiberty/openliberty.io/issues/800

**Comment by steven1046** [comment]
Duplicate - combining this into #800
