### ISSUE TITLE
[Static guides] Examples are more prominent than actions the reader needs to take

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#821]
getting-started guide

(this applies to other sections but I noticed it most here)

The bit `<logging traceSpecification="<component_1>=<level>:<component_2>=<level>:..."/>` looks really prominent like it's some action I need to take but it's not clear what.

Then when I get to "Try enabling detailed logging of the MicroProfile Health feature by adding the logging element." I nearly missed it as it looked really hidden (even the active clickable bit).

![image](https://user-images.githubusercontent.com/3322532/49297228-324c0900-f4b2-11e8-9dd2-bb710bae9ec3.png)

**Comment by TreeHanh** [comment]
Issue has been fixed. 

<img width="569" alt="Screen Shot 2019-03-14 at 12 17 02 PM" src="https://user-images.githubusercontent.com/18586040/54373187-35c76280-4653-11e9-9fcd-647a88618e04.png">
