### ISSUE TITLE
Indentation for multi-platform does not match current OL site - High priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#825]
The indentation for multi-platform on the current OL site:

<img width="1680" alt="screen shot 2018-12-03 at 12 39 05 pm" src="https://user-images.githubusercontent.com/18709242/49391040-86e0c580-f6f8-11e8-8468-525bd319ceb3.png">

What is showing on the multipane site: 
<img width="1680" alt="screen shot 2018-12-03 at 12 39 32 pm" src="https://user-images.githubusercontent.com/18709242/49391042-87795c00-f6f8-11e8-9770-0fbe6a49f177.png">

**Comment by justineechen** [comment]
At the very least, the multipane site should show the indentations to match the OL site but a better design could also be suggested so that users will be able to clearly distinguish between instructions based off of their platform.

See this issue for concerns about the original design: https://github.com/OpenLiberty/guides-common/issues/179

**Comment by steven1046** [comment]
In the call today, we discussed that we need to port over the indention styling from the old layout to the new multipane layout. One of the guides that uses the indention currently is https://openliberty.io/guides/kubernetes-intro.html.

**Comment by steven1046** [comment]
Fixed: https://qa-guides-multipane.mybluemix.net/guides/kubernetes-intro.html#prerequisites
