### ISSUE TITLE
Secure Engineering

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#84]
Implement secure engineering, which consists of:

- Required to ensure our public sites are secure.
- Threat model
- Secure code review
- Automated AppScan of code and web scan (or something equivalent)
- Up to date security patches for any prereqs
- Assess whether there are private backend services being called, and security implications.

**Comment by mchenggit** [comment]
Reminder that due date is March 30, 2018

**Comment by steven1046** [comment]
@mchenggit do you know what needs to be done for this work item?
