### ISSUE TITLE
Code_command arrow behaviour when [role='command'] is used in the same subsection - High priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#844]
This code_command arrow does not look as it's supposed to:
<img width="584" alt="screen shot 2018-12-16 at 10 50 50 am" src="https://user-images.githubusercontent.com/18709242/50171489-977c6880-02c0-11e9-9fb7-414c02b8d79d.png">

The JSON file it corresponds to also does not appear in the right panel. Not sure if this is because of the file or something to do with the arrow behavior not working completely.

**Comment by steven1046** [comment]
It should be fixed: https://qa-guides-multipane.mybluemix.net/guides/microprofile-fallback.html#building-and-running-the-application
