### ISSUE TITLE
Multi-lined hotspots that are not adjacent - High priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#845]
We will need hotspotting to work on lines that are not adjacent for scenarios like this, where we need users to add two annotations to two separate functions in the same file.
(This is in the JWT guide in Securing the inventory service)

<img width="1680" alt="screen shot 2018-12-18 at 12 35 24 pm" src="https://user-images.githubusercontent.com/18709242/50171837-8ed86200-02c1-11e9-9f7e-d27ae817d7e1.png">

**Comment by steven1046** [comment]
Hotspots will now work for multiple lines of code:
For inline hotspots just add another hotspot keyword:
```
This bean contains three simple functions. The [hotspot=21-23 hotspot=25-27 file=0]`get()` function is for retrieving entries from calling the `system` service.
```

For the listing block, it will be the same manner:
```
[role="code_command hotspot=5 hotspot=14-39", subs="quotes"]
----
Create the `InventoryManager` class.
`src/main/java/io/openliberty/guides/inventory/InventoryManager.java`
----
```

**Comment by steven1046** [comment]
@justineechen just making sure you saw this ^.

**Comment by justineechen** [comment]
Thank you! @steven1046
