### ISSUE TITLE
Links do not open in new tab - Medium Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#846]
Links that are clicked in the guide do no open in a new tab, this could disrupt the flow for the user. Would it be possible for us to change all links to open in a new tab or window? 
@cajaygle @steven1046 @lauracowen

**Comment by lauracowen** [comment]
I believe this was on purpose because opening in new tabs can be seen as taking control away from the user. If someone wants to follow a link, they can (and will). If people want to work in multiple tabs, they will.

cc @NottyCode

**Comment by lauracowen** [comment]
However, @NottyCode tells me the design was to open external URLs in new tabs so I'll butt out now and let @cajaygle  respond for definite. :)

**Comment by steven1046** [comment]
We do have a precedence on the rest of the site if a link is for an external site then we open it in a new tab.

**Comment by justineechen** [comment]
@NottyCode @cajaygle Is there a decision for this so it can be implemented before multipane is published? Thanks!

**Comment by steven1046** [comment]
One way to do this is in asciidoc by specifying window="_blank":
```https://somewebsite.com[display_name, window="_blank"]```

**Comment by cajaygle** [comment]
Internal links open in same tab, external links open in new tab.

**Comment by mbroz2** [comment]
Closing issue; see above for how (and when) to open links in new tabs.
