### ISSUE TITLE
Link that is not clickable - Low priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#847]
Is it possible to implement a link that is not clickable by the user? 
For example, the link here would be grayed out and not clickable: 
![image](https://user-images.githubusercontent.com/18709242/50364595-ab350280-053e-11e9-9fc0-49cef030a8f1.png)

**Comment by steven1046** [comment]
Yes, one option is to add a class to the URL to disable:
```
If you are interested in learning more about REST services and how you can write them, read
[unclickable]#https://openliberty.io/guides/rest-intro.html[Creating a RESTful web service]#.
```

**Comment by steven1046** [comment]
Fixed using a backslash in the asciidoc.
