### ISSUE TITLE
guide-microprofile-opentracing feedback

### ISSUE THREAD

**Issue by AidanPolese** [OpenLiberty/openliberty.io#849]
### Checklist for Review
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present
- [ ] Any links are hyperlinks with the webpage title not the URL
- [ ] Feature versions should not be included in the guide
**In the README.adoc:**
- [ ] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
    - [ ] start directory
    - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by AidanPolese** [comment]
Section: Existing Tracer implementation
not sure if "Maven plug-in" is pointing to the correct code

Section: Enabling distributed tracing
@Traced does not got highlighted 
-The MicroProfile OpenTracing feature enables tracing of all JAX-RS methods by default. To further control and customize these traces, use the @Traced annotation to enable and disable tracing of particular methods. You can also inject a custom Tracer object to create and customize spans.

server.xml doesn't get highlighted
-Because tracing of all JAX-RS methods is enabled by default, you need only to enable MicroProfile OpenTracing and the Zipkin user feature in the server.xml file to see some basic traces in Zipkin.

@Traced does not got highlighted 
-Use the @Traced annotation to define explicit span creation for specific classes and methods. If you place the annotation on a class, then it’s automatically applied to all methods within that class. If you place the annotation on a method, then it overrides the class annotation if one exists.

@Traced does not got highlighted 
-The @Traced annotation can be configured with the following two parameters:

listContents() InventoryResource list() InventoryManager don't highlight
-Next, run the mvn compile command from the start directory to recompile your services. Point to the http://localhost:9081/inventory/systems URL, check your Zipkin server, and sort the traces by newest first. You see a new trace record that is two spans long with one span for the listContents() JAX-RS method in the InventoryResource class and another span for the list() method in the InventoryManager class. Verify that these spans have the following names:

getProperties() SystemResource getPropertiesForHost() InventoryResource addToInventoryList() dont highlight
-Next, run the mvn compile command from the start directory to recompile your services. Point to the http://localhost:9081/inventory/systems/localhost URL, check your Zipkin server, and sort the traces by newest first. You see two new trace records, one for the system service and one for the inventory service. The system trace contains one span for the getProperties() method in the SystemResource class. The inventory trace contains two spans. The first span is for the getPropertiesForHost() method in the InventoryResource class. The second span is the custom span that you created around the addToInventoryList() call. Verify that all of these spans have the following names:

In .travis.yaml
- mvn clean install does not have -q

Pom.xml

Failsafe and Surefire are not the correct versions in start and finish

<parent>
        <groupId>net.wasdev.wlp.maven.parent</groupId>
        <artifactId>liberty-maven-app-parent</artifactId>
        <version>RELEASE</version>
    </parent>
missing from start and finish POM

liberty-maven-version plugin version still remains in start and finish

**Comment by justineechen** [comment]
This feedback was a part of multipane conversion, the issues have addressed and more information can be found in the guide repo's issue for multipane.
