### ISSUE TITLE
Guide-microprofile-rest-client feeback

### ISSUE THREAD

**Issue by AidanPolese** [OpenLiberty/openliberty.io#851]
### Checklist for Review
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present
- [ ] Any links are hyperlinks with the webpage title not the URL
- [ ] Feature versions should not be included in the guide
**In the README.adoc:**
- [ ] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
    - [ ] start directory
    - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

```
Section: Writing the RESTful client interface

SystemClient does not highlight 
-When the getProperties() method is invoked, the SystemClient instance sends a GET request to the <baseUrl>/properties endpoint.

Secrion: Injecting the client with dependency injection

both instances of SystemClient dont hihglight the interface 
-Now, instantiate the SystemClient interface and use it in the inventory service. If you want to connect only with the default host name, you can easily instantiate the SystemClient with CDI annotations. CDI injection simplifies the process of bootstrapping the client.

SystemClient, pom.xml, and server.xml don't highlight
-First, you need to define the base URL of the SystemClient instance. Configure the default base URL with the MicroProfile Config feature. This feature is enabled for you in both server.xml and pom.xml files.

io.openliberty.guides.inventory.client.SystemClient/mp-rest/url doesn't highlight
-The config property to add the base URL is <fullyQualifiedInterfaceName>/mp-rest/url. In this case, add the config property io.openliberty.guides.inventory.client.SystemClient/mp-rest/url. Configure this property to the default http://localhost:9080/system base URL:

InventoryManager doesn't highlight
-Inject the SystemClient interface into the InventoryManager class, which is another CDI managed bean.

InventoryManager class doesn't highlight
-@Inject and @RestClient annotations inject an instance of the SystemClient called defaultRestClient to the InventoryManager class.

Section: Building and running the application

pom.xml doesn't get highlighted
-This goal starts an Open Liberty server instance. Your Maven pom.xml is already configured to start the application in this server instance. 
```

**Comment by justineechen** [comment]
This feedback was a part of multipane conversion, the issues have addressed and more information can be found in the guide repo's issue for multipane.
