### ISSUE TITLE
Table vertical alignment not clear

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/openliberty.io#855]
eg https://openliberty.io/docs/ref/command/#runnablejarfiles.html

The rows are alternately shaded to show row boundaries but the shading is not clearly rendered on all displays. The contents of the cells need to be top-aligned (not center-aligned).

Or consider whether to have row borders? @cajaygle 

eg on a Mac laptop screen:
![image from ios 1](https://user-images.githubusercontent.com/3322532/50652147-6f0d9300-0f7d-11e9-9a0e-7e18686a54f1.jpg)

versus on an external LCD monitor:
![image from ios](https://user-images.githubusercontent.com/3322532/50652150-72a11a00-0f7d-11e9-90d1-4add77b20a8a.jpg)

cc @NottyCode

**Comment by TreeHanh** [comment]
We decided to go with the cell borders and the contents of the cell are now top-aligned.

![lines](https://user-images.githubusercontent.com/18586040/53915450-ea4afe00-402d-11e9-80d4-96957af4c952.jpg)
