### ISSUE TITLE
guide-cors feedback

### ISSUE THREAD

**Issue by AidanPolese** [OpenLiberty/openliberty.io#861]
### Checklist for Review
**Through the browser:**
- [x] Read over guide and run through all commands (copy and paste using browser etc..)
- [x] Test the actual application (use it, hit endpoints, etc.)
- [x] No files in the middle panel (guide section)
- [x] Appropriate files are being displayed on the right hand side at the right time
- [x] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [x] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [x] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [x] Guide attribution is present
- [x] Any links are hyperlinks with the webpage title not the URL
- [x] Feature versions should not be included in the guide
**In the README.adoc:**
- [x] Tags in the front matter are correct (MicroProfile, Maven, Docker, Kubernetes, Gradle, Java EE)
    - [x] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [x] Failsafe plugin and Surefire plugin updates if applicable
- [x] Parent POM update
    - [x] start directory
    - [x] finish directory
- [x] Files are formatted correctly
- [x] .travis.yaml file is updated accordingly

```
When code gets highlighted, the two files to pick from disappear and can no longer be selected.  They only return when scorlling in the left pane (the pane with instructions in it)

section: Enabling CORS

This flag only points to a funtion of the class.  It should hihglight the whole class
-Edit the TestCors class src/test/java/it/io/openliberty/guides/cors/TestCors.java

It also doesn't say to add the test testSimpleCorsRequest, not explicit enough.

Be more explicit about adding

OPTIONS highlights the wrong code i think
```

**Comment by justineechen** [comment]
This feedback was a part of multipane conversion, the issues have addressed and more information can be found in the guide repo's issue for multipane.
