### ISSUE TITLE
Long hotspots do not wrap - Medium Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#864]
Hotspots that are longer than the middle pane will get cut off.
<img width="1680" alt="screen shot 2019-01-04 at 4 19 31 pm" src="https://user-images.githubusercontent.com/18709242/50711567-9b3c1900-103c-11e9-9cba-f35b40218fde.png">

**Comment by justineechen** [comment]
After discussing this with @cajaygle, we will manually word wrap long paths and make them into separate hotspots in the README.

**Comment by justineechen** [comment]
After discussing this with @cajaygle, we will manually word wrap long paths and make them into separate hotspots in the README.

This is the proposed fix:
```
The DAO is injected into `finish/backendServices/src/main/java/io/`
`openliberty/guides/events/resource/filename.java`
```
@lauracowen @yeekangc @gkwan-ibm

**Comment by yeekangc** [comment]
@justineechen, is there a screen cap or sample of how this will look?

How does it behave when window is resized or the guide is viewed from mobile device?

**Comment by justineechen** [comment]
@cajaygle @yeekangc 
This is how it looks when the table of contents is on the left:
<img width="1680" alt="screen shot 2019-01-09 at 10 14 01 am" src="https://user-images.githubusercontent.com/18709242/50908258-5bd44a80-13f7-11e9-9e23-11609e4c6cf0.png">

However when we minimize the table of contents the spacing isn't quite right:
<img width="1680" alt="screen shot 2019-01-09 at 10 14 10 am" src="https://user-images.githubusercontent.com/18709242/50908281-65f64900-13f7-11e9-8eb4-17e7891db705.png">

**Comment by justineechen** [comment]
https://qa-guides-multipane.mybluemix.net/guides/jpa-intro.html#performing-crud-operations-using-jpa
https://qa-guides-multipane.mybluemix.net/guides/microprofile-health.html

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/openliberty.io/pull/928

**Comment by cajaygle** [comment]
It's awkward the way it is on the QA site currently.  Guide authors shouldn't need to do anything except make a single hotspot.  Hopefully #928 takes care of this.

**Comment by steven1046** [comment]
@justineechen it should be fixed now on qa-guides-multipane.
