### ISSUE TITLE
Load the last tab viewed with a hotspot/click

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#868]
When scrolling to a step already seen, show the tab that was previously viewed.

**Comment by justineechen** [comment]
"In the later guides, the pom.xml came into focus when it should have been the java code.  I think there may have been other similar focus problems" - Feedback from Graham Charters

I think this issue addresses this feedback ^

**Comment by steven1046** [comment]
Thanks, i think the latest pull request should address this.
