### ISSUE TITLE
Create a new category on the Reference docs page

### ISSUE THREAD

**Issue by bsbyrd1** [OpenLiberty/openliberty.io#887]
Create a new category on the Reference docs page, where newly written concepts and references can be organized. There are some concepts and references that don't fit in the existing categories, and it would make our content more findable if the topics were published in a growing hierarchy. It might be sparse to start, and I expect to iterate on the category itself, but it at least gives developers a better chance of finding our content.

**Comment by cajaygle** [comment]
Here is the plan for a temporary design.  We will add a new card to the current Reference Docs section labeled **General reference**.   the URL will follow this form, similar to other reference categories: /docs/ref/general/#rol_Java11.html.   the breadcrumb will be Docs > Reference > General > Java SE support in Open Liberty.  The Reference dropdown in the nav bar will have a General entry.  The General Reference page will have the same layout as the Server Commands page.  This is not an ideal solution but it is a temporary solution that allows us to start publishing these types of references docs.

**Comment by steven1046** [comment]
Just a note for the developers, the > General > in the breadcrumb should link to /docs/#general so it scrolls to the general reference section of the /docs/ page and also the Reference link in the breadcrumb should link to /docs/#docs_container which is where the cards are. I think this was in one of the redlines and was missed.

**Comment by mbroz2** [comment]
Note: the General References page will have no Overview or header in the TOC (like https://www.openliberty.io/docs/ref/feature/) so the user will land on the first item in the list, which will be the Java Support doc.

**Comment by bsbyrd1** [comment]
@ellenwyllie Thanks for picking this one up. Is there an outlook on the Reference category being published? Thanks!

**Comment by ellenwyllie** [comment]
@bsbyrd1 It is currently on our staging site: https://openlibertydev.mybluemix.net/docs/ref/general. I just made a small fix so we should be publishing soon!
