### ISSUE TITLE
[Static guides] Text box word wrapping - Low Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#895]
https://qa-guides-multipane.mybluemix.net/guides/kubernetes-intro.html#building-and-containerizing-the-microservices

![image](https://user-images.githubusercontent.com/18709242/51333364-8bb0cd00-1a4b-11e9-8a40-e845d45ad5db.png)

Would there be a way to format this differently so it would look more readable? 
This isn't very high priority because it's checking if the output matches and there is just too much text for when the window is collapsed.

**Comment by ellenwyllie** [comment]
It looks like all the text in that box is a single element with the spaces hard coded in so I don't think there's anything we can do unless we change that.

**Comment by mbroz2** [comment]
perhaps a way to allow a guide author to specify a min-width for a code block, after which it would render a horizontal scrollbar?

**Comment by mbroz2** [comment]
May be related to #1200
