### ISSUE TITLE
Hide the current page from the navigation bar

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#91]
When the user navigates to a certain page, that page option should disappear on the nav (because there's no point). For example, if the user is on the Community page, 'community' should not be in the site nav at the top.

**Comment by lauracowen** [comment]
Isn't it more usual to leave it there but have it highlighted to show where you are relative to the rest of the site? Or am I misunderstanding this issue?

**Comment by kinueng** [comment]
@lauracowen 
This issue was per design.  When I showed various people in the office the hiding of the current page in the nav bar, users thought it was weird to see the button disappear after clicking.  I relayed the feedback to design and have sense paused on going forward with this issue.

**Comment by steven1046** [comment]
I think it would be weird for tabs to disappear, especially if the user saw it once and then goes to the link and doesn't see it again. We've had users in the past on another project comment when something wasn't consistent and it's good that we provide a consistent experience all the time when the user expects something to stay the same.

**Comment by kinueng** [comment]
Based on the several recent redlines, this issue is no longer needed.
