### ISSUE TITLE
Redesign of the guide page

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#92]
# Description
Redesign the guide page to from a long white area to multiple cards.
# Preview
![image](https://user-images.githubusercontent.com/31117513/33863605-24103354-deae-11e7-96c8-97b67c707965.png)

**Comment by megmulsy** [comment]
Hey Kevin - this design will only be used when the browser is so small that a two panel solution isn't the best idea. 

Some updates to the cards were just approved by the guides team. Please disregard the lefthand nav - the changes that need to be made are in the structure of the information inside the cards. There are areas that call out the instructions. 'Non-copiable' areas are outlined in blue w a white background - they should not be made copiable on hover, as per request from the Docs team. 

Guides Single Page Card Formatting  
PNG: https://ibm.box.com/s/or1al6guj5dzyybtvv3x6jlkzyzc5bmn
(with markups)- https://ibm.box.com/s/s2909qy1vahq5n8ak6ilvfw5wzv42oia
Redlines: https://ibm.box.com/s/jfafi1mc36mgwr9295wjs10owpjnt2bm

I've also updated this boxnote here w all of this same info: https://ibm.box.com/s/71569ald8apgs5l57rc4x4m9fp2xzwg8

**Comment by kevinwlau** [comment]
@megmulsy Is the two-panel solution is still under the design process right now?

For the instruction piece, I believe all the guides' asciidoc must be updated to call out the instructions - currently there is no way to differentiate the instructions from any other generic paragraph.

**Comment by kevinwlau** [comment]
Also, I noticed there are two different styles for the code blocks. Is there anything differentiating the two?

![image](https://user-images.githubusercontent.com/689163/35122394-3bf7b784-fc64-11e7-80bd-69e60ee2f63f.png)
