### ISSUE TITLE
Support images from guides

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#935]
We need to update the guide clone script to handle images coming from different guides, and how to handle intersection of duplicate image names.

**Comment by kinueng** [comment]
The alternative is to keep images in each guide repository and revisit #120

**Comment by steven1046** [comment]
The reason we need to copy over the images to a central location when cloning the guides repos, is so that the guide's path doesn't have to be hardcoded in the asciidoc for the guide.

**Comment by evelinec** [comment]
@steven1046 @kinueng any update on this issue? We have a guide that we may publish this cycle that depends on this issue.

**Comment by steven1046** [comment]
Hi @evelinec, what is the target release for that particular guide?

**Comment by evelinec** [comment]
> Hi @evelinec, what is the target release for that particular guide?

3/29

**Comment by evelinec** [comment]
Tested on local environment with the UI code. The image is scaled properly now. But still need to copy the image manually. @steven1046 said the images will be handled properly at the build process.
