### ISSUE TITLE
Remove /about page and redirect to homepage

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#939]
The About page essentially hasn't been updated since our launch.

**Comment by BachAmadou** [comment]
Hello sir, 
Im Bachir please, i would like to contribute to the issue. Is it still available? thank you

**Comment by mbroz2** [comment]
Once the new homepage redesign goes live, we'll remove all links to the about page.

The link will remain accessible until doc page is updated with new content, at which point /about will redirect to it (not part of this issue unless the doc update happens before the home page redesign occurs)

**Comment by mbroz2** [comment]
The content that this /about would redirect to is tracked under https://github.com/OpenLiberty/docs/issues/223

**Comment by mbroz2** [comment]
/about should be removed and instead redirect to the homepage.

**Comment by mbroz2** [comment]
Consider doing at the same time as #1505
