### ISSUE TITLE
Float off the code column when at the end of guide

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#947]
We need to float away the code column like the toc and guide column do when scrolling into the end of guide section.

**Comment by steven1046** [comment]
I had attempted this issue on branch `Code_Column_Scroll_Away` and it partly works but do we want the code tabs to scroll away? It also makes the Circuit breaker playground and other interactive guide playgrounds unusable once the right side starts scrolling out of view.

**Comment by mbroz2** [comment]
No impact on end user, and large development effort to make changes (also would introduce new issues in interactive guides).
