### ISSUE TITLE
Change interactive guide code actions.

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#948]
Change from:
<img width="367" alt="screen shot 2019-02-01 at 3 40 52 pm" src="https://user-images.githubusercontent.com/27516391/52148800-d0865780-2638-11e9-85ec-18f2340b7ab0.png">

to:
<img width="351" alt="screen shot 2019-02-01 at 3 41 09 pm" src="https://user-images.githubusercontent.com/27516391/52148807-d3814800-2638-11e9-9846-9c2072fdc39e.png">

This change comes as a result of user testing where some users tried to copy the code from the button in order to paste it in the editor, and in the process they clicked the button.  In the tweaked design, the code block is separated from the Change/Add button.  If the user hovers over the code block they get the Copy to clipboard action icon.  Clicking in the code block has no effect.

For add actions, the button label would be Add:
<img width="351" alt="screen shot 2019-02-01 at 3 41 09 pm" src="https://user-images.githubusercontent.com/27516391/52148975-691cd780-2639-11e9-8a68-3a531ee405dc.png">

When laying out the code block we should use a set minimum width independent of the size of the code.  That is, don't shrink the code block to the text size, as seen in the Add example.   We should also set a maximum code block width so that if the instruction pane is very wide, the code block is not as wide.   About 280px minimum -- I think that's about right given the minimum instruction pane width.  And about 600px maximum -- I don't think we have blocks wider than that now.

As part of this change, the Add/Change buttons are disabled immediately after they are clicked -- to help signal to the user that code has been inserted into the editor.  But the entire action section isn't disabled until the Run button is pressed.

Lastly, for code Change scenarios we can use a hotspot to show the existing code that is to be changed.  As shown in the Change scenario above, @ CircuitBreaker is a hotspot that highlights the current code.  In the Add scenario @ CircuitBreaker is not a hotspot.

**Comment by cajaygle** [comment]
#F1F4FE for the code block background color, and #C8D5FF for the border color.

**Comment by dmorgant** [comment]
Issue moved to [OpenLiberty/iguides-common #322](https://github.com/OpenLiberty/iguides-common/issues/322) via [**ZenHub**](https://www.zenhub.com/)
