### ISSUE TITLE
Design change for interactive guide URL actions

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#950]
In the interactive guides, change the format of URL actions from:

![Screen Shot 2019-02-02 at 5.17.13 PM.png](https://images.zenhubusercontent.com/5a9815324b5806bc2bc8fac2/55892110-a683-48e4-821a-581804264731)

to:
![Screen Shot 2019-02-02 at 5.17.19 PM.png](https://images.zenhubusercontent.com/5a9815324b5806bc2bc8fac2/65fef9c9-2d24-4cd6-a1db-bbd7c667a4ed)

This change is a result of user testing where users had difficulty copying text from the action button.  One user also failed to click the Enter button.  This change provides a single button to open the page but also allows the user to copy and paste the URL if they wish.

Note I changed the wording to refer to the "sample bank app browser" to make it more clear that they shouldn't enter the URL into their real browser.  Feel free to tweak the wording.

**Comment by dmorgant** [comment]
Issue moved to [OpenLiberty/iguides-common #321](https://github.com/OpenLiberty/iguides-common/issues/321) via [**ZenHub**](https://www.zenhub.com/)
