### ISSUE TITLE
Restore dev site indicator in nav bar

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#954]
We need to restore the dev site indicator in our nav bar.

See
https://github.com/OpenLiberty/openliberty.io/blob/master/src/main/content/_assets/js/devEnvironment.js

**Comment by kinueng** [comment]
This issue is only partially fixed.  We are still missing the indicator on the homepage and any non-doc page.

**Comment by ellenwyllie** [comment]
This issue should be fully fixed by #980

**Comment by kinueng** [comment]
Fixed by #981
