### ISSUE TITLE
font-family fallback

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/openliberty.io#963]
Currently our default font-family is Asap, with no fallback; therefore if Asap fails to load, the site is rendered in the browser's default font. 
Instead, we should have a graceful fallback to other fonts, so something like:
font-family: Asap, Helvetica, Arial, sans-serif;

We'll need design to decide what the fallback should be.

**Comment by TreeHanh** [comment]
These will be the fallback fonts for Asap and Bunuelo.
Font-family:  Asap, Trebuchet MS, Helvetica, Arial;
Font-family:  Bunuelo, Arial Narrow, Helvetica, Arial;

**Comment by steven1046** [comment]
@TreeHanh should Arial Narrow, Helvetica, and Arial be the fallback fonts for both Bunuelo light and Bunuelo Bold?

**Comment by TreeHanh** [comment]
@steven1046 Yes it should be for both
