### ISSUE TITLE
Blogs - Support `Note:` syntax

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#968]
We are not properly rendering Asciidoc's Admonition syntax on openliberty.io.
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#paragraphs

Example of `Note: `
https://github.com/OpenLiberty/blogs/blob/master/publish/2019-02-06-java-11.adoc

On GitHub.com
![image.png](https://images.zenhubusercontent.com/59d7b56bb0222d5de47a9368/1462a6d4-04d0-48a6-9a03-5d667995df01)

On openliberty.io
![image.png](https://images.zenhubusercontent.com/59d7b56bb0222d5de47a9368/47c51080-21dd-4412-aba0-71fefc9186f4)

**Comment by kinueng** [comment]
We also need designs for `Note: ` syntax for the new General Reference documentation.  Currently they look like..

![image](https://user-images.githubusercontent.com/31117513/53103735-c0ed8680-34f3-11e9-80f4-ddd61264c62c.png)

**Comment by TreeHanh** [comment]
"Note" support on blogs and General Reference Documentation.

![7_Blog_Post_Desktop_Notes](https://user-images.githubusercontent.com/18586040/54223779-9e390700-44ce-11e9-8d78-b8e7d6f30d7e.jpg)

![Notes](https://user-images.githubusercontent.com/18586040/54223784-a002ca80-44ce-11e9-80da-ae1b1306385d.jpg)
