### ISSUE TITLE
Upgrade Liberty version monthly instead of quarterly

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#972]
By default, openliberty.io is running on the Liberty `quarterly` release from the buildpack.  Consider enabling the usage of the Liberty `monthly` release.  

To start using the `monthly` release...
```
To use the V19.0.01 Liberty monthly release, you must set the following environment variables:
JBP_CONFIG_LIBERTY = 'version: +'
IBM_LIBERTY_MONTHLY = true
```
19001 buildpack announcement
https://console.bluemix.net/status/notification/d5ebe0fb74647bcf134512e304e75588

**Comment by steven1046** [comment]
The link is expired, if we put +, will it be automatic each month?

**Comment by steven1046** [comment]
Let's test this out on the draft pipeline and wait 3 months to see if it builds fine without manual interaction with the version.

**Comment by steven1046** [comment]
I added the properties to the openliberty.io draft pipeline and it seems to be working:
Setting env variable 'JBP_CONFIG_LIBERTY' to 'version: +' for app draft-openlibertyio in org WASdev2 / space Open Liberty as mbroz@us.ibm.com...
OK
TIP: Use 'cf restage draft-openlibertyio' to ensure your env variable changes take effect
Setting env variable 'IBM_LIBERTY_MONTHLY' to 'true' for app draft-openlibertyio in org WASdev2 / space Open Liberty as mbroz@us.ibm.com...
OK

Let's wait another month to see if it updates to the latest Liberty version.

**Comment by steven1046** [comment]
I added 

`cf set-env "${CF_APP}" JBP_CONFIG_LIBERTY "[version: +, app_archive: {features: [jaxrs-2.1,cdi-2.0,concurrent-1.0,jsonb-1.0,webCache-1.0,mpRestClient-1.3,concurrent-1.0]}]"`
`cf set-env "${CF_APP}" IBM_LIBERTY_MONTHLY true`

to the ui-draft pipeline and it did not work. That string is what was mentioned in the #bluemix-buildpacks channel and said it worked for them but we got this error:

`ERROR -- /tmp/buildpacks/1e470f032289e909a7ec1f1d5fcfbb3b/liberty/lib/liberty_buildpack/buildpack.rb:50:in `rescue in drive_buildpack_with_logger': Compile failed with exception #<RuntimeError: No Liberty download defined in buildpack.>`

**Comment by kinueng** [comment]
With the move away from Cloud Foundry, this issue is no longer needed
