### ISSUE TITLE
Update blog post design for clearer navigation

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/openliberty.io#973]
In the new blog design, if a user comes to a blog post from an external link it's not clear how they navigate to other blog posts or the rest of the site.

We should keep the OL site navigation at the top of the page, as well as a link back to the main blog page.  Currently navigation links are presented at the bottom of the blog page in the new design.

The Share action could be moved to the top as well (or put at both top and bottom).

**Comment by steven1046** [comment]
Closing to move this into the new blog design

**Comment by mdenby** [comment]
Posting the designs here too--though also in #458 

![7_blog_post_desktop_top](https://user-images.githubusercontent.com/26823018/52733942-00ffb700-2f92-11e9-85ab-e4e6f529054d.png)
![8_blog_post_desktop_bottom](https://user-images.githubusercontent.com/26823018/52733943-00ffb700-2f92-11e9-8506-2bc6517e9a78.png)
![10_blog_post_mobile](https://user-images.githubusercontent.com/26823018/52733944-00ffb700-2f92-11e9-9aa6-d9e93c2a2818.png)
![9_blog_post_tablet](https://user-images.githubusercontent.com/26823018/52733945-00ffb700-2f92-11e9-9024-00777c5dfb61.png)

**Comment by mdenby** [comment]
Newest designs--with 'Recommend Posts' removed.

![8_blog_post_desktop_bottom](https://user-images.githubusercontent.com/26823018/52819132-907e9600-3076-11e9-9068-21083bea825f.png)
![10_blog_post_mobile](https://user-images.githubusercontent.com/26823018/52819133-907e9600-3076-11e9-9607-ba44f90f9499.png)
![9_blog_post_tablet](https://user-images.githubusercontent.com/26823018/52819134-907e9600-3076-11e9-8aa0-c10724dbbabc.png)
