### ISSUE TITLE
Double "Nice Work!" at the end of some guides

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#988]
'Nice Work!' shows up before both lines under `Great work! You're done!`

For this particular guide it looks like this in the `README.adoc`:
```
== Great work! You're done!

You built and tested a web application project with an Open Liberty server using Gradle.

You can quickly create this project structure by using the https://liberty-app-accelerator.wasdev.developer.ibm.com/start/[Liberty App Accelerator^] 
and choose to create a Gradle project.


include::https://raw.githubusercontent.com/OpenLiberty/guides-common/multipane/attribution.adoc[subs="attributes"]
```

<img width="1361" alt="screen shot 2019-02-13 at 9 14 28 am" src="https://user-images.githubusercontent.com/18709242/52717793-e61c4b00-2f6f-11e9-8daa-ce02eb898eff.png">

**Comment by justineechen** [comment]
@steven1046 Are we only supposed to have one paragraph in this section? Or is this a bug?

**Comment by steven1046** [comment]
That's a bug, ill fix it.
