### ISSUE TITLE
Text in files in right pane change color after hot spotted - Medium Priority

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/openliberty.io#991]
In the following section of the guide, if you hover over the hotspots `image` and `containerPort`, notice the color of the text in the right pane changes from blue to black. It's quite subtle so might not be noticeable right away.
 
https://qa-guides-multipane.mybluemix.net/guides/kubernetes-intro.html#deploying-the-microservices

**Comment by steven1046** [comment]
This is part of the design.

**Comment by justineechen** [comment]
The text only changes for two lines of the file and only parts of those lines. 
See here when I hotspot `label` 
before:
<img width="1680" alt="screen shot 2019-02-14 at 12 11 56 pm" src="https://user-images.githubusercontent.com/18709242/52804280-decd6e00-3051-11e9-8191-1f40239eda37.png">
after:
<img width="1680" alt="screen shot 2019-02-14 at 12 12 01 pm" src="https://user-images.githubusercontent.com/18709242/52804288-e3922200-3051-11e9-93c7-d419db4c33d6.png">

But when I hover over `image`,
before:
<img width="1414" alt="screen shot 2019-02-14 at 12 12 07 pm" src="https://user-images.githubusercontent.com/18709242/52804310-f0167a80-3051-11e9-9a94-aad2726dd4f8.png">

after:
<img width="1016" alt="screen shot 2019-02-14 at 12 12 12 pm" src="https://user-images.githubusercontent.com/18709242/52804318-f4db2e80-3051-11e9-85d0-b118b6ee7c6c.png">

Only the second `image` changes color and this doesn't happen to any other lines of code that gets hot spotted except `containerPort`:
<img width="379" alt="screen shot 2019-02-14 at 12 12 16 pm" src="https://user-images.githubusercontent.com/18709242/52804366-0cb2b280-3052-11e9-9318-f01ffe9557ab.png">

**Comment by justineechen** [comment]
Before hovering over hotspots `image` and `containerPort`:
<img width="306" alt="screen shot 2019-02-14 at 12 11 52 pm" src="https://user-images.githubusercontent.com/18709242/52804397-1b996500-3052-11e9-8c96-3a1c6d254d49.png">

After hovering over hotspots:
<img width="543" alt="screen shot 2019-02-14 at 12 06 03 pm" src="https://user-images.githubusercontent.com/18709242/52804402-1d632880-3052-11e9-9f94-916a6c6f2dea.png">

**Comment by steven1046** [comment]
Thanks @justineechen, I will take a look at why it's behaving this way!

**Comment by justineechen** [comment]
Thank you @steven1046!
