### ISSUE TITLE
Missing Development builds

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/openliberty.io#993]
# Problem
**ONLY** the development builds are blank.  The other tables are populated.
![image](https://user-images.githubusercontent.com/31117513/52820652-2106a780-3072-11e9-8bb2-06b4b542b577.png)

# Debug Info
I am worried that the problem is with the server side API https://openliberty.io/api/builds/data.  The API now uses a cache and async calls to get the latest DHE information.

Doesn't matter how you get to the development table, the table is blank
1. https://openliberty.io/downloads/#development_builds
2. https://openliberty.io/downloads/ then clicking `Development Builds`

No browser console errors.

API call to get build data returns this
https://openliberty.io/api/builds/data
> `{"latest_releases":{"runtime":{"version":"19.0.0.1","date_time":"2019-01-24_2339","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/openliberty-19.0.0.1.zip","size_in_bytes":"128361081","total_tests":"10401","test_passed":"10401","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/open-liberty.unitTest.results.zip","package_locations":["javaee8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/openliberty-javaee8-19.0.0.1.zip","webProfile8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/openliberty-webProfile8-19.0.0.1.zip"]},"tools":{"version":"18.0.0.4","date_time":"2018-12-06_1706","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2018-12-06_1706/openlibertytools-18.0.0.4.zip","size_in_bytes":"5944778"}},"builds":{"runtime_releases":[{"version":"17.0.0.3","date_time":"2017-09-27_1951","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-09-27_1951/openliberty-17.0.0.3.zip","size_in_bytes":"79745618","total_tests":"6126","test_passed":"6126","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-09-27_1951/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-09-27_1951/open-liberty.unitTest.results.zip"},{"version":"17.0.0.4","date_time":"2017-12-06_1606","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-12-06_1606/openliberty-17.0.0.4.zip","size_in_bytes":"92855160","total_tests":"6444","test_passed":"6444","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-12-06_1606/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2017-12-06_1606/open-liberty.unitTest.results.zip"},{"version":"18.0.0.1","date_time":"2018-03-09_2209","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-03-09_2209/openliberty-18.0.0.1.zip","size_in_bytes":"97254589","total_tests":"7190","test_passed":"7190","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-03-09_2209/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-03-09_2209/open-liberty.unitTest.results.zip"},{"version":"18.0.0.2","date_time":"2018-06-19_0502","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-06-19_0502/openliberty-18.0.0.2.zip","size_in_bytes":"122284255","total_tests":"8500","test_passed":"8500","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-06-19_0502/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-06-19_0502/open-liberty.unitTest.results.zip","package_locations":["javaee8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-06-19_0502/openliberty-javaee8-18.0.0.2.zip","webProfile8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-06-19_0502/openliberty-webProfile8-18.0.0.2.zip"]},{"version":"18.0.0.3","date_time":"2018-09-05_2337","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-09-05_2337/openliberty-18.0.0.3.zip","size_in_bytes":"126560688","total_tests":"8500","test_passed":"8500","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-09-05_2337/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-09-05_2337/open-liberty.unitTest.results.zip","package_locations":["javaee8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-09-05_2337/openliberty-javaee8-18.0.0.3.zip","webProfile8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-09-05_2337/openliberty-webProfile8-18.0.0.3.zip"]},{"version":"18.0.0.4","date_time":"2018-11-21_0300","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-11-21_0300/openliberty-18.0.0.4.zip","size_in_bytes":"128149498","total_tests":"10210","test_passed":"10210","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-11-21_0300/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-11-21_0300/open-liberty.unitTest.results.zip","package_locations":["javaee8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-11-21_0300/openliberty-javaee8-18.0.0.4.zip","webProfile8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2018-11-21_0300/openliberty-webProfile8-18.0.0.4.zip"]},{"version":"19.0.0.1","date_time":"2019-01-24_2339","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/openliberty-19.0.0.1.zip","size_in_bytes":"128361081","total_tests":"10401","test_passed":"10401","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/gradle.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/open-liberty.unitTest.results.zip","package_locations":["javaee8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/openliberty-javaee8-19.0.0.1.zip","webProfile8.zip=https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/runtime/release/2019-01-24_2339/openliberty-webProfile8-19.0.0.1.zip"]}],"tools_releases":[{"version":"17.0.0.3","date_time":"2017-10-04_1748","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2017-10-04_1748/openlibertytools-17.0.0.3.zip","size_in_bytes":"4551517"},{"version":"17.0.0.4","date_time":"2017-12-14_0130","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2017-12-14_0130/openlibertytools-17.0.0.4.zip","size_in_bytes":"5279504"},{"version":"18.0.0.1","date_time":"2018-03-13_0030","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2018-03-13_0030/openlibertytools-18.0.0.1.zip","size_in_bytes":"5652983"},{"version":"18.0.0.2","date_time":"2018-06-20_1913","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2018-06-20_1913/openlibertytools-18.0.0.2.zip","size_in_bytes":"6050953"},{"version":"18.0.0.3","date_time":"2018-09-14_1330","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2018-09-14_1330/openlibertytools-18.0.0.3.zip","size_in_bytes":"6079701"},{"version":"18.0.0.4","date_time":"2018-12-06_1706","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/release/2018-12-06_1706/openlibertytools-18.0.0.4.zip","size_in_bytes":"5944778"}],"tools_nightly_builds":[{"date_time":"2019-01-18_0907","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-18_0907/openlibertytools-19.0.0.3.v2019-01-18_0907.zip","size_in_bytes":"5945203","total_tests":"114","test_passed":"113","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-18_0907/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-18_0907/test_results.html"},{"date_time":"2019-01-20_0902","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-20_0902/openlibertytools-19.0.0.3.v2019-01-20_0902.zip","size_in_bytes":"5713148","total_tests":"114","test_passed":"113","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-20_0902/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-20_0902/test_results.html"},{"date_time":"2019-01-22_0908","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-22_0908/openlibertytools-19.0.0.3.v2019-01-22_0908.zip","size_in_bytes":"5941470","total_tests":"114","test_passed":"113","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-22_0908/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-22_0908/test_results.html"},{"date_time":"2019-01-24_0908","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-24_0908/openlibertytools-19.0.0.3.v2019-01-24_0908.zip","size_in_bytes":"5944292","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-24_0908/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-24_0908/test_results.html"},{"date_time":"2019-01-26_0902","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-26_0902/openlibertytools-19.0.0.3.v2019-01-26_0902.zip","size_in_bytes":"5940546","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-26_0902/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-26_0902/test_results.html"},{"date_time":"2019-01-28_0902","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-28_0902/openlibertytools-19.0.0.3.v2019-01-28_0902.zip","size_in_bytes":"5941114","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-28_0902/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-28_0902/test_results.html"},{"date_time":"2019-01-30_0902","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-30_0902/openlibertytools-19.0.0.3.v2019-01-30_0902.zip","size_in_bytes":"5941987","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-30_0902/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-01-30_0902/test_results.html"},{"date_time":"2019-02-01_0903","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-01_0903/openlibertytools-19.0.0.3.v2019-02-01_0903.zip","size_in_bytes":"5944717","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-01_0903/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-01_0903/test_results.html"},{"date_time":"2019-02-03_0902","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-03_0902/openlibertytools-19.0.0.3.v2019-02-03_0902.zip","size_in_bytes":"5945363","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-03_0902/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-03_0902/test_results.html"},{"date_time":"2019-02-05_1154","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-05_1154/openlibertytools-19.0.0.3.v2019-02-05_1154.zip","size_in_bytes":"5945335","total_tests":"114","test_passed":"114","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-05_1154/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-05_1154/test_results.html"},{"date_time":"2019-02-07_0903","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-07_0903/openlibertytools-19.0.0.3.v2019-02-07_0903.zip","size_in_bytes":"5941140","total_tests":"114","test_passed":"112","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-07_0903/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-07_0903/test_results.html"},{"date_time":"2019-02-09_0905","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-09_0905/openlibertytools-19.0.0.3.v2019-02-09_0905.zip","size_in_bytes":"5937275","total_tests":"114","test_passed":"113","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-09_0905/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-09_0905/test_results.html"},{"date_time":"2019-02-11_0906","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-11_0906/openlibertytools-19.0.0.3.v2019-02-11_0906.zip","size_in_bytes":"5944906","total_tests":"114","test_passed":"112","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-11_0906/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-11_0906/test_results.html"},{"date_time":"2019-02-12_1159","driver_location":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-12_1159/openlibertytools-19.0.0.3.v2019-02-12_1159.zip","size_in_bytes":"5945200","total_tests":"114","test_passed":"113","build_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-12_1159/build.log","tests_log":"https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/tools/nightly/2019-02-12_1159/test_results.html"}]}}
`

**Comment by kinueng** [comment]
This is happening again today.

**Comment by kinueng** [comment]
This happened again tonight.

**Comment by aguibert** [comment]
Noticed this again today

**Comment by alexsm82** [comment]
Noticed this happening today
