### ISSUE TITLE
Can't use mpRestClient from EJB

### ISSUE THREAD

**Issue by jwalcorn** [OpenLiberty/openliberty.io#994]
I've been using mpRestClient-1.1 from my JAX-RS classes, packaged in a war, without any problems.  In fact, mpRestClient is my favorite MicroProfile technology.  But now I'm trying to use it from an EJB (specifically, an MDB that is pulling messages from MQ), and it's failing to inject the RestClient.  It's saying it can't determine the base URL (even though I see it, when I log the results of System.getProperty("com.ibm.hybrid.cloud.sample.stocktrader.messaging.client.NotificationClient/mp-rest/url") in a static initializer block I just added for debugging.  I'm setting that via a jvm.options entry (just like I do from my JAX-RS classes, which works).  I gathered a com.ibm.ws.microprofile.rest.client.cdi=all trace.  It, and my server.xml, jvm.options, and my ear file (containing the EJB jar) are zipped up and attached here.  Let me know if anything else is needed.  Thanks!
[mpRestClientFromEJB.zip](https://github.com/OpenLiberty/openliberty.io/files/2867216/mpRestClientFromEJB.zip)

**Comment by jwalcorn** [comment]
I forgot to mention, this is all in GitHub, at https://github.com/IBMStockTrader/messaging.  The built image is in DockerHub, at https://hub.docker.com/r/ibmstocktrader/messaging.  I can provide access to the Kubernetes environment hosting that Docker image if needed.  oh, and I'm running on Liberty 19.0.0.1

**Comment by aguibert** [comment]
Issue moved to [OpenLiberty/open-liberty #6534](https://github.com/OpenLiberty/open-liberty/issues/6534) via [**ZenHub**](https://www.zenhub.com/)
