### ISSUE TITLE
The issue numbers on the contribute page are not on the cards

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/openliberty.io#999]
https://openliberty.io/contribute/
![image](https://user-images.githubusercontent.com/6392944/53027853-56711380-342b-11e9-98cb-91b2355cebea.png)

**Comment by steven1046** [comment]
We lost the "pull-right" class while switching to bootstrap 4. 

![image](https://user-images.githubusercontent.com/6392944/53032914-74dc0c80-3435-11e9-8239-eb58a3be0559.png)
The documentation says to use .float-right instead. Although it doesn't fix it completely, does anyone know what it used to look like?

**Comment by steven1046** [comment]
View past designs: https://web.archive.org/web/20180612143111/https://www.openliberty.io/

**Comment by kinueng** [comment]
Wayback machine shows this
![image](https://user-images.githubusercontent.com/31117513/53200428-22425200-35e7-11e9-91e7-51d9e1733813.png)
